### ISSUE TITLE
[Feature request] CACTI templates on github

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#1837] opened 2018-08-15 13:22 UTC
Hi Everyone,

this is not a "real" CACTI NMS request but I would like to propose to have a section here on github to host official and user templates and data query in order to facilitate sharing and extention of the NMS.

Thanks in advance

**Comment by netniV** [comment] 2018-08-15 14:57
The main website (cacti.net) is the official source for most releases.  Whilst GitHub does have some of the relevant sources, the packages are generally held elsewhere.  There has been an issue opened on here already about having a centrally hosted location to identify plugins that could be downloaded by the website directly into the NMS, though we are conscious that we would need to consider this from a security aspect too.

If you look at docs.cacti.net, that is where most of the pre-1.x stuff was found.  These days with GitHub, sources are available and people can use `git` to maintain and update those sources (I do) but that isn’t something that most users/admins want to do.

**Comment by jhonnyx82** [comment] 2018-08-15 15:03
That's OK, 
I don't use github on everything (just to not break production systems) but the point on having it here is that I believe less and less people look at the forum (that is still a good resource) and comes more here and also if there would be a repository here on github it would help people that may develop components to put them all together.

Consider that many times the quality of an NMS is it's framework but people mostly look at extensions,plugins etc and as you mentioned most of the plugins on cacti.net are for old versions.

**Comment by jpobeda** [comment] 2018-08-15 21:06
I got divided opinions about this, on one hand git hub doesn't give you as much flexibility as you may want but could address an up-to-date repository issue now and updates coming from different author could be forced to be versioned, maybe writing some guidelines and restrictions document, which of course also adds more load to Cacti's team.

On the other hand, Cacti's website won't be refreshed for quite some time (correct me if I'm wrong) but it might be the best place to have it if there is a suitable interface to maintain it. Plans?

**Comment by cigamit** [comment] 2018-08-15 23:35
The plan is five fold:
1) Provide a mechanism to manage template packages and locate them somewhere where they can be accessed directly from an install script or GUI (including install GUI).
2) Provide a mechanism to manager plugin packages and locate them somewhere where they can be accessed directly from an install script or GUI (including install GUI).
3) Provide a Management GUI to allow you to import these packages directly, upgrade plugins directly, etc.
4) Provide a way from Package and Plugin Developers to upload their packages and or plugins to that location.
5) Release our Packaging plugin so users can create packages.

For me, a single GitHub repo would be perfect for such things.

However, @ronytomen must agree to the proposal and he seems always to be too busy.

**Comment by netniV** [comment] 2018-08-16 15:48
Closing as a duplicate of https://github.com/Cacti/cacti/issues/1837

**Closed by netniV** 2018-08-16 15:48 UTC

**Comment by cigamit** [comment] 2018-08-20 02:47
Open a new ticket to support the udp6: prefix, though I think I may have tested this with net-snmp, and it worked.  I think you need to be on net-snmp 5.7 or better though.

**Comment by netniV** [comment] 2018-08-20 07:56
Should we be adding that as a pre-requisite check?
