### ISSUE TITLE
intermittent warning messages: poller output table not empy

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#2366] opened 2019-02-01 19:25 UTC
I'm seeing intermittent but regular warnings across various DS. getting hundreds of messages a day emailed to the admin account. 
i don't imagine i'm worried too much about the warnings, but the email notifications is an issue

**Comment by pautiina** [comment] 2019-02-01 21:47
Some like this:?
![image](https://user-images.githubusercontent.com/11805503/52151439-c5a0e680-267b-11e9-83c9-31e22c546186.png)

**Comment by KnoAll** [comment] 2019-02-01 21:55
Yep, exactly

**Comment by cigamit** [comment] 2019-02-01 23:41
How is the data collector running?  Is it running fine?  Is it running at or near a polling interval?  Are you running boost?

**Comment by KnoAll** [comment] 2019-02-01 23:44
Poller seems to be running well, spine on 1m cron. Finishing in plenty of time.  Not running boost I don’t think

**Comment by cigamit** [comment] 2019-02-01 23:48
Tell me about the data source in question, or is it random?  What is the Data Template?  Is it script, snmp, or script server?

**Comment by cigamit** [comment] 2019-02-01 23:48
Be specific.

**Comment by KnoAll** [comment] 2019-02-02 00:11
It appears to be not a consistent host, but seems to be similar to a template. it is an SNMP Informant for Windows which i've been running for ages. this appears to only have started after 1.2.0 upgrade.
it is a Get SNMP Data input method.

**Comment by cigamit** [comment] 2019-02-02 00:16
There is another ticket along the same lines.  Can you run the following query and respond with the results:

`SELECT COUNT(*) FROM poller_item WHERE arg1 LIKE '%.';`

**Comment by KnoAll** [comment] 2019-02-02 00:20
+----------+
| COUNT(*) |
+----------+
|       17 |
+----------+

**Comment by KnoAll** [comment] 2019-02-02 00:31
apologies, you lost me on editing the IDs and correcting the indexes

**Comment by cigamit** [comment] 2019-02-02 00:38
1) Run the SQL query again.  Instead of COUNT(*) use "DISTINCT local_data_id"
2) Goto the Console > Manaagement > Data Sources
3) Sort the Data Sources numerically and find the Data Sources by their "local_data_id"
4) Edit those Data Sources, noting the Template, Index and Value columns.
5) In a separate browser, goto New Graphs and Select the Device and Data Query look for the correct Index value and update the value in the other screen.

Let me know if these are truely orphaned data sources, or if they lost their association.  Also, let us know what Data Template(s) were impacted.

**Comment by cigamit** [comment] 2019-02-03 14:56
Note that there is also a fix for this to remove these entries from causing the aforementioned error in the develop branch as well.  Starting with 1.2.2, you will be able to identify these Data Sources quickly.

**Comment by cigamit** [comment] 2019-02-03 15:01
Closing as this is a duplicate of issue #2357

**Closed by cigamit** 2019-02-03 15:01 UTC

**Comment by KnoAll** [comment] 2019-02-04 16:13
Updating the index values makes the select statement not pull anything, but the errors have not stopped completely. I haven't seen another error on a couple of the DS, but one of them i am still seeing errors, and there are at least 2 others that I am still seeing the error on that were not returned by the select query.
