### ISSUE TITLE
Boost "found extra data on update argument:"

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2980] opened 2019-09-26 23:17 UTC
After applying boost updates yesterday, I noticed several completely blank graphs. Upon inspection of the boost.log, I have found many of these:
```
ERROR: /cacti/cacti-1.2.6-prod/rra/thorn-a_file_sz_71176.rrd: found extra data on update argument: all
ERROR: /cacti/cacti-1.2.6-prod/rra/thorn-a_plist_sz_71178.rrd: found extra data on update argument: all
ERROR: /cacti/cacti-1.2.6-prod/rra/thorn-a_procs_71179.rrd: found extra data on update argument: all
ERROR: /cacti/cacti-1.2.6-prod/rra/thorn-a_cswchs_71180.rrd: found extra data on update argument: all
ERROR: /cacti/cacti-1.2.6-prod/rra/thorn-a_runq_sz_71181.rrd: found extra data on update argument: all
ERROR: /cacti/cacti-1.2.6-prod/rra/thorn-a_dentunusd_71182.rrd: found extra data on update argument: all
```
This spans several devices, and seems to affect mostly the System Activity Reporter data sources, which has the following script output fetched over SNMP:

```
2019/09/26 17:16:13 - SPINE: Poller[1] PID[13047] Device[1] HT[2] DS[12815] SCRIPT: perl /cacti/cacti-1.2.6-prod/scripts/sarfetch.pl '127.0.0.1' '2' 'public' '161' '1500', output: CPU:all user:12.72 nice:0.00 system:2.05 iowait:0.02 steal:0.00 idle:85.21 procs:168.00 cswchs:15959.00 pgpgins:0.00 pgpgouts:1320.00 faults:120505.00 majflts:0.00 pgfrees:26572.00 pgscanks:0.00 pgscands:0.00 pgsteals:0.00 vmeff:0.00 kbmemfree:73572468 kbmemused:323435288 memused:81.47 kbbuffers:1143916 kbcached:275727852 kbswpused:122713496 swpused:26.44 dentunusd:10895193 file_sz:6144 inode_sz:9924471 pty_sz:4 runq_sz:22 plist_sz:2582 ldavg_1:3.42 ldavg_5:3.77 ldavg_15:4.03 totsck:727 tcpsck:19 udpsck:51 rawsck:0 ip_frag:0 tcp_tw:1913
```
I think the "CPU:all" is tripping it up. This has worked just fine for several years. Not exactly sure why it's not working now. But, I can see why that "CPU:all" shouldn't really be there.

**Comment by eschoeller** [comment] 2019-09-26 23:34
I modified the script to throw away the "CPU:all" and restored some of the graphs from this template. But there are several other areas that are impacted by whatever changed. I know something in the Cacti collector/boost template is also broken, trying to track that down.

**Comment by eschoeller** [comment] 2019-09-26 23:42
The "Boost Runtime" and both "Boost Updates" graphs broke as well. 
Both are broken in this manner:
```
ERROR: /cacti/cacti-1.2.6-prod/rra/thorn_time_59733.rrd: expected 2 data source readings (got 1) from RRDUpdates
```
Which has the poller output:
```
2019/09/26 17:41:09 - SPINE: Poller[1] PID[15875] Device[1] HT[5] DS[59733] SS[3] SERVER: /cacti/cacti-1.2.6-prod/scripts/ss_poller.php ss_boost, output: Time:36.4200 RRDUpdates:378596
```
I can't see what's wrong with that though.

**Comment by eschoeller** [comment] 2019-09-26 23:47
I suspect this could be partially related to #2965

**Comment by cigamit** [comment] 2019-09-27 00:37
It's actually duplicate of #2977.  I'm going to close this one.  Update to latest and keep us posted as we plan on releasing this weekend.  Boost will be a little slower, but should run error free.

**Closed** 2019-09-27 00:37 UTC
Labels: duplicate
