### ISSUE TITLE
[1.3 QA] Device template ACME is applied to Windows machines in automation

### ISSUE THREAD

**Issue by jab60** [Cacti/cacti#5520] opened 2023-10-03 20:23 UTC
# Describe the bug

Default installation has a built in device rule template for ACME.
This device template is selected when any Windows machines are detected due to matching rule on OS name with "Windows".
Ive not got any ACME devices but they dont look like they are a MS Windows type device, and my real Windows machines get the wrong template applied under automation rules.

## To Reproduce

1. Go to 'Automation>>Device Rules'
2. View default rules
3. Under System Description Match the ACME template has "Windows"

## Expected behavior

It should match to something else
The Template match for Windows machines should be "Windows Device"

## Screenshots

ACME device match in red circle
Windows device in green circle
![image](https://github.com/Cacti/cacti/assets/108667514/ef97fc33-47f7-4c21-a476-428eeda6ec93)

## Desktop (please complete the following information)

- W10 22H2
- Chrome
- Ubuntu 22.04
- cacti  [ 1.3.0 - Dev a4d06bf1 @ 2023-10-03 20:30 ]

## Smartphone (please complete the following information)

- N/A

**Comment by TheWitness** [comment] 2023-10-03 21:27
This is going to happen till the templating exercise is complete.  So, for now, just delete those entries.

**Comment by TheWitness** [comment] 2023-11-24 14:29
This is a duplicate of #5583.

**Comment by TheWitness** [comment] 2023-11-24 14:31
And this commit also is material.

https://github.com/Cacti/cacti/commit/33be80063b5a68847f86d42ecd2770cf4e7ada3b

**Closed by TheWitness** 2023-11-24 14:31 UTC
Labels: bug, duplicate, automation, confirmed, QA, type:bug, status:confirmed
