### ISSUE TITLE
New install on Centos 7 date.timezone error php(web)

### ISSUE THREAD

**Issue by mrbullman** [Cacti/cacti#4809] opened 2022-06-07 18:38 UTC
New install of Centos 7 with a new install of Cacti 1.2.21.  I cannot get past the pre-installation checks.  

PHP - Recommendations (web)
version 	            7.3.33 	>= 5.4.0 	        Passed 	PHP 5.4.0 is the mimimum version
memory_limit 	800M 	>= 400M 	Passed 	A minimum of 400M memory limit
max_execution_time 	60 	>= 60 	        Passed 	A minimum of 60 m execution time
date.timezone 		        >= 	                Error 	A valid timezone that matches MySQL and the system

i added the date.timezone to the /etc/php.ini file and it fixed the
PHP - Recommendations (cli)
date.timezone 	America/Denver 	>= 	Passed 	A valid timezone that matches MySQL and the system

but I cannot find a spot to add for the (web) php

the only php.ini file on the system is  in /etc/

**Comment by netniV** [comment] 2022-06-07 19:04
Duplicate of #4807

**Closed by netniV** 2022-06-07 19:04 UTC

**Comment by vireyesp** [comment] 2022-11-11 17:59
Hi @mrbullman , did you solve the date.timezone problem?
