### ISSUE TITLE
Allow Boost to use more than one CPU

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/cacti#2200] opened 2018-12-04 07:00 UTC
i see the php poller_boost.php is using only one CPU. can this be fixed? or is it expected?

```
top - 06:57:42 up 20 days, 21:58,  2 users,  load average: 1.98, 1.91, 1.83
Tasks: 202 total,   2 running, 200 sleeping,   0 stopped,   0 zombie
%Cpu0  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  :  0.3 us,  0.3 sy,  0.0 ni, 97.0 id,  2.3 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  : 24.7 us,  1.7 sy,  0.0 ni, 73.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu6  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu8  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu9  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu10 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu11 : 97.7 us,  2.3 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 24653708 total,  1316092 free, 11506464 used, 11831152 buff/cache
KiB Swap: 16777212 total, 15841524 free,   935688 used. 12435120 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
32271 apache    20   0  465208  88960  10824 R 100.0  0.4   8:53.38 php
32343 apache    20   0 2773572 2.428g   3024 S  26.3 10.3   2:09.02 rrdtool
```

```
[FREE::root@cacti1a.ams2 ~]# ps -ef | grep php
root     26685 23704  0 06:57 pts/1    00:00:00 grep php
apache   32271     1 96 06:48 ?        00:08:49 /usr/bin/php -q /var/www/cacti/poller_boost.php
[FREE::root@cacti1a.ams2 ~]#
```

**Comment by netniV** [comment] 2018-12-04 09:05
I've changed the title of this because it's not a 1.2 specific thing but a PHP thing.  PHP only uses one core during its processing cycle.  The only two ways around that are MultiThreading (not really supported in all environments) or spawning multiple processes (Workers) that would process a portion of the load.  That is effectively have the poller and script server functionality work.

Don't forget though, if boost were to start eating up more cores, that is less cores available to serve end users, especially if a system were not configured properly and spawned the boost update process too often (as we have seen in another issue on here).

**Comment by netniV** [comment] 2018-12-04 11:35
So it would appear to be an unused setting introduced a year ago but without the backing functionality for it during commit c004b6beb44a3a09b87d035780cc0bc5abd0a213.

```
commit c004b6beb44a3a09b87d035780cc0bc5abd0a213
Author: cigamit <jimmy@sqmail.org>
Date:   Sun Nov 19 15:03:04 2017 -0600

    Remove whitespace, use html_escape()
```

**Comment by netniV** [comment] 2018-12-04 11:52
It is likely that the functionality for this setting will be introduced in 1.3.

**Comment by vishnubraj** [comment] 2018-12-04 11:54
ok will wait for 1.3

**Comment by cigamit** [comment] 2018-12-06 12:49
This feature has been developed by one of our developers, but needs architectural review prior to merging.

**Comment by TheWitness** [comment] 2021-01-23 20:32
Duplicate of #4066

**Closed by TheWitness** 2021-01-23 20:32 UTC
Labels: enhancement, performance
