### ISSUE TITLE
Recache Event Detected for Device - Constant Messages each Poll

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#3548] opened 2020-05-10 08:55 UTC
I have an Cisco SG300 switch that is added to Cacti, but every time it is polled the following output is sent to the logs:

10/May/2020 18:10:28 - POLLER: Poller[1] Device[31] HT[1] DQ[1] RECACHE ASSERT FAILED '23=22
10/May/2020 18:10:29 - SYSTEM STATS: Time:26.5154 Method:cmd.php Processes:1 Threads:0 Hosts:28 HostsPerProcess:28 DataSources:491 RRDsProcessed:280
10/May/2020 18:10:31 - PCOMMAND Device[31] WARNING: Recache Event Detected for Device
10/May/2020 18:10:32 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.0771 RRDUser:0.0000 RRDSystem:0.0000 RRDReal:0.0000
10/May/2020 18:10:38 - RECACHE STATS: Poller:1 RecacheTime:6.6103 DevicesRecached:1
10/May/2020 18:15:28 - POLLER: Poller[1] Device[31] HT[1] DQ[1] RECACHE ASSERT FAILED '23=22
10/May/2020 18:15:29 - SYSTEM STATS: Time:26.4955 Method:cmd.php Processes:1 Threads:0 Hosts:28 HostsPerProcess:28 DataSources:491 RRDsProcessed:280
10/May/2020 18:15:31 - PCOMMAND Device[31] WARNING: Recache Event Detected for Device
10/May/2020 18:15:32 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.1006 RRDUser:0.0000 RRDSystem:0.0000 RRDReal:0.0000
10/May/2020 18:15:38 - RECACHE STATS: Poller:1 RecacheTime:6.6365 DevicesRecached:1
10/May/2020 18:20:28 - POLLER: Poller[1] Device[31] HT[1] DQ[1] RECACHE ASSERT FAILED '23=22
10/May/2020 18:20:29 - SYSTEM STATS: Time:26.4997 Method:cmd.php Processes:1 Threads:0 Hosts:28 HostsPerProcess:28 DataSources:491 RRDsProcessed:280
10/May/2020 18:20:32 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.2032 RRDUser:0.0000 RRDSystem:0.0000 RRDReal:0.0000
10/May/2020 18:20:32 - PCOMMAND Device[31] WARNING: Recache Event Detected for Device
10/May/2020 18:20:39 - RECACHE STATS: Poller:1 RecacheTime:6.6371 DevicesRecached:1
10/May/2020 18:25:28 - POLLER: Poller[1] Device[31] HT[1] DQ[1] RECACHE ASSERT FAILED '23=22
10/May/2020 18:25:29 - SYSTEM STATS: Time:26.5150 Method:cmd.php Processes:1 Threads:0 Hosts:28 HostsPerProcess:28 DataSources:491 RRDsProcessed:280
10/May/2020 18:25:31 - PCOMMAND Device[31] WARNING: Recache Event Detected for Device
10/May/2020 18:25:32 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.1509 RRDUser:0.
0000 RRDSystem:0.0000 RRDReal:0.0000
10/May/2020 18:25:33 - SYSTEM DSSTATS STATS: Type:DAILY, Time:0.8293 RRDUser:0.2200 RRDSystem:0.0100 RRDReal:0.7700
10/May/2020 18:25:38 - RECACHE STATS: Poller:1 RecacheTime:6.4471 DevicesRecached:1
10/May/2020 18:30:28 - POLLER: Poller[1] Device[31] HT[1] DQ[1] RECACHE ASSERT FAILED '23=22
10/May/2020 18:30:29 - SYSTEM STATS: Time:26.5268 Method:cmd.php Processes:1 Threads:0 Hosts:28 HostsPerProcess:28 DataSources:491 RRDsProcessed:280
10/May/2020 18:30:31 - PCOMMAND Device[31] WARNING: Recache Event Detected for Device
10/May/2020 18:30:32 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.1758 RRDUser:0.0000 RRDSystem:0.0000 RRDReal:0.0000
10/May/2020 18:30:39 - RECACHE STATS: Poller:1 RecacheTime:7.1295 DevicesRecached:1
10/May/2020 18:35:28 - POLLER: Poller[1] Device[31] HT[1] DQ[1] RECACHE ASSERT FAILED '23=22
10/May/2020 18:35:29 - SYSTEM STATS: Time:26.4848 Method:cmd.php Processes:1 Threads:0 Hosts:28 HostsPerProcess:28 DataSources:491 RRDsProcessed:280
10/May/2020 18:35:32 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:0.1940 RRDUser:0.0000 RRDSystem:0.0000 RRDReal:0.0000
10/May/2020 18:35:32 - PCOMMAND Device[31] WARNING: Recache Event Detected for Device
10/May/2020 18:35:38 - RECACHE STATS: Poller:1 RecacheTime:6.3381 DevicesRecached:1

This is the SNMP information for the switch:

SWITCH - switch-3.trevascus.name (switch-3.trevascus.name)
SNMP Information
System: SG300-10 10-Port Gigabit Managed Switch
Uptime: 311853400 (36days, 2hours, 15minutes)
Hostname: switch-3

No other devices apart from this one are doing this.  There are valid graphs being produced for the device.

The Associated Data Query has a Data Query of "SNMP - Interface Statistics" set with Index Count as the Re-Index method.  It reports Success [232 Items, 23 Rows]

A Data Query Debug looks like this:

Total: 0.000000, Delta: 0.000000, Found data query XML file at '/var/www/cacti.reub.net/htdocs/resource/snmp_queries/interface.xml'Total: 0.000000, Delta: 0.000000, Running Data Query [1].Total: 0.000000, Delta: 0.000000, Found Type = '3' [SNMP Query].Total: 0.000000, Delta: 0.000000, XML file parsed ok.Total: 0.020000, Delta: 0.020000, Executing SNMP get for num of indexes @ '.1.3.6.1.2.1.2.1.0' Index Count: 22Total: 0.200000, Delta: 0.180000, Executing SNMP walk for list of indexes @ '.1.3.6.1.2.1.2.2.1.1' Index Count: 23Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.49' value: '49'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.50' value: '50'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.51' value: '51'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.52' value: '52'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.53' value: '53'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.54' value: '54'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.55' value: '55'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.56' value: '56'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.57' value: '57'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.58' value: '58'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1000' value: '1000'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1001' value: '1001'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1002' value: '1002'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1003' value: '1003'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1004' value: '1004'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1005' value: '1005'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1006' value: '1006'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1007' value: '1007'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.3000' value: '3000'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.7000' value: '7000'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.20000' value: '20000'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.100000' value: '100000'Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.300000' value: '300000' | Total: 0.000000, Delta: 0.000000, Found data query XML file at '/var/www/cacti.reub.net/htdocs/resource/snmp_queries/interface.xml' | Total: 0.000000, Delta: 0.000000, Running Data Query [1]. | Total: 0.000000, Delta: 0.000000, Found Type = '3' [SNMP Query]. | Total: 0.000000, Delta: 0.000000, XML file parsed ok. | Total: 0.020000, Delta: 0.020000, Executing SNMP get for num of indexes @ '.1.3.6.1.2.1.2.1.0' Index Count: 22 | Total: 0.200000, Delta: 0.180000, Executing SNMP walk for list of indexes @ '.1.3.6.1.2.1.2.2.1.1' Index Count: 23 | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.49' value: '49' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.50' value: '50' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.51' value: '51' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.52' value: '52' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.53' value: '53' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.54' value: '54' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.55' value: '55' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.56' value: '56' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.57' value: '57' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.58' value: '58' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1000' value: '1000' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1001' value: '1001' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1002' value: '1002' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1003' value: '1003' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1004' value: '1004' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1005' value: '1005' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1006' value: '1006' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.1007' value: '1007' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.3000' value: '3000' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.7000' value: '7000' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.20000' value: '20000' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.100000' value: '100000' | Total: 0.200000, Delta: 0.000000, Index found at OID: '.1.3.6.1.2.1.2.2.1.1.300000' value: '300000'

Is this log message indicative of a bug?  The error occurs every poll and has been ongoing for some time.

**Comment by TheWitness** [comment] 2020-05-12 01:32
Yea, there is some issue where the polller_reindex table is not being updated.  Going to try to reproduce.

**Comment by TheWitness** [comment] 2020-05-12 01:37
I've tested with both spine and cmd.php, and it works as expected.  I have a few things for you to check:

1) Damaged table poller_reindex, run a repair on it
2) For the host_id and data_query_id in question, see if you have more than one row for that data_query_id and host_id.  If so, report that back.

**Comment by TheWitness** [comment] 2020-05-12 01:37
What version of Cacti BTW?

**Comment by reubenfarrelly** [comment] 2020-05-12 05:31
I'm tracking 1.2.x in git - updated regularly.  This problem has been around for some time and is not a recent regression.  But as it doesn't have an obvious impact I haven't been in a rush to report it.
Only one version of the host id 31.
I'm using cmd.php.
Running php repair_database.php didn't indicate any issues and the problem is still there afterwards.
Looking in the poller_reindex table it states that the assert_value = 23 for that host id, but if I run the arg1 query I get:

# snmpwalk -v 2c -c xxx switch-3.trevascus.name .1.3.6.1.2.1.2.1.0
IF-MIB::ifNumber.0 = INTEGER: 22

I wonder if the host is reporting 22 interfaces but returning 23 when they are listed?  I only have one switch with this firmware so it could be a firmware bug....

**Comment by TheWitness** [comment] 2020-05-12 15:11
Right, it due to this in the interface.xml file:

```xml
<oid_num_indexes>.1.3.6.1.2.1.2.1.0</oid_num_indexes>
```

And your Devices Data Query re-index method is set to Index Count Changed.  If you change it do Uptime Goes backward, the problem goes away too.

**Comment by TheWitness** [comment] 2020-05-12 15:11
So, basically the device manufacturer is setting that value improperly.

**Comment by TheWitness** [comment] 2020-05-12 15:12
I'm going to close this now.  Submit a ticket to the manufacturer.

**Closed by TheWitness** 2020-05-12 15:12 UTC
Labels: bug, unverified
