### ISSUE TITLE
Character encoding(?) issue with Script data queries using SNMP STRING type objects

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#410] opened 2017-03-12 07:10 UTC
While continuing some tests after a 0.8.8b -> 1.0.4 upgrade I discovered a problem with some data queries we run.
Thankfully all the data is still cached, but it's only a matter of time until these hosts start to re-index and ... explode. 

Example output of the data query from 0.8.8b:
$ php -q /cacti/cacti-0.8.8b-prod/scripts/query_servertech_cord_sentry4.php 172.20.1.2 public 2 161 1500 10 "" "" "" "" "" "" query index
1!1
2!2

Example output of the same data query under 1.0.4:
$ php -q /cacti/cacti-1.0.4-prod/scripts/query_servertech_cord_sentry4.php 172.20.1.2 public 2 161 1500 10 "" "" "" "" "" "" query index
�!�
�!�

Likewise, within the Cacti GUI the data query really doesn't seem to work at all. I also checked to make sure this wasn't a regression from the changes I made previously in lib/snmp.php. It's not. I also removed the auto-loading of MIB files we do in /etc/snmp/snmp.local.conf. No change. It seems there is some other difference within the cacti_snmp_get and cacti_snmp_walk functions. 

I have other data queries written in nearly the same manner which are not exhibiting any problems. I am starting to suspect the difference lies in the type of device, and those which are using a STRING type object instead of an INTEGER are seeming to cause the problem. 

Here are the indexes of a device having an issue:
$ snmpwalk -v2c -c public 172.20.1.2 Sentry4-MIB::st4InputCordID
Sentry4-MIB::st4InputCordID.1.1 = STRING: AA
Sentry4-MIB::st4InputCordID.2.1 = STRING: BA

Versus this type of device:
$ snmpwalk -v2c -c public 172.20.1.3 SPAGENT-MIB::sensorTemperatureIndex
SPAGENT-MIB::sensorTemperatureIndex.21 = INTEGER: 21
SPAGENT-MIB::sensorTemperatureIndex.23 = INTEGER: 23
SPAGENT-MIB::sensorTemperatureIndex.25 = INTEGER: 25
SPAGENT-MIB::sensorTemperatureIndex.30 = INTEGER: 30
SPAGENT-MIB::sensorTemperatureIndex.31 = INTEGER: 31
SPAGENT-MIB::sensorTemperatureIndex.32 = INTEGER: 32

PHP 5.4.39 (cli) (built: Apr  2 2015 13:00:03)

Let me know if you need any more info! It looks like as a work-around I can simply include global.php and snmp.php from my old installation into these broken data queries and it will work ok.

**Comment by cigamit** [comment] 2017-03-12 12:25
Back off both lib/functions.php and lib/data_query.php to the 1.0.4 version and see if the problem is fixed.

**Comment by cigamit** [comment] 2017-03-12 12:25
Also, upload your XML file for the data query.  The one in the resources directory.  If you can do these two things right away, we would appreciate it.

**Comment by cigamit** [comment] 2017-03-12 15:55
Any update?  We are trying to release today.

**Comment by eschoeller** [comment] 2017-03-12 16:08
I am currently running 1.0.4 ... do you mean to back off data_query and functions back to 0.8.8b?

**Comment by eschoeller** [comment] 2017-03-12 16:11
XML file for the data query attached here.

[query-servertech-cord-sentry4.xml.txt](https://github.com/Cacti/cacti/files/836624/query-servertech-cord-sentry4.xml.txt)

**Comment by eschoeller** [comment] 2017-03-12 16:14
Here's the script too. 
[query_servertech_cord_sentry4.php.txt](https://github.com/Cacti/cacti/files/836629/query_servertech_cord_sentry4.php.txt)

**Comment by cigamit** [comment] 2017-03-12 17:17
Okay, looking at the query, you should likely review the query and make changes to be compatible with 1.0.x.  It would seem that it's pretty pedestrian in nature, and should in-fact migrate cleanly.

So, it's something likely pretty simple.  I'm not going to consider this a show stopper for the 1.0.5 release.  However, if you take the 'development' branch as it stands now and retest this query, it would help us know if we it fixed itself on it's own in the last two weeks.  Let us know.

**Comment by eschoeller** [comment] 2017-03-12 17:19
Do you have any references or examples for what I might need to tweak to make this 1.0.x compliant? I'll see if I can snag a development branch

**Comment by cigamit** [comment] 2017-03-12 17:23
Just grab the development branch and install it on a test server that uses this data query.  Then, run the re-index like you did manually.  You should do some var_dump() of the return array inside your code to figure out what happened with the query.  It should just work.  But if you look at the ss_host_disk.php script, you will see that we did add snmpEngineID and snmpContext, but we added them at the end.  So, it should be okay.

**Comment by eschoeller** [comment] 2017-03-12 17:36
Yep, working on upgrading a dev instance as we speak. Probably another 15 minutes

**Comment by cigamit** [comment] 2017-03-12 17:48
Tony is going to be releasing as soon as we get you squared away.  Review my comments on the other bug as well.

**Comment by eschoeller** [comment] 2017-03-12 18:11
This upgrade is not going very well. I hadn't seen anything in the log file for 15 minutes and the browser is still churning. I found the apache process and traced it. I found this was just repeating over and over:
sendto(15, "V\0\0\0\3ALTER TABLE `graph_tree` AD"..., 90, MSG_DONTWAIT, NULL, 0) = 90
poll([{fd=15, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=15, revents=POLLIN}])
recvfrom(15, "+\0\0\1\377+\4#42000Invalid defaul", 27, MSG_DONTWAIT, NULL, NULL) = 27
poll([{fd=15, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=15, revents=POLLIN}])
recvfrom(15, "t value for 'locked'", 183, MSG_DONTWAIT, NULL, NULL) = 20
sendto(15, "V\0\0\0\3ALTER TABLE `graph_tree` AD"..., 90, MSG_DONTWAIT, NULL, 0) = 90
poll([{fd=15, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=15, revents=POLLIN}])
recvfrom(15, "+\0\0\1\377+\4#42000Invalid default val"..., 163, MSG_DONTWAIT, NULL, NULL) = 47
sendto(15, "V\0\0\0\3ALTER TABLE `graph_tree` AD"..., 90, MSG_DONTWAIT, NULL, 0) = 90

I got some more output in the log file after 20 minutes so I suppose it's making slow progress. I've been carrying these databases around for probably over a decade now. Who knows what's happened to them :( I'm going to keep waiting on it.

**Comment by eschoeller** [comment] 2017-03-12 18:14
Lots of these messages in the log file:

2017-03-12 12:05:33 - ERROR PHP WARNING: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound in file: /cacti/cacti-1.0.5-pre-dev/lib/database.php  on line: 333
2017-03-12 12:05:33 - CMDPHP PHP ERROR WARNING Backtrace: (/cli/add_perms.php: 167 displayHostGraphs)(/lib/api_automation_tools.php: 505 db_fetch_assoc)(/lib/database.php: 310 db_fetch_assoc_prepared)(/lib/database.php: 333 execute)(CactiErrorHandler)(/lib/functions.php: 4194 cacti_debug_backtrace)
2017-03-12 12:05:33 - CMDPHP SQL Backtrace: (/cli/add_perms.php: 33 include)(/include/global.php: 306 include_once)(/include/global_languages.php: 65 read_user_i18n_setting)(/include/global_languages.php: 528 db_fetch_row_prepared)(/lib/database.php: 297 cacti_debug_backtrace)

**Comment by cigamit** [comment] 2017-03-12 18:20
None of that debug information is lining up with the development branch.  Are you sure you are using it?

**Comment by cigamit** [comment] 2017-03-12 18:21
That strace issue should have been resolved.  Can you look at the cacti log and see where the invalid values column is?

**Comment by cigamit** [comment] 2017-03-12 18:24
The invalid value is likely the default for the columns locked_date and last_modified.  Those should have a default of '0000-00-00' which is like '0'.  But likely your database is a recent MySQL or MariaDB which does not like those values.  But our database.php should be setting a session variable to allow them.

**Comment by eschoeller** [comment] 2017-03-12 18:37
Crap, it doesn't look like I am running the latest. I went to clone/download and downloaded "cacti-develop.zip", I was hoping that would be the same as cloning from git, but after looking at some recent commits and comparing to my tree, it's not what I have. Why is that?? Sorry I'm not git-saavy [yet]. 

Cacti log from this upgrade attached here:
[upgrade.log.txt](https://github.com/Cacti/cacti/files/836796/upgrade.log.txt)

Mysql is: Server version: 5.6.23-log

What would I need to poke at in the DB to resolve this? Upgrade is still spinning along...

**Comment by cigamit** [comment] 2017-03-12 18:42
I'd whack it and start over again.  Just restore your database, grab the development branch and start again.  We corrected this in the database.php as a part of the connect, we set several options to allow the zero dates.

**Comment by cigamit** [comment] 2017-03-12 18:43
I've told Tony to go ahead with the release.  We'll figure this stuff out on the flip side.

**Comment by eschoeller** [comment] 2017-03-12 18:48
ok sounds good. Sorry I didn't get it all together in time for you guys. I pulled down the latest from git just now and I'll import my template in and see how it works there and report back.

**Comment by eschoeller** [comment] 2017-03-12 19:16
OK, I have it all set in another instance that I'm sure is now running the latest code, imported the templates, added a host. Queries don't work in GUI and also still return the funky �!� on the command line. I'll play around with the query code a bit later today and see what I find.

**Comment by cigamit** [comment] 2017-03-12 20:42
Keep us posted on what you find when you debug your template.  This will be interesting.

**Comment by cigamit** [comment] 2017-03-18 13:49
You out there on this fine Saturday?  By a computer?

**Comment by cigamit** [comment] 2017-03-18 13:58
I've just updated lib/functions.php.  Please test using it.  Thanks.

**Comment by eschoeller** [comment] 2017-03-18 19:50
Yep I'm here .. barely ;) Pulled down the latest from git about 2 hours ago and upgraded a test instance with the troublesome template loaded. It's working as expected now, so whatever you changed - it worked! I may have a couple other templates to check on, but I'm moving pretty darn slow today:)

**Comment by cigamit** [comment] 2017-03-18 20:01
Thanks for taking the time!

**Closed by cigamit** 2017-03-18 20:01 UTC
Labels: unverified
