### ISSUE TITLE
Unable to create Generic OID graph

### ISSUE THREAD

**Issue by adfire** [Cacti/cacti#438] opened 2017-03-16 10:31 UTC
While trying to add generic oid graph, after pressing "Create" button I get redirected to the header, graph is not created and the following messages appear in the log:

PHP notice: Undefinied index: legend_direction in /opt/cacti/lib/template.php on line 704

The same in version 1.0.4, 1.0.5 and 1.0.6.

Data source for generic oid shows the right value, but there is no way to create graph.

**Comment by cigamit** [comment] 2017-03-17 01:05
Is this what you get when you goto Console -> Create -> Create New Graphs, pick the SNMP - Generic OID Graph?

![genericoidgraph](https://cloud.githubusercontent.com/assets/957322/24024777/e35faf82-0a83-11e7-8ee2-21981224bf28.PNG)

It's working perfectly on 1.0.6 (with auth_login.php patch).

**Comment by adfire** [comment] 2017-03-17 10:00
You say it's working perfectly. So what I did again, step by step:

- fresh 1.0.6 installation
- add a device (without any graphs, queries and so on)
- console->create->create new graph->SNMP generic OID (but look at the screenshot below - it looks different than on yours- it was the same in previous version, installations - I did't change anything, all settings are default). Here I tried many, many combinations ->create
- I see only pop'up window "created graph:", but it's not created, there's no graph in graph list for that device
- when I look into data sources - it looks fine, it even shows the right values for previously added generic oid (I see that in info and debug mode) 
- adding another graph from template, for example memory usage - it's all ok !

While trying to set it up correctly I used different Cacti versions, devices (and OIDs), browsers, generic OID template configurations... everything.  

![1](https://cloud.githubusercontent.com/assets/26457871/24037296/9253d49a-0afd-11e7-81f1-32ea75d8ce59.PNG)
![2](https://cloud.githubusercontent.com/assets/26457871/24037297/9255a4a0-0afd-11e7-90fc-a338649b12a2.PNG)

**Comment by cigamit** [comment] 2017-03-17 12:35
Thanks for the clarification.  Question, when did you install this cacti?  Was it an upgrade or fresh install?  If a fresh install, when did you install it?

**Comment by adfire** [comment] 2017-03-17 12:47
It was today, fresh install (Ubuntu 16.04). But I struggle with this for a while (from 1.0.4 version when I stared to test it). Yesterday I did an upgrade, the same happens. 
Thanks for your concern about this issue !

**Comment by cigamit** [comment] 2017-03-17 23:56
This is duplicate of Issue #337 which has been resolved.  To resolve for yourself, just import the attached Template.

[cacti_graph_template_snmp_-_generic_oid_template.xml.txt](https://github.com/Cacti/cacti/files/852004/cacti_graph_template_snmp_-_generic_oid_template.xml.txt)

**Comment by cigamit** [comment] 2017-03-17 23:56
The new install fix will be a part of the 1.0.7 release.

**Closed by cigamit** 2017-03-17 23:56 UTC
Labels: unverified
