### ISSUE TITLE
Graph Filters: template filter have empty value.

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#1106] opened 2017-11-27 09:22 UTC
Hello.
The latest develop branch have this problem:
![63](https://user-images.githubusercontent.com/11805503/33259302-20420a80-d365-11e7-8be4-d2eaf1df5338.png)

When I click them-choose: All Graphs & Templates

**Comment by netniV** [comment] 2017-11-28 10:12
The filter uses index 0 as "All Graphs and Templates" but then searches graph_local for matches against graph_template_id. However, if index 0 is passed as a variable, it is also used in the search.  Now when I looked at my database, the following entry existed:

```
select * from graph_local where graph_template_id = 0;
+------+-------------------+---------+---------------+---------------------+------------+
| id   | graph_template_id | host_id | snmp_query_id | snmp_query_graph_id | snmp_index |
+------+-------------------+---------+---------------+---------------------+------------+
| 1837 |                 0 |       0 |             0 |                   0 |            |
+------+-------------------+---------+---------------+---------------------+------------+

```
Therefore, it displays an index, but can't get a name for the template since there is no template with ID 0.

```
select * from graph_templates where id = 0;
Empty set (0.00 sec)

```

I don't know whether this is by design but the fix is to change graph_view.php from:
```
	foreach ($graph_templates as $gt) {
		$found = db_fetch_cell_prepared('SELECT id
			FROM graph_local
			WHERE graph_template_id = ? LIMIT 1',
			array($gt['id']));

		if ($found) {
			print "<option value='" . $gt['id'] . "'";
			if (sizeof($selected)) {
				if (in_array($gt['id'], $selected)) {
					print ' selected';
				}
			}
			print '>';
			print $gt['name'] . "</option>\n";
		}
	}

```
to be 

```
	foreach ($graph_templates as $gt) {
		if ($gt['id'] != 0) {
			$found = db_fetch_cell_prepared('SELECT id
				FROM graph_local
				WHERE graph_template_id = ? LIMIT 1',
				array($gt['id']));

			if ($found) {
				print "<option value='" . $gt['id'] . "'";
				if (sizeof($selected)) {
					if (in_array($gt['id'], $selected)) {
						print ' selected';
					}
				}
				print '>';
				print $gt['name'] . "</option>\n";
			}
		}
	}

```

However, there may be other places to fix that too so I haven't submitted it as a fix.  The alternative to changing the code would be to remove that errornous graph_local entry.

`DELETE FROM graph_local where graph_template_id = 0;
`

**Comment by pautiina** [comment] 2017-11-28 11:48
I used your Mysql query: 
```
mysql> select * from graph_local where graph_template_id = 0 ;
+------+-------------------+---------+---------------+---------------------+------------+
| id   | graph_template_id | host_id | snmp_query_id | snmp_query_graph_id | snmp_index |
+------+-------------------+---------+---------------+---------------------+------------+
| 8357 |                 0 |       0 |             0 |                   0 |            |
| 8388 |                 0 |       0 |             0 |                   0 |            |
| 7351 |                 0 |       0 |             0 |                   0 |            |
+------+-------------------+---------+---------------+---------------------+------------+
3 rows in set (0.00 sec)
```
and delete this entry. After this template filter not have empty value.
But I don't know: It's my bug, when I deleted some template or cacti bug.
@netniV thanks you for help found mistake entry

**Comment by netniV** [comment] 2017-11-28 12:08
It's definitely a cacti bug, but what causes it is still unknown.  Might be one for @cigamit or @ronytomen

**Comment by pautiina** [comment] 2017-11-28 13:20
Still, it's a bug Cacti.
When deleting graphs from the database, the aggregation graphics have disappeared.
Now I recreate graphics aggregation and I again appeared empty filter value.
!!! Do not query the database:
`DELETE FROM graph_local where graph_template_id = 0;`

**Comment by netniV** [comment] 2017-11-28 15:57
I shall have to go check mine!

**Comment by netniV** [comment] 2017-11-28 15:58
You are correct, I did have an aggregate graph and that delete command removed it. I will edit my earlier post so no one else runs it.

**Comment by netniV** [comment] 2017-11-28 16:12
It turns out that the aggregate_graphs table links into graph_local.  

```
select id, local_graph_id, title_format from aggregate_graphs;
+----+----------------+-------------------+
| id | local_graph_id | title_format      |
+----+----------------+-------------------+
|  2 |           1938 | BT - Ping Latency |
+----+----------------+-------------------+
1 row in set (0.00 sec)
```

```
select * from graph_local where graph_template_id = 0;
+------+-------------------+---------+---------------+---------------------+------------+
| id   | graph_template_id | host_id | snmp_query_id | snmp_query_graph_id | snmp_index |
+------+-------------------+---------+---------------+---------------------+------------+
| 1938 |                 0 |       0 |             0 |                   0 |            |
+------+-------------------+---------+---------------+---------------------+------------+
1 row in set (0.00 sec)
```

When we removed the graph_local entry, some code must clean up the aggregate_graph table (or maybe there's a database-level trigger?).  I don't know enough about it to properly comment.

**Comment by netniV** [comment] 2017-11-29 12:35
I have committed a fix for this in my local repositiory https://github.com/netniV/cacti/commit/59018378c295487ca2421346734c399a47f66ee1 which should be part of a pull request that is still outstanding.

**Comment by netniV** [comment] 2017-11-29 15:02
Created a pull request of #1114 which separates out the previous #1107 pull request into individual components.

**Comment by cigamit** [comment] 2017-12-02 17:29
Marking this resolved now.  Thanks for the help!

**Closed by cigamit** 2017-12-02 17:29 UTC
