### ISSUE TITLE
[1.2.19] Possible infinite loop

### ISSUE THREAD

**Issue by NotAProfessionalDeveloper** [Cacti/cacti#4469] opened 2021-11-20 19:51 UTC
After upgrade from Cacti 1.2.18 to 1.2.19 I get this at the end of a poller run:

```
PHP Fatal error:  Uncaught Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames in /srv/www/vhosts/cacti/lib/functions.php:2367
Stack trace:
#0 /srv/www/vhosts/cacti/lib/functions.php(2367): preg_replace()
#1 /srv/www/vhosts/cacti/lib/database.php(1520): clean_up_lines()
#2 /srv/www/vhosts/cacti/lib/database.php(265): db_strip_control_chars()
#3 /srv/www/vhosts/cacti/lib/database.php(515): db_execute_prepared()
#4 /srv/www/vhosts/cacti/lib/database.php(501): db_fetch_assoc_prepared()
#5 /srv/www/vhosts/cacti/lib/dsdebug.php(115): db_fetch_assoc()
#6 /srv/www/vhosts/cacti/lib/poller.php(571): dsdebug_poller_output()
#7 /srv/www/vhosts/cacti/lib/poller.php(591): process_poller_output()
#8 /srv/www/vhosts/cacti/lib/poller.php(591): process_poller_output()
#9 /srv/www/vhosts/cacti.secu.lu/cactici in /srv/www/vhosts/cacti/lib/functions.php on line 2367
```

Running without Xdebug, Mysql is at very high CPU. I couldn't keep it running for a long time or investigate more. I had to downgrade.

Cacti 1.2.19, SLES12-5, PHP 7.4, MariaDB 10.2, rrdtool 1.4, net-snmp 5.7

**Comment by bmfmancini** [comment] 2021-11-20 20:47
This is a duplicate of #4406

**Comment by bmfmancini** [comment] 2021-11-20 20:47
Sorry duplicate of #4460

**Comment by TheWitness** [comment] 2021-11-27 16:01
Going to close as this is duplicate.

**Closed by TheWitness** 2021-11-27 16:01 UTC
Labels: bug, unverified
