### ISSUE TITLE
Problem with consolidation function after upgade to 1.2.6

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#2925] opened 2019-09-04 07:16 UTC
**Describe the bug**
Cacti only output the MAX value on all graphs.

For example, the default "Interface Traffic" graph template will show the "MAX" value by "Line",
and show "AVERAGE" value by "Area". But My Cacti will draw them with same value.

**To Reproduce**
1. All the graphs show the MAX value only, and the RRD commands is not correct:

Here is the graph template content:
![Screenshot from 2019-09-04 15-29-50](https://user-images.githubusercontent.com/13309854/64234439-edfe0580-cf28-11e9-8379-78f87f5e723c.png)

It's RRD command output:
![Screenshot from 2019-09-04 15-13-56](https://user-images.githubusercontent.com/13309854/64233458-cf970a80-cf26-11e9-9202-8f1485fbe78f.png)

**Expected behavior**
![Screenshot from 2019-09-04 14-52-17](https://user-images.githubusercontent.com/13309854/64232717-15eb6a00-cf25-11e9-8907-47000309a7be.png)
(From another Cacti server)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 76

**Additional context**
I have another Cacti 1.2.6 server, and it works well.

**Comment by netniV** [comment] 2019-09-04 13:30
Can you copy/paste the text version of your outputs?  They will be useful during diagnosis.

**Comment by cigamit** [comment] 2019-09-05 03:43
I can confirm this.  Have to review the code to see what happened.

**Comment by cigamit** [comment] 2019-09-05 04:13
Okay, I recall this now.  It was done due to an RRDtool quirk around the first RRA around the fact that the max and average would both be the same.  Boy wish I had kept better notes on this.  It did not show up sooner due to the coding error that was resolved recently that allowed it to go unchecked.  Let me see if I can do better math.  Maybe I'll just revert the change.  More to follow.

**Comment by cigamit** [comment] 2019-09-05 04:18
The source commit was here.  https://github.com/Cacti/cacti/commit/cd14f260dde6499bec829753a026a1e1f37a67a5#diff-e93c440af885a2ac30d2e08c774a3934  It had to do with Aggregate.  I have to re-review the reason for the change.

**Comment by cigamit** [comment] 2019-09-08 18:36
I'm going to close this now.  Let me know if you are satisfied with the fix.

**Closed by cigamit** 2019-09-08 18:36 UTC
Labels: bug, resolved

**Comment by skyjou** [comment] 2019-09-09 00:31
I just test this fix on my two cacti servers. And both of them work perfectly. Thank you.
