### ISSUE TITLE
Tree column is narrower and narrower on each click

### ISSUE THREAD

**Issue by skyjou** [Cacti/cacti#2435] opened 2019-02-20 11:50 UTC
**Describe the bug**
When the scroll bar shows, the tree column is narrower and narrower on each click.

**To Reproduce**
1. Go to 'Graphs'
2. Click on 'Tree'

**Expected behavior**
Tree column should be the same width.

**Screenshots**
If the tree is enough long to let the scroll bar appear, then each click on tree cause column width of tree be narrower.
![cacti_tree](https://user-images.githubusercontent.com/13309854/53089869-b6111100-3548-11e9-8b77-9b6cf29601cc.gif)

**Desktop**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 72

**Comment by netniV** [comment] 2019-02-21 09:38
I can confirm that this is a bug and does indeed happen only when the scroll bar shows.  Once the scroll bar is removed, the width again stays static.

**Comment by netniV** [comment] 2019-02-21 09:40
This occurs in:

* Chrome

Does not occur in:

* Firefox
* Internet Explorer
* Edge

**Comment by netniV** [comment] 2019-02-21 09:44
In fact, I can get weird things to happen depending on the size of one of the nodes that is appearing.  If I collapse and expand nodes, sometimes a longer value will expand the width, others it will keep it at the same width but not long enough to read the whole text.

**Comment by cigamit** [comment] 2019-02-24 13:37
Marking this as a Chrome bug as it only impacts Chrome right now.

**Comment by skyjou** [comment] 2019-02-24 13:38
No, this issue impacts Firefox and IE too. Do I need to upload the video?

**Comment by skyjou** [comment] 2019-02-24 13:52
Here is the Firefox video:
![firefox](https://user-images.githubusercontent.com/13309854/53300168-731fa800-387e-11e9-87fd-3b0cab6b4e87.gif)

**Comment by netniV** [comment] 2019-02-24 14:10
Interesting as I could not get this to replicate in IE/Firefox

**Comment by skyjou** [comment] 2019-02-24 15:19
My Firefox version is 65.0.1 (64-bit).

I can also reproduce it in IE11:

![ie](https://user-images.githubusercontent.com/13309854/53301194-9fd9bc80-388a-11e9-974f-e23637542b57.gif)

**Comment by cigamit** [comment] 2019-03-15 11:13
I tested again last weekend on this and again, I'm unable to reproduce.  Must be doing something wrong.

**Comment by skyjou** [comment] 2019-03-15 13:24
I just update Cacti to the latest development version, and I can still see the issue. It seems be more obvious in the Modern theme.

**Comment by cigamit** [comment] 2019-03-16 19:44
This is resolved now.

**Closed by cigamit** 2019-03-16 19:44 UTC
Labels: bug, gui, resolved

**Comment by skyjou** [comment] 2019-03-17 05:34
I pull the latest version from GitHub. I find it be wider and wider now.

**Comment by skyjou** [comment] 2019-03-17 06:02
In Paw theme, the tree work well now.

**Comment by netniV** [comment] 2019-03-17 23:12
I don't know, you stop it shrinking and people moan, you just can't win (joking 👍 ).  Will test this out tomorrow and see what each of the themes brings to the table.
