### ISSUE TITLE
Cannot Delete Tree Entries

### ISSUE THREAD

**Issue by PE1NUT** [Cacti/cacti#3035] opened 2019-10-16 14:53 UTC
Deleting items from the tree management interface is not possible when right-clicking, because the menu ends up underneath the existing entries. See attached picture.

Cacti is version 1.2.7 from Debian Testing.

Desktop is Ubuntu 19.04, with Firefox 69.0.2
The same issue happens with Firefox 69.0.2 on OSX 10.12.6
The same issue also happens with Safari 12.1.2 on OSX 10.12.6

![Cacti-Tree-bug](https://user-images.githubusercontent.com/47217436/66930792-6a5e2b00-f035-11e9-839b-ef0d1f1ea271.png)

**Comment by bmfmancini** [comment] 2019-10-16 15:22
I am not seeing the same thing also on 1.2.7

![image](https://user-images.githubusercontent.com/13388748/66933428-15a3bb80-f007-11e9-88c0-8392e731a51c.png)


I am using firefox 58.0.2

**Comment by netniV** [comment] 2019-10-16 21:34
@bmfmancini if you have the 1.2.x branch, you are technically on 1.2.7+dev which is < 1.2.8 but on its way there 👍 

I do believe that this was addressed by someone else raising the issue already, check though the issues since 1.2.7 and you will likely see the fix being applied.

**Comment by cigamit** [comment] 2019-10-16 22:56
If you installed this from apg-get, then I suggest you log a Debian packaging bug as it's not a core cacti bug.  Just adding @paulgevers to the thread in case.

**Comment by PE1NUT** [comment] 2019-10-17 13:12
Confirmed as a Debian/Ubuntu bug:

When installing the Cacti 1.2.2 package on my Ubuntu 19.04 desktop, it has the same bug
Installing Cacti 1.2.7 from source on the same machine does -not- have the same bug. I'll try to figure out the differences, and report the results Debian/Ubuntu.

**Comment by paulgevers** [comment] 2019-10-18 20:43
@PE1NUT can you elaborate what you did *exactly*? In Debian we don't use the theme files provided by Cacti, but link to the system version of jstree.

I think I need to start building a check for Cacti modifications to those files. However, it would be awesome if Cacti would just ship unmodified files and instead overload stuff in main.css.

**Comment by cigamit** [comment] 2019-10-19 13:04
Thanks for the confirmation @paulgevers.  Let's keep this open then.

**Comment by paulgevers** [comment] 2019-10-21 18:56
Hi PE1NUT,

On 21-10-2019 19:41, PE1NUT wrote:
> @paulgevers <https://github.com/paulgevers> The simplest way to
> reproduce the issue is:
> 
>  1. Install Cacti from Debian or Ubuntu pacakges
>     Specifically, I did this on a Ubuntu 19.04 machine, which installed
>     package cacti-1.2.2+ds1-2.
>  2. Add a few graphs to the cacti tree.
>  3. Try to right-click to remove one of the entries - this results in
>     the screenshot shown above.

Thanks, I was able to reproduce this earlier already.

> Our production cacti since a recent upgrade (from 0.8.x) runs on Debian
> Buster, and I installed (using pinning) the 1.2.7 Debian package from
> testing, as I had too many issues with earlier versions. In the Debian
> package version 1.2.7, the tree menu bug still exists. I applied the
> workaround suggested in #2988
> <https://github.com/Cacti/cacti/issues/2988> as a stopgap until we can
> fully figure out what's breaking things.

I was referring to this text. What exactly did you do and in which file?

Paul

**Comment by PE1NUT** [comment] 2019-10-21 19:54
Ah, gotcha. I implemented what was suggested in this comment, to a very similar bug:
https://github.com/Cacti/cacti/issues/2988#issuecomment-537029475

Which is indeed quite cryptic, but amounts to this 'hack':

index 0703168..ec72841 100644
--- a/libjs-jquery-jstree-3.3.7+dfsg1/src/themes/default/style.css
+++ b/usr/share/javascript/jstree/themes/default/style.css
@@ -122,6 +122,7 @@
   background: #f5f5f5;
   border: 1px solid #979797;
   box-shadow: 2px 2px 2px #999999;
+  z-index: 99;
 }
 .vakata-context ul {
   list-style: none;

**Comment by paulgevers** [comment] 2019-10-21 20:22
Hi PE1NUT,

On 21-10-2019 21:54, PE1NUT wrote:
> index 0703168..ec72841 100644
> --- a/libjs-jquery-jstree-3.3.7+dfsg1/src/themes/default/style.css
> +++ b/usr/share/javascript/jstree/themes/default/style.css
> @@ -122,6 +122,7 @@
> background: #f5f5f5;
> border: 1px solid #979797;
> box-shadow: 2px 2px 2px #999999;
> 
>   * z-index: 99;
>     }
>     .vakata-context ul {
>     list-style: none;

Can you try if this works equally well for you?

If it does, it short of strengthens my desire of the Cacti maintainers
to maintain the delta of their themes in main.css instead of in the
theme default/style.css (which comes from upstream).

paul@testavoira ~/packages/cacti/cacti-upstream/include/themes/modern $
diff main.css /usr/share/cacti/site/include/themes/modern/main.css
2626a2627,2630
>
> .vakata-context ul {
>     z-index: 99;
> }

**Comment by cigamit** [comment] 2019-11-09 18:43
Okay, I've resolved this one.  Does it also happen in other themes?

**Closed** 2019-11-29 16:51 UTC
Labels: bug, resolved

**Comment by paulgevers** [comment] 2019-11-29 22:42
@cigamit thanks for fixing it in main.css

**Comment by cigamit** [comment] 2019-12-01 01:46
Not a problem.  Keep the bugs coming.

**Comment by netniV** [comment] 2019-12-02 10:26
> Not a problem. Keep the bugs coming.

I'm sure @cigamit actually means `Now tell us we have found and quashed every last bug yay!` 😄
