### ISSUE TITLE
[1.2.0] Beta 1 (8766f24 ) Backtraces for poller

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#2017] opened 2018-10-06 08:01 UTC
Hi,
I have some free time now and I just updated my Cacti Dev release.
Now I'm getting following errors:
![image](https://user-images.githubusercontent.com/35721406/46568997-a6ed4600-c94e-11e8-9b38-7d689ccc0e9d.png)

And here are the steps I followed for upgrade:
cp -rp /tmp/cacti-develop/* /usr/share/cacti
chown -R apache.apache /usr/share/cacti/resource/
chown -R apache.apache /usr/share/cacti/scripts
chown -R apache.apache /usr/share/cacti/cache/

Than I perform a https://cactidev/cacti/install

And while cheking logs got the result from picture, any hints?

**Comment by netniV** [comment] 2018-10-06 08:44
Duplicate of #2000

**Closed by netniV** 2018-10-06 08:44 UTC

**Comment by jackouille-ch** [comment] 2018-10-06 10:28
Yes greta, it solves my issue:
root@cactidev:/usr/share/cacti/cli# php -q upgrade_database.php --forcever=1.1.38
Upgrading from v1.1.38
Upgrading from v1.1.38 (DB 1.2.0 - Beta 1 (DB: 1.2.0)) to v1.2.0
+++++++++++-+++++++++++++++++++
root@cactidev:/usr/share/cacti/cli#

Maybe you could add directly within install script in order to avoid further same tickets, what do you think?

**Comment by netniV** [comment] 2018-10-06 12:10
Was this a fresh install or an upgrade?

**Comment by jackouille-ch** [comment] 2018-10-06 17:42
Nope I was upgrading my last release from 1.2.0 from about one month ago.
So it's maybe a normal situation for my case.

**Comment by netniV** [comment] 2018-10-06 17:56
If it's an in-place upgrade, then yes, it's normal as it was added after your initial install.  If you every upgrade dev code after already running that version it's always a recommendation to run upgrade_database.php to correct it.
