### ISSUE TITLE
Poller Output Table not empty for poller id 1

### ISSUE THREAD

**Issue by hvspa** [Cacti/cacti#5545] opened 2023-11-01 15:36 UTC
I am again running into "Poller Output Table not Empty" issue, after recent "yum cacti update" from 1.2.20 to 1.2.25.

This what i am seeing in the logs:

`2023/11/01 19:25:01 - POLLER: Poller[1] PID[13006] WARNING: Poller Output Table not Empty.  Issues: 2, DS[3249, 3244]`

when checking the table itself, i am seeing this:

```
+---------------------+
| now()               |
+---------------------+
| 2023-11-01 19:25:18 |
+---------------------+
1 row in set (0.000 sec)

+---------------+----------+---------------------+-----------------------------------------------------------------------------------------------------------------+
| local_data_id | rrd_name | time                | output                                                                                                          |
+---------------+----------+---------------------+-----------------------------------------------------------------------------------------------------------------+
|          3249 |          | 2023-11-01 19:25:02 | valid:1 invalid:0 active:0 sleeping:0 garbage:0 uactive:0 usleeping:0                                           |
|          3244 |          | 2023-11-01 19:25:02 | Time:38.7011 Method:spine Processes:1 Threads:1 Hosts:35 HostsPerProcess:35 DataSources:4398 RRDsProcessed:2213 |
+---------------+----------+---------------------+-----------------------------------------------------------------------------------------------------------------+
2 rows in set (0.000 sec)

MariaDB [cacti]> 

```

not sure how to reproduce. only issue that's coming into my mind is that my cacti is now 1.2.25, and spine poller is 1.2.19

`SPINE 1.2.19  Copyright 2004-2021 by The Cacti Group`

attached is the screen of the two "problematic" DS from Cacti web

![cacti](https://github.com/Cacti/cacti/assets/27876987/e963cda3-fa3a-4122-8c8e-954067d5fa8d)

will upgrade of spine resolve this issue?

```
wget https://github.com/Cacti/spine/archive/master.zip
unzip master.zip
cd spine-master
./bootstrap
./configure
make
sudo make install

```

- OS:  win10 desktop, centos 7 (server)

- Browser Firefox

thanks in advance for all your help!

**Comment by hvspa** [comment] 2023-11-01 21:45
actually, i have updated the spine to latest version 1.2.25

`SPINE 1.2.25  Copyright 2004-2023 by The Cacti Group`

 but the issue is still present:

```
+---------------------+
| now()               |
+---------------------+
| 2023-11-02 01:43:41 |
+---------------------+
1 row in set (0.000 sec)

+---------------+----------+---------------------+-----------------------------------------------------------------------------------------------------------------+
| local_data_id | rrd_name | time                | output                                                                                                          |
+---------------+----------+---------------------+-----------------------------------------------------------------------------------------------------------------+
|          3249 |          | 2023-11-02 01:40:01 | valid:2 invalid:0 active:0 sleeping:0 garbage:0 uactive:0 usleeping:0                                           |
|          3244 |          | 2023-11-02 01:40:01 | Time:36.5497 Method:spine Processes:1 Threads:1 Hosts:35 HostsPerProcess:35 DataSources:4398 RRDsProcessed:2213 |
+---------------+----------+---------------------+-----------------------------------------------------------------------------------------------------------------+
2 rows in set (0.000 sec)

MariaDB [cacti]> 
```

how can i get this resolved?

**Comment by bmfmancini** [comment] 2023-11-01 22:24
Do you have any poller timeouts?

**Comment by hvspa** [comment] 2023-11-02 05:51
> Do you have any poller timeouts?
> […](#)

thanks for responding! i dont think i have any timeouts:

```
less /var/log/cacti/cacti.log | grep -i time | grep -i out | tail
2023/11/02 09:40:01 - SPINE: Poller[1] PID[29289] PT[140411247421184] Device[52] HT[1] DS[3244] TT[0.99] SS[0] SERVER: /usr/share/cacti/scripts/ss_poller.php ss_poller, output: Time:27.5349 Method:spine Processes:1 Threads:1 Hosts:30 HostsPerProcess:30 DataSources:4329 RRDsProcessed:2213
2023/11/02 09:40:02 - SPINE: Poller[1] PID[29289] PT[140411247421184] Device[52] HT[1] DS[3311] TT[0.66] SS[0] SERVER: /usr/share/cacti/scripts/ss_hstats.php ss_hstats '52' polling_time, output: 0.579
2023/11/02 09:40:02 - SPINE: Poller[1] PID[29289] PT[140411247421184] Device[52] HT[1] DS[3312] TT[0.33] SS[0] SERVER: /usr/share/cacti/scripts/ss_hstats.php ss_hstats '52' uptime, output: 82665300
2023/11/02 09:40:16 - SPINE: Poller[1] PID[29286] PT[139928620508928] Device[35] HT[1] DS[2196] TT[0.37] SS[0] SERVER: /usr/share/cacti/scripts/ss_hstats.php ss_hstats '35' polling_time, output: 4.428
2023/11/02 09:40:16 - SPINE: Poller[1] PID[29286] PT[139928620508928] Device[35] HT[1] DS[2197] TT[0.27] SS[0] SERVER: /usr/share/cacti/scripts/ss_hstats.php ss_hstats '35' uptime, output: 2349254200
2023/11/02 09:45:01 - SPINE: Poller[1] PID[30092] PT[140637902595840] Device[52] HT[1] DS[3244] TT[0.85] SS[0] SERVER: /usr/share/cacti/scripts/ss_poller.php ss_poller, output: Time:26.5223 Method:spine Processes:1 Threads:1 Hosts:30 HostsPerProcess:30 DataSources:4329 RRDsProcessed:2213
2023/11/02 09:45:01 - SPINE: Poller[1] PID[30092] PT[140637902595840] Device[52] HT[1] DS[3311] TT[0.56] SS[0] SERVER: /usr/share/cacti/scripts/ss_hstats.php ss_hstats '52' polling_time, output: 0.623
2023/11/02 09:45:01 - SPINE: Poller[1] PID[30092] PT[140637902595840] Device[52] HT[1] DS[3312] TT[0.30] SS[0] SERVER: /usr/share/cacti/scripts/ss_hstats.php ss_hstats '52' uptime, output: 82695300
2023/11/02 09:45:16 - SPINE: Poller[1] PID[30089] PT[140130707199744] Device[35] HT[1] DS[2196] TT[0.42] SS[0] SERVER: /usr/share/cacti/scripts/ss_hstats.php ss_hstats '35' polling_time, output: 4.008
2023/11/02 09:45:16 - SPINE: Poller[1] PID[30089] PT[140130707199744] Device[35] HT[1] DS[2197] TT[0.27] SS[0] SERVER: /usr/share/cacti/scripts/ss_hstats.php ss_hstats '35' uptime, output: 2349284200
```

i have cleaned few non responding devices, but the situation is still the same:

```
+---------------------+
| now()               |
+---------------------+
| 2023-11-02 09:50:00 |
+---------------------+
1 row in set (0.000 sec)

+---------------+----------+---------------------+-----------------------------------------------------------------------------------------------------------------+
| local_data_id | rrd_name | time                | output                                                                                                          |
+---------------+----------+---------------------+-----------------------------------------------------------------------------------------------------------------+
|          3249 |          | 2023-11-02 09:45:01 | valid:0 invalid:0 active:0 sleeping:0 garbage:0 uactive:0 usleeping:0                                           |
|          3244 |          | 2023-11-02 09:45:01 | Time:26.5223 Method:spine Processes:1 Threads:1 Hosts:30 HostsPerProcess:30 DataSources:4329 RRDsProcessed:2213 |
+---------------+----------+---------------------+-----------------------------------------------------------------------------------------------------------------+
2 rows in set (0.000 sec)

MariaDB [cacti]> 
```

**Comment by hvspa** [comment] 2023-11-02 06:23
the first row (3249) is the output of the following script, however i am not sure why it is not being emptied once the polling is complete:

```
sudo -u apache php -q cacti_user_stats.php
valid:0 invalid:0 active:0 sleeping:0 garbage:0 uactive:0 usleeping:0
```

i have disabled the two DS-s,  and now the table is empty after next run. 

![Screenshot 2023-11-02 102114](https://github.com/Cacti/cacti/assets/27876987/6ab0ce9a-78c6-4713-b177-12ba34fd33ef)

my question is why these were staying in the table, and what will be the consequence of disabling those?
is it possible that after upgrade these DS-s lost their RRD-s and now not being collected hence staying in the DB? as you can see there is no RRD name in the sql query output for those DS-s. or is there a way to restore the RRDs for these DS-s?

thanks in advance

**Comment by hvspa** [comment] 2023-11-02 06:34
i checked further the RRD-s, and seems right after upgrade of cacti yesterday (Nov 1, 16:20), these two DS 3244 and 3249 stopped collecting, the rest are still fine:

```
**-rw-r--r-- 1 apache apache 641K Nov  1 16:20 asa_static_rrdsprocessed_3244.rrd
-rw-r--r-- 1 apache apache 641K Nov  1 16:20 asa_static_active_3249.rrd**
-rw-r--r-- 1 apache apache 185K Nov  2 10:30 asa_static_traffic_in_3299.rrd
-rw-r--r-- 1 apache apache  94K Nov  2 10:30 asa_static_polling_time_3311.rrd
-rw-r--r-- 1 apache apache  94K Nov  2 10:30 asa_static_5min_cpu_3310.rrd
-rw-r--r-- 1 apache apache  94K Nov  2 10:30 asa_static_uptime_3312.rrd
-rw-r--r-- 1 apache apache 185K Nov  2 10:30 asa_static_traffic_in_3362.rrd
-rw-r--r-- 1 apache apache 185K Nov  2 10:30 asa_static_traffic_in_3363.rrd
-rw-r--r-- 1 apache apache 185K Nov  2 10:30 asa_static_traffic_in_3365.rrd
-rw-r--r-- 1 apache apache 185K Nov  2 10:30 asa_static_traffic_in_3364.rrd
-rw-r--r-- 1 apache apache 185K Nov  2 10:30 asa_static_traffic_in_3367.rrd
-rw-r--r-- 1 apache apache 185K Nov  2 10:30 asa_static_traffic_in_3366.rrd
```

any ideas why this could have happened and how it can be restored?

**Comment by TheWitness** [comment] 2023-11-02 23:04
For the two, post the data template and graphs template.  For the rrdfiles post "redtool info $filename"

**Comment by hvspa** [comment] 2023-11-03 04:47
good morning, 

files are  attached:

[3244.info.txt](https://github.com/Cacti/cacti/files/13246754/3244.info.txt)
[3249.info.txt](https://github.com/Cacti/cacti/files/13246755/3249.info.txt)
[cacti_data_template_cacti_stats_-_main_poller.xml.txt](https://github.com/Cacti/cacti/files/13246756/cacti_data_template_cacti_stats_-_main_poller.xml.txt)
[cacti_data_template_cacti_stats_-_user_stats.xml.txt](https://github.com/Cacti/cacti/files/13246757/cacti_data_template_cacti_stats_-_user_stats.xml.txt)
[cacti_graph_template_cacti_stats_-_main_poller_dsrrd.xml.txt](https://github.com/Cacti/cacti/files/13246758/cacti_graph_template_cacti_stats_-_main_poller_dsrrd.xml.txt)
[cacti_graph_template_cacti_stats_-_user_logins.xml.txt](https://github.com/Cacti/cacti/files/13246759/cacti_graph_template_cacti_stats_-_user_logins.xml.txt)

for cacti stats, graph templates i have attached only user logins. please let me know if the other two are also required.
thanks

**Comment by TheWitness** [comment] 2023-11-05 14:48
Screen Shot's.  Sorry for the confusion.

**Comment by hvspa** [comment] 2023-11-05 15:17
you mean this type of screenshots?

> Screen Shot's. Sorry for the confusion.

![Screenshot 2023-11-05 191658](https://github.com/Cacti/cacti/assets/27876987/c8dc29b4-58ad-49d9-89ca-6fa5b4c1f82e)

**Comment by TheWitness** [comment] 2023-11-05 15:19
Yup

**Comment by hvspa** [comment] 2023-11-05 15:38
here you go 
![data template cacti stats user stats](https://github.com/Cacti/cacti/assets/27876987/5fd34821-1fa4-44ea-b13f-ccc8c656e810)
![graph template cacti stats main poller](https://github.com/Cacti/cacti/assets/27876987/5c9afb84-8ab5-4cf3-8d15-1290d8d0a0c6)
![graph template cacti stats user logins](https://github.com/Cacti/cacti/assets/27876987/113324ac-e994-4442-a18d-b65b02fba60c)

**Comment by TheWitness** [comment] 2023-11-05 16:03
Okay, after spending more time reading your ticket, I can now trace the issue.

**Comment by TheWitness** [comment] 2023-11-05 16:06
Can you push out the host?  Then, see if this error goes away.

**Comment by TheWitness** [comment] 2023-11-05 16:07
Also, it looks like the Graphs were removed, and you choose to disable the data sources.  Let me verify that that logic is sound.

**Comment by hvspa** [comment] 2023-11-05 16:08
push out meaning? also how do i know which host?


Sent from Yahoo Mail for iPhone


On Sunday, November 5, 2023, 20:06, TheWitness ***@***.***> wrote:




Can you push out the host? Then, see if this error goes away.

**Comment by hvspa** [comment] 2023-11-05 16:09
yeap, and i trying to understand how the update of cacti removed the graphs?

Sent from Yahoo Mail for iPhone


On Sunday, November 5, 2023, 20:08, TheWitness ***@***.***> wrote:




Also, it looks like the Graphs were removed, and you choose to disable the data sources. Let me verify that that logic is sound.

**Comment by TheWitness** [comment] 2023-11-05 16:11
I'm trying to reproduce, and the poller cache is clear of the entries.  So, in your case, repopulating the poller cache (aka pushing out the host) should clear the issue.

**Comment by hvspa** [comment] 2023-11-05 16:19
i have tried to re-index the device and re-populate the cache, but after enabling the DS-s i started to get the alarm again:
```

MariaDB [cacti]>  select now(); select * from poller_output;                                                        
+---------------------+
| now()               |
+---------------------+
| 2023-11-05 20:17:46 |
+---------------------+
1 row in set (0.000 sec)

+---------------+----------+---------------------+-----------------------------------------------------------------------------------------------------------------+
| local_data_id | rrd_name | time                | output                                                                                                          |
+---------------+----------+---------------------+-----------------------------------------------------------------------------------------------------------------+
|          3244 |          | 2023-11-05 20:15:01 | Time:26.4541 Method:spine Processes:1 Threads:1 Hosts:30 HostsPerProcess:30 DataSources:4327 RRDsProcessed:2213 |
|          3249 |          | 2023-11-05 20:15:01 | valid:1 invalid:0 active:0 sleeping:0 garbage:0 uactive:0 usleeping:0                                           |
+---------------+----------+---------------------+-----------------------------------------------------------------------------------------------------------------+
2 rows in set (0.000 sec)

MariaDB [cacti]> 
```

the templates to which the DS should be linked are not active, meaning they are somehow not linked, which they were previously:

![data sources disabled](https://github.com/Cacti/cacti/assets/27876987/e5c57a7d-c537-49b7-8139-3ba8d1a3b438)

for all other DS the template names are clickable

**Comment by TheWitness** [comment] 2023-11-05 16:43
What spine version?  Just delete the Data Sources to close this down.  But I'm curious how this happened.

**Comment by hvspa** [comment] 2023-11-05 16:52
spine version- i downloaded and compiled the layest version 1.2.25
for deleting, i can delete of course, just wondering what i will lose? how happened, like always i did the yum cacti update. almost every time i do that i am facing similar issues


Sent from Yahoo Mail for iPhone


On Sunday, November 5, 2023, 20:44, TheWitness ***@***.***> wrote:




What spine version? Just delete the Data Sources to close this down. But I'm curious how this happened.

**Comment by TheWitness** [comment] 2023-11-05 17:10
Well, if you are worried about that, you can note the name of the RRDfile and then copy it over the new one.  Just copy the old file over the new one.

**Comment by TheWitness** [comment] 2023-11-05 17:10
Just closing for house cleaning, but we can keep talking.

**Closed as completed by TheWitness** 2023-11-05 17:10 UTC
Labels: support

**Comment by hvspa** [comment] 2023-11-05 17:30
> Well, if you are worried about that, you can note the name of the RRDfile and then copy it over the new one. Just copy the old file over the new one.

can i ask you to help me with steps how do i do that?

thanks in advance

**Comment by TheWitness** [comment] 2023-11-05 18:37
```sql
SELECT local_data_id, rrd_path FROM poller_item WHERE local_data_id IN(?, ?, ?)
```

Then backup the RRDfiles and recreate and copy old to new.

**Comment by hvspa** [comment] 2023-11-05 19:29
thanks, i know the rrd files, which stopped to work after upgrade. i am wondering what do i need to recreate? DS? if yes, how?

**Comment by hvspa** [comment] 2023-11-05 19:35
this is the diff between working and non-working, for 3244 and 3249 rrd_name is missing, while for 324 it is present (not sure how it disappeared after upgrade):

```
MariaDB [cacti]> SELECT local_data_id, rrd_name, rrd_path, arg1 FROM poller_item WHERE local_data_id IN(3244, 3249);         
+---------------+----------+--------------------------------------------------------+-----------------------------------------------------------+
| local_data_id | rrd_name | rrd_path                                               | arg1                                                      |
+---------------+----------+--------------------------------------------------------+-----------------------------------------------------------+
|          3244 |          | /usr/share/cacti/rra/nn_rrdsprocessed_3244.rrd | /usr/share/cacti/scripts/ss_poller.php ss_poller          |
|          3249 |          | /usr/share/cacti/rra/nn_active_3249.rrd        | /bin/php -q /usr/share/cacti/scripts/cacti_user_stats.php |
+---------------+----------+--------------------------------------------------------+-----------------------------------------------------------+
2 rows in set (0.000 sec)

MariaDB [cacti]> SELECT local_data_id, rrd_name, rrd_path, arg1 FROM poller_item WHERE local_data_id IN(324);       
+---------------+-------------+------------------------------------------------------+-----------------------------+
| local_data_id | rrd_name    | rrd_path                                             | arg1                        |
+---------------+-------------+------------------------------------------------------+-----------------------------+
|           324 | traffic_in  | /usr/share/cacti/rra/mirror_traffic_in_324.rrd | .1.3.6.1.2.1.31.1.1.1.6.21  |
|           324 | traffic_out | /usr/share/cacti/rra/mirror_traffic_in_324.rrd | .1.3.6.1.2.1.31.1.1.1.10.21 |
+---------------+-------------+------------------------------------------------------+-----------------------------+
2 rows in set (0.000 sec)

MariaDB [cacti]> 
```

**Comment by hvspa** [comment] 2023-11-05 19:37
or the linked graphs disappeared.

**Comment by TheWitness** [comment] 2023-11-05 19:44
The simple answer, delete and re-create the graphs.  How it happened, for me to answer that I would have to be an oracle, which I'm not.

**Comment by hvspa** [comment] 2023-11-06 04:51
ok :) thanks anyways. since i am not sure which graphs I need to recreate, i will just leave the DS as disabled. if later one someone complains, will go from there. thanks again!
