### ISSUE TITLE
No graphs plotting: Device is down. But it is not!

### ISSUE THREAD

**Issue by NotAProfessionalDeveloper** [Cacti/cacti#2549] opened 2019-03-20 14:11 UTC
Some of our hosts are experiencing this issue.

From debug log:

```
2019/03/20 15:01:31 - PING Device[161] PING: ICMP Ping Success (1.065 ms)
2019/03/20 15:01:31 - PING Device[161] SNMP: Device did not respond to SNMP
2019/03/20 15:01:31 - POLLER: Poller[1] Device[161] STATUS: Device 'XXX' is Down.
```

From web interface: SNMP info is displayed!

![image](https://user-images.githubusercontent.com/277893/54690628-197b6800-4b22-11e9-9569-87f6286ed9b6.png)

So which is true?

Cacti 1.2.2, Poller: cmd.php

**Comment by netniV** [comment] 2019-03-20 14:28
So the down status is because the SNMP side of the "Ping and SNMP Uptime" failed due to the SNMP getting no response on the OID it's requesting.

**Comment by netniV** [comment] 2019-03-20 14:29
The question is, why does the device edit page manage this, were the poller does not.  What are your SNMP settings?

**Comment by NotAProfessionalDeveloper** [comment] 2019-03-20 18:44
The problem is with the SNMP session. Here:
```
function cacti_snmp_session_get($session, $oid, $strip_alpha = false) {
...
      try {
    $out = $session->get($oid); <----
  } catch (Exception $e) {
    $out = false;
  }
```
$out evaluates to false. (The $session object exists, and there is no exception.)

I've tried putting "cacti_log" and "file_put_contents()" into `private function uniget($command, $oids) {` in order to debug. It doesn't show errors, but it doesn't output anything either.

**Comment by NotAProfessionalDeveloper** [comment] 2019-03-20 18:45
> What are your SNMP settings?

What settings do you mean apart from the device settings in the screenshot?

**Comment by NotAProfessionalDeveloper** [comment] 2019-03-20 22:47
The problem seems to be the SNMP engine ID. The hosts experiencing problems all use the same because they are based off the same template. Now we can reconfigure the hosts alright, but I would love to understand why this poses a problem. Cacti config is not specifying any engine id to use, and why would it worry if they were all the same?

**Comment by cigamit** [comment] 2019-03-24 00:21
@NotAProfessionalDeveloper keep checking and let us know.  Make sure you test with php-snmp installed and uninstalled.  We know that there are some critical enhancements that we need for php-snmp.  So, that may be the cause.

**Comment by rb83** [comment] 2019-04-25 16:52
> The question is, why does the device edit page manage this, were the poller does not. What are your SNMP settings?

Might be SELinux that denies httpd to do SNMP and/or ping. Poller runs as a different process/user alltogether. Ran into this just today. Also see #185.

**Comment by netniV** [comment] 2019-04-26 13:53
If the $session object exists, then you wouldn't really get an error with the ->get() function unless the device was not there.  If there was no value to return, that would explain the above.  The reason you are getting no value may be in how the session is being created.  

If you are able to, can you try to log the session parameters to see if there is a difference between a session that is created for the working devices and the non-working one.

**Comment by bmfmancini** [comment] 2019-05-06 17:13
I am having a similar problem with 1.2.4 but only with a ping availability check 
The device is reachable via ping but it shows down 


Date | Mon, 06 May 2019 13:06:21 -0400
-- | --
Cacti Version | 1.2.4
Cacti OS | unix
RSA Fingerprint | 5f:c6:e7:c5:42:82:af:57:cb:65:cf:fb:38:d7:67:51
NET-SNMP Version | NET-SNMP version: 5.7.3
RRDtool Version Configured | 1.7.0+
RRDtool Version Found | 1.7.0
Devices | 11
Graphs | 99

![image](https://user-images.githubusercontent.com/13388748/57241887-10762580-7000-11e9-90f8-7dd0f3539d30.png)


![image](https://user-images.githubusercontent.com/13388748/57241909-2683e600-7000-11e9-8c79-4863053c8b5c.png)


I am using spine  all other graphs that use SNMP as a avalibility check are working 


Here is the output from the graph debug  you can see that RRD is getting the values from ping but the graph is not building  because the device is showing down

AREA:cdefcj#F51D30FF:  \
GPRINT:a:AVERAGE:'Min\:%8.2lf ms'  \
GPRINT:b:AVERAGE:'Avg\:%8.2lf ms'  \
GPRINT:c:MAX:'Max\:%8.2lf ms'  \
GPRINT:e:AVERAGE:'Dev\:%8.2lf ms\n'  \
COMMENT:'Avg Latency\:'  \
LINE1:b#00BD27FF:'\n'

**Comment by bmfmancini** [comment] 2019-05-06 17:16
Ok weird so this seems to be an issue with spine 

I switched from spine to cmd.php as the poller type and we are up now ....Interesting

**Comment by bmfmancini** [comment] 2019-05-06 17:23
Here is my spine output

SPINE: Using spine config file [/etc/cacti/spine.conf]
SPINE: Version 1.2.2 starting
2019/05/06 13:20:34 - SPINE: Poller[1] DEBUG: In Poller, About to Start Polling of Device for Device ID 38
2019/05/06 13:20:34 - SPINE: Poller[1] Device[38] DEBUG: Entering ICMP Ping
2019/05/06 13:20:34 - SPINE: Poller[1] Device[38] DEBUG: ICMP Device Alive, Try Count:1, Time:5.4519 ms
2019/05/06 13:20:34 - SPINE: Poller[1] Device[38] HT[1] Device has no information for recache.
2019/05/06 13:20:34 - SPINE: Poller[1] Device[38] HT[1] NOTE: There are '1' Polling Items for this Device
2019/05/06 13:20:35 - SPINE: Poller[1] Device[38] HT[1] DS[307] SS[0] SERVER: /var/www/html/cacti/scripts/ss_fping.php ss_fping '****' '20' 'ICMP' , output: min:5.3720 avg:5.4098 max:5.4480 dev:0.0191 loss:5.0000
2019/05/06 13:20:35 - SPINE: Poller[1] Device[38] HT[1] Total Time:   1.4 Seconds
2019/05/06 13:20:35 - SPINE: Poller[1] Device[38] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
2019/05/06 13:20:35 - SPINE: Poller[1] DEBUG: The Value of Active Threads is 0 for Device ID 38
2019/05/06 13:20:36 - SPINE: Poller[1] DEBUG: In Poller, About to Start Polling of Device for Device ID 41
2019/05/06 13:20:36 - SPINE: Poller[1] Device[41] DEBUG: Entering ICMP Ping
2019/05/06 13:20:36 - SPINE: Poller[1] Device[41] DEBUG: ICMP Device Alive, Try Count:1, Time:3.4319 ms
2019/05/06 13:20:36 - SPINE: Poller[1] Device[41] HT[1] Device has no information for recache.
2019/05/06 13:20:36 - SPINE: Poller[1] Device[41] HT[1] NOTE: There are '1' Polling Items for this Device
2019/05/06 13:20:37 - SPINE: Poller[1] Device[41] HT[1] DS[343] SS[0] SERVER: /var/www/html/cacti/scripts/ss_fping.php ss_fping '8.8.8.8' '20' 'ICMP' , output: min:3.4180 avg:3.4455 max:3.4760 dev:0.0130 loss:0.0000
2019/05/06 13:20:37 - SPINE: Poller[1] Device[41] HT[1] Total Time:  0.32 Seconds
2019/05/06 13:20:37 - SPINE: Poller[1] Device[41] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
2019/05/06 13:20:37 - SPINE: Poller[1] DEBUG: The Value of Active Threads is 0 for Device ID 41
SPINE: Time: 7.7001 s, Threads: 1, Devices: 11
root@cacti-lab:/usr/local/spine/bin# ^C
root@cacti-lab:/usr/local/spine/bin#

**Comment by bmfmancini** [comment] 2019-05-06 17:25
I re-compiled spine all good on my end now

**Comment by cigamit** [comment] 2019-05-12 11:59
I'm going to go ahead and close this @NotAProfessionalDeveloper is everything working on your end with the latest develop?  I'm just tying up a few loose ends before we attempt the 1.2.4 release.  We are having some issues as @netniV has been in an accident, and therefore were are in a bit of a holding pattern on the release.

**Closed** 2019-05-12 11:59 UTC
Labels: unverified
