### ISSUE TITLE
Network Discovery Range Does not Save Custom Reachability Settings

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#3918] opened 2020-11-12 12:12 UTC
# Describe the bug

Network Discovery Range Does not Save Custom Reachability Settings.

## To Reproduce

Go to Network -> Create your Network Filters -> Modify Any custom Reachability Settings -> Save
If you reload the page the Sttings on the bottom (Reachabiliy) goes back to default.

## Expected behavior

If you make custom changes, I expect to keep the custom change..

## Screenshots // Gif
![ff](https://user-images.githubusercontent.com/57998098/98938528-ef896d00-24df-11eb-90e7-17c158f6f0da.gif)

## Versions

- Browser - chrome
- Cacti Version - 1.2.14
- Docker Version - 19.03.10

## Additional context

I'm Running a Container with external mysql Database.
And uMatrix Plugin is Disabled.

**Comment by zuka1337** [comment] 2020-11-12 12:23
Also for **Notification Settings**, if you enable with your custom config then save, it will auto-disable..

**Comment by bmfmancini** [comment] 2020-11-12 12:36
Can you do that same thing but open up your browser console in the dev
tools do any errors come up ?

Also anything in the cacti log ?

**Comment by zuka1337** [comment] 2020-11-12 13:11
No erros on the console or logs, is going to seem a bit crazy, but now is working.
The error apeear once in a while as I've shown in the gif.
Suspicious..

Where you able to reproduce?

**Comment by zuka1337** [comment] 2020-11-12 13:15
This happends when this windows is not shown (As in the gif):

![image](https://user-images.githubusercontent.com/57998098/98944461-fcf72500-24e8-11eb-8004-f19e9163884e.png)

**Comment by netniV** [comment] 2020-11-17 23:14
That would be correct, which suggests that an error is occurring in your PHP/Apache logs or the cacti ones.  If not, it would require some diagnostics of the program flow against your db.

**Comment by TheWitness** [comment] 2020-11-18 12:10
Very odd.

**Comment by TheWitness** [comment] 2020-11-20 14:11
I'm unable to reproduce this with the latest 1.2.15.  We really need some diagnostic data, do you have entries in your Cacti log after saving?  Are you missing those columns in your automation_networks table?  Is this an upgrade, or new install?

**Comment by TheWitness** [comment] 2020-11-20 14:13
All values are saved.  Logic is sound.

![image](https://user-images.githubusercontent.com/1439914/99809677-a3a67b80-2b10-11eb-8a5a-2d901a1d67ea.png)

**Comment by zuka1337** [comment] 2020-11-20 14:35
Well, I think I may know what cause this issue..
- Before this happend, I did an network scan which din't resolve the snmp options (Normal, cause I did not choose any snmp options).

**Comment by zuka1337** [comment] 2020-11-20 15:55
You may close this one.

**Comment by TheWitness** [comment] 2020-11-22 14:41
Just note that you can also close these on your own.  I'll close this one this time though.

**Closed by TheWitness** 2020-11-22 14:41 UTC
Labels: bug, unverified
