### ISSUE TITLE
Cacti 1.2.7 | Automation | Graph Rules not working

### ISSUE THREAD

**Issue by azefanas** [Cacti/cacti#3223] opened 2020-01-29 11:51 UTC
Hello, 

I'm using cacti 1.2.7 and my Graph Rules are not working automatically, I got a new device added but the graphs are not been created automatically. 

![image](https://user-images.githubusercontent.com/60429626/73354406-8e184a80-428d-11ea-9112-7c864e32a5d8.png)

![cmtszinho](https://user-images.githubusercontent.com/60429626/73353876-46dd8a00-428c-11ea-9d47-403199f1dfe2.png)

On  cacti setting, I got "Enable Automatic Graph Creation" active 

![image](https://user-images.githubusercontent.com/60429626/73353981-7e4c3680-428c-11ea-8fda-18897270b96d.png)

I would like to have this working for new devices and if any of my devices add a new interface they auto-create the graph 

If I run manually the automation rule on the device, it works with no problem, but automatically is not working, does it have any log that I can find the reason of this issue? On  cacti.log I have no error about this.

**Comment by cigamit** [comment] 2020-01-29 17:35
Do you have an automation network setup with a schedule set?

**Comment by azefanas** [comment] 2020-01-29 19:32
I don't have any network setup configured. 

Is it necessary to update devices? Because on cacti documentation it says this option is to add new hosts found on the network and I don't want to add them automatically, just update interface and graph

If it is necessary, how can I configure "Subnet Range" to get all the devices I already have, I got 1.4k devices and lots of them use public IP, is almost impossible to collect and create network setup for each one.

All that I want is just create a new graph when a network interface comes UP

**Comment by cigamit** [comment] 2020-01-29 19:56
For the Network, unless the option "Automatically Add to Cacti" is checked, its not going to add any new devices to Cacti.  You also have to enable the option "Rerun Data Queries" for it to find new interfaces.  With how your network is setup, this is probably not feasible.

The only other way do what you want would be to script it yourself via the CLI commands.

**Comment by azefanas** [comment] 2020-01-30 12:00
I did a Network setup for the specific host but still doesn't apply the Graph rule 

![image](https://user-images.githubusercontent.com/60429626/73447045-d733d180-4355-11ea-87b4-c08e943e4033.png)

![image](https://user-images.githubusercontent.com/60429626/73447247-372a7800-4356-11ea-9515-38fda927b4c4.png)

Debug mode


![image](https://user-images.githubusercontent.com/60429626/73447690-30503500-4357-11ea-8ba2-912f82616559.png)

Rule: 

![image](https://user-images.githubusercontent.com/60429626/73448130-195e1280-4358-11ea-955f-8b2b0cf89a2e.png)

**Comment by cigamit** [comment] 2020-01-31 00:49
![AutomationSettings](https://user-images.githubusercontent.com/957322/73503202-36630780-4391-11ea-8260-115ac81b3740.PNG)

You might want to confirm these settings too.

**Comment by azefanas** [comment] 2020-01-31 10:55
I got the Graph enabled 

![image](https://user-images.githubusercontent.com/60429626/73533590-1bd37180-4417-11ea-9c63-ec75328788c1.png)

Does Automation need the other rules to work or it can just have "Network" + "Graph Rule" created?

**Comment by cigamit** [comment] 2020-01-31 14:13
Okay, that's good.  So, the devices, are they already in Cacti?  If so, goto the Devices page, select the devices that you wish to run automation on, and from the drop down, select Run Automation on them and see if the graphs are created.  Maybe we should add that to the rules section as well.

If the graphs are then created, you should ensure that 'Rerun Data Queries' is checked on which will force the creation of new Data Query graphs if an existing device is found.  If that is in fact selected, then we have a bug.  It might be wise to rename that setting too, since it does not really completely document or infer what will really happen.

**Comment by irocosta** [comment] 2020-02-04 12:39
If I apply the change manually on the device "Run Automation" it creates the graphic but if I got a new port UP on this device the rule is not applied automatically

**Comment by TheWitness** [comment] 2020-03-15 18:10
I think this is a duplicate of #3261.  So, I'm going to close.

**Comment by TheWitness** [comment] 2020-04-05 17:05
Please retest after upgrading to 1.2.11.  If the issue persists there, please open a new ticket.  Also, please verify that your Automation Templates are intact.  We found an upgrade bug that was removing them and this might be the root cause for the automation not working as expected.

**Closed by TheWitness** 2020-04-05 17:05 UTC
Labels: automation, duplicate
