### ISSUE TITLE
memory error during graph export

### ISSUE THREAD

**Issue by dsclassen** [Cacti/cacti#252] opened 2017-02-02 00:28 UTC
Not sure if this should be submitted here or under the gexport project.

```
2017-02-01 16:25:30 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4276 cacti_debug_backtrace)
2017-02-01 16:25:30 - ERROR PHP ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in file: /cacti/lib/rrd.php on line: 762
```

**Comment by ronytomen** [comment] 2017-02-02 00:40
You need to increase the PHP `memory_limit` configuration setting to more than 128M.  This is not a code issue, but a configuration issue.

Yes, we could set it in the script, but we can not determine how much memory will be needed.

Also, this is a plugin issue.

**Comment by dsclassen** [comment] 2017-02-02 00:41
yep. I figured as much.
I increased to 512M and it's still running out of memory. I'll take this issue over to gexport.
thanks

**Comment by ronytomen** [comment] 2017-02-02 02:12
Sorry if I seemed blunt.  I just want to make sure issues are created in the correct places. :)

**Comment by cigamit** [comment] 2017-02-02 03:11
I'm a bit mystified.  There has to be a memory leak somewhere in rrdtool calls.  There are a number of potential exec() and shell_exec() calls as well as fopen()/fclose() activities.  When you log the bug in the gexport area, please let us know the number of graphs you are exporting, and the OS and PHP versions too.

**Comment by cigamit** [comment] 2017-02-02 03:21
Okay, this is not a bug in gexport.  It's a bug in the rrdtool_function_fetch() call.  I'm re-opening as it needs to be fixed in core.

**Comment by cigamit** [comment] 2017-02-02 03:23
It's also not being caused by gexport but likely by data source statistics.  Tell me again about how many data sources you have?

**Comment by cigamit** [comment] 2017-02-02 03:26
Also, please let me know the number of thresholds you have?

**Comment by cigamit** [comment] 2017-02-02 03:31
Okay, so here is the deal.  Every time thold fetches the current data, it stores a md5 hash of a number of metrics into a cache array.  This is really not required since, in general, once the fetch array is loaded for a local_data_id, it's only used once for that data collector pass.  So, caching it has no value.

There 'could' be a potential slowdown due to excessive forks of the rrdtool command, which is an additional bug that we need to address, in other words, we open a pipe to rrdtool at the beginning of every poller run, and unfortunately, the rrdtool_function_fetch() function does not use the pipe.  So, you get quite a few forks of rrdtool when checking thresholds.

I'll open that as a separate performance bug.  One for Cacti and another for thold.  In the mean time, please test with the updated rrd.php.

**Comment by dsclassen** [comment] 2017-02-02 04:32
```
SYSTEM STATS: Time:11.4646 Method:spine Processes:2 Threads:10 Hosts:44 HostsPerProcess:22 DataSources:707 RRDsProcessed:0
```
CentOS 7 - Linux 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64
PHP 5.6.5

I'm attempting to export ~380 graphs

I'll pull your latest commit and test.

**Comment by dsclassen** [comment] 2017-02-02 05:25
Still seeing the same memory error.

```
2017-02-01 21:23:09 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4276 cacti_debug_backtrace)
2017-02-01 21:23:09 - ERROR PHP ERROR: Allowed memory size of 537919488 bytes exhausted (tried to allocate 32 bytes) in file: /cacti/lib/rrd.php on line: 778
```

**Comment by cigamit** [comment] 2017-02-03 02:40
Okay, there has to be a memory leak.  I guess the trick is to find it.  Are their any updated versions of PHP available for your distro?

**Comment by dsclassen** [comment] 2017-02-03 18:34
I could try php7.... makes me very scared though. What is the current state of php7 support within the cacti code?

**Comment by ronytomen** [comment] 2017-02-03 21:58
What version of PHP is being use to run Graph Exports?

**Comment by cigamit** [comment] 2017-02-03 23:22
Before you go there, let me commit an instrumented poller_gexport.php that will output memory consumption to standard output when run by hand in debug mode, and let's see if we can find the leak.

**Comment by cigamit** [comment] 2017-02-03 23:38
Okay, I have added instrumentation.  Here are the instructions:

cd /var/www/html/cacti/plugins/gexport
php -q poller_export.php --force --debug --id=yourid

You should see the memory creeping up.

**Comment by dsclassen** [comment] 2017-02-04 01:27
I tried your debug script. I see lots of lines, and the MEMUSE does creep up a wee bit,but not much. It starts at about MEMUSE: 8,000,000 and get up to about MEMUSE: 10,000,000.

example output:

```
OK u:15.69 s:1.00 r:257.78
MEMUSE: 9,922,264, MESSAGE: Creating Graph '/cacti_export/graphs/graph_2923.png'
MEMUSE: 9,921,768, MESSAGE: Creating File  '/cacti_export/graph_2923.html
MEMUSE: 9,923,208, MESSAGE: Creating Graph '/cacti_export/graphs/graph_2923_6.png'
MEMUSE: 9,923,304, MESSAGE: Creating Graph '/cacti_export/graphs/graph_2923_7.png'
703x213
OK u:15.71 s:1.00 r:257.90
MEMUSE: 9,923,304, MESSAGE: Creating Graph '/cacti_export/graphs/graph_2923_8.png'
MEMUSE: 9,923,304, MESSAGE: Creating Graph '/cacti_export/graphs/graph_2923_9.png'
703x241
OK u:15.74 s:1.00 r:257.96
MEMUSE: 9,923,304, MESSAGE: Creating Graph '/cacti_export/graphs/graph_2923_10.png'
MEMUSE: 9,921,824, MESSAGE: Exporting Graph ID: 2924
MEMUSE: 9,922,720, MESSAGE: Creating Graph '/cacti_export/graphs/thumb_2924.png'
MEMUSE: 9,922,464, MESSAGE: Creating Graph '/cacti_export/graphs/graph_2924.png'
703x241
OK u:15.77 s:1.01 r:258.11
MEMUSE: 9,921,968, MESSAGE: Creating File  '/cacti_export/graph_2924.html
MEMUSE: 9,923,408, MESSAGE: Creating Graph '/cacti_export/graphs/graph_2924_6.png'
MEMUSE: 9,923,504, MESSAGE: Creating Graph '/cacti_export/graphs/graph_2924_7.png'
MEMUSE: 9,923,504, MESSAGE: Creating Graph '/cacti_export/graphs/graph_2924_8.png'
MEMUSE: 9,923,504, MESSAGE: Creating Graph '/cacti_export/graphs/graph_2924_9.png'
MEMUSE: 9,923,504, MESSAGE: Creating Graph '/cacti_export/graphs/graph_2924_10.png'
703x241
OK u:15.80 s:1.01 r:258.30
MEMUSE: 9,922,024, MESSAGE: Exporting Graph ID: 2915
MEMUSE: 9,922,920, MESSAGE: Creating Graph '/cacti_export/graphs/thumb_2915.png'
MEMUSE: 9,923,840, MESSAGE: Creating Graph '/cacti_export/graphs/graph_2915.png'
703x241
OK u:15.84 s:1.01 r:258.59
703x241
```

and later on:

```
MEMUSE: 10,074,056, MESSAGE: Creating Graph '/cacti_export/graphs/graph_3019_6.png'
703x227
OK u:32.60 s:1.68 r:1182.46
MEMUSE: 10,074,168, MESSAGE: Creating Graph '/cacti_export/graphs/graph_3019_7.png'
703x255
OK u:32.64 s:1.68 r:1196.27
MEMUSE: 10,074,136, MESSAGE: Creating Graph '/cacti_export/graphs/graph_3019_8.png'
703x255
OK u:32.66 s:1.68 r:1197.17
MEMUSE: 10,074,152, MESSAGE: Creating Graph '/cacti_export/graphs/graph_3019_9.png'
703x255
OK u:32.67 s:1.68 r:1199.38
```

seems like an awefully long time to export these graphs:

```
2017-02-03 17:25:36 - EXPORT STATS: ExportID:2 ExportDate:2017-02-03_17:25:36 ExportDuration:1966.97 TotalGraphsExported:361
2017-02-03 17:25:36 - EXPORT MASTER STATS: Time:1966.97 Exports:1 Exported:1
```

**Comment by cigamit** [comment] 2017-02-04 02:43
So, what happens when you force running from the GUI?  Is it finishing then?

**Comment by cigamit** [comment] 2017-02-08 00:29
Assuming this is resolved since there has been no feedback.

**Closed by cigamit** 2017-02-08 00:29 UTC
