### ISSUE TITLE
Double vertical scroll bars version 1.1.23

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1172] opened 2018-01-05 10:49 UTC
In cacti classic theme double scroll bars appears.
please find the attached screen shot.
![screenshot_1](https://user-images.githubusercontent.com/35136010/34606289-d1f27948-f234-11e7-92e4-5f985151c700.png)

**Comment by pautiina** [comment] 2018-01-05 10:58
And what about the latest version of Cacti?
Try update and look for this problem again.

**Comment by netniV** [comment] 2018-01-05 11:04
I was literally typing that out myself :)  

I'm not sure it will make a difference after readlng the docs/CHANGELOG but it's always worth a try.  The latest mention of scrollbars was 1.1.20.

**Comment by pautiina** [comment] 2018-01-05 11:10
On my Cacti 1.30 and Firefox I dont have this problem:
![73](https://user-images.githubusercontent.com/11805503/34606885-bd6bdbd8-f219-11e7-8289-58c59528522e.png)

**Comment by netniV** [comment] 2018-01-05 11:21
I don't have the issue either on Chrome, could be a local issue or unique layout issue that doesn't affect us.  Will see what happens if the upgrade is done.

**Comment by cigamit** [comment] 2018-01-05 13:21
There was an issue a few releases ago about this.  It should be fixed in the latest release.  The bug was caused by a miscalculation of the #main window and effected a few of the themes.

**Comment by chathurag** [comment] 2018-01-10 03:20
@pautiina 
Even I upgrade the cacti from version 1.1.20 to 1.1.30 double scroll bar issue exists.

**Comment by cigamit** [comment] 2018-01-12 23:32
Please refresh your:

http://cacti/include/themes/classic/main.css 
http://cacti/include/themes/classic/main.js

files.  Basically load the above URL's into your browser, and then once you can see the text, hit Ctrl-R (to reload them into the cache), and then it should render fine.  I can not reproduce this issue.

**Comment by cigamit** [comment] 2018-01-12 23:33
If that does not work, verify that you are using the latest Chrome.

**Closed by cigamit** 2018-01-12 23:32 UTC
