### ISSUE TITLE
SNMP wont pull port details if it fails the first pull

### ISSUE THREAD

**Issue by Alkanov** [Cacti/cacti#2378] opened 2019-02-06 12:15 UTC
To replicate it:

1. Create a Cisco device that doesnt have the SNMP community configured, cacti will fail to add the device cause it cannot get to it (fine)
2. Add the SNMP community config to your Cisco device
3. On the same screen where you got the error before (add device page), hit create again. It will add the device this time but wont pull any information (like port details) than the basics - now you have to delete the device and add it again.

**Comment by cigamit** [comment] 2019-02-06 13:26
What feature are you talking about?

**Comment by Alkanov** [comment] 2019-02-06 15:59
What do you mean? Cacti->Device->Add

**Comment by cigamit** [comment] 2019-02-07 02:42
Just re-index the host.  Green thingy to the right of the Query.  This is not a bug.  So, closing.

**Closed by cigamit** 2019-02-07 02:42 UTC

**Comment by Alkanov** [comment] 2019-02-07 11:29
Alright if it's not a bug it's definitely a weird behavior as it doesn't re-index itself when re-adding the device

**Comment by cigamit** [comment] 2019-02-07 13:27
Well, if the SNMP information is wrong on first creating the device, it actually can not index.  After the device has been created, we could make re-indexing automatic upon edit, but for some devices, that re-index can take in excess of a minute.

To work around this, we provide CLI tools too allow you to schedule re-index operations either from cron, and we also provide the ability to re-index known Devices on a schedule through the Automation Networks part of Cacti.  During discovery passes, if a Device is found that is already in Cacti, the automation process can optionally re-index those Devices automatically.

So, in the case where companies have defined specific subnets that include their switches, routers, etc., having this option makes it very convenient to keep the system in good working order.
