### ISSUE TITLE
exporting graph templates with all dependency from higher version of cacti to lower one

### ISSUE THREAD

**Issue by gj00354347** [Cacti/cacti#4138] opened 2021-02-19 11:17 UTC
Dear Developers ,

we have cacti 1.2.16 in test environment and in prod we have 1.2.14 , and we have developed some new data templates and graph templates in Test and want to export those graph templates with all dependencies to Prod Environment .

But cacti complains that export from higher version to lower version does not work . I understand with every new release you have some new feature added and those are lacking in the previous version of cacti which makes or has the potential to make graph template incompatible in bot the environment .

but what if my data templates and graph templates have not used any new feature ,so it is possible like while we do export of data templates and graph templates from higher version of cacti (1.2.16) , we edit some field in the export  where this cacti version is mentioned and make them to lower version (1.214) and export works .

I believe this would be a nice feature addition , like generally we update Cacti in Test First and then we move to Prod . So during this period , development do not stop and that's being done in Test Version which is a higher one and then moving graph templates manually to Prod becomes a very tedious task .

Best Regards,
Gopal

**Comment by TheWitness** [comment] 2021-02-19 11:19
This is more of a bug than a feature request.

**Comment by netniV** [comment] 2021-02-21 15:35
I am not sure that we should classify that as a bug.  There are working features that may not necessarily be new but have been fixed and tested with the template against that version.  Exporting to an older version isn't guaranteed to work and therefore increases the likelihood of issues being raised purely due to the mismatch of versions.

**Comment by cigamit** [comment] 2021-02-22 01:01
Definitely not a bug, its actually a feature to protect you from destroying another system with a lower version.  Your development version and production version should be like for like before trying to migrate things.

**Comment by TheWitness** [comment] 2021-02-22 03:41
Well, technically speaking the version code hash is what dictates compatibility.  When we add new columns to the templated tables, we presently need to bump that.  It's at 102 I think now.

**Comment by TheWitness** [comment] 2021-02-23 13:15
Moving this to an enhancement category.

**Comment by bernisys** [comment] 2021-04-11 16:37
Do you still intend to push that enhancement into 1.2.17? Because from my point of view i think it is not that critical, as once we are on 17 on both test and prod systems, we can freely migrate templates again (Gopal, the reporter, is one of my colleagues).
Still worth looking into, but maybe not in this version, as it might delay the release too much.

**Closed** 2021-09-05 15:29 UTC
Labels: enhancement
