### ISSUE TITLE
Add ability to export Autom8 networks to CSV

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3705] opened 2020-07-19 02:51 UTC
Hey guys 

one thing that would be very useful would be to have the ability to export the subnets and description to a CSV file 
this can help for auditing and such a output like below is what I pulled from a DB query  which I found helpful

MariaDB [cacti]> select name,poller_id,subnet_range,last_started,last_status,site_id  from automation_networks;
+--------------+-----------+----------------+---------------------+-------------+---------+
| name         | poller_id | subnet_range   | last_started        | last_status | site_id |
+--------------+-----------+----------------+---------------------+-------------+---------+
| Test Network |         3 | 192.168.1.0/24 | 2020-07-17 01:00:03 |             |       0 |
| test456      |         1 | 192.168.2.0/24 | 0000-00-00 00:00:00 |             |       1 |
+--------------+-----------+----------------+---------------------+-------------+---------+
2 rows in set (0.01 sec)

**Comment by TheWitness** [comment] 2023-04-22 17:02
Duplicate of #412

**Closed by TheWitness** 2023-04-22 17:02 UTC
Labels: duplicate, enhancement, automation
