### ISSUE TITLE
Remote collectors share same path configuration for spine

### ISSUE THREAD

**Issue by stefanbrudny** [Cacti/cacti#2529] opened 2019-03-16 23:41 UTC
Spine binary location and configuration is shared among cactis, while it should not be.

1. add remote pollers
2. change default path on one of remote pollers
3. observe changes propagated to other pollers and main cacti

Expected behavior
It is expected change of path is valid for one poller only

Additional context
This blocks the corner case to use different pollers in same IPv4 networks using linux kernel namespaces. Currently, this seems to be the only blocker, but there are potentially others on the road. 

This is to scale Cacti way beyond to what any of Cacti developer ever imagined. Last time, this effort ultimately failed on 170k devices, this time I would like to poll approx 207k devices.

**Comment by cigamit** [comment] 2019-03-17 00:02
So, the only thing that I see potentially blocking on this might be the poller_output_boost table.  To overcome that limiting factor, we can do an enhancement to create separate poller_output_boost tables per data collector.

Since each poller is completely independent of the mother ship now, I'm curious to see where you hit the wall.  How many graphs were you going to create for each device?

**Comment by stefanbrudny** [comment] 2019-03-17 00:57
Well, that's good approach. I am testing it now, and I wouldn't say separation is  sufficient, but I'll come to this later. 

Number of graphs have never been any problem for me, all sorts of issues hits much earlier than performance of decent server is saturated. I tested 1.2.2 thoroughly, and here was no to little improvement in what I require to accept a solution at scale. 

https://forums.cacti.net/viewtopic.php?f=21&t=54036&start=15

**Comment by cigamit** [comment] 2019-03-17 01:22
Well, the appropriate place to open bugs, performance and scalability wise will be here.  I'm sure @netniV, would be more than interested to investigate how things are working at this scale.  Separate bugs of course.

**Comment by cigamit** [comment] 2019-03-17 13:50
This issue is a known issue.  Something we need to document better, though, I do believe that it is documented already, just maybe not in big bold letters.  We've tried to give users some flexibility, but officially, we have stated that we need a uniform directory space.  Easier said than done, especially if you want your data collectors to be Windows and your server to be Linux.

**Comment by cigamit** [comment] 2019-03-17 13:53
This is a duplicate of the following https://github.com/Cacti/cacti/issues/2125

**Comment by TheWitness** [comment] 2020-03-17 01:22
This issue is resolved now.  Each data collector saves it's own paths including spine.

**Closed** 2020-03-17 01:23 UTC
Labels: bug, duplicate, known issue, resolved
