### ISSUE TITLE
Cacti Version 1.2.16 login problem

### ISSUE THREAD

**Issue by mosharaflink** [Cacti/cacti#3986] opened 2020-12-05 18:47 UTC
After upgrading cacti version 0.8.8h to Version 1.2.16 getting an authentication problem for a new user but the previous user is working well. New user login error as follows:

2020-12-05 19:18:48 - AUTH LOGIN: User 'admin' Authenticated
2020-12-05 19:18:48 - AUTH LOGIN: Local Login Failed for user '' from IP Address '202.84.42.5'.

OS: CentosV7
cacti new version : 1.2.16
Cacti Old version : 0.8.8h

**Comment by TheWitness** [comment] 2020-12-05 18:51
Edit the user and verify that:

1) They have access to the View Graphs permission.
2) Ensure that they have access to the graphs that are required.

If the users (plural), lost access to Graph View, and they are based upon a Template user, and their realm is either Web Basic, or LDAP, you can simply delete their accounts and they will be re-mapped to the Template account.

Note that the permission system changed drastically between Cacti 0.8.x and Cacti 1.2.x.  So, you may have had permissions assigned to users in previous versions that worked out of only some freak of nature, that no longer work in the current Cacti.  The current Cacti is doing permissions in an unambiguous way though.

**Comment by mosharaflink** [comment] 2020-12-05 19:01
After creating and login with a new user show the error as follows
![Cacti login problem 2020-12-06 010116](https://user-images.githubusercontent.com/32505239/101261073-9919f200-375e-11eb-8cd4-cec75aab1ec9.png)



The page isn’t redirecting properly
Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
This problem can sometimes be caused by disabling or refusing to accept cookies.

**Comment by TheWitness** [comment] 2020-12-05 19:03
Upload screen shot of general and permissions tabs.

**Comment by mosharaflink** [comment] 2020-12-05 19:06
Can you share the details of how can I get the screenshot of general and permission tabs?

**Comment by TheWitness** [comment] 2020-12-05 19:09
![image](https://user-images.githubusercontent.com/1439914/101261201-6989cc00-3703-11eb-8920-b813909e1b7a.png)

![image](https://user-images.githubusercontent.com/1439914/101261207-7ad2d880-3703-11eb-873c-03311aa1900d.png)

**Comment by TheWitness** [comment] 2020-12-05 19:10
I guess I should edit out my email ;)

**Comment by TheWitness** [comment] 2020-12-05 19:11
There is conceivably a way to create a re-direct loop by not having the "View Graphs" page, and then also making your Default page, "View Graphs".

**Comment by TheWitness** [comment] 2020-12-05 19:23
I've removed all permissions from the a test user, and not getting there.  So, I really need a screen capture from a broken user, all tabs.

**Comment by mosharaflink** [comment] 2020-12-05 19:31
I got the error and it was a permission issue which now resolved. But getting another login issue. My cacti home directory is /var/www/html/cacti which is also soft link to another folder of cacti-0.8.8h (this folder is an upgrade version of 1.2.16 content.)
/var/www/html/cacti -> cacti-0.8.8h

while accessing the cacti through "http://mrtg.example.com/cacti is working well but while accessing http://mrtg.example.com show the following error



2020-12-06 01:28:00 - AUTH LOGIN: User 'V0032' Authenticated
2020-12-06 01:28:00 - AUTH LOGIN: Local Login Failed for user '' from IP Address '202.84.42.5'.

**Comment by TheWitness** [comment] 2020-12-05 19:33
If you do not due what you are asked, I can not help.  You need to focus on one issue at a time.  If you already resolved this issue and don't share what was done to fix it, how can I help you?

**Comment by mosharaflink** [comment] 2020-12-05 19:40
My issue is the login problem after upgrading to the new version. Here is two cases of login problem. 
1. using URL http://mrtg.example.com/cacti login is working but shows redirect problem which is now fixed by giving graph view permission
2. Using URL http://mrtg.example.com the login does works and it shows an error on the log as below which is not resolved
2020-12-06 01:28:00 - AUTH LOGIN: User 'V0032' Authenticated
2020-12-06 01:28:00 - AUTH LOGIN: Local Login Failed for user '' from IP Address 'x.x.x.x'.

**Comment by TheWitness** [comment] 2020-12-05 19:41
Show all the permission tabs for user V0032.

**Comment by mosharaflink** [comment] 2020-12-05 19:44
![v0032_permission-1](https://user-images.githubusercontent.com/32505239/101261888-78ed3180-3764-11eb-990d-e225e46ac8af.png)
![v0032_permission-2](https://user-images.githubusercontent.com/32505239/101261889-7a1e5e80-3764-11eb-8058-5d70ca49e61b.png)
Attached the file for permission of v0032 user

**Comment by TheWitness** [comment] 2020-12-05 19:55
Well, that's 2 of 8.  The general tab is the most important at this point.  Though I need to see Device, Template, and Tree as well.  If the user is a member of a graph, I'll need to see that, just general and permissions tabs.

**Comment by mosharaflink** [comment] 2020-12-05 20:03
But as I can log in successfully using an URL then what it mean to check user permission rather than the infrastructure setting. I can't login using any user for URL http://mrtg.example.com but can be using http://mrtg.example.com/cacti. 

I hope you got all the point of what I want to mean.

**Comment by TheWitness** [comment] 2020-12-05 20:04
That looks like a Web Server configuration issue there.  In the base directory you need an entry like this

```php
<?php
header('Location: ./cacti/index.php');
```

**Comment by mosharaflink** [comment] 2020-12-05 20:06
where I need to put the entry??
does it will be new file or an existing file??

**Comment by TheWitness** [comment] 2020-12-05 20:07
In my case it's:

```sh
cd /var/www/html/
vim index.php
```

In there.  Mine looks like this exactly:

```php
<?php
header("Location:cacti/index.php");
```

**Comment by TheWitness** [comment] 2020-12-05 20:08
Your system may be different if it's Debian based.  If that does not get it, it's your Web Server config, and likely the vhost definition.

**Comment by mosharaflink** [comment] 2020-12-05 20:08
my current index.php has 125 lines of code. Do I need to remove them by adding your code only??

**Comment by TheWitness** [comment] 2020-12-05 20:10
Not clue, that's not our code.  Something put in by whoever setup you site.

**Comment by TheWitness** [comment] 2020-12-05 20:33
Sounds like you know the root cause now.  Not a Cacti issue, and I'm glad for that.  Good luck.

**Closed by TheWitness** 2020-12-05 20:33 UTC
Labels: not a bug

**Comment by TheWitness** [comment] 2020-12-05 23:34
One thing you might want to check, if you open the index.php in the web root, and it's Cacti code, it'll have a copyright.  You can edit include/config.php and change the $config['url_path'] to '/';  That might be the problem.  But if it's not Cacti code, then it's some custom deal.

**Comment by mosharaflink** [comment] 2020-12-06 08:34
For graph viewing, there is an issue. After login to cacti shows not graph data on the main page but while clicking on settings of the 
![graph-1](https://user-images.githubusercontent.com/32505239/101275455-1893d980-37d0-11eb-8992-b6f38a035813.png)
![graph-2](https://user-images.githubusercontent.com/32505239/101275457-19c50680-37d0-11eb-9414-cbbfb85b49a8.png)

graph shows data is pulling. Please check the screenshot for your review.
