### ISSUE TITLE
Somewhat misleading upgrade progress

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3494] opened 2020-04-24 04:10 UTC
Here is where I got slightly misled with my recent 1.2.9 -> 1.2.11 upgrade:
![up1](https://user-images.githubusercontent.com/12864741/80174037-c25e8700-85ae-11ea-8ee2-1bb83b741d94.png)

I see the "Finished UPGRADE" log message. But I'm stuck at 77% and my Last Updated counter was stuck for 3 minutes. 

SO I went and hooked an strace onto the background.php. I saw it was still doing stuff. SO I waited. Then it finally finished. But it seemed like something was "stuck" here. 

Plus, the output of the log file is bottom to top, which is also kinda strange. The refresh bar would keep spinning, but nothing else would change. Perhaps something else that can make it clear the installer is actually still doing something ... would be helpful. I was using Firefox .. and older version, and I did not try to hit the refresh icon in the upper right. 

No big deal if there's nothing to be done here, I just felt a bit uncomfortable at this point in the install.

**Comment by TheWitness** [comment] 2020-04-24 12:18
Well that is indeed odd.  Were you able to capture any of the queries that were running?  You unchecked all the templates according to your other bug, so it wasn't that process.  I'm wondering what else it could have been doing.

**Comment by netniV** [comment] 2020-04-26 17:35
I am wondering if this related to the package changes.  Unfortunately, not sure whether this is before or after that fix.

**Comment by TheWitness** [comment] 2020-04-26 18:16
Well, the way that it was before, it would import the package and what was causing the lockups (which were not lockups at all), it is was removing orphans from each graph.  If you have like 60k graphs, that's going to take a while, at least the way the process it today.

Long term, we should only store graph data that overrides the template.  That way we would have a whole lot less graph_templates_item rows and data_input_data rows to deal with.  Those tables get real big on big installs, and it slow the graph render time:

Tables like:

```console
graph_local
data_local
data_template_data
graph_templates_graph
```

Would still be one for one, but tables like:

```console
graph_templates_item
data_input_data
data_template_rrd
```

Could shrink dramatically.  Also, with less clutter, it'll be easier to perform other re-design tasks associated with Template and Package versioning.

**Comment by netniV** [comment] 2020-04-27 12:49
Yes, definitely a future enhancement.  Not sure why you would have such a late progress stop.  I suspect this may have been a race condition where something took slightly longer to finish so set the progress value back to a lower setting, whilst the status was marked completed (they are two separate fields).

**Comment by netniV** [comment] 2020-04-27 12:49
I think we should close this since I haven't been able to reproduce it and I think it's a one off.  If anyone is able to reproduce it, I will gladly reopen it.

**Closed by netniV** 2020-04-27 12:49 UTC
Labels: unverified

**Comment by eschoeller** [comment] 2020-04-28 05:14
Wow, @TheWitness that sounds like a great future enhancement. I think some of my tables would shrink drastically. I'm hoping that one gets some traction. 

My only point with this report was to highlight the fact that the log said "Finished UPGRADE" but it was not yet done and still churning away. So, the timing of that log message might need to be looked at more carefully and actually logged once the whole thing is really done. But, I am also accustomed to being a one-off situation:) My database is 10+ years old. You all have seen a copy of it:)

**Comment by netniV** [comment] 2020-04-29 13:33
Lots of queries right now expect to find direct connections, so removing them with only a potential of being there (LEFT JOIN / RIGHT JOIN) means speculative querying and that's where lots of beta testing will be needed.
