### ISSUE TITLE
Allow legends to be modified for Aggregate Graphs

### ISSUE THREAD

**Issue by frankfer01** [Cacti/cacti#3013] opened 2019-10-07 15:36 UTC
Recently I upgraded cacti from 1.2.6 to 1.2.7.  In the version 1.2.6 I reported that the legends can't be modified in aggregate graphs with the  issue #2951 and you write to me that the solution will be available in the  1.2.7. Today I have to opportunity to upgrade to this version, but is not possible modified legends. In the change log said: " issue#2951: Allow legends to be modified for Aggregate Graphs" but I can't. Yu can explain to me how I can modified legends in aggregate graphs?

**Comment by eschoeller** [comment] 2019-10-10 21:33
+1 on this one.

**Comment by cigamit** [comment] 2019-10-12 20:11
Well, it's the ability to convert Aggregate graphs to 'non-aggregate' graphs, where you can modify the legend under Console > Management > Graphs instead of Console > Management > Aggregate Graphs.

I'm not sure that there is a good programmatic way to allow legends to be extended right now under the context of a bug fix other than that.  I also allowed some 'COMMENT' lines to also be non skippable in the 1.2.x branch due to someone displaying why it should be allowed.

I guess demonstrating by example will help here.  What are you trying to accomplish?

**Comment by eschoeller** [comment] 2019-10-12 21:25
Personally, I’m just trying to fix the sort order. It seems to be entirely random. I’ll post a photo of an example. 

Eric.

**Comment by eschoeller** [comment] 2019-10-13 07:58
![image](https://user-images.githubusercontent.com/12864741/66712627-bc186400-ed5c-11e9-8128-172e5cef5697.png)
I can't understand why the "D6" sensors aren't listed first in this items list. No matter which Reorder Type I try, there is no difference. If you'd like, I'll submit a separate issue for this.

**Comment by cigamit** [comment] 2019-10-13 17:10
What re-order method did you use?  What are the names of these objects?  I have a idea.

**Comment by cigamit** [comment] 2019-10-13 17:10
Yea, this is a separate issue, but nice graph though!

**Comment by eschoeller** [comment] 2019-10-13 17:16
Heh, thanks. I've been digging the black theme, but it's got some quirks that I'll eventually figure out how to reproduce. I'll open another issue.

**Comment by frankfer01** [comment] 2019-10-14 15:22
Ok, let to explain with an example:
I have two graph of two interfaces and I want to create a aggregate graphs:"
![image](https://user-images.githubusercontent.com/55502569/66761745-f9731380-ee7a-11e9-890b-c5ac74ce977b.png)
 
![image](https://user-images.githubusercontent.com/55502569/66761765-07289900-ee7b-11e9-9581-e2c56f5a45c5.png)

This is the new graph, the legends loose and you cant modified:
![image](https://user-images.githubusercontent.com/55502569/66762209-eca2ef80-ee7b-11e9-9313-a9309a8c5abe.png)

This are the details:
![image](https://user-images.githubusercontent.com/55502569/66762044-92a22a00-ee7b-11e9-9bf9-422337c7ae78.png)

I took your suggestion and convert it to normal graph. Now the graph move from Aggregates to Graphs:
![image](https://user-images.githubusercontent.com/55502569/66762444-61762980-ee7c-11e9-9173-65a8f167868a.png)

At this point, I cant change or modify any legend.
This part it's too important to me, actually I'm using the version 0.8.8b and want to migrate to the new version. In my case it's create aggregate graph of all interface on a router. This graph will be monitored by a NOC to check the fluctuations, but the operator need to see the legends of this unique graph.

**Comment by tyit** [comment] 2019-10-16 01:34
Yes, the new version of the graphics summary has been very bad, I am currently using the 0.8.8.x series, but I can't write the code to change to the state I expected.

**Comment by frankfer01** [comment] 2019-10-31 15:22
Nobody knows if in a future version this will be fixed?

**Comment by cigamit** [comment] 2019-11-09 18:52
@frankfer01, so when you edit the converted graph, you can not edit or move the items?  That's a bug for sure.  Let me test that out on my system.  So far the convert to a normal graph has not been released.

**Comment by cigamit** [comment] 2019-11-09 18:58
Okay, update graphs.php and now when you edit the aggregate that has been converted to a normal graph, you can now edit all the items.

**Comment by frankfer01** [comment] 2019-11-11 11:55
Thanks @cigamit , how I can get the file graphs.php to make some tests?

**Comment by TheWitness** [comment] 2019-11-26 17:09
Basically simply download the branch 1.2.x and replace all the files.

**Comment by cigamit** [comment] 2019-11-29 16:53
I've closed this as I have tested the conversion to a normal graph and it's working just fine.

**Closed** 2019-11-29 16:52 UTC
Labels: bug, resolved

**Comment by frankfer01** [comment] 2020-01-20 12:58
Hi, it's true, when you convert to normal graph you can edit any items, but if you have a lot of aggregate graphs, is impossible(a lot of work) to modify  one by one. It's is possible to the next version of cacti that aggregate graphs work as well like the version 0.8.8.8 ?

**Comment by netniV** [comment] 2020-01-20 13:17
There have been a lot of changes around the system, so unfortunately, things will never be what they once were overnight.  But we are constantly trying to improve and make things better so keep the suggestions coming in where we can improve things.
