### ISSUE TITLE
[1.2.28] UI Timezone Issues

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#5926] opened 2024-11-20 10:37 UTC
Hello, it's been awhile!

I recently swept through and upgraded from 1.2.24 to 1.2.28 and also switched from Debian 10 to Debian 12. 

I'm now seeing a little issue with the timezone in the Cacti UI. The "From" and "To" fields in the graph view seem to be stuck in GMT, however I am in MST. Generally I can switch my profile from the Cacti Server Timezone to My Browser's Timezone and that fixes it - for a brief while - but eventually that setting doesn't seem to "hold", especially across browsers. 

My system is very clearly in MST

Date	Wed, 20 Nov 2024 03:27:01 -0700
Cacti Version	1.2.28
Cacti OS	unix
NET-SNMP Version	NET-SNMP version: 5.9.3
RRDtool Version Configured	1.7.2+
RRDtool Version Found	1.7.2
Devices	326
Graphs	12,695
Data Sources	Script/Command: 1,015
SNMP Get: 2,093
SNMP Query: 3,184
Script Query: 6,514
Script Server: 30
Script Server Query: 24
Total: 12,860

Cookie	CactiTimeZone=-420; Cacti=umpXXXXXXXdjge; cacti_remembers=1%2C0%2C12106a9bbd74ab88XXXXXb459e24d32; CactiDateTime=Wed Nov 20 2024 03:26:06 GMT-0700 (Mountain Standard Time); _ga=GA1.1.229041410.1732050092; _ga_HBJ1X4XVSS=GS1.1.1732086323.2.1.1732087606.0.0.0; _ga_PT4VWDPXNE=GS1.1.1732086323.2.1.1732087606.0.0.0
HTTP Response Headers
Last-Modified	Wed, 20 Nov 2024 10:27:57 GMT
X-Frame-Options	SAMEORIGIN
Content-Security-Policy	default-src *; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline' ; script-src 'self' 'unsafe-inline' ; frame-ancestors 'self'; worker-src 'self' ;
P3P	CP="CAO PSA OUR"
Cache-Control	no-store, no-cache, must-revalidate
Expires	Thu, 19 Nov 1981 08:52:00 GMT
Pragma	no-cache`

You can see here CactiDateTime is set in the cookie - but I don't know what this "CactiTimeZone=-420" is all about :)

date/time support	enabled
timelib version	2022.10
"Olson" Timezone Database Version	0.system
Timezone Database	internal
Default timezone	Etc/GMT+7
Directive	Local Value	Master Value
date.default_latitude	31.7667	31.7667
date.default_longitude	35.2333	35.2333
date.sunrise_zenith	90.833333	90.833333
date.sunset_zenith	90.833333	90.833333
date.timezone	Etc/GMT+7	UTC`

no value	no value
intl
Internationalization support	enabled
ICU version	72.1
ICU Data version	72.1
ICU TZData version	2022e
ICU Unicode version	15.0
Directive	Local Value	Master Value
intl.default_locale	no value	no value
intl.error_level	0	0
intl.use_exceptions	Off	Off

I've clicked around for awhile - its 3AM here and I'm calling it quits - hopefully it's something simple I've overlooked somewhere. Cheers!

**Comment by eschoeller** [comment] 2024-11-20 10:38
![image](https://github.com/user-attachments/assets/219f30aa-5414-40b2-99f0-cfecb2b205bf)

**Comment by eschoeller** [comment] 2024-11-20 10:39
I'd also say that when I use the "last day" preset it's detecting the time as 10:21 while it's actually 3:38AM. So not only is it off by the GMT offset, it's mixed in a few extra minutes there too, which is really odd.

**Comment by eschoeller** [comment] 2024-11-20 10:42
If I right-click the graph and zoom-out by 2x the From/To times are updated correctly; and the Preset switches to Custom.

**Comment by eschoeller** [comment] 2024-11-20 10:44
PHP Version	8.2.24

**Comment by TheWitness** [comment] 2024-11-20 13:06
This is fixed already in the 1.2.x branch.

**Comment by TheWitness** [comment] 2024-11-20 16:06
There are a few things that are driving the 1.2.29 release that are kind of significant there's a boost issue as well but this is the other big one.

**Comment by TheWitness** [comment] 2024-11-20 16:06
We're trying to minimize changes as we prepped for the next major release.

**Comment by eschoeller** [comment] 2024-11-22 21:22
Oh, okay! Already a known issue:) I looked through open issues but didn't really find anything - perhaps I shouldn't have been working that late!

**Comment by TheWitness** [comment] 2024-11-30 16:05
Duplicate of #5847

**Closed by TheWitness** 2024-11-30 16:05 UTC
Labels: bug, duplicate, unverified, type:bug, status:needs-verification

**Comment by eschoeller** [comment] 2025-01-21 23:49
Will v1.2.29 make it to a release status or at least get a tag or something in github?

**Comment by TheWitness** [comment] 2025-01-22 20:31
I hope, @netniV is a bit distracted at the moment.

**Comment by netniV** [comment] 2025-01-26 18:21
We are on course for next weekend.  Just need the final round of testing to be clear.

**Comment by eschoeller** [comment] 2025-01-28 22:56
Great thanks for the update!
