### ISSUE TITLE
Update console navigation menu to show/hide via pin button

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1508] opened 2018-03-30 14:07 UTC
If we are already in graphs tab page cannot be reloaded by clicking graphs again.

Also for nectar tab this happens. When we are editing one report unable to use browser back button or reload nectar main settings by clicking nectar tab.

**Comment by netniV** [comment] 2018-03-30 14:13
The top tab being non-clickable is by design since you are on that tab currently because when you are on the console tab, it shows/hides the console menu.  We could potentially allow it to work differently on the non console tabs as I can see how it would be useful clicking them to force a reload.

**Comment by cigamit** [comment] 2018-03-30 16:46
I've been re-thinking this behavior.  But no changes for now.  We'll keep this open for the moment.

**Comment by netniV** [comment] 2018-08-12 20:09
No further thoughts in a while, so I'm going to close this one.

**Comment by cigamit** [comment] 2018-08-13 10:47
Right now, in the Classic, Modern, and Dark themes, you can re-click the breadcrumbs and that will force a page reload.  I use that all the time when I need to.  For the other themes, you need to press F5.  I know what the user is asking for here, and I've given it some thought, but it is not important enough for the 1.2 release.

I suggest we open a new ticket and request something more positive then negative.  What I'm suggesting is a widget by the left pane navigation that allows you to open and close it.  That way we can remove the show/hide of the navigation feature on the second click of the tab behavior.  But the bug should be labeled as such.

**Comment by netniV** [comment] 2018-08-13 11:02
Like a side-ways button when collapsed that would expand, with maybe a pin for keeping it permenantly open? Similar to this:

![nav](https://user-images.githubusercontent.com/9052188/44028076-a1fd7774-9ef0-11e8-9207-1e701f1c3736.gif)

**Comment by netniV** [comment] 2018-08-13 20:16
Found this fiddle that seems to be similar to what I was suggested: http://jsfiddle.net/W7sNp/1/

**Comment by netniV** [comment] 2018-08-14 10:33
So we leave the old functionality for classic, since it's classic.  Put the new functionality into the new themes?

**Comment by cigamit** [comment] 2018-11-18 19:08
I've seen an interesting method of doing this lately, that should not be too complicated.  All these UI issues should be moved to 1.3.

**Comment by TheWitness** [comment] 2024-10-13 23:37
This issue is resolved differently in the Cacti 1.2.x and above using local storage.

**Closed by TheWitness** 2024-10-13 23:37 UTC
Labels: enhancement, gui
