### ISSUE TITLE
Backups & Restore GUI

### ISSUE THREAD

**Issue by cobusv** [Cacti/cacti#691] opened 2017-05-13 07:22 UTC
It would really be awesome if there was a backup/restore section in the GUI in order to backup and restore your cacti data. This would really be helpful if you had a crash and need to restore to a previous state.

**Comment by cigamit** [comment] 2017-05-13 11:37
Totally agree.

**Comment by cigamit** [comment] 2017-05-26 03:54
I attempted to write a plugin to do this long ago, but the feasibility to have it working across all the various architectures out there isn't really worth the time and effort I would have had to put into it.  Instead I really recommend that you have a proper backup mechanism in place, the same as all of your systems (Cacti isn't special).  Anything we would have in the GUI would at best be backing up to the local system, so if the system crashed then you would still lose everything.  You need to have a separate system backing up both the files and the database and storing it on a remote system.

**Comment by ronytomen** [comment] 2017-05-29 01:32
This would be a plugin and would not be included in main line.

As @cigamit mentioned, there are really a few components you need to backup.

* RRD Files
* Database (usually a dump is fine, excluding ```poller_output``` and ```poller_output_boost```)
* ```resources``` directory
* ```scripts``` directory

I'm changing this issue to a documentation task as we do need documentation on backing up Cacti.

**Comment by cigamit** [comment] 2017-05-29 23:10
I would like to see backup handled in two ways.
1) support copying/rsyncing the RRDfiles to a shared location
2) backing up the database, resources, and scripts into a recoverable tar/zip file

**Comment by jpobeda** [comment] 2017-06-14 20:40
Since you are planning to be selective I think it would be a good idea to include the plugin folder as well. Those running weathermap for example, will want to backup their map configs or the routerconfigs backup directory, IF they are within Cacti directory structure of course.

**Comment by interduo** [comment] 2019-09-15 16:42
I think that the backup should be done in higher level. It's better for You to use hypervisor and lxc or kvm.

You should have 2 backups.
- whole wirtual machine,
- db dump.

Only this strategy fully works in all problematic scenario.

Doing a backup of only one component rrds/db/files is complicated and hard to restore.

So the issue is much work whitch is done allready in another way as expected by author od this issue.

**Comment by cigamit** [comment] 2019-11-09 21:14
There is also a case where some plugin developers have proprietary range partitioned tables.  We have to have a regex to skip backing up files more than once, to handle them separately.  We also need a way to skip backups for certain tables as indicated by @ronytomen

**Comment by TheWitness** [comment] 2024-12-25 18:45
So I wrote a plug-in for this and I hope to release it in the new year so I'm going to go ahead and close this. Enjoy Cacti guys.

**Closed** 2024-12-25 18:45 UTC
Labels: enhancement, resolved, documentation, database
