### ISSUE TITLE
jQuery UI - Update to 1.12.1 

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1227] opened 2018-01-17 22:36 UTC
jQuery UI needs to be updated at some point to the 1.12.1 version as per https://github.com/Cacti/cacti/issues/1195#issuecomment-358114935.  However, this has CSS and JS implications as themes may need to be rebuilt etc.

**Comment by netniV** [comment] 2018-01-17 22:39
It was noted that most themes seem to be based off Smoothness, and that we would need to rework from Base.  However, I noticed that Smoothness was still available as a theme to download even under 1.12.1.  So, as a starting point, I dropped in the latest js to /include/js/jquery-ui.js, and the jquery-ui.theme.css to /include/themes/modern/jquery-ui.css I ended up with the following layout differences:

![image](https://user-images.githubusercontent.com/9052188/35071012-388f78e4-fbd7-11e7-8c83-746122adbbc9.png)

**Comment by cigamit** [comment] 2018-01-18 00:30
Which is which?

**Comment by netniV** [comment] 2018-01-18 01:00
Left is new, right is current.

**Comment by cigamit** [comment] 2018-01-18 11:59
Yea, that might be the jQuery time picker plugin.  You better see if there is an update for it.

**Comment by netniV** [comment] 2018-01-18 15:03
The drop downs have done the same time so I think the next thing is to see what's in main.css that's overriding the jquery-ui.css

**Comment by cigamit** [comment] 2018-01-19 13:31
Latest Timepicker was just merged into develop.  See if that fixes things.

**Comment by pautiina** [comment] 2018-01-19 22:05
![74](https://user-images.githubusercontent.com/11805503/35173848-a3dc655e-fd75-11e7-9d84-f83b5e9752b3.png)

**Comment by cigamit** [comment] 2018-01-19 22:57
David gave us a free timepicker, but did not update the CSS file.  Not entirely sure that is is, but I'm guessing maybe.  I've asked him to do a fresh pull and include the CSS.

**Comment by cigamit** [comment] 2018-01-19 23:29
Alex, all fixed up.  Keep them coming.

**Comment by paulgevers** [comment] 2018-01-24 19:39
Please check the work done in issue #186.

**Comment by cigamit** [comment] 2018-02-17 19:18
Closing since this is a duplicate of #186.

**Closed by cigamit** 2018-02-17 19:18 UTC
Labels: gui, performance
