### ISSUE TITLE
ss_host_[cpu|disk].php use a colon as delimiter which breaks some ipv6 device monitoring

### ISSUE THREAD

**Issue by mhoran** [Cacti/cacti#1416] opened 2018-02-27 16:28 UTC
Since Cacti 1.1.34, CPU utilization graphs no longer work for an OpenBSD host. I had configured these using the CPU utilization host MIB, as the OpenBSD snmpd is not ucd/net. They had been working for some time, but as of 1.1.34 no longer do.

I tried reverting the change introduced to fix #1274, but that didn't fix it. I see the following in my logs:

```
2018/02/27 11:21:25 - CMDPHP ERROR: Invalid Return Value in ss_host_cpu.php for get 3 and host_id 10
2018/02/27 11:21:05 - CMDPHP ERROR: Invalid Return Value in ss_host_cpu.php for get 2 and host_id 10
2018/02/27 11:20:45 - CMDPHP ERROR: Invalid Return Value in ss_host_cpu.php for get 1 and host_id 10
2018/02/27 11:20:24 - CMDPHP ERROR: Invalid Return Value in ss_host_cpu.php for get 0 and host_id 10
```

I'm not entirely sure where to start debugging this, and haven't been able to figure out why this stopped working. When I go to create graphs for the device, no processors show up under "Data Query [SNMP - Get Processor Information]". Four CPUs used to show up there.

Any help would be much appreciated.

**Comment by netniV** [comment] 2018-02-27 17:10
OK, this may be down to the fact that we narrowed the focus of what is being queried from 1.3.6.1.2.1.25.3.3.1 to 1.3.6.1.2.1.25.3.3.1.2 which is the actual processor values.  Can you run an snmp walk against both and post the results?

**Comment by netniV** [comment] 2018-02-27 17:11
Also, you may need to re-import the SNMP Templates package as there is a change made to introduce CPUTotal (index 4000) which is a combined usage figure divided by the number of processors.

**Comment by mhoran** [comment] 2018-02-27 20:06
```
[mhoran@friction] ~% snmpwalk -Os -c public -v 2c 'udp6:brooklyn' 1.3.6.1.2.1.25.3.3.1
hrProcessorFrwID.1 = OID: zeroDotZero
hrProcessorFrwID.2 = OID: zeroDotZero
hrProcessorFrwID.3 = OID: zeroDotZero
hrProcessorFrwID.4 = OID: zeroDotZero
hrProcessorLoad.1 = INTEGER: 1
hrProcessorLoad.2 = INTEGER: 1
hrProcessorLoad.3 = INTEGER: 1
hrProcessorLoad.4 = INTEGER: 0
[mhoran@friction] ~% snmpwalk -Os -c public -v 2c 'udp6:brooklyn' 1.3.6.1.2.1.25.3.3.1.2
hrProcessorLoad.1 = INTEGER: 1
hrProcessorLoad.2 = INTEGER: 1
hrProcessorLoad.3 = INTEGER: 1
hrProcessorLoad.4 = INTEGER: 0
```

I tried importing the latest netsnmp template package from https://docs.cacti.net/templates but it didn't seem to do anything (checking preview didn't show any preview, and submitting with preview unchecked didn't seem to do anything either.)

**Comment by netniV** [comment] 2018-02-27 20:57
I'll take a look tomorrow, I'm just trying to get some important debugging down on routerconfigs plugin which is still playing up for automatic midnight downlaod and hour retries.  If you haven't had any update in the next day or so, just remind me.

**Comment by mhoran** [comment] 2018-02-28 02:33
Tried importing the templates, no change.

**Comment by netniV** [comment] 2018-02-28 12:16
Try rebuilding your poller cache in utilities

**Comment by mhoran** [comment] 2018-03-01 02:46
No change.

**Comment by cigamit** [comment] 2018-03-04 16:06
Post a screen shot of the entries in the Poller Cache, and also run the script server by hand and post the output you get using the script server testing procedure published on the doc's site.

**Comment by mhoran** [comment] 2018-03-11 23:04
![screenshot at 2018-03-11 18-56-51](https://user-images.githubusercontent.com/5330/37259603-c11673ec-255e-11e8-88a5-10e81260dcf3.png)

Here is the output when running `ss_host_cpu.php`:
```
/usr/local/share/cacti/scripts/ss_host_cpu.php ss_host_cpu 'brooklyn.matthoran.com' '10' '2:161:5000:1:10:public::::::' 'get' 'usage' '0'
Timeout: No Response from brooklyn.matthoran.com:161
Timeout: No Response from brooklyn.matthoran.com:161
U
```

Interestingly, running another script against the same host works just fine:
```
/usr/local/share/cacti/scripts/ss_host_disk.php ss_host_disk 'brooklyn.matthoran.com' '10' '2:161:5000:1:10:public::::::' 'get' 'total' '31'
498284544
```

The host is only reachable over IPv6.

**Comment by mhoran** [comment] 2018-03-11 23:16
When using the IP instead of name, the `ss_host_cpu.php` script works fine. `ss_host_disk.php` supports both the name and IP.

**Comment by netniV** [comment] 2018-03-12 07:30
That would suggest it's down to your DNS resolution timing out then on occasions, maybe you have more than one server and it's only one of them responding slower?

**Comment by mhoran** [comment] 2018-03-12 13:42
I don't think there's a DNS issue; that wouldn't explain why `ss_host_disk.php` works fine when `ss_host_cpu.php` does not.

What I do think is happening is that for some reason `ss_host_cpu.php` is preferring IPv4 instead of IPv6. I can see that, when `ss_host_cpu.php` runs, it reaches out to `brooklyn` via IPv4 instead of IPv6. `ss_host_disk.php` reaches out via IPv6, every time.

**Comment by netniV** [comment] 2018-03-12 14:00
Can you show the poller cache for that device and those two scripts?  I wonder if one is using a hostname, the other an IP address.

**Comment by mhoran** [comment] 2018-03-12 14:15
For `ss_host_cpu.php`:
![poller-cache-cpu](https://user-images.githubusercontent.com/5330/37288619-1f01de0e-25de-11e8-9fc4-f88e90a5396f.png)

For `ss_host_disk.php`:
![poller-cache-drive-space](https://user-images.githubusercontent.com/5330/37288622-215bf8ce-25de-11e8-8b5c-cc485f475e1a.png)

**Comment by netniV** [comment] 2018-03-12 15:02
So there is a slight difference between the two disks.  When getting most data, it's using cacti_snmp_walk() to get the data.  However, for the total and used it uses cacti_snmp_get().

Depending on how your system is configured, it may well be using  PHP's snmp_get functions over the snmpget command line program.  

You could try disable PHP's SNMP library as the code will fall back to using the program instead, though i'm not sure what impact that would have on the rest of the system.  I think @cigamit would be best commenting on that.

**Comment by mhoran** [comment] 2018-03-12 20:45
Interesting. I guess that could explain things. I still don't totally understand why this suddenly stopped working when I upgraded to 1.1.34 -- there were no corresponding DNS changes or configuration changes on the SNMP server. Looking through the code, nothing jumps out at me.

I'm working around this by using a new hostname that I created that has only an AAAA record. This breaks the Unix - Ping Host script for other reasons (I'll send a PR to fix that), but is a workaround.

I'd prefer to just have a single hostname and figure out what caused this to happen in the first case, since now I'll have to update two records should my IP ever change. But at least my CPU graphs are working again.

**Comment by netniV** [comment] 2018-03-12 22:16
There have been many changes around the PHP code. Obviously, using the built in function should be quicker than using an external program.  So does the IPv4 or the IPv6 work? You said you created an AAAA which I thought was IPv6, though I thought only an IPv4 SNMP was working?

Did you try it with the PHP SNMP module disabled?

**Comment by mhoran** [comment] 2018-03-12 22:36
> There have been many changes around the PHP code. Obviously, using the built in function should be quicker than using an external program. So does the IPv4 or the IPv6 work? You said you created an AAAA which I thought was IPv6, though I thought only an IPv4 SNMP was working?

Sorry for the confusion; the setup is a bit convoluted. The SNMP host is *only* accessible via IPv6. The host also has an A record, though there is no SNMP agent listening on that IP address.

Previously (and for another host behind the same router), the `ss_host_cpu.php` script worked just fine when polling this host. The host has both an A and AAAA record, but the script preferred the AAAA record, which is what I'd expect based on my Cacti host's configuration.

So by creating a new DNS entry with a single AAAA entry, whatever code is involved here is forced to use IPv6, and does not try IPv4 (which will fail) first.

> Did you try it with the PHP SNMP module disabled?

I just tried, with the same outcome.

**Comment by netniV** [comment] 2018-03-13 07:37
I'm surprised you don't have the same issues with the command line programs too.

**Comment by netniV** [comment] 2018-03-13 14:37
Whilst that is used during the ping command, I don't believe that hostname resolution occurs during the SNMP walk within cacti.  Rather than that is done by either the PHP function or the external programs.  If your system is built to prefer IPv4, then resolution will prefer IPv4.

**Comment by mhoran** [comment] 2018-03-13 14:44
I believe my system is configured to prefer IPv6. That is, at least, what `ip6addrctl` shows. Again, nothing changed with the DNS entries or Cacti host configuration when this stopped working, so I'm still a bit confused as to what could have happened.

**Comment by netniV** [comment] 2018-03-13 14:53
I think for now, I'm going to say it's not a cacti bug, per sae, so we should close this issue.

**Comment by mhoran** [comment] 2018-03-13 14:57
But there does seem to have been a change in Cacti that caused this regression. I've been using this configuration for many years without issue, and it only suddenly became one.

There is another host, behind the same router, with the same configuration, that is working just fine. There just seems to be something about this one script that is wonky, and I would like to get to the bottom of it.

I can bisect the changes between 1.1.33 and 1.1.34 to try and identify the issue, but that is going to be time consuming.

**Comment by netniV** [comment] 2018-03-13 15:05
Are you using `git` to update your sources? If so, you can switch between editions using `git checkout release/x.x.x` and if you can identify the one that made it fail it would be useful. I wouldn't want to start doing a mass compare of those to versions to find it was actually earlier or later.

**Comment by mhoran** [comment] 2018-03-13 15:38
I checked out Cacti to another directory and found that 1.1.33 is good and 1.1.34 is bad (as suspected).

Bisect shows the following commit causes the issue: 252333336bf84dc382d733b17eafa25adae134d2. So it seems previously I had not been utilizing `snmpbulkwalk` even though it was available. Indeed, unsetting the `snmpbulkwalk` path in settings resolves the issue.

I'm not entirely sure where to go from here. While you may consider my configuration might to be a bit odd, there's no way to get Cacti to do the right thing without removing the A record for this host (or setting up a separate DNS entry with only an AAAA record.) I'd expect that if I could prepend the hostname with `udp6` this issue would be resolved, but that doesn't seem ideal. I'd also prefer not to have two hostnames, and I can't make the SNMP daemon listenon the IPv4 address.

Thanks for your help so far!

**Comment by netniV** [comment] 2018-03-13 16:23
That commit was by me 👍  And it fixed a problem for me because the walk wasn't correctly being picked up if set. So, that suggests that the SNMPWALK command on your system must exist but it isn't preferring the IPv6.

I'm wondering if that is something we can add as an option but it would mean quite a big code change.  For now, you could just undo the addition of the read_config_option() so that the file_exists will always fail.

**Comment by mhoran** [comment] 2018-03-14 00:49
So to summarize: it seems that the built-in PHP functions prefer IPv6, as evidenced by all hosts with the exception of the one using `ss_host_cpu.php` working fine. In reviewing [lib/snmp.php](https://github.com/Cacti/cacti/blob/5f8165e5ffd9a4f5e100e78f5ebaf1e6e37a7917/lib/snmp.php), that totally makes sense. It looks like the built-in PHP functions are preferred for most actions, with the exception of `walk`, which will use the `snmpbulkwalk` if it exists. By unsetting the path to the `snmpbulkwalk` binary, the PHP functions are used.

Regarding an option: I wonder if it makes sense to extend lib/snmp.php to support the `udp6` prefix as is done in [lib/ping.php](https://github.com/Cacti/cacti/blob/5f8165e5ffd9a4f5e100e78f5ebaf1e6e37a7917/lib/ping.php#L726-L747). The command line programs seem to require the `udp6` prefix, else they prefer IPv4 (despite system settings.)

It looks like a similar issue was reported against [Spine](https://github.com/Cacti/spine/issues/24), which also requires the `udp6` prefix.

**Comment by cigamit** [comment] 2018-04-06 03:06
ipv6 as exposed by SNMP for example is a total bitch.  It's changed fundamentally between the early 5.x releases of Net-SNMP and the more recent versions.  So, supporting that prefix (udp6:) works on some OS' and not on others.  Makes me want to pull out my hair actually.

So, reading on.  I see the issue, we use the colon (:) as a delimiter in that file (oops).  If you use the hmib plugin, it'll use the value coming from hmib.  I'll be faster too.  However, that would appear to be the real bug.  I guess we should do something a little more elegant.  Let me update the description of this bug.  Wow.  I should learn to read more closely.

**Comment by netniV** [comment] 2018-04-06 13:35
It's not just those scripts, a lot of scripts use the colon as a separator.

**Comment by cigamit** [comment] 2018-08-20 00:00
I just reread the whole thing.  Yea, my previous comment, I must have been riding the horses too long that day.  I'm going to close this one, but I did see a few suggestions for improvement.  We also need to help the php team update the php-snmp library suggesting starting with net-snmp 5.7 as the baseline.

**Closed by cigamit** 2018-08-20 00:00 UTC
Labels: bug

**Comment by mhoran** [comment] 2018-08-20 00:04
So what's the recommended course of action? Right now I've worked around this by removing the paths to the net-snmp binaries. This forces use of the PHP library functions, which prefer IPv6 as desired.

If the PHP functions are brought in line with net-snmp, I'd presume they'll prefer IPv4. Then I'll need another solution, like the udp6 prefix, which doesn't currently work.

I don't want to have to set up an AAAA record just for Cacti. That seems a bit silly, since everything else works as expected.

**Comment by cigamit** [comment] 2018-08-20 02:55
Open a sepatate bug to have Cacti support the udp6: prefix, though I think I tested this and it worked at php5.7 or better.  I guess i have to figure out why these two scripts are not working with the udp6 prefix.

**Comment by netniV** [comment] 2018-08-20 07:58
It's because they take a single parameter in the form of field1:field2:field3:field4, so if you update field1 to have the upd6 prefix, it becomes udp6:field:field2:field3:field4 which offsets everything and breaks the script, I think.

**Comment by cigamit** [comment] 2018-08-21 20:10
This is not an issue, everything works.  The problem is in the hostname specification.  The way you define ipv6 address is as follows:

`udp6:[my::very::odd::looking::ip]`

Then everything works as expected.  The square brackets is very important for IPV6.  Now, getting the IPv6 address back from DNS, that is another story.
