### ISSUE TITLE
Graph Management shows bogus Template names

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1761] opened 2018-07-29 08:25 UTC
Using release from 2018-07-29.
![image](https://user-images.githubusercontent.com/35721406/43364391-79522d0c-9319-11e8-8694-f86a1a3d82b2.png)

Problem is also with first graphs displayed with Data Query as Source Type.

But when opening for editing it shows correct data:
![image](https://user-images.githubusercontent.com/35721406/43364406-b136564e-9319-11e8-84ab-f4e35d16db50.png)

Except that Graph Template is empty and scrolling list is empty.

How can I correct this?

**Comment by cigamit** [comment] 2018-07-29 12:50
Oh, you have found the issue.  I suspected this was the problem, but did not have verification.  This verifies the issue.  Please upload the Screen2Gif anyway.

**Comment by cigamit** [comment] 2018-07-29 16:10
I would also like a dump of your database, and a copy of the resource directory:

`mysqldump cacti > /tmp/issue1761.sql`
`tar -zcf /tmp/issue1761.tgz /var/www/html/cacti/resource`

Let us know where to download those two files.

**Comment by jackouille-ch** [comment] 2018-07-29 17:11
Great, what did I win for having found this issue? (Joking...)
So here is the Screen2Gif.
![1761](https://user-images.githubusercontent.com/35721406/43368803-1a73362e-9363-11e8-80ce-deb96668abd4.gif)
Regarding the dump, I prefer not to put it on a public path. Could you send me an email please?

**Comment by cigamit** [comment] 2018-07-29 17:20
Try developers@cacti.net

**Comment by jackouille-ch** [comment] 2018-07-30 07:01
Maybe something that could help: some of these graphs were imported from Cacti 0.8.8
My concern is that I have at least 50 graphs concerned and I must update some of them.
How could I proceed (which table/column) should I update?

**Comment by cigamit** [comment] 2018-07-31 01:46
Okay, I have resolved this now.  I've also completed a few additional features/bugs.

1) Multi-selects now have a reasonable width
2) Selectmenu on the Graphs page shows the complete information (no trimming ...)
3) Non Templated Graphs and Graph Template Not Found Graphs can be properly filtered
4) Selectmenus should be faster
5) Selectmenus not size themselves per the selection

The mysqldump proved very handy.

**Comment by cigamit** [comment] 2018-07-31 01:46
There are a number of pulls requests to resolve this, just clone develop to get all the changes.

**Comment by cigamit** [comment] 2018-07-31 02:11
Closing this one.

**Comment by jackouille-ch** [comment] 2018-07-31 11:19
Ok I clone the develop and reinstall: still having trouble with graphs that have bad Source Type:
![image](https://user-images.githubusercontent.com/35721406/43456258-0fe60996-94c3-11e8-930a-8ddb38ade70f.png)

Searched template is right but the first 4 answers are not showing the right templates and while opening the first graph, getting the following:
![image](https://user-images.githubusercontent.com/35721406/43456297-3c3212a6-94c3-11e8-96f1-5ccf7457f17d.png)
Select Graph Template is empty, nothing in.

And I update a graph and reopened it: same as before, Graph template is defined as _test:
![image](https://user-images.githubusercontent.com/35721406/43456587-55cc4eba-94c4-11e8-943b-66be323b7433.png)

**Comment by cigamit** [comment] 2018-07-31 12:15
Funny, I spent so much time on the other stuff that I missed the original problem.

**Comment by cigamit** [comment] 2018-07-31 12:55
So, you have a database corruption issue.  It' looks like the CMTS template was once based upon a Data Query (Interface Traffic Bits/Second), but in your example using Device: Bodeli-CMTS and Template: CMTS - DS traffic EuroDocsis (20DS), you have three Graph ID's 9797, 9803, 9805, and 9809 that appear to be Data Query based, then some later Graphs in the 13k range, that are not Not Query based (and therefore won't work).  Worse yet you can not edit them for reasons that I will explain below.

It looks to me that you deleted the CMTS - DS traffic EuroDocsis (20DS) Graph Templates from the Interface Traffic Bits/Second Data Query.  Can you explain how that happened?

I would suggest that you create a separate and distinct Data Query for the CMTS - DS traffic Templates.  So, this goes back to how the Data Query was created/modified.

**Comment by jackouille-ch** [comment] 2018-07-31 15:16
In fact I started to create graphs in Cacti 0.8.8 (those ones before 9800), then created all single data sources on Cacti 0.8.8, migrating to 1.2.0 then creating new graphs on 1.2.0
I also send you per email the SQL export that I used, hoping this will help you.
But it seems to happen to other type of graphs where old one are seen as Data Query instead of Template. But the good news is that Cacti sees them with the right template while you perform a search by Template name:
![image](https://user-images.githubusercontent.com/35721406/43468862-3efb4e22-94e5-11e8-9698-db628e15ed98.png)
It means that Graph Template ID might be kept somewhere in DB.

**Comment by jackouille-ch** [comment] 2018-07-31 16:16
But there are two issues:
1. Template is changed while editing a graph (always)
2. Some graphs are not categorized rightly

**Comment by cigamit** [comment] 2018-08-01 01:34
You will have to resend that pre-1.x dump again.  Deleted it by accident.

**Comment by jackouille-ch** [comment] 2018-08-01 07:08
Ok email has been sent again

**Comment by jackouille-ch** [comment] 2018-08-02 07:02
Maybe something that could help: some of these graphs were imported from Cacti 0.8.8
My concern is that I have at least 50 graphs concerned and I must update some of them.
How could I proceed (which table/column) should I update?
Graph with Problem:
![image](https://user-images.githubusercontent.com/35721406/43567576-6b1da3b2-9632-11e8-8b0a-06308c82fa6e.png)

Graph OK:
![image](https://user-images.githubusercontent.com/35721406/43567604-7a3be8f4-9632-11e8-969f-51227fe4916b.png)

So if I manually update data in DB it comes again as others.
But while editing, template is still wrong.

**Comment by cigamit** [comment] 2018-08-03 01:46
So, this specific Data Query was damaged by someone before the upgrade to 1.2.  It's not the fault of 1.x upgrade or anything.  I reviewed the template/data query, and it's just messed up.  Not sure what else to tell you but to restore from an old backup of the Data Query and start over.

Playing with the database settings is not the way to go instead you should:

1) Note the RRDfile names of the good graphs, you will need to back them up, and then rename them once you have fixed everything.
2) Backup those RRDfiles
3) Reimport that last known good version of the Data Query
4) Delete the Graphs
5) Recreate the Graphs
6) Restore the old RRDfiles over the new ones

There is not much more to say about this except that your test case provided us the opportunity to improve the output of the various Cacti pages that included templates.  I actually have one more fix to do in that account.  Thanks again.  Sorry I don't have better news.

**Comment by jackouille-ch** [comment] 2018-08-03 06:33
DB probelm has been solved.
Now I didn't have anymore empty Template Data but problem is still present:
When a graph has been created, the Graph Template i correct but after you have pout the right Data Sources, Data Template is not taken by default, it's the first one, as displayes here:
![1761-1](https://user-images.githubusercontent.com/35721406/43627761-f474a780-96f7-11e8-8823-b956873e13f7.gif)

**Comment by netniV** [comment] 2018-08-03 07:34
Did you correct your template?  That is what @cigamit  mentioned above.  If you have a broken template, and keep using it, things will still be broken.

**Comment by jackouille-ch** [comment] 2018-08-06 09:46
Nope, template is correct because it opens fine when graph has been created.
I am also able to add Data Sources within fields without trouble, when it's the first time.
When I edit other graphs that are already good, the same problem appears, for all graphs!

As said, the strange thing is that graphs are opening correctly for edition, the only problem is that Graph Template switched to the first one in the template list:
![image](https://user-images.githubusercontent.com/35721406/43709795-15c8f74c-996e-11e8-9fda-e53ca9065bc9.png)
All Templates were imported from 0.8x and they work fine.

If I simply change _Test with the right template it works fine, but I need to search the template again.

If still think that this a bug.
Doing the proposal from @Cigamit is also not possible for me (too many graphs to rebuild)

**Comment by jackouille-ch** [comment] 2018-08-06 09:47
Ticket #1759 is for the same topic, you can close it.

**Comment by cigamit** [comment] 2018-08-06 23:14
I'm still not clear what you are doing, but hey, I've only been doing Cacti for a long time.  There may be some holes that I have never fallen into.  I'll be the first to admit it.  I'm going to close this, but I'm a bit uneasy at the moment.

**Comment by jackouille-ch** [comment] 2018-08-07 08:19
The strange thing is that when I open a graph template that I made, Requested Data Sources from my template are displayed correctly and it is used but Graph Template used to display this page is not used as default for Graph Template.
It looks Graph Template is lost during page treatment and Selected Graph Template is not using the right one but the first within alphabetical order.
[1761-20180807.txt](https://github.com/Cacti/cacti/files/2265588/1761-20180807.txt)
Within the text file, on line 200 it should be 287, not 202
Here is the graph_local DB entry:
![image](https://user-images.githubusercontent.com/35721406/43763353-da919c16-9a2a-11e8-8210-e4866c55fedc.png)

So in DB it's correct but it looks like graphs.php with action=graph_edit is facing an issue when Data Sources are filled, when graph template is empty (after creation, it's ok), after filling DS and saving it's still ok but while editing it with DS, Graph Template seems to be not seen and could be not linked within existing template, then it might be assigned to first alphabetical sorted template.

**Comment by jackouille-ch** [comment] 2018-08-07 09:40
Created a new graph:
![image](https://user-images.githubusercontent.com/35721406/43767504-9db3ab76-9a35-11e8-9558-e2e1244ba118.png)

Entering right DS:
![image](https://user-images.githubusercontent.com/35721406/43767622-e876e22c-9a35-11e8-897a-dd13ab00f231.png)

![1761-3](https://user-images.githubusercontent.com/35721406/43767940-82778886-9a36-11e8-8a7f-635327df9dd0.gif)
With the above animation you can see that Graph Template is seen correctly but when I try to edit it, the original Template is not kept and if you don't take care you graph will become usable after saving...

**Comment by cigamit** [comment] 2018-08-07 12:53
I think this has to do with the way your are creating these graphs.  They would appear to be template based graphs, but the data inside of the template would appear to be from the result of a data source created by possibly a data query?  That's not how templates are supposed to work.

Can you demonstrate how you add a data source to the various graphs in an animation or very detailed steps?  Seems you have found a method to create graphs that was never intended to work, and I need to know the exact steps to reproduce.

**Comment by jackouille-ch** [comment] 2018-08-07 15:41
Ok so here is the full creation animation:
![1761-4](https://user-images.githubusercontent.com/35721406/43786549-2b52b2b4-9a69-11e8-80db-87c11dd8ae11.gif)

**Comment by jackouille-ch** [comment] 2018-08-09 18:02
@Cigamit: was the above animation helpful to determine where the issue is (Cacti or me)?

**Comment by cigamit** [comment] 2018-08-13 10:51
Yea, I'm going to re-open this and attempt to find a workaround now that I know what you are doing.  I would simply use an aggregate graph myself.  So, I'll re-open this one.  We will attempt to fix this either in beta, or before depending on @ronytomen and his availability.

**Comment by jackouille-ch** [comment] 2018-08-13 11:56
Excellent, thanks!

**Comment by cigamit** [comment] 2018-08-16 23:39
Should be kind of resolved now with the latest graphs.php

**Comment by jackouille-ch** [comment] 2018-08-17 06:43
Ok I will take the latest release and test it

**Comment by jackouille-ch** [comment] 2018-08-17 07:27
Sorry but I still have my issue:
![image](https://user-images.githubusercontent.com/35721406/44253359-a7dfe200-a1ff-11e8-814c-a069aa9b5c7b.png)
I download the latest export from today, perform the install and simply open one graph.

**Comment by cigamit** [comment] 2018-08-18 15:58
Okay, you can run the following query short term to resolve the bogus issues.  I'll be quickly writing an upgrade query to find any more:

`UPDATE graph_local AS gl INNER JOIN (SELECT DISTINCT graph_template_id FROM graph_local AS gl WHERE snmp_query_id=1 HAVING graph_template_id NOT IN (SELECT graph_template_id FROM snmp_query_graph WHERE snmp_query_id=1)) AS rs ON gl.graph_template_id=rs.graph_template_id SET snmp_query_id=0, snmp_query_graph_id=0, snmp_index='';`

**Comment by cigamit** [comment] 2018-08-18 17:10
Okay, stet that.  Instead just reforce the running of the upgrade script and the issues will be resolved with the latest commit.

**Comment by jackouille-ch** [comment] 2018-08-25 10:18
Tested with commit a574fd9 and new setup, still the same.
Here is the result from your query:
mysql> UPDATE graph_local AS gl INNER JOIN (SELECT DISTINCT graph_template_id FROM graph_local AS gl WHERE snmp_query_id=1 HAVING graph_template_id NOT IN (SELECT graph_template_id FROM snmp_query_graph WHERE snmp_query_id=1)) AS rs ON gl.graph_template_id=rs.graph_template_id SET snmp_query_id=0, snmp_query_graph_id=0, snmp_index='';
Query OK, 38 rows affected (0.02 sec)
Rows matched: 224  Changed: 38  Warnings: 0

**Comment by cigamit** [comment] 2018-08-25 17:11
You did not follow my updated directions.  First update to the latest develop, just don't cherry pick.  Second, after you have done all that, do as I had instructed and rerun the upgrade_database.php script using the forcever option.

**Comment by jackouille-ch** [comment] 2018-08-25 21:09
I download the commit full develop a574fd9, removed log and rra folders, copy all these files on /usr/share/cacti, run the install via GUI and perform the following:
 php -q /usr/share/cacti/cli/upgrade_database.php --forcever=1.1.38
Upgrading from v1.1.38
Upgrading from v1.1.38 (DB 1.2.0) to v1.2.0
.......................

What do I miss because I still have the issue?

**Comment by cigamit** [comment] 2018-08-31 00:45
You are going to have to explain what is breaking in pictures again.  Just saying it is still broke became difficult when I fixed all the corruption in your database through the upgrade script.

**Comment by cigamit** [comment] 2018-09-13 02:31
I'm assuming that things started working since you have not updated in a while.  Some of your graphs, the ones already broken, you just have to edit and re-save and everything should be okay.

**Closed by cigamit** 2018-09-13 02:31 UTC
