### ISSUE TITLE
Windows Download 404

### ISSUE THREAD

**Issue by EanNewton** [Cacti/cacti#4401] opened 2021-09-15 06:30 UTC
The link to your download for the Windows installer from the https://www.cacti.net/info/downloads page 404's 

https://files.cacti.net/cacti/windows/cacti-1.2.18.zip

**Comment by TheWitness** [comment] 2021-09-15 11:40
Duplicate of #4360

**Closed by TheWitness** 2021-09-15 11:40 UTC
Labels: bug, unverified

**Comment by TheWitness** [comment] 2021-09-15 11:53
Should be fixed now.

**Comment by EanNewton** [comment] 2021-09-15 12:30
Confirmed to be working, thank you!
