### ISSUE TITLE
Aggregate graph gives CMDPHP errors

### ISSUE THREAD

**Issue by Weppel** [Cacti/cacti#307] opened 2017-02-19 08:29 UTC
When viewing my aggregate graph I see the following CMDPHP errors in cacti.log:

`2017-02-19 09:18:16 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_json.php: 148 rrdtool_function_graph)(/lib/rrd.php: 1402 variable_nth_percentile)(/lib/graph_variables.php: 297 nth_percentile)(/lib/graph_variables.php: 86 CactiErrorHandler)(/lib/functions.php: 4237 cacti_debug_backtrace)`
`2017-02-19 09:18:16 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /home/www/html/lib/graph_variables.php on line: 86`
`2017-02-19 09:18:16 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_json.php: 148 rrdtool_function_graph)(/lib/rrd.php: 1402 variable_nth_percentile)(/lib/graph_variables.php: 297 nth_percentile)(/lib/graph_variables.php: 85 reset)(CactiErrorHandler)(/lib/functions.php: 4237 cacti_debug_backtrace)`
`2017-02-19 09:18:16 - ERROR PHP WARNING: reset() expects parameter 1 to be array, null given in file: /home/www/html/lib/graph_variables.php on line: 85`
`2017-02-19 09:18:16 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_json.php: 148 rrdtool_function_graph)(/lib/rrd.php: 1402 variable_nth_percentile)(/lib/graph_variables.php: 297 nth_percentile)(/lib/graph_variables.php: 86 CactiErrorHandler)(/lib/functions.php: 4237 cacti_debug_backtrace)`
`2017-02-19 09:18:16 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /home/www/html/lib/graph_variables.php on line: 86`
`2017-02-19 09:18:16 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_json.php: 148 rrdtool_function_graph)(/lib/rrd.php: 1402 variable_nth_percentile)(/lib/graph_variables.php: 297 nth_percentile)(/lib/graph_variables.php: 85 reset)(CactiErrorHandler)(/lib/functions.php: 4237 cacti_debug_backtrace)`
`2017-02-19 09:18:16 - ERROR PHP WARNING: reset() expects parameter 1 to be array, null given in file: /home/www/html/lib/graph_variables.php on line: 85`
`2017-02-19 09:18:16 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_json.php: 148 rrdtool_function_graph)(/lib/rrd.php: 1402 variable_nth_percentile)(/lib/graph_variables.php: 297 nth_percentile)(/lib/graph_variables.php: 86 CactiErrorHandler)(/lib/functions.php: 4237 cacti_debug_backtrace)`
`2017-02-19 09:18:16 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /home/www/html/lib/graph_variables.php on line: 86`
`2017-02-19 09:18:16 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_json.php: 148 rrdtool_function_graph)(/lib/rrd.php: 1402 variable_nth_percentile)(/lib/graph_variables.php: 297 nth_percentile)(/lib/graph_variables.php: 85 reset)(CactiErrorHandler)(/lib/functions.php: 4237 cacti_debug_backtrace)`
`2017-02-19 09:18:16 - ERROR PHP WARNING: reset() expects parameter 1 to be array, null given in file: /home/www/html/lib/graph_variables.php on line: 85`

My aggregate template looks like this:

![image](https://cloud.githubusercontent.com/assets/6195608/23100601/b5ef7670-f685-11e6-8dcf-07a196066bbb.png)

The templated interface graph looks like this:

![image](https://cloud.githubusercontent.com/assets/6195608/23100605/cad3c01e-f685-11e6-809e-bd3d8c575ed3.png)

And the actual aggregate graph looks like this:

![image](https://cloud.githubusercontent.com/assets/6195608/23100609/e0d26ef6-f685-11e6-9082-de7e268a135c.png)

**Comment by cigamit** [comment] 2017-02-24 00:06
I'm going to go ahead and close this one.  I was unable to reproduce, but I did perform some additional changes in the code, to prevent a users from using 'Total' on some graph elements that have no business being aggregated, which I expect to be the source of this issue.

**Closed by cigamit** 2017-02-24 00:06 UTC
