### ISSUE TITLE
Multiple AD AUTH LOGIN: LDAP Error:

### ISSUE THREAD

**Issue by huangchao-shanghai** [Cacti/cacti#1051] opened 2017-10-28 13:49 UTC
problem: use AD AUTH 
error message only : `LOGIN: LDAP Error:`
cacti.log:
`2017/10/28 21:27:07 - CMDPHP PHP ERROR WARNING Backtrace: (/index.php: 25 include)(/include/auth.php: 82 include)(/auth_login.php: 634 CactiErrorHandler)(/lib/functions.php: 4403 cacti_debug_backtrace)`
`2017/10/28 21:27:07 - ERROR PHP WARNING: Illegal string offset 'name' in file: /opt/cacti/auth_login.php on line: 634`
`2017/10/28 21:27:07 - CMDPHP PHP ERROR WARNING Backtrace: (/index.php: 25 include)(/include/auth.php: 82 include)(/auth_login.php: 634 CactiErrorHandler)(/lib/functions.php: 4403 cacti_debug_backtrace)`
`2017/10/28 21:27:07 - ERROR PHP WARNING: Illegal string offset 'selected' in file: /opt/cacti/auth_login.php on line: 634`
`2017/10/28 21:27:07 - AUTH LOGIN: LDAP Error:`

System:
`Ubuntu 16.04.3 LTS` `Cacti 1.1.27` ` php 7.0.22` `mysql-server  5.7.20` `RRDtool 1.5.5-4`

please help

**Comment by cigamit** [comment] 2017-10-28 19:57
I'm not able to reproduce that.  Why don't you do this.  In the auth_login.php file, do the following:

1) Goto the line in question, 634
2) Just before that line add a cacti_log() call like this:

`cacti_log("Index:" . $index . ",Array Keys:" . array_keys($realm) . ", Array Values:" . array_values($realm));`

Goto the page again, and then send the output of the Cacti log that is generated.  Should be at least two lines.

**Comment by huangchao-shanghai** [comment] 2017-10-29 11:43
Thank you very much.
When I changed the browser to  Google Chrome, the problem disappeared. Taobo UC browser was used before.

**Comment by cigamit** [comment] 2017-10-29 13:46
Okay, closing this then.

**Closed by cigamit** 2017-10-29 13:46 UTC
