### ISSUE TITLE
Aggregate Graph can sometimes change order of comment fields, resulting in random changes.

### ISSUE THREAD

**Issue by realpg** [Cacti/cacti#3147] opened 2019-12-15 01:39 UTC
Cacti version: 1.2.7
When I found this bug, the version was 1.2.3. I upgraded it to the newest version 1.2.7 and the bug's still there.

I created aggregates of some interface traffics graph with 95th percentile.

Aggregate template is simple,

**Source graph template:** Interface - Traffic (bits/sec, 95th)
**Graph Type:** Keep Type and STACK
**Totaling:** Print All legend Items.
**Total Type:** Total Similar Data Sources.
**Prefix for GPRINT Totals:** Total
**Reorder Type:** No Reording.

And Graph Items skip all inbound items. I want outbounds only.

It works well. But the graph have a little problem.

The Total item make a newline before [Maxium] randomly.

VERY RANDOM, 50% to 50% :

![image](https://user-images.githubusercontent.com/12572518/70856829-a8d17280-1f1e-11ea-8bce-5137481a5101.png)

![image](https://user-images.githubusercontent.com/12572518/70856835-bd156f80-1f1e-11ea-81ad-cb4efd11c573.png)

**I enter the rrdtool command debug mode with this url:**

`https://MYDOMAIN/graph.php?action=properties&header=false&local_graph_id=943&rra_id=0&view_type=&graph_start=1576187640&graph_end=1576220220`

At the end of the rrdtool command, the position of newline "\n" changes randomly too. Every F5 refresh, sometimes here, sometimes there:

![image](https://user-images.githubusercontent.com/12572518/70856843-c69ed780-1f1e-11ea-8a0b-5c75afc50968.png)

![image](https://user-images.githubusercontent.com/12572518/70856846-cd2d4f00-1f1e-11ea-84f6-ae84d06babe7.png)

**Comment by netniV** [comment] 2019-12-16 12:39
This is almost like the sort order is not quite tied down correctly and thus creates the shift.  Since you appear to be able to reproduce this with your own data, is there any chance you could share that with us?  Also include a link that shows the issue that you posted above just so we know what it's related to (developers@cacti.net)

**Comment by realpg** [comment] 2019-12-16 12:47
@netniV 
The billing system data is classified. 
I'll find a way to copy some data to a public system and try to reproduce this, and share this with you.

It will take some time. Because I need to talk my leader and CTO to get the permission.

**Comment by netniV** [comment] 2019-12-16 13:03
Hmm, well we will just have to see what we can do in the meantime then, as changing the data could result in a different outcome.  Let us look into the code and see if we can spot anything.

**Comment by tyit** [comment] 2019-12-20 13:19
I responded to this problem before, maybe it was not good enough.     #2826

**Comment by netniV** [comment] 2019-12-21 20:39
Thanks @tyit, it does look like the same issue.

**Comment by cigamit** [comment] 2019-12-22 17:25
Can you please test using latest 1.2.8.  There have been some improvements on ordering.

**Comment by realpg** [comment] 2019-12-24 08:23
> Can you please test using latest 1.2.8. There have been some improvements on ordering.
@cigamit  I'll upgrade to 1.2.8 later.


I got a permission to copy some data to public network to verify the bug.  I'm working on it.

I've confirmed that this bug (random newline position) occured with the same data (use date range in queries, data not changed).

**Comment by cigamit** [comment] 2019-12-24 16:06
You have to edit the Aggregate, or Aggregate Template, change something, and then re-save.  Can you do that too?  Like change the order to Graph, Data Source or something.  You can change it back and save again afterward.  These things are required to properly update the Aggregate.

I also need a screen shot of the Graph Template that this aggregate was based upon, and the Aggregate view showing the graph items as well.  Please upload those.

**Comment by realpg** [comment] 2019-12-26 06:43
> You have to edit the Aggregate, or Aggregate Template, change something, and then re-save. Can you do that too? Like change the order to Graph, Data Source or something. You can change it back and save again afterward. These things are required to properly update the Aggregate.
> 
> I also need a screen shot of the Graph Template that this aggregate was based upon, and the Aggregate view showing the graph items as well. Please upload those.

We will upgrade our system to newest v1.2.8 at Saturday midnight(localtime, UTC+8). 
After that we'll try. Thank you very much.

**Comment by cigamit** [comment] 2019-12-26 15:31
You might want to also take lib/api_aggregate.php from the 1.2.x branch.

**Comment by cigamit** [comment] 2020-01-11 01:26
Any update?

**Comment by TheWitness** [comment] 2020-05-22 11:02
Issue is not resolved

**Comment by TheWitness** [comment] 2020-11-22 16:08
I think I know the source of this.  You have a few graphs in the aggregate that have that modified layout.  What I suggest you do is reconfirm that the Graph Template is properly formatted, and then perform a Sync Template.  After that, make sure you re-save the aggregate.  However, note, aggregate has a quirk that if you don't change something in the aggregate, it won't recreate the graph items.  Make sure you are at 1.2.14+ before you do this though.  Since this is the real issue, I'll just go ahead and close this.

In a future version of Cacti we will remove the chance of things like this happening to the various graphs.

**Closed by TheWitness** 2020-11-22 16:08 UTC
Labels: aggregate, bug, enhancement, unverified
