### ISSUE TITLE
Data Source Duplication When Creating Graphs

### ISSUE THREAD

**Issue by coozoo** [Cacti/cacti#2246] opened 2018-12-31 10:29 UTC
Hello,
This  related to the issue that I've already opened, I've missed in some reason moment when it was fixed, to verify it:
https://github.com/Cacti/cacti/issues/948

But now when I'm selecting create 24 graphs, I want to make them use the same datasource.
But I can't find option to do that.

In old cacti it was possible to create datasource and when creating new graph attach it to the same datasource.

Now when I'm creating some graph it's adding new datasource again and again.

After that the only way to fix it manually and it much more harder than select for new

As result I end up with a bunch of identical datasources..
![image](https://user-images.githubusercontent.com/25594311/50558402-b9c9a980-0cf6-11e9-8f9d-cee56a5f40b6.png)

Can you tell me what I'm doing wrong o how to prevent such behavior, maybe there is some option how to turn on old way?

thank you

**Comment by coozoo** [comment] 2018-12-31 12:38
forgot to mention it's Fedora's package cacti.noarch 1.1.38-4.fc29 so suppose latest stable

**Comment by cigamit** [comment] 2018-12-31 18:13
We had another report of this in the 1.2 stream.  It's been fixed there.

**Comment by netniV** [comment] 2018-12-31 19:44
It was reported in #948 I believe

**Comment by coozoo** [comment] 2019-01-02 15:11
@netniV  So I've tried to remove cacti DB to make it fresh
Imported my templates and tried to create from scratch for each graph created new data source.
And I can't find the way how to prevent to do this.
Sure every datasource is not deletable because it's locked by created graph and impossible to change relations.

Can you at least point me where to set id of datasource for graph because I've tried to find and only see data sources.. but can not find graph relations.

If you want I can attach xml with templates

thanks

**Comment by cigamit** [comment] 2019-01-02 23:20
@coozoo can you do a simple screen 2 gif capture of how you are creating the graphs/data sources.  We need to know the exact steps.

**Comment by coozoo** [comment] 2019-01-03 00:20
@cigamit hi Yes  I can but recorded video almost 20MB so maybe it's better simply to write steps because my templates are not secret :) (tomorrow maybe I will do screens)

It's made for collecting java machine properties.
1. You need to import attached file
2. go to device and create any
3. got to Create->new graphs and select few
4. next screen you can fill in each graph datasource parameters and create them
5. go to datasources you will have as many of them as you've selected graphs before

[cacti_host_template_jmx_-_device_java8.zip](https://github.com/Cacti/cacti/files/2722400/cacti_host_template_jmx_-_device_java8.zip)

**Comment by coozoo** [comment] 2019-01-03 06:42
Small video with adding graph, you can see two datasourcesalready exist (created in a bunch) and one more I've just addeed as result I've got another datasource (there is no difference if I'm filling datasource host port). And it will be as many as graphs selected.
[out-1.ogv.tar.gz](https://github.com/Cacti/cacti/files/2722883/out-1.ogv.tar.gz)

**Comment by coozoo** [comment] 2019-01-08 08:38
Some kind of workaround through UI it's to left only one active datasource and all other datasources set to the same rrd and disable them.
Minus of this method you still have a lot of datasources for one each graph actually all of them using one rrd which filed with a data from one source....

**Comment by cigamit** [comment] 2019-01-09 00:18
Okay, I have confirmed that duplicate data sources in your case are still created.  I'm going to open this as a feature request though.  This is due to the fact that your custom data can be different for every graph your create.  I also correct the visual issue with the presentation of that custom data under the paper-plane them.

Since the custom data is potentially different for each graph, this was likely why it was not caught or scoped in the prior two bug report.

**Comment by cigamit** [comment] 2019-02-24 15:52
Pretty sure this is resolved now.  Marking resolved.  Please update to 1.2.2 and then provide additional feedback.  Closing this ticket.  You can refer to it if after you upgrade to 1.2.2 the problem still exists

**Closed** 2019-02-24 15:52 UTC
Labels: enhancement, resolved
