### ISSUE TITLE
Feature request: Add $config['rra_path'] variable in config.php

### ISSUE THREAD

**Issue by mikygee** [Cacti/cacti#3745] opened 2020-08-08 23:08 UTC
Cacti version: 1.2.14

Hello,

I like to have my rrd files on a specific directory which is outside of cacti.
Typically /var/www/data/cacti/rra
I host other application than cacti and try to put other application data in /var/www/data

Because these data tend to take space my /var/www/data directory is actually another disk on my computer.
I use SSD for the operating system but I use traditional disks for data because they are cheaper.

So my feature request is that I would like to be able to specify the $config['rra_path'] = '/data/cacti/rra' in the config.php file (My Nginx is chrooted hence it's /data/cacti/rra and not /var/www/data/cacti/rra

At the moment I edit global.php and replace
$config['rra_path'] = $config['base_path'] . '/rra';
with
$config['rra_path'] = '/data/cacti/rra';
Because, as I said my rrd files are stored outside the cacti directory.

Also it's more simple for version migration of cacti.

I hope my request is well explained.

Thank you

**Comment by netniV** [comment] 2020-08-09 00:49
This is a duplicate of #3187 and has been introduced as a new feature of 1.3.0 that is under development.

**Closed by netniV** 2020-08-09 00:49 UTC
Labels: duplicate, enhancement

**Comment by mikygee** [comment] 2020-08-09 12:09
Hello,
Thank you for your answer and sorry for the duplicate. I had forgotten I opened this feature request.
I'll try it on 1.3.0.
Have an nice day
