### ISSUE TITLE
Devices added to tree twice with snmp tree automation rules

### ISSUE THREAD

**Issue by nowthatscool** [Cacti/cacti#1536] opened 2018-04-12 16:56 UTC
Hi,
I have already posted a thread about this on the Cacti forums, (https://forums.cacti.net/viewtopic.php?f=21&t=58578) and was advised to report this here.
Currently we are testing the new automation rules for Cacti within our company. We are trying to organize our trees as follows:

[TreeA]
-Postcode
--SiteA
---DeviceA
---DeviceB
--SiteB
---DeviceC
---DeviceD

The core of this idea is working with the following tree automation rules:
![tree rule](https://user-images.githubusercontent.com/38328038/38691995-c2026666-3e82-11e8-95dc-1f73a2b3e3b3.PNG)

Now the problem is, the rule is adding the devices to the tree _twice_. Once in the correct branch as described above, and once in the root of the tree. So you would end up with something like this:

[TreeA]
-Postcode
--SiteA
---DeviceA
---DeviceB
--SiteB
---DeviceC
---DeviceD
DeviceA
DeviceB
DeviceC
DeviceD

I've been trying to resolve this on my own with different rules and settings. It seems that whenever I use a "Field Name" with "snmp", the devices are created double (such as h.snmp_sysLocation and h.snmp_sysName). Whenever I use rules without "snmp" in the name, such as h.description, the devices are created only once as they should. This won't solve my problem though, since I depend on the "h.snmp_sysLocation".

Currently we are using the following software versions:
Cacti 1.1.37
RHEL 7
PHP 5.4.16
MariaDB 10.2.8
RRDTool 1.4

**Comment by cigamit** [comment] 2018-04-21 23:54
Can you please review your tree rules.  I suspect that this might be a duplicate rule.  Please cofirm.

**Comment by nowthatscool** [comment] 2018-04-22 12:38
Do you mean under Automation -> Tree Rules? If so, I only have the rule described above enabled.

**Comment by cigamit** [comment] 2018-04-22 12:48
The only think I can think of is possibly that two of the automation scripts were running at the same time and somehow arrived at the same point in time and created the tree roughly at the same point in time.  If it were a bug where the existing tree was not detected, then they would continue to stack up.  Are the id's sequential?

**Comment by nowthatscool** [comment] 2018-04-23 07:57
The device ID's under Console->Devices are sequential. But when I look at the devices in the tree, they have other ID's altogether. I don't know if that's supposed to be that way (I see this by looking at the url when clicking a device in the tree). Also, it seems the devices for the root of the tree are added first, then shorty after that the devices is placed again in the correct leaf defined by the tree rule, with an ID of 1 digit higher than it's counterpart.

**Comment by cigamit** [comment] 2018-04-23 12:39
Well, at least we have a log to drive back to the code.  This helps.

**Comment by nowthatscool** [comment] 2018-04-23 13:50
Ok so I tried some more things and it seems the issue can be worked around, it is not optimal though, especially when there are lots of devices. (Like in my case)
So when I remove the devices from the tree (not from Cacti), and then go to Console->Management->Devices and apply the automation rule again, the devices get added to the tree correctly and only once. So it would seem the problem only occurs when new devices are discovered via Console->Automation->Networks.
This would mean though that I would have to first add all the necessary devices to Cacti, and after that manually apply the rest of the automation rules. This of course is not a good solution to the problem but it's something.

**Comment by nowthatscool** [comment] 2018-04-30 13:55
Today I also tried installing php7.2 instead of 5. I also tried using spine instead of cmd.php, but unfortunately both didn't make a difference.

**Comment by netniV** [comment] 2018-04-30 14:46
You should be careful with PHP 7.2, there is at least one bug we've already fix were 7.2 complains with cacti 1.2 (dev).  That fix hasn't been back-ported at this time.

**Comment by cigamit** [comment] 2018-05-11 00:28
This can not be Cacti 1.2.  His log message is as follows:

`2018/04/23 14:07:05 - AUTOM8 NOTE: Function[create_device_node] Device[site1-01-test-s1.ict.local] Tree Item - Added - id: (3927)`

It should be `Device[host_id]`, but it's `Device[hostname]`, which is not in the code.  This is not committed this way in mainline.  Thus I will close this issue.

**Comment by netniV** [comment] 2018-05-11 04:51
Actually, that would be because when I updated the AUTOM8 for better logging support, I made it meet the CLOG standards for devices, thus it automajickally replaces the host, graphs, datasources etc as per the cacti.log standards 👍 

That only came about after cda6a03e which was a 1.2 only change.

**Comment by cigamit** [comment] 2018-05-11 23:14
Oh jeez, well.  In my code review of this issue, I can not see a way this could happen is in a case where you have two devices with the same host/description but different host_id's.

**Comment by cigamit** [comment] 2018-08-19 23:52
I have added some instrumentation, see if you can reproduce this again.  Send the same logs as above.

**Comment by netniV** [comment] 2018-09-21 18:34
No response, closing for now.

**Closed by netniV** 2018-09-21 18:34 UTC
Labels: automation, unverified

**Comment by nowthatscool** [comment] 2019-01-03 13:20
Sorry for the lack of response, we still have a Cacti 0.8.8 server in production and will soon get a new test server for Cacti 1.x.
I will report back once I can test with the new machine.
