### ISSUE TITLE
[1.3 QA] Need to click Device filter drop down box twice for host list to appear

### ISSUE THREAD

**Issue by jab60** [Cacti/cacti#5531] opened 2023-10-14 21:14 UTC
# Describe the bug

On forms where the filter includes the Device drop down box. Need to click the drop down arrow twice for the list to be expanded.
The first click only highlights the box contents.
Also after the list drops down the item in the main control remains highlighted, which is different to other drop down boxes.

## To Reproduce

1. Go to 'Management>>Graphs'
2. Click the drop down arrow on the Device control, the list does not appear
3. Click a second time and the list appears

## Expected behavior

The list of devices should drop down on first click

## Screenshots

Video of effect on the Management>>Graphs and Data Sources forms
![Need2Clickstoactivatedropdown](https://github.com/Cacti/cacti/assets/108667514/ffa4a24a-2f48-4bae-a340-3dbe61f7b147)

## Desktop (please complete the following information)

- W10 22H2
- Chrome & FF
- cacti 1.3.0 develop

## Smartphone (please complete the following information)

- N/A

## Additional context

The issue persists across forms where the Device drop down filter box is used. Bit tricky to describe.
If you are on Graphs form and the list **has dropped down**, if you then go to data sources form the list will not drop down on first click.
Conversely if you are on Graphs form and the list **did not drop down**, if you then go to the data sources the list will now drop down on first click.
Hope that make sense. It appears to happen on all forms where a call to `html_host_filter` is made.

**Comment by TheWitness** [comment] 2023-10-14 22:23
I cant reproduce this.  Check first for JavaScript errors, and then on the Debug > Network Panel see if the callback activates on the first click.

**Comment by TheWitness** [comment] 2023-10-14 22:24
I see how you do it now.  Bah humbug.

**Comment by jab60** [comment] 2023-10-16 17:06
I nearly didnt report it thought it was me going mad. - Tricky little one

**Comment by TheWitness** [comment] 2023-11-14 00:25
Fixed now.  You will have to reset your browser cache.

**Closed by TheWitness** 2023-11-14 00:25 UTC
Labels: bug, resolved, confirmed, type:bug, status:confirmed
