### ISSUE TITLE
[CACTI 1.2.X - LATEST]  PHP Errors related to authentication type LOCAL and LDAP.

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#3784] opened 2020-09-02 06:52 UTC
# Describe the bug

PHP Errors related to authentication type LOCAL and LDAP.

## To Reproduce

Go to Cacti and login.

## Screenshots

![image](https://user-images.githubusercontent.com/1744639/91941457-8c1dda80-ecf9-11ea-917e-8d7e5d8947b7.png)

## Desktop (please complete the following information)

- win10

- Opera

- Latest

## Error:

2020/09/02 08:46:45 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php[25]:include(), /include/auth.php[171]:require_once(), /auth_login.php[669]:html_common_header(), /lib/html.php[2381]:is_view_allowed(), /lib/auth.php[617]:CactiErrorHandler())
2020/09/02 08:46:45 - ERROR PHP NOTICE: Undefined index: sess_user_id in file: /var/www/html/cacti/lib/auth.php on line: 617
2020/09/02 08:46:45 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php[25]:include(), /include/auth.php[171]:require_once(), /auth_login.php[669]:html_common_header(), /lib/html.php[2381]:is_view_allowed(), /lib/auth.php[603]:CactiErrorHandler())
2020/09/02 08:46:45 - ERROR PHP NOTICE: Undefined index: sess_user_id in file: /var/www/html/cacti/lib/auth.php on line: 603

**Comment by netniV** [comment] 2020-09-03 20:22
This is a duplicate of #3781

**Closed by netniV** 2020-09-03 20:22 UTC
Labels: bug, duplicate
