### ISSUE TITLE
Add a way to export/import automation rule

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#3325] opened 2020-03-05 16:03 UTC
If a new server is has to be installed, all automation rule have to be re-created by hand.
Or if you have access to the DB you need to make a backup of some table.
Not practical.

It could be nice to have a export/import feature for automation rules.

**Comment by cigamit** [comment] 2020-03-08 15:53
Duplicate of this enhancement.

**Comment by cigamit** [comment] 2020-03-08 15:54
https://github.com/Cacti/cacti/issues/412

**Closed** 2020-03-08 15:54 UTC
Labels: duplicate, enhancement
