### ISSUE TITLE
Ragged graph

### ISSUE THREAD

**Issue by gadzet21** [Cacti/cacti#1548] opened 2018-04-18 13:37 UTC
Hey,
Download value from SNMP is normal, but graph is ragged. Graph in realtime is every time OK. 
Why is not always the value saved in the database and the rrd file?

General Information:
Date | Wed, 18 Apr 2018 15:34:23 +0200
Cacti Version | 1.1.35
Cacti OS | unix
RSA Fingerprint | bb:b2:39:dd:1e:39:67:f1:1e:d4:df:3d:c9:e2:ed:79
NET-SNMP Version | NET-SNMP version: 5.7.3
RRDtool Version | RRDtool 1.6.x
Devices | 972
Graphs | 49959
Data Sources | SNMP Get: 1SNMP Query: 37019Script Server: 9Script Query - Script Server: 12929Total: 49958

Poller Information:
Interval | 300
Type | SPINE 1.1.31  Copyright 2004-2017 by The Cacti Group
Items | Action[0]: 53683Action[2]: 12938Total: 66621
Concurrent Processes | 5
Max Threads | 10
PHP Servers | 5
Script Timeout | 60
Max OID | 50
Last Run Statistics | Time:40.8138 Method:spine Processes:5 Threads:10 Hosts:972 HostsPerProcess:195 DataSources:66621 RRDsProcessed:0

System Memory:
MemTotal | 4.96 K MB
MemFree | 358.72 MB
Buffers | 90.02 MB
Cached | 3.60 K MB
Active | 3.61 K MB
Inactive | 822.93 MB
SwapTotal | 1.02 K MB
SwapFree | 985.27 MB

PHP Information:
PHP Version | 7.0.27-0+deb9u1
PHP OS | Linux
PHP uname | Linux cacti2 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64
PHP SNMP | Installed
max_execution_time | 60
memory_limit | 256M

![cacti-graph1](https://user-images.githubusercontent.com/33205464/38932845-ab6cc768-4317-11e8-9739-706f9750c66a.jpg)
![cacti-logs1](https://user-images.githubusercontent.com/33205464/38932866-af852660-4317-11e8-9389-70ea3aeeabdd.jpg)
![cacti-mysql1](https://user-images.githubusercontent.com/33205464/38932869-b1c7d4cc-4317-11e8-9ba6-51898d454b2b.jpg)
![cacti-realtime1](https://user-images.githubusercontent.com/33205464/38933116-68cf6ffe-4318-11e8-803e-9d02ff57244a.jpg)
[cacti-172.18.225.10 - 29 - CPU Used.xlsx](https://github.com/Cacti/cacti/files/1924034/cacti-172.18.225.10.-.29.-.CPU.Used.xlsx)

**Comment by gadzet21** [comment] 2018-04-19 07:45
I did upgrade Cacti and spine to 1.1.38. I've increased the number of processes.
Settings look like this:

General Information:
Date | Thu, 19 Apr 2018 08:50:17 +0200
Cacti Version | 1.1.38
Cacti OS | unix
RSA Fingerprint | bb:b2:39:dd:1e:39:67:f1:1e:d4:df:3d:c9:e2:ed:79
NET-SNMP Version | NET-SNMP version: 5.7.3
RRDtool Version | RRDtool 1.6.x
Devices | 972
Graphs | 49959
Data Sources | SNMP Get: 1SNMP Query: 37019Script Server: 9Script Query - Script Server: 12929Total: 49958

Poller Information:
Interval | 300
Type | SPINE 1.1.38  Copyright 2004-2017 by The Cacti Group
Items | Action[0]: 53683Action[2]: 12938Total: 66621
Concurrent Processes | 10
Max Threads | 10
PHP Servers | 5
Script Timeout | 60
Max OID | 50
Last Run Statistics | Time:298.0428 Method:spine Processes:10 Threads:10 Hosts:972 HostsPerProcess:98 DataSources:66621 RRDsProcessed:0

System Memory:
MemTotal | 4.96 K MB
MemFree | 174.61 MB
Buffers | 60.40 MB
Cached | 1.75 K MB
Active | 3.45 K MB
Inactive | 1.01 K MB
SwapTotal | 1.02 K MB
SwapFree | 860.97 MB

PHP Information:
PHP Version | 7.0.27-0+deb9u1
PHP OS | Linux
PHP uname | Linux cacti2 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64
PHP SNMP | Installed
max_execution_time | 60
memory_limit | 256M

Chart appearance from another device and script:
![cacti-graph2](https://user-images.githubusercontent.com/33205464/38977968-3be1c7be-43b6-11e8-9299-f8b1030e6b44.jpg)
Gaps in graphs are mainly found in recently added devices.
What else can I check?

**Comment by gadzet21** [comment] 2018-04-19 12:58
2018/04/19 06:32:47 - SYSTEM BOOST STATS: Time:440.9500 RRDUpdates:323944
2018/04/19 06:32:18 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:3.4532
2018/04/19 06:32:15 - SYSTEM THOLD STATS: Time:0.0289 Tholds:0 TotalDevices:972 DownDevices:9 NewDownDevices:
2018/04/19 06:30:00 - SYSTEM STATS: Time:299.3149 Method:spine Processes:10 Threads:10 Hosts:972 HostsPerProcess:98 DataSources:66621 RRDsProcessed:0
2018/04/19 06:25:28 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:2.3595
2018/04/19 06:25:25 - SYSTEM THOLD STATS: Time:0.0214 Tholds:0 TotalDevices:972 DownDevices:9 NewDownDevices:
2018/04/19 06:25:01 - SYSTEM STATS: Time:299.3209 Method:spine Processes:10 Threads:10 Hosts:972 HostsPerProcess:98 DataSources:66621 RRDsProcessed:0
2018/04/19 06:20:26 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:1.6926
2018/04/19 06:20:23 - SYSTEM THOLD STATS: Time:0.0145 Tholds:0 TotalDevices:972 DownDevices:9 NewDownDevices:
2018/04/19 06:20:01 - SYSTEM STATS: Time:298.9021 Method:spine Processes:10 Threads:10 Hosts:972 HostsPerProcess:98 DataSources:66621 RRDsProcessed:0
2018/04/19 06:15:25 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:1.8786
2018/04/19 06:15:23 - SYSTEM THOLD STATS: Time:0.0421 Tholds:0 TotalDevices:972 DownDevices:9 NewDownDevices:
2018/04/19 06:15:00 - SYSTEM STATS: Time:298.1637 Method:spine Processes:10 Threads:10 Hosts:972 HostsPerProcess:98 DataSources:66621 RRDsProcessed:0
2018/04/19 06:11:17 - SYSTEM DSSTATS STATS: Type:DAILY, Time:957.7566
2018/04/19 06:10:32 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:3.6562
2018/04/19 06:10:27 - SYSTEM THOLD STATS: Time:0.0202 Tholds:0 TotalDevices:972 DownDevices:9 NewDownDevices:
2018/04/19 06:10:00 - SYSTEM STATS: Time:298.5626 Method:spine Processes:10 Threads:10 Hosts:972 HostsPerProcess:98 DataSources:66621 RRDsProcessed:0
2018/04/19 06:05:31 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:3.3621
2018/04/19 06:05:27 - SYSTEM THOLD STATS: Time:0.0205 Tholds:0 TotalDevices:972 DownDevices:9 NewDownDevices:
2018/04/19 06:05:01 - SYSTEM STATS: Time:297.7005 Method:spine Processes:10 Threads:10 Hosts:972 HostsPerProcess:98 DataSources:66621 RRDsProcessed:0
2018/04/19 06:01:33 - SYSTEM DSSTATS STATS: Type:HOURLY, Time:3.1439
2018/04/19 06:01:30 - SYSTEM THOLD STATS: Time:0.0258 Tholds:0 TotalDevices:972 DownDevices:9 NewDownDevices:
2018/04/19 06:00:00 - SYSTEM STATS: Time:299.1299 Method:spine Processes:10 Threads:10 Hosts:972 HostsPerProcess:98 DataSources:66621 RRDsProcessed:0

**Comment by cigamit** [comment] 2018-04-20 02:56
I would enable on demand updating.  That is the only way you will get beyond this.  I can be found under Console > Settings > Performance.  Once enabled, you will see your polling times drop significantly, but you have to ensure that your cron account and your web account both have write access to the RRDfiles.  Otherwise, you will get gaps from another source.

I would suggest that this is not a bug, but rather a usage issue.  So, I will close this issue.  Another note by the way if you run the following command:

`du -hs /var/www/html/cacti/rra`

And it reports more memory than is available for disk cach.  You MUST enable On Demand Updating.

**Closed by cigamit** 2018-04-20 02:56 UTC

**Comment by gadzet21** [comment] 2018-04-20 08:54
@cigamit  - thanks for you prompt.
I have enable on demand updating. 

![cacti-menu1](https://user-images.githubusercontent.com/33205464/39033756-e791551c-4473-11e8-9352-b03d0db50868.jpg)

Result of the command: du -hs /var/cacti/rra
11G

I also have another cacti installation (0.8.7g) in which it is over 6450 devices, 109187 graphs and it is everything OK. Result of the command: 80G

@anarkia1976 - because of the very frequent changes in interfaces and frequent updates on CMTS I can not switch re-index to none.

@netniV - I was change number of CPU too 8 and threads too 30 - I will see if it will be better.
Script and Script Server Timeout Value - 60s

**Comment by anarkia1976** [comment] 2018-04-20 13:30
Do you have real cpu/threads on your machine?
if you have 8 cpu i think threads will be 16 or 32, why 30?
this is my configuration and all working without problems:
![image](https://user-images.githubusercontent.com/1744639/39053620-c851a058-44af-11e8-8b87-d8e942f2a6c7.png)

**Comment by netniV** [comment] 2018-04-20 17:13
I don't think threads needs to be a multiple of the cpus, but the number of processes is usually aligned so it's one per processor.

**Comment by gadzet21** [comment] 2018-04-20 20:55
@anarkia1976 @netniV  - you are right, the mistake was allocated only 1 CPU
Currently it is 6.
`2018/04/20 22:15:49 - SYSTEM STATS: Time:47.4413 Method:spine Processes:4 Threads:25 Hosts:972 HostsPerProcess:243 DataSources:66573 RRDsProcessed:0`

@cigamit - maybe it is worth to put in the settings tab - poller in the line "Maximum Concurrent Poller Processes" something similar to?
... The max number of CPU in your machine is: "cat /proc/cpuinfo | grep processor | wc -l"

By the way - thank you for your help.

**Comment by anarkia1976** [comment] 2018-04-24 05:56
@netniV you are right, it's related to the cpu type (virtual or physical). 

@gadzet21 please check and close if it's fixed. I don't think is necessary to make a banner for max cpus.

**Comment by netniV** [comment] 2018-04-24 14:14
It was already closed 4 days ago 😵 

Undecided if the wording should be changed.  If you feel like it should, create a pull request and it'll be reviewed 👍
