### ISSUE TITLE
[1.3 QA] Installer never ends, always redirect to step1

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5563] opened 2023-11-12 19:45 UTC
Actual develop branch.

After installation, I'm redirected again to step 1 (licence agreement)
Tested on firefox, chrome.
No error or warning in log.

Part of install-complete.log:
[2023-11-12 20:39:38] [          global always  ] Import of Package #1 'ESXi_Device.xml.gz' under Profile '1' succeeded
[2023-11-12 20:39:38] [          global always  ] About to import Package #2 'Fortigate.xml.gz'.
[2023-11-12 20:39:39] [          global always  ] Import of Package #2 'Fortigate.xml.gz' under Profile '1' succeeded
[2023-11-12 20:39:39] [          global always  ] Repairing Automation Rules
[2023-11-12 20:39:39] [      automation always  ] Setting default data source profile to 5 Minute Collection (1)
[2023-11-12 20:39:39] [          global always  ] Updating automation network (1), mode "on" => "", subnet "192.168.1.0/24" => 192.168
[2023-11-12 20:39:39] [          global always  ] WARNING: Device Template for your Operating System Not Found.  You will need to impo
[2023-11-12 20:39:39] [          global always  ] Repopulating poller cache
[2023-11-12 20:39:39] [          global always  ] Repopulating SNMP Agent cache
[2023-11-12 20:39:39] [          global always  ] Generating RSA Key Pair
[2023-11-12 20:39:39] [          global always  ] Finished INSTALL Process for v1.3.0.99.1699817667.d891712f
[2023-11-12 20:39:39] [            sync always  ] Found 0 poller(s) to sync
[2023-11-12 20:39:39] [            sync always  ] No Remote Data Collectors found for full synchronization
[2023-11-12 20:39:39] [          global always  ] Installation was started at 2023-11-12 19:39:37, completed at 2023-11-12 19:39:39

**Comment by dallenk** [comment] 2023-11-13 06:36
This also occurred on my 1.3 installation

**Comment by TheWitness** [comment] 2023-11-13 22:32
Duplicate of #5500

**Closed by TheWitness** 2023-11-13 22:32 UTC
Labels: bug, duplicate, unverified, type:bug, status:needs-verification
