### ISSUE TITLE
[1.2.0 beta 1] cli/upgrade_database.php fails to upgrade to 1.2.0 beta 1

### ISSUE THREAD

**Issue by paulgevers** [Cacti/cacti#2103] opened 2018-10-21 18:39 UTC
As part of the Debian packaging of cacti, it runs cli/upgrade_database.php after installing the new files to upgrade the database to the latest state. (This avoids the need for the admin to manually trigger the update in the web interface.)

However, with the beta release I see this:
```
10/21/2018 05:39:42 PM Running cli/upgrade_database.php as part of package update...
10/21/2018 05:39:44 PM Invalid Cacti version 1.2.0 - Beta 1 (DB: 1.1.36), cannot upgrade to 1.2.0
```

**Comment by netniV** [comment] 2018-10-23 13:16
I will try and give this a go tonight.

**Comment by paulgevers** [comment] 2018-10-23 19:35
@cigamit this is what I have in my post-installation script which is run with the old version of the installed Debian cacti package as $2:
```
# Make sure the database is up-to-date
if [ -n "$2" ] ; then
    { echo "Running cli/upgrade_database.php as part of package update..." ; \
      php /usr/share/cacti/cli/upgrade_database.php ; } | \
        if [ -f /usr/bin/ts ] ; then LC_TIME=C ts "%m/%d/%Y %I:%M:%S %p" | tee -a /var/log/cacti/cacti.log ; \
        else tee -a /var/log/cacti/cacti.log ; fi
fi
```
Or are you asking for something different?

**Comment by netniV** [comment] 2018-10-23 19:54
Confirmed, this is a bug with the upgrade_database script, nothing to do with @paulgevers' stuff.  I'll see why shortly.

**Comment by netniV** [comment] 2018-10-23 19:56
It should be noted that whilst using the upgrade_database.php will be fine for upgrades, the cli install_cacti.php should really be used for new installs to properly populate templates, automation etc.

**Comment by netniV** [comment] 2018-10-24 08:16
Let me review this at the weekend and I'll come back to you.  I have a busy couple of days ahead so won't have much time before then.

**Comment by netniV** [comment] 2018-10-27 07:53
This should now be resolved in the latest development version.

**Comment by cigamit** [comment] 2018-11-10 16:50
Closing due to lack of feedback.  Pretty sure it's solved.

**Closed by cigamit** 2018-11-10 16:50 UTC
Labels: beta, bug

**Comment by paulgevers** [comment] 2018-12-02 20:36
> It should be noted that whilst using the upgrade_database.php will be fine for upgrades, the cli install_cacti.php should really be used for new installs to properly populate templates, automation etc.

@netniV I still hope that once you can come with a recommendation for Debian how to use the new install_cacti.php script. Currently I am still using my old method.

**Comment by netniV** [comment] 2018-12-03 09:46
@paulgevers It's been a few months since I last tested the install so I will run through some tests this week and try and get some documentation sorted out for it.  Unfortunately, the day job has been ramping up quite a bit at the moment so left me needing more downtime but I really need to get that sorted before release.
