### ISSUE TITLE
[1.2.19] - Remote pollers forcing install on web gui

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#4464] opened 2021-11-15 18:00 UTC
# Describe the bug

When going to remote poller gui, install is being forced, even when install process is completed, install routine is started over

## To Reproduce

Remote Poller web gui, install process, options make no difference. Install process 'completes' but then starts back over.

Have tried removing all 'install_' entries in the db to no avail.
Mail poller is online, and remote pollers all appear to be working and reporting results, this appears to only impact the remote gui. (which i use to look at the log files)

- OS: CentOS7

- Browser: FF

## Additional context

This is an install with 13 remote pollers all on Centos7

**Comment by netniV** [comment] 2021-11-15 18:08
I think this is a duplicate of #4454, try getting the updated install/functions.php and then running a command line install to see what output is produced as per that thread.

**Comment by netniV** [comment] 2021-11-15 18:09
If you need to send the output securely, please email developers@cacti.net

**Comment by KnoAll** [comment] 2021-11-15 18:19
Interesting. Once I updated the functions.php everything seems to be back to normal

**Comment by netniV** [comment] 2021-11-15 21:40
Strange, coz there was no real code updates, just more logging.

**Comment by TheWitness** [comment] 2021-12-10 19:47
Cool.  I'm going to close this then.

**Comment by TheWitness** [comment] 2021-12-10 19:47
Writing it off to maybe a permission issue.  If it happens again, you can always open a new ticket.

**Closed by TheWitness** 2021-12-10 19:47 UTC
Labels: question
