### ISSUE TITLE
1.3.0 - QA ping only device sit in unknown state

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5062] opened 2022-12-06 22:14 UTC
When creating a device that has ping set as the availability mode 
the device sits in unknown state

![image](https://user-images.githubusercontent.com/13388748/206034659-86cb3814-1d48-4c1c-a6bf-673952124325.png)

**Comment by bmfmancini** [comment] 2022-12-06 22:16
![image](https://user-images.githubusercontent.com/13388748/206034985-34ab6eff-22f9-4bb8-a7d5-1c3a7d2a19e2.png)

Poller is cmd.php

**Comment by bmfmancini** [comment] 2022-12-07 02:27
I don't think so
However on my 1.2.x install I'm running spine in 1.3.x just running cmd

**Comment by netniV** [comment] 2022-12-10 13:49
My 1.3.x ping only device came up.  Does the device have polled items?

**Comment by bmfmancini** [comment] 2022-12-12 15:52
Ok so these sites had no graphs I just updated the template to add a ds to each site

**Comment by bmfmancini** [comment] 2022-12-12 15:53
Ok so when the device has 0 data sources site sits in Unknown state 
if it had a DS the correct state is shown

**Comment by netniV** [comment] 2022-12-12 22:40
I think that's by design if you check with @TheWitness

**Comment by TheWitness** [comment] 2022-12-15 02:07
Hmm.  Did I fix that issue only for SNMP Ping?

**Comment by bmfmancini** [comment] 2022-12-15 02:20
Not sure

I've tested the same scenario in 1.2.22 it works fine  but that's using
spine I've not tried cmd.php

**Comment by TheWitness** [comment] 2022-12-15 02:31
Oh, the difference between Spine and cmd.php, is spine will mark the device up if it simply pings.  cmd.php instead only polls the device if it has Data Sources.  I don't want to change this for 1.3.0 though.  Too many higher priority things.  Use spine 💯

**Comment by TheWitness** [comment] 2022-12-15 02:31
Closing this in hopes that it's fine

**Closed by TheWitness** 2022-12-15 02:31 UTC
Labels: not a bug, no plans
