### ISSUE TITLE
DST not handled correctly

### ISSUE THREAD

**Issue by reboot1983** [Cacti/cacti#1052] opened 2017-10-29 07:45 UTC
Since this morning I have a gap in my graphs because last night DST ended.
The gap is strange, because we did not miss an hour.

Raspberry Pi - up2date
PHP 5.6.30
Cacti 1.1.27
RRDTool 1.4.x

![image](https://user-images.githubusercontent.com/20405704/32141613-fd867aa4-bc84-11e7-8529-de525f415708.png)

**Comment by cigamit** [comment] 2017-10-29 13:50
The only way to really resolve this is to have your system in something like GMT, where there is no such thing as DST, and then grab the zone information from the browser and correct the output that way.  I don't think its a major change from a Cacti perspective.  However, there migrating systems might be a bit more complex.

Therefore, I'm not in a hurry to resolve this at the moment.

**Comment by dmrzzz** [comment] 2017-11-03 18:56
Actually I've found a simple way to correct this in cmd.php; see issue #1061 and PR #1062

**Comment by cigamit** [comment] 2017-11-04 14:10
Can you answer if when this is applied, will there be any other gaps created for older systems?

**Comment by netniV** [comment] 2018-01-09 06:46
This may also be a related issue:
https://forums.cacti.net/posting.php?mode=reply&f=2&t=58327

> The graph details (a.k.a tabular data) shows a data point at 14.30PM whereas the visual graph shows the same point at 19.30PM. The visual graph is exactly 5 hours ahead of the graph data. I have set the timezone in /etc/php.ini to America/New York. The visual graph is correct and matches local time. Why is the graph data behind? System time on the linux machine is in UTC.
>
> Overall, the graphing action also begins a several hours after I began polling. Appreciate any thoughts on this.

**Comment by TheWitness** [comment] 2021-04-12 13:15
This is a duplicate of #645 which has been resolved and will be a part of both spine and cacti 1.2.17.

**Closed by TheWitness** 2021-04-12 13:15 UTC
Labels: enhancement, poller

**Comment by TheWitness** [comment] 2021-04-12 13:21
Sorry, was not the other number, but this has been resolved in both spine and cmd.php and will be a part of the 1.2.17 release.
