### ISSUE TITLE
Deprecation warnings when attempting real-time Graphs with PHP8.1

### ISSUE THREAD

**Issue by manhvu1997** [Cacti/cacti#4853] opened 2022-07-01 05:47 UTC
I installed cacti 1.2.20. I created a graph and device success, but when I viewed the graph in realtime, I faced the issue below:
![image](https://user-images.githubusercontent.com/58839875/176831834-2e346542-ddf2-4cad-9053-519c2b424b5b.png)

The log file said: 
2022-07-01 12:44:11 - ERROR PHP DEPRECATED: Implicit conversion from float 35.4375 to int loses precision in file: /var/www/html/cacti/lib/rrd.php  on line: 3670
2022-07-01 12:44:11 - CMDPHP PHP ERROR Backtrace:  (/graph_realtime.php[244]:rrdtool_create_error_image(), /lib/rrd.php[3670]:wordwrap(), CactiErrorHandler())

Can you help me to fix that?

**Comment by netniV** [comment] 2022-07-01 09:36
This bug still exists under v1.2.22, what PHP version are you running?

**Comment by manhvu1997** [comment] 2022-07-01 09:53
Thanks for your reply
My PHP version is  8.1

**Comment by TheWitness** [comment] 2022-07-01 11:56
I saw this the other day and neglected to look into it.

**Comment by manhvu1997** [comment] 2022-07-01 17:22
How can I change the PHP core from PHP 8.1 to PHP 7.4 on cacti?
![image](https://user-images.githubusercontent.com/58839875/176941507-cebb51d1-480c-48e2-a665-3982183fb844.png)

**Comment by TheWitness** [comment] 2022-07-01 17:32
You should not need to downgrade as this is a very narrowly defined error and only happens when your Data Sources have not had their RRDfiles created.  But if you still want to do it, you need to do it through aptitude (apt).

**Comment by TheWitness** [comment] 2022-07-01 20:42
What Cacti release is this?

**Comment by manhvu1997** [comment] 2022-07-02 02:31
I fixed it, but I faced new issue, can you help me to fix this:
![image](https://user-images.githubusercontent.com/58839875/176983483-e33b8a49-3c06-460c-b5a4-f1cb158a5658.png)

**Comment by TheWitness** [comment] 2022-07-02 09:16
Closing this one now as the first bug was fixed.  

This second issue is better served on the forums as its not a bug.

Basically, you database is setup using one collation/charset and was not fully migrated.

Best thing to do is go to `Console > System Utilities > Technical Support` then scroll to the bottom to see how wrong your charset and collation are from the database side.

Then make the required changes and restart the database.  After that, reverify from that page, and if all is good, run the CLI script `convert_innodb.php` (will check this) using the utf8 option.

**Closed** 2022-07-02 09:20 UTC
Labels: bug, resolved, confirmed, PHP8

**Comment by manhvu1997** [comment] 2022-07-04 00:52
Thank you theWitness
All proplems were solved by running command "/usr/bin/php /var/www/html/cacti/cli/convert_tables.php --debug --innodb --utf8"
