### ISSUE TITLE
Feature Request: "Combined" Graphs

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#793] opened 2017-06-05 19:07 UTC
I am in desperate need of a new feature I would describe as a "combined" graph. It differs from an aggregate graph in that you may select multiple existing graphs using different graph templates and still "combine" them into a single view. Aggregate is limited to joining up graphs of only the same graph template type. 
For years I have been "breaking" aggregate by creating aggregated graphs of different graph template types, but this still allowed me to get the necessary data sources on the same graph and the ability to go in and "fix" the parts that were broken. Now in the newer versions of Cacti, I can't trick the system anymore. 
I could go through numerous examples of where I need this functionality, but a simple example is combining a temperature and humidity graph together. And now with right y-axis labeling abilities in RRDtool, you have the opportunity to do some really great things here. 
I also have cases where I need to combine multiple different types of temperature graphs together all using different graph templates. 
Any help is greatly appreciated!

**Comment by cigamit** [comment] 2017-06-07 23:32
Bah, too many features, not enough time :(  Understood.  This has been a message expressed by others for a long time.  You can presently do this using the Advanced feature, you just have to build it one data source at a time.  So, though it takes a little time, you can still get to where you are, or were, before the 1.x upgrade.  Are you clear on that?

**Comment by cigamit** [comment] 2017-08-11 23:32
I'm going to close this one as it's a duplicate of this one.  Yes, a number of people have asked for this... https://github.com/Cacti/cacti/issues/431

**Closed by cigamit** 2017-08-11 23:32 UTC
Labels: enhancement

**Comment by eschoeller** [comment] 2018-06-09 21:03
I'm actually not clear on what the process would be to add things one data source at a time to a graph. I've switched to advanced mode but don't really see what I'd need to do next. Sorry for the late reply, I'm just needing this again.

**Comment by eschoeller** [comment] 2018-06-10 01:43
I went back and found an old Aggregate graph, copied it, removed all the data source items from it and manually added whatever I needed. That seems to work. Certainly a hack, but I can at least get graphs with whatever data I need again. If you have a better way, let me know if you get a chance.

**Comment by superkily086** [comment] 2019-03-22 13:16
i met the same problem.
