### ISSUE TITLE
Installer shows innodb unset in MariaDB 10.11

### ISSUE THREAD

**Issue by chrisch80** [Cacti/cacti#5607] opened 2023-12-05 15:46 UTC
Seems I have the same issue like https://github.com/Cacti/cacti/issues/5030
![grafik](https://github.com/Cacti/cacti/assets/24794879/0ce05b90-5727-4fa3-bacb-a9e996cb24d7)

MariaDB [(none)]> show engines;
+--------------------+---------+-------------------------------------------------------------------------------------------------+--------------+------+------------+
| Engine             | Support | Comment                                                                                         | Transactions | XA   | Savepoints |
+--------------------+---------+-------------------------------------------------------------------------------------------------+--------------+------+------------+
| CSV                | YES     | Stores tables as CSV files                                                                      | NO           | NO   | NO         |
| MRG_MyISAM         | YES     | Collection of identical MyISAM tables                                                           | NO           | NO   | NO         |
| MEMORY             | YES     | Hash based, stored in memory, useful for temporary tables                                       | NO           | NO   | NO         |
| Aria               | YES     | Crash-safe tables with MyISAM heritage. Used for internal temporary tables and privilege tables | NO           | NO   | NO         |
| MyISAM             | YES     | Non-transactional engine with good performance and small data footprint                         | NO           | NO   | NO         |
| SEQUENCE           | YES     | Generated tables filled with sequential values                                                  | YES          | NO   | YES        |
| InnoDB             | DEFAULT | Supports transactions, row-level locking, foreign keys and encryption for tables                | YES          | YES  | YES        |
| PERFORMANCE_SCHEMA | YES     | Performance Schema                                                                              | NO           | NO   | NO         |
+--------------------+---------+-------------------------------------------------------------------------------------------------+--------------+------+------------+
8 rows in set (0.001 sec)

MariaDB [(none)]> SHOW GLOBAL VARIABLES LIKE 'innodb_version';
Empty set (0.002 sec)

MariaDB [(none)]> SHOW GLOBAL VARIABLES LIKE 'version';
+---------------+---------------------------+
| Variable_name | Value                     |
+---------------+---------------------------+
| version       | 10.11.4-MariaDB-1~deb12u1 |
+---------------+---------------------------+
1 row in set (0.001 sec)

$ uname -a
Linux ptc-cacti02 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-1 (2023-07-14) x86_64 GNU/Linux

Any idea how I can solve it?

EDIT:
Cacti Version: v1.2.25 with fresh install

**Comment by chrisch80** [comment] 2023-12-05 16:03
BTW: Cacti Version v1.2.25

**Comment by TheWitness** [comment] 2023-12-05 16:56
I think this is addressed in 1.2.26.  That's the 1.2.x branch.  Can you test that out?

**Comment by TheWitness** [comment] 2023-12-05 23:46
I just confirmed.  It was removed after 10.7.  So, let me make an update.

**Comment by TheWitness** [comment] 2023-12-05 23:48
Duplicate of https://github.com/Cacti/cacti/issues/5030

**Comment by TheWitness** [comment] 2023-12-05 23:49
Fixed now.

**Closed by TheWitness** 2023-12-05 23:49 UTC
Labels: bug, QA, type:bug
