### ISSUE TITLE
Errors when doing a graph Sync 1.2.12

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3759] opened 2020-08-17 14:25 UTC
Hey Guys 

I am not sure if this is a duplicate I have not found any other reports 

I noticed today that when you do a sync graph after changing a graph template the dialogue box pops up and hangs
when you check the log the following comes up 

2020-08-17 10:13:38 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())

2020-08-17 10:13:38 - ERROR PHP ERROR: Uncaught Error: Call to undefined function api_data_source_cache_crc_update() in /var/www/html/cacti/lib/utility.php:745 Stack trace: #0 /var/www/html/cacti/lib/template.php(547): push_out_host('313', '1457') #1 /var/www/html/cacti/lib/template.php(882): update_graph_data_source_output_type('1306', 0) #2 /var/www/html/cacti/lib/template.php(622): change_graph_template('1306', '80', true) #3 /var/www/html/cacti/graph_templates.php(305): retemplate_graphs('80') #4 /var/www/html/cacti/graph_templates.php(49): form_actions() #5 {main} thrown in file: /var/www/html/cacti/lib/utility.php on line: 745

**Comment by bmfmancini** [comment] 2020-08-17 14:40
Oh I also found then when this does fail the graphs come back as damaged

**Comment by netniV** [comment] 2020-08-17 15:16
Pretty sure this is a duplicate.

**Comment by cigamit** [comment] 2020-08-18 05:22
While yes it is a duplicate of #3646 and #3717, Larry's commit only fixes the CLI.  It also happens in the UI on the Graph Template page when you select "Sync Graphs".  Word of caution when testing before fixing.  It will corrupt the current graphs, so you will have to restore your DB.

**Closed** 2020-09-06 23:54 UTC
Labels: bug, resolved
