### ISSUE TITLE
Intropage plugin Dashboards wiped out

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#4405] opened 2021-09-21 00:11 UTC
I'm posting this in Cacti because I believe it to be related to the plugin changes made the 1st week of Sept 9/4-9/6? Related to #4390 maybe? It happened then after updating 1.2.x branch for testing and I wrote it off as a fluke or some 1 time issue related to the changes. It Just happened again and no changes have been made since 9/6 1.2.x branch pull. My session was idle for hours and I came back to monitor a few things and Cacti wouldn't load pages. I tried to go to log, then console management etc.. wouldn't respond, then I got the 
```
Sorry, we could not process your last action.
Error:	403 Forbidden
Reason:	You don't have permission to access this resource. Server unable to read htaccess file, denying access to be safe
```
I closed the browser and logged in again, there was no intropage dashboard built, all back to defaults. I asked a colleague to check and his dashboard was gone also. In the logs I could see that something happened.

```
2021/09/20 19:58:03 - CMDPHP SQL Backtrace: (/index.php[105]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:intropage_console_after(), /plugins/intropage/include/settings.php[75]:display_information(), /plugins/intropage/display.php[33]:intropage_upgrade_database(), /plugins/intropage/include/database.php[349]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:58:03 - CMDPHP ERROR: A DB Exec Failed!, Error: Multiple primary key defined
2021/09/20 19:58:03 - CMDPHP SQL Backtrace: (/index.php[105]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:intropage_console_after(), /plugins/intropage/include/settings.php[75]:display_information(), /plugins/intropage/display.php[33]:intropage_upgrade_database(), /plugins/intropage/include/database.php[267]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:58:03 - CMDPHP ERROR: A DB Exec Failed!, Error: Multiple primary key defined
2021/09/20 19:57:55 - CMDPHP SQL Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[514]:include_once(), /include/global_arrays.php[2750]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:plugin_webseer_config_arrays(), /plugins/webseer/setup.php[308]:plugin_webseer_check_config(), /plugins/webseer/setup.php[50]:plugin_webseer_upgrade(), /plugins/webseer/setup.php[107]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:57:55 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'compression'
2021/09/20 19:57:55 - CMDPHP SQL Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[514]:include_once(), /include/global_arrays.php[2750]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:plugin_webseer_config_arrays(), /plugins/webseer/setup.php[308]:plugin_webseer_check_config(), /plugins/webseer/setup.php[50]:plugin_webseer_upgrade(), /plugins/webseer/setup.php[105]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:57:55 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'compression'
2021/09/20 19:57:55 - CMDPHP SQL Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[514]:include_once(), /include/global_arrays.php[2750]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:plugin_webseer_config_arrays(), /plugins/webseer/setup.php[308]:plugin_webseer_check_config(), /plugins/webseer/setup.php[50]:plugin_webseer_upgrade(), /plugins/webseer/setup.php[103]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:57:55 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'compression'
2021/09/20 19:57:55 - CMDPHP SQL Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[514]:include_once(), /include/global_arrays.php[2750]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:plugin_webseer_config_arrays(), /plugins/webseer/setup.php[308]:plugin_webseer_check_config(), /plugins/webseer/setup.php[50]:plugin_webseer_upgrade(), /plugins/webseer/setup.php[100]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:57:55 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'notify_format'
2021/09/20 19:57:55 - CMDPHP SQL Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[514]:include_once(), /include/global_arrays.php[2750]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:plugin_webseer_config_arrays(), /plugins/webseer/setup.php[308]:plugin_webseer_check_config(), /plugins/webseer/setup.php[50]:plugin_webseer_upgrade(), /plugins/webseer/setup.php[99]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:57:55 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.plugin_webseer_url_log' doesn't exist
2021/09/20 19:57:55 - CMDPHP SQL Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[514]:include_once(), /include/global_arrays.php[2750]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:plugin_webseer_config_arrays(), /plugins/webseer/setup.php[308]:plugin_webseer_check_config(), /plugins/webseer/setup.php[50]:plugin_webseer_upgrade(), /plugins/webseer/setup.php[93]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:57:55 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'proxy_server'
2021/09/20 19:57:55 - CMDPHP SQL Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[514]:include_once(), /include/global_arrays.php[2750]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:plugin_webseer_config_arrays(), /plugins/webseer/setup.php[308]:plugin_webseer_check_config(), /plugins/webseer/setup.php[50]:plugin_webseer_upgrade(), /plugins/webseer/setup.php[92]:db_column_exists(), /lib/database.php[852]:db_fetch_cell(), /lib/database.php[411]:db_fetch_cell_prepared(), /lib/database.php[427]:db_execute_prepared())
2021/09/20 19:57:55 - CMDPHP ERROR: A DB Cell Failed!, Error: Table 'cacti.plugins_webseer_urls' doesn't exist
2021/09/20 19:57:55 - CMDPHP SQL Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[514]:include_once(), /include/global_arrays.php[2750]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:plugin_webseer_config_arrays(), /plugins/webseer/setup.php[308]:plugin_webseer_check_config(), /plugins/webseer/setup.php[50]:plugin_webseer_upgrade(), /plugins/webseer/setup.php[78]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:57:55 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'plugin_webseer_proxies' already exists
```

**Comment by jdcoats** [comment] 2021-09-21 00:35
I'm going to update to current tonight but if you guys can came up with any reasoning for this happening twice now... well... there it is above.

**Comment by netniV** [comment] 2021-09-21 01:27
This appears to be related to webseer given your logs above.  The recent changes were more about notifications on plugin issues with hooks not creating duplicate columns etc.

**Comment by jdcoats** [comment] 2021-09-21 01:36
Thanks, I thought that also however I do not think webseer was enabled the last time this happened. I will try to verify that. Either way, can you imagine how one plugin should be able to blow away another's settings/configuration rather this:
```
2021/09/20 19:58:03 - CMDPHP SQL Backtrace: (/index.php[105]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:intropage_console_after(), /plugins/intropage/include/settings.php[75]:display_information(), /plugins/intropage/display.php[33]:intropage_upgrade_database(), /plugins/intropage/include/database.php[349]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:58:03 - CMDPHP ERROR: A DB Exec Failed!, Error: Multiple primary key defined
2021/09/20 19:58:03 - CMDPHP SQL Backtrace: (/index.php[105]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:intropage_console_after(), /plugins/intropage/include/settings.php[75]:display_information(), /plugins/intropage/display.php[33]:intropage_upgrade_database(), /plugins/intropage/include/database.php[267]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:58:03 - CMDPHP ERROR: A DB Exec Failed!, Error: Multiple primary key defined
2021/09/20 19:57:55 - CMDPHP SQL Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[514]:include_once(), /include/global_arrays.php[2750]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:plugin_webseer_config_arrays(), /plugins/webseer/setup.php[308]:plugin_webseer_check_config(), /plugins/webseer/setup.php[50]:plugin_webseer_upgrade(), /plugins/webseer/setup.php[107]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:57:55 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'compression'
2021/09/20 19:57:55 - CMDPHP SQL Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[514]:include_once(), /include/global_arrays.php[2750]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:plugin_webseer_config_arrays(), /plugins/webseer/setup.php[308]:plugin_webseer_check_config(), /plugins/webseer/setup.php[50]:plugin_webseer_upgrade(), /plugins/webseer/setup.php[105]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:57:55 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'compression'
2021/09/20 19:57:55 - CMDPHP SQL Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[514]:include_once(), /include/global_arrays.php[2750]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:plugin_webseer_config_arrays(), /plugins/webseer/setup.php[308]:plugin_webseer_check_config(), /plugins/webseer/setup.php[50]:plugin_webseer_upgrade(), /plugins/webseer/setup.php[103]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:57:55 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'compression'
2021/09/20 19:57:55 - CMDPHP SQL Backtrace: (/index.php[25]:include(), /include/auth.php[28]:require_once(), /include/global.php[514]:include_once(), /include/global_arrays.php[2750]:api_plugin_hook(), /lib/plugins.php[82]:api_plugin_run_plugin_hook(), /lib/plugins.php[215]:plugin_webseer_config_arrays(), /plugins/webseer/setup.php[308]:plugin_webseer_check_config(), /plugins/webseer/setup.php[50]:plugin_webseer_upgrade(), /plugins/webseer/setup.php[100]:db_execute(), /lib/database.php[238]:db_execute_prepared())
2021/09/20 19:57:55 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate column name 'notify_format'
```
still puzzled by it.

**Comment by netniV** [comment] 2021-09-25 00:33
So the problem is that you're attempting to upgrade intropage when it's already applied the upgrades so it fails because they are already there.  intropage isn't actually testing whether the primary key exists.

**Comment by jdcoats** [comment] 2021-09-25 00:38
I have not changed intropage since 8/13. So is it an intropage bug? I'm not intentionally trying to upgrade anything. Just normal operation, session timeout or something and I have to close and re-open browser when this happens and then intropage dashboard is gone.

**Comment by netniV** [comment] 2021-09-25 09:55
Does this keep happening? If so, what is the plugin version in the plugin table vs the one in the INFO file?

**Comment by TheWitness** [comment] 2021-09-25 14:54
This one is pretty weird.  Let me dig in a bit.

**Comment by TheWitness** [comment] 2021-09-25 14:56
What MySQL/MariaDB version are you using on the back end?

**Comment by TheWitness** [comment] 2021-09-25 15:13
It's almost as if the table `plugin_config` was emptied for some reason.  Run a check table on that table.

**Comment by jdcoats** [comment] 2021-09-25 15:24
```
 mysql cacti
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 8743505
Server version: 10.5.10-MariaDB-log Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [cacti]> check table plugin_config;
+---------------------+-------+----------+----------+
| Table               | Op    | Msg_type | Msg_text |
+---------------------+-------+----------+----------+
| cacti.plugin_config | check | status   | OK       |
+---------------------+-------+----------+----------+
1 row in set (0.001 sec)
```

It has happened twice.

**Comment by jdcoats** [comment] 2021-09-25 15:32
@netniV 
```
MariaDB [cacti]> select * from plugin_config;
+----+---------------+------------------------+--------+-----------------------------+-------------------------------------------+---------+
| id | directory     | name                   | status | author                      | webpage                                   | version |
+----+---------------+------------------------+--------+-----------------------------+-------------------------------------------+---------+
|  0 | intropage     | Intropage/Dashboard    |      1 | The Cacti Group, Petr Macek | https://github.com/cacti/plugin_intropage | 4.0.0   |
|  6 | thold         | Thresholds             |      1 | The Cacti Group             | http://www.cacti.net                      | 1.6     |
|  7 | routerconfigs | Router Configs         |      1 | The Cacti Group             | http://www.cacti.net                      | 1.5.3   |
| 11 | mactrack      | Device Tracking        |      1 | The Cacti Group             | http://www.cacti.net                      | 4.4     |
| 12 | monitor       | Device Monitoring      |      4 | The Cacti Group             | http://www.cacti.net                      | 2.5     |
| 13 | hmib          | Host MIB Tool          |      1 | The Cacti Group             | http://www.cacti.net                      | 3.3     |
| 17 | weathermap    | PHP Network Weathermap |      1 | Howard Jones                | http://www.network-weathermap.com/        | 0.98a   |
| 20 | audit         | Audit Plugin for Cacti |      1 | The Cacti Group             | http://www.cacti.net                      | 1.0     |
| 23 | syslog        | Syslog Monitoring      |      1 | The Cacti Group             | http://www.cacti.net                      | 3.2     |
+----+---------------+------------------------+--------+-----------------------------+-------------------------------------------+---------+
9 rows in set (0.000 sec)

MariaDB [cacti]> exit
Bye
syslog01 ~ # grep -i version /var/www/localhost/htdocs/cacti/plugins/intropage/INFO
version = 4.0.0
syslog01 ~ #
```
notice that i did go ahead and uninstall webseer. Still waiting to see if the issue is reproducable.

**Comment by TheWitness** [comment] 2021-09-25 17:15
So, was webseer even installed at one time?

**Comment by jdcoats** [comment] 2021-09-25 18:03
yes webseer was installed and enabled but i was not using it. There was nothing configured for it so i just uninstalled it after this issue came up.

**Comment by TheWitness** [comment] 2021-09-25 18:16
Okay.  Interesting, so the WebSeer code is not very 'error proofed' like the Cacti Database Upgrade code.  I think that should be resolved there.  How about the other errors with Intropage, are they gone?

**Comment by jdcoats** [comment] 2021-09-26 00:27
The intropage errors only showed up when the issue took place, otherwise none are present.

**Comment by jdcoats** [comment] 2021-09-26 00:33
I may be speculating but I have been able to preproduce the issue where my session has been idle for hours on the clog page and got the 👍 
![image](https://user-images.githubusercontent.com/42470924/134789190-0c9649fa-f3b9-4967-ad38-3ffd18d1c46a.png)

when i returned. However now after selecting console or graphs or some other tab or even refresh it does recover without generating the errors in the log and the intropage dashboard is not lost.

**Comment by netniV** [comment] 2021-09-26 00:42
So, the error above suggests that for some reason you were being directed into displaying a .htaccess page which seems weird.  Are you using Apache/Nginx level auth ? If not, which method are you using?

**Comment by jdcoats** [comment] 2021-09-26 00:45
Apache with ldap auth configured.

**Comment by TheWitness** [comment] 2021-09-26 00:50
So, do you have "Remember Me" enabled?  I'm guessing you didn't, and the forced logout redirected somewhere where it was not supposed to.  But the funny thing is if you are on the clog page, your session should be updating with each refresh which should block the session from being erased by apache.

**Comment by netniV** [comment] 2021-09-26 00:50
LDAP auth at the apache level or cacti level?

**Comment by netniV** [comment] 2021-09-26 00:52
> So, do you have "Remember Me" enabled? I'm guessing you didn't, and the forced logout redirected somewhere where it was not supposed to. But the funny thing is if you are on the clog page, your session should be updating with each refresh which should block the session from being erased by apache.

I've said before that our session logic over timeouts isn't quite right.  Each tab handles it's own timeout, and doesn't seem to take notice of other tabs so one tab can logout all others.  Something we can test for and properly address in 1.3.

**Comment by jdcoats** [comment] 2021-09-26 00:59
ldap in cacti. I'm almost 99% sure that the last time i logged in i had check the remember me but i cannot be 100% sure that I do/have every time. I can say that in versions over the past year that my users have reported similar and I've just been shrugging them off and telling them to close their browser and start over. It only really stood out as an issue that I should bring up when the dashboards got wiped out. May be related and may not be but since i have no clue at this point I can only provide the feedback that I am.

**Comment by netniV** [comment] 2021-09-26 01:06
I think the intropage losing it's data is more than likely one of several scenarios.... you accidentally uninstalled it rather than disabling it (unlikely to happen without you going oops).... you had an issue with the various flavours of changes to the plugin logic that clashed with intropage making it try to recreate the tables somehow (maybe manual versioning adjustments ?)... someone truncated the wrong table.... there's an unknown bug in intropage that can lead to emptying the tables?

I think for now, as we have little hope in identifying the cause, and it's not repeatedly happening we are just going to have to close this issue off without knowing why.  The session logic is really a separate bug tracker.

**Comment by jdcoats** [comment] 2021-09-26 01:16
I didn't disable or uninstall the plugin once much less twice. I promise that I didn't have an oops moment twice :) So I will make a prediction that there is an unknown bug in intropage that can lead to emptying the tables. I'm ok with closing this and I will open a new one If I can re-create knowing that all of my unused plugins are disabled and uninstalled. Thanks guys for all you do!

**Comment by TheWitness** [comment] 2021-10-02 15:02
I'll buy that.  Once you get more information, can you create a new bug in Intropage issue tracker?  I'm going to close this one.

**Closed by TheWitness** 2021-10-02 15:02 UTC
Labels: bug, unverified
