### ISSUE TITLE
Unable to install plugins on 1.2.18

### ISSUE THREAD

**Issue by lichtl** [Cacti/cacti#4361] opened 2021-07-28 12:26 UTC
# Describe the bug

On a fresh 1.2.18 installation install a plugin will result in the following error message.

Error:	500 Internal Server Error
Reason:	The response to the last action was unexpected.

```
2021-07-28 12:16:03 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'Reportit'
2021-07-28 12:16:03 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2021-07-28 12:16:03 - ERROR PHP COMPILE_ERROR in Plugin 'Reportit': require_once(): Failed opening required '/opt/www/cacti/plugins/reportit/system/install.php' (include_path='.:/usr/share/pear:/usr/share/php') in file: /opt/www/cacti/plugins/Reportit/setup.php on line: 583
2021-07-28 12:16:03 - CMDPHP SQL Backtrace: (/plugins.php[74]:api_plugin_install(), /lib/plugins.php[671]:db_execute_prepared())
2021-07-28 12:16:03 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'name' cannot be null
2021-07-28 12:16:03 - DBCALL ERROR: A DB Exec Failed!, Error: 1048, SQL: 'INSERT INTO plugin_config (directory, name, author, webpage, version) VALUES (?, ?, ?, ?, ?)'
```

## To Reproduce

1. Go to 'Configuration>Plugins'

2. Click on 'Install Plugin' (tested on various plugins - reportit, monitor, thold)

```
Error:	500 Internal Server Error
Reason:	The response to the last action was unexpected.
```
```
2021-07-28 12:16:03 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'Reportit'
2021-07-28 12:16:03 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2021-07-28 12:16:03 - ERROR PHP COMPILE_ERROR in Plugin 'Reportit': require_once(): Failed opening required '/opt/www/cacti/plugins/reportit/system/install.php' (include_path='.:/usr/share/pear:/usr/share/php') in file: /opt/www/cacti/plugins/Reportit/setup.php on line: 583
2021-07-28 12:16:03 - CMDPHP SQL Backtrace: (/plugins.php[74]:api_plugin_install(), /lib/plugins.php[671]:db_execute_prepared())
2021-07-28 12:16:03 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'name' cannot be null
2021-07-28 12:16:03 - DBCALL ERROR: A DB Exec Failed!, Error: 1048, SQL: 'INSERT INTO plugin_config (directory, name, author, webpage, version) VALUES (?, ?, ?, ?, ?)'
```
## Expected behavior

Plugin to be installed.

## Desktop (please complete the following information)

- OS: [e.g. iOS] Linux

- Browser [e.g. chrome, safari] Chrome

- Version [e.g. 22] 1.2.18

## Additional context

Running on 10.6.3-MariaDB

**Comment by bmfmancini** [comment] 2021-07-28 12:28
Interesting

Do. You have SELinux enabled?
What does your Apache error. Log show

**Comment by xmacan** [comment] 2021-07-28 12:35
Tested on 1.2.18, I tried to install thold plugin and it works fine. Do all files have the correct permissions? Are they (at least) readable for web servers?

**Comment by lichtl** [comment] 2021-07-28 12:37
Just checked. SElinux is set to "Permissive"

Below the apache log error related to the above event
```
[Wed Jul 28 12:16:03.498498 2021] [php7:error] [pid 21636] [client 172.16.49.14:6018] PHP Fatal error:  require_once(): Failed opening required '/opt/www/cacti/plugins/reportit/system/install.php' (include_path='.:/usr/share/pear:/usr/share/php') in /opt/www/cacti/plugins/Reportit/setup.php on line 583, referer: http://10.49.5.212/cacti/plugins.php
[root@DEFRAS28 plugins]#
```

**Comment by bmfmancini** [comment] 2021-07-28 12:39
Do you have your plugin folder permissions set (readable by apache)

**Comment by lichtl** [comment] 2021-07-28 12:39
all files/folders are owned by user/group of apache

**Comment by xmacan** [comment] 2021-07-28 12:43
Please show result of:
ls -al /opt/www/cacti/plugins/Reportit/

And check php.ini - open_basedir directive

**Comment by lichtl** [comment] 2021-07-28 12:44
```
ls -al /opt/www/cacti/plugins/Reportit/
total 352
drwxr-xr-x. 14 apache apache  4096 Jul 28 11:03 .
drwxrwxr-x. 10 apache apache   139 Jul 28 11:03 ..
drwxr-xr-x.  2 apache apache    23 Jul 28 11:03 archive
drwxr-xr-x.  2 apache apache    23 Jul 28 11:03 cache
drwxr-xr-x.  2 apache apache    23 Jul 28 11:03 exports
drwxr-xr-x.  8 apache apache   163 Jul 28 11:03 .git
drwxr-xr-x.  3 apache apache    28 Jul 28 11:03 .github
-rw-r--r--.  1 apache apache    48 Jul 28 11:03 .gitignore
-rw-r--r--.  1 apache apache  7730 Jul 28 11:03 graph.php
drwxr-xr-x.  2 apache apache  4096 Jul 28 11:03 images
drwxr-xr-x.  3 apache apache    86 Jul 28 11:03 include
-rw-r--r--.  1 apache apache    40 Jul 28 11:03 index.php
-rw-r--r--.  1 apache apache   344 Jul 28 11:03 INFO
-rw-r--r--.  1 apache apache 13731 Jul 28 11:03 items.php
drwxr-xr-x.  2 apache apache  4096 Jul 28 11:03 lib
-rw-r--r--.  1 apache apache 15171 Jul 28 11:03 LICENSE
drwxr-xr-x.  4 apache apache    76 Jul 28 11:03 locales
-rw-r--r--.  1 apache apache 21341 Jul 28 11:03 measurands.php
-rw-r--r--.  1 apache apache 23851 Jul 28 11:03 README.md
-rw-r--r--.  1 apache apache 44221 Jul 28 11:03 reports.php
-rw-r--r--.  1 apache apache 19882 Jul 28 11:03 rrdlist.php
-rw-r--r--.  1 apache apache  5797 Jul 28 11:03 run.php
-rw-r--r--.  1 apache apache 37874 Jul 28 11:03 runtime.php
-rw-r--r--.  1 apache apache 26553 Jul 28 11:03 setup.php
drwxr-xr-x.  2 apache apache    44 Jul 28 11:03 system
-rw-r--r--.  1 apache apache 37361 Jul 28 11:03 templates.php
drwxr-xr-x.  2 apache apache    23 Jul 28 11:03 tmp
-rw-r--r--.  1 apache apache  1052 Jul 28 11:03 .travis.yml
drwxr-xr-x.  2 apache apache   101 Jul 28 11:03 upgrade
-rw-r--r--.  1 apache apache 18994 Jul 28 11:03 variables.php
-rw-r--r--.  1 apache apache 35454 Jul 28 11:03 view.php
```

```
; open_basedir, if set, limits all file operations to the defined directory
; and below.  This directive makes most sense if used in a per-directory
; or per-virtualhost web server configuration file.
; Note: disables the realpath cache
; http://php.net/open-basedir
;open_basedir =

```

**Comment by xmacan** [comment] 2021-07-28 12:48
**drwxr-xr-x.**  2 apache apache    44 Jul 28 11:03 system

Dot at the and  implies that the file has an Access Control List (ACL) with SELinux. You can set or delete ACL association for a file by using the setfacl command

**Comment by lichtl** [comment] 2021-07-28 12:50
```
getfacl system
# file: system
# owner: apache
# group: apache
user::rwx
group::r-x
other::r-x

getfacl system/install.php
# file: system/install.php
# owner: apache
# group: apache
user::rw-
group::r--
other::r--


```

**Comment by xmacan** [comment] 2021-07-28 12:58
HA! Please rename plugin folder name. Use only lowercase, you have **R**eportit

**Comment by lichtl** [comment] 2021-07-28 13:01
Yes that solved it. Intersting since I cloned from git and then there was the error message to rename them equal to the name. Maybe this then should be adjusted since there it indicate the name with first char in Upercase

![image](https://user-images.githubusercontent.com/1228155/127326353-cc361f83-d7fb-4fdf-abc4-8f9279ef3e80.png)

**Comment by xmacan** [comment] 2021-07-28 13:07
Yes, I will look at it

**Comment by netniV** [comment] 2021-08-13 14:48
@xmacan did you submit a PR for the above message issue?

**Comment by xmacan** [comment] 2021-08-13 18:46
@netniV - It is on my TODO list. I will try it at the weekend

**Comment by xmacan** [comment] 2021-08-17 19:24
@netniV  I don't think we can solve anything here. The plugin uses lower case for include ("...plugin/reportit/file.php"), but the user named the directory Reportit.
We could probably just test if there are uppercase letters in the directory name and display a warning if so. But there are plugins that use capital letters, so the message could be confusing.
There are no exact rules for plugin folder names. 
I suggest we close it and don't deal with it anymore.

**Comment by netniV** [comment] 2021-08-17 19:25
The problem is the message showing the wrong case

**Comment by xmacan** [comment] 2021-08-17 19:27
ups ... sorry. I will look again

**Comment by xmacan** [comment] 2021-08-17 19:47
We don't know if upper case is correct or not. We read INFO file and start with ucfirst(name). Rozsirit tedy pouze varovani?
![cacti_names](https://user-images.githubusercontent.com/26485719/129790626-00c8ef81-cef1-48cf-98bb-1e9c86aa190e.png)

**Comment by netniV** [comment] 2021-08-18 11:32
I think at one point Larry was going talking about enforcing it, but I would have to review the code to give a problem indication.  For general use, the Plugin Name is ucfirst()'d but the directory should be lower.

**Comment by xmacan** [comment] 2021-08-18 13:36
ok, I will prepare PR only with strtolower('folder')

**Comment by TheWitness** [comment] 2021-09-08 23:24
@xmacan, is this problem resolved now?  If so, can you please let us know.  I thought I merged something for you.

**Comment by xmacan** [comment] 2021-09-09 06:08
@TheWitness  Yes, it is resolved. You can close this issue

**Closed** 2021-09-09 10:25 UTC
Labels: bug
