### ISSUE TITLE
Under certain circumstances Real Time counter gets stuck and does not count down

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#4917] opened 2022-09-05 13:06 UTC
relating to issue #4893 
it is not solved yet as, at days, graphs still appear with non decrementing timers, 6 as this day for example, out of 52

**Comment by TheWitness** [comment] 2022-09-11 18:55
Bring up the browser debug window for the Realtime window and make it a stand alone window and the find and post the JavaScript error you are getting.

**Comment by TheWitness** [comment] 2022-09-11 18:55
This could be caused by a third party plugin too.

**Comment by majed17** [comment] 2022-09-12 06:24
![cacti-realtime-error](https://user-images.githubusercontent.com/35138065/189586713-a6af979f-fcec-46fa-80c1-12bc303fc46a.png)
is this what you asking for?

**Comment by ahouston** [comment] 2022-09-12 10:45
I believe this is what you were looking for:

![cacti-realtime-dev-console](https://user-images.githubusercontent.com/1083694/189633971-42cbb409-f87a-4a9f-95f3-23fc704138fd.png)

It looks like it's being caused by the async option that's added in lib/html.php on line 2596, looks like the jQuery `$(function()` call is referencing this maybe before the browser has loaded the realtime.js file?

`print get_md5_include_js('include/realtime.js', true);`

I tried removing the true and it fixed the issue for me, I'm just not sure what else it'll break as I assume that the async was added for a reason?

I can't reproduce this in Firefox by the way, but it affects Chrome every time.

**Comment by TheWitness** [comment] 2022-09-12 13:15
That second one was what I 2ass looking for. Thanks!

**Comment by TheWitness** [comment] 2022-09-15 12:43
This is caused by a lazy load issue.  Should be fixed now.  Just update `lib/html.php` and do a full page refresh.

**Comment by majed17** [comment] 2022-09-15 12:46
if it be God's will and if we be living, i'll report tomorrow if that fixes it...

**Comment by TheWitness** [comment] 2022-09-15 12:47
Yea, just had surgery myself this week.  Getting old sucks.  So, moving slow.

**Comment by majed17** [comment] 2022-09-15 13:40
surgery for what?

**Comment by TheWitness** [comment] 2022-09-15 13:44
Hernia as a complication from laparoscopic surgery earlier in the year.

**Comment by majed17** [comment] 2022-09-15 13:56
what are you ill off?

**Comment by majed17** [comment] 2022-09-16 07:17
seems to be working now. by the way, diseases, sorrows, are all God visits... and someone who opens one's diseases to others, will soon be cured!

**Comment by TheWitness** [comment] 2022-09-16 08:19
Amen.

**Closed** 2022-09-16 08:20 UTC
Labels: bug, resolved, confirmed
