### ISSUE TITLE
Cacti 1.2.16: Spine poller "INFO: SNMP Device timeout" in debug in Medium log level 

### ISSUE THREAD

**Issue by iskandarbasman** [Cacti/cacti#4137] opened 2021-02-19 01:14 UTC
# Describe the bug

Enabling medium level logs indicates excessive "INFO: SNMP Device timeout" logs.
Suspect the logs to be false positives.
Below screenshot shows that even localhost is generate these timeout logs to rule out network issue.
Graphing is normal.

![image](https://user-images.githubusercontent.com/67727557/108442454-0a633e80-7292-11eb-82a3-166060f935c9.png)

## To Reproduce

1. Enabled logging level in cacti to medium.
2. Go to cacti log and filter for keyword 'timeout'
3. Many "INFO: SNMP Device timeout" will be generated.

## Expected behavior

Not expecting to see all these timeout logs especially for localhost polling.
Suspect these logs to be false positives.

## Screenshots

As shown above.

**Comment by netniV** [comment] 2021-02-21 15:36
That is not likely a bug but the reporting of something that is actually happening.

**Comment by iskandarbasman** [comment] 2021-02-22 01:06
How should I verify this ?
Why does it only appear the MEDIUM log levels and not LOW ?
Graphing looks okay from what I can see.

> 
> 
> That is not likely a bug but the reporting of something that is actually happening.

**Comment by bmfmancini** [comment] 2021-02-22 01:37
It's because the medium reporting is more verbose

But also those are not errors they are informational stating the timeout
setting for localhost it doesn't actually say a timeout has occurred

**Comment by TheWitness** [comment] 2021-02-22 03:42
I've got an update coming.

**Comment by TheWitness** [comment] 2021-02-23 00:17
Well, we like to keep logging at low unless you are doing diagnostics.  Since this is really not a bug.  I'm going to close this one.  When I first commented, I did not note that this was for successive polling cycles.

**Closed by TheWitness** 2021-02-23 00:17 UTC
Labels: bug, unverified

**Comment by iskandarbasman** [comment] 2021-02-23 00:27
How can I tell whether this these snmp timeouts at the MEDIUM level is valid.
How is this different from the snmp timeout at the LOW logging level ?
> 
> 
> Well, we like to keep logging at low unless you are doing diagnostics. Since this is really not a bug. I'm going to close this one. When I first commented, I did not note that this was for successive polling cycles.

**Comment by bmfmancini** [comment] 2021-02-23 00:30
They are not timeouts

They are simply telling you what the timeout is set to

**Comment by iskandarbasman** [comment] 2021-02-23 00:50
Argghh... So that means. DOH!
So that means I need to filter these logs when troubleshooting. I SEE...
