### ISSUE TITLE
[1.2.0] Templates-Aggregate Template-Aggregate Item uneditable

### ISSUE THREAD

**Issue by 311villagehead** [Cacti/cacti#2285] opened 2019-01-08 07:46 UTC
As show in the figure，Template Aggregate's Item uneditable.Then,I can not use Aggregate template to create aggregate graph
![123](https://user-images.githubusercontent.com/29101156/50816574-ef583d80-135b-11e9-96d1-55bc750144ba.jpg)
![234](https://user-images.githubusercontent.com/29101156/50816749-7c9b9200-135c-11e9-9046-7014cdb74b5a.jpg)

**Comment by cigamit** [comment] 2019-01-08 12:42
This was done by design as it would produce several hrules.

**Comment by cigamit** [comment] 2019-01-08 23:36
Please let us know what you were thinking about.  Nth percentile does not really aggregate well, which is why is was disabled.

**Comment by 311villagehead** [comment] 2019-01-09 08:45
I want to create graph like this，it was in 0.8.8h
![333](https://user-images.githubusercontent.com/29101156/50886500-7d4f2980-142b-11e9-8112-3f2095572dd0.jpg)
but int 1.2.0 i can't use it anymore,because i can't edit item.For example,our company has a network device,now I must create a graph that show four interfaces traffic. My boss only want to know total Interfaces traffic and 95th percentile.Can you tell me how to achieve it,thank you!

**Comment by cigamit** [comment] 2019-01-11 00:18
Goto Console > Settings > General and enable Advanced Graph/Data Source Creation Method and you can hand create graphs like you did before.

**Comment by cigamit** [comment] 2019-01-12 19:57
Posted your updated aggregate template screen.

**Comment by cigamit** [comment] 2019-01-12 19:58
You may have to delete and re-create your, or remove all items, and then put them back again.  Post the screen first before you take that step.

**Comment by 311villagehead** [comment] 2019-01-16 03:15
I don't understand what you are talking about,can you give me a document to explain how it works,better have pictures，thanks！

**Comment by cigamit** [comment] 2019-01-16 12:38
Sorry, post your updated 'manual' graph.  You should be able to add the nth ptile stuff there, you just can't use aggregate to generate it.

**Comment by cigamit** [comment] 2019-01-16 12:38
I had you confused with another ticket.

**Comment by cigamit** [comment] 2019-01-16 12:43
This is how you re-enable the advanced mode.

![graphcreationmode](https://user-images.githubusercontent.com/957322/51249779-f84b9f00-1959-11e9-9c8a-9b7efe0509a3.png)

**Comment by cigamit** [comment] 2019-01-16 13:02
Additionally, if you are running develop, I've made a few changes to allow that HRULE to be selectable.  Not sure if the backend covers that properly though.

**Comment by cigamit** [comment] 2019-01-16 13:02
I marked it for the wrong issue.  Here is the commit 41f2da5494f4d72c3f9a7eb68ed3d80f63e8bf32

**Comment by cigamit** [comment] 2019-01-16 13:09
So, after some testing, the hrule appears on the graph and only correctly if you are using one of the totaling method, but the value shown is always zero.  That could be due to the lack of traffic though.

**Comment by 311villagehead** [comment] 2019-01-17 09:06
Thank you. I hope that in the next version, the option of aggregation template can be edited so that you can easily create your own graphics using aggregation template. Especially in China,most billing accounts are totale 95th percentile.

**Comment by cigamit** [comment] 2019-01-27 18:02
I'm going to close this one.  Aggregate needs a lot of work for 1.3.

**Closed by cigamit** 2019-01-27 18:02 UTC
Labels: resolved
