### ISSUE TITLE
FATAL: MySQL Error:'2013', Message:'Lost connection to MySQL server during query' [110, Connection timed out] (Spine thread)

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#1713] opened 2018-07-18 06:04 UTC
I have the problem every day at the same time:
![image](https://user-images.githubusercontent.com/17400240/42862666-32b4331c-8a69-11e8-85fa-5d8479bf6987.png)
Cacti 1.1.37
Maria DB setting:
max_heap_table_size = 400M
max_allowed_packet = 25165824
tmp_table_size = 128M
join_buffer_size = 128M
innodb_buffer_pool_size = 2048M
innodb_doublewrite = off
innodb_flush_log_at_timeout = 3
innodb_read_io_threads = 32
innodb_write_io_threads = 16
wait_timeout = 28800

2018-07-18 02:41:35 - SPINE: Poller[Main Poller] FATAL: MySQL Error:'2006', Message:'MySQL server has gone away' [110, Connection timed out] (Spine thread)
--
2018-07-18 02:41:35 - SPINE: Poller[Main Poller] ERROR: SQL Failed! Error:'2013', Message:'Lost connection to MySQL server during query', SQL Fragment:'UPDATE poller_reindex SET assert_value='1267431156' WHERE host_id='75' AND data_query_id='1' AND arg1='.1.3.6.1.2.1.1.3.0''
2018-07-18 02:41:35 - SPINE: Poller[Main Poller] FATAL: MySQL Error:'2006', Message:'MySQL server has gone away' [110, Connection timed out] (Spine thread)
2018-07-18 02:41:35 - SPINE: Poller[Main Poller] ERROR: SQL Failed! Error:'2013', Message:'Lost connection to MySQL server during query', SQL Fragment:'UPDATE poller_reindex SET assert_value='967242716' WHERE host_id='281' AND data_query_id='1' AND arg1='.1.3.6.1.2.1.1.3.0''
2018-07-18 02:41:35 - SPINE: Poller[Main Poller] ERROR: SQL Failed! Error:'2013', Message:'Lost connection to MySQL server during query', SQL Fragment:'UPDATE poller_time SET end_time=NOW() WHERE poller_id=1 AND pid=78810'
18-Jul-2018 02:41:06 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 632 CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)
18-Jul-2018 02:41:06 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/html/cacti/poller.php on line: 632

**Comment by cigamit** [comment] 2018-07-18 13:21
Check your mysql error log.  Maybe you are running a backup the wrong way.  Make sure you use --lock-tables=false to prevent ruining your graphs.

**Comment by Izmenoff** [comment] 2018-07-20 06:15
Thanks!
I tuned mariaDB and error has left. But I see new problem from 2:30-2:40pm. Spine does not enough time for poller. But other time polling is ok (20-30sec).
I have just increased threads from 20 to 50 and waiting for tomorrow result

2018-07-20 02:29:04 - SPINE:   Poller[Main Poller] ERROR: Spine Timed Out While   Waiting for Threads to End
--
2018-07-20 02:29:01 - SPINE:   Poller[Main Poller] ERROR: Spine Timed Out While   Processing Devices Internal

**Comment by netniV** [comment] 2018-07-20 07:53
It sounds like you have a cpu or disk intensive process kicking in at that time.

**Comment by cigamit** [comment] 2018-07-21 12:47
You have too many threads.  More than likely some of your disk status are timing out or providing a very slow response.  Are you monitoring disks on Windows machines?  Are you monitoring disks for other server types?  Are you using the hmib plugin.

Show us a few rows of your system stats.  If you are running 50 threads and more than one process, you graphing will tank as you only have 100 max connections in mysql.  You have to remember the theory on this one:

`total_connections = processes * (threads + script_servers per process)`

If your VM only have two cores and does not have hyperthreading enabled, you have to tune the number of threads.  More is not always good, especially if you are using ICMP ping, which is very expensive.  Better to use SNMP ping.

**Comment by cigamit** [comment] 2018-07-21 12:48
The problem with ICMP ping is that all ping responses interrupt ALL threads, by design.  So, it's a horrible way to ping a device.

**Comment by cigamit** [comment] 2018-07-21 12:54
I would suggest a `max_connections` no less than 300.  Make sure you restart MySQL/MariaDB after that.  Once that is done, you will be all set.  As such, I will go ahead and close this issue.

**Closed by cigamit** 2018-07-21 12:54 UTC

**Comment by pavinthan** [comment] 2019-04-03 03:34
It's happing to me also 
Version 0.8.8b

<img width="339" alt="Screen Shot 2019-04-03 at 9 03 20 AM" src="https://user-images.githubusercontent.com/13897936/55451151-60bc2b00-55ef-11e9-808f-63f24c2e21cb.png">

```
cur_time='0.000000', avg_time='0.000000', total_polls='1972', failed_polls='1972', availability='0.0000' WHERE id='4398''
04/03/2019 11:25:46 AM - SPINE: Poller[0] ERROR: SQL Failed! Error:'2013', Message:'Lost connection to MySQL server during query', SQL Fragment:'INSERT INTO poller_output (local_data_id, rrd_name, time, output) VALUES (109630,'ib_lock_time','2019-04-03 11:25:33','1036226'),(109631,'ob_lock_time','2019-04-03 11:25:33','1036750'),(109632,'cpu_util','2019-04-03 11:25:33','5'),(109633,'tot_ob_packets','2019-04-03 11:25:33','68571863'),(109634,'total_OB_KBs','2019-04-03 11:25:33','24781541'),(109635,'total_IB_bytes','2019-04-03 11:25:33','19354646'),(109636,'ob_current_esn0','2019-04-03 11:25:33','1441'),(109637,'ib_current_power','2019-04-03 11:25:33','11'),(109638,'ob_pckts_16apsk2p3','2019-04-03 11:25:33','2164'),(109639,'ob_pckts_16apsk3p4','2019-04-03 11:25:33','5630'),(109640,'ob_pckts_16apsk4p5','2019-04-03 11:25:33','10827'),(109641,'ob_pckts_16apsk5p6','2019-04-03 11:25:33','68229'),(109642,'ob_pckts_16apsk8p9','2019-04-03 11:25:33','0'),(109643,'ob_pckts_16apsk9p10','2019-04-03 11:25:33','0'),(109644,'ob_pckts_32apsk3p4','2019-04-03 11:25:33','0'),(109645,'ob_pckts_32apsk4p5','2019-04-03 11:25:33','0'),(109646,'ob_pckts_32apsk5p6','2019-04-03 11'
04/03/2019 11:25:47 AM - SPINE: Poller[0] ERROR: SQL Failed! Error:'2013', Message:'Lost connection to MySQL server during query', SQL Fragment:'INSERT INTO poller_output (local_data_id, rrd_name, time, output) VALUES (109704,'ib_lock_time','2019-04-03 11:25:33','771745'),(109705,'ob_lock_time','2019-04-03 11:25:33','771740'),(109706,'cpu_util','2019-04-03 11:25:33','6'),(109707,'tot_ob_packets','2019-04-03 11:25:33','51030558'),(109708,'total_OB_KBs','2019-04-03 11:25:33','18456464'),(109709,'total_IB_bytes','2019-04-03 11:25:33','14334486'),(109710,'ob_current_esn0','2019-04-03 11:25:33','1316'),(109711,'ib_current_power','2019-04-03 11:25:33','10'),(109712,'ob_pckts_16apsk2p3','2019-04-03 11:25:33','5422'),(109713,'ob_pckts_16apsk3p4','2019-04-03 11:25:33','7919'),(109714,'ob_pckts_16apsk4p5','2019-04-03 11:25:33','6252'),(109715,'ob_pckts_16apsk5p6','2019-04-03 11:25:33','44522'),(109716,'ob_pckts_16apsk8p9','2019-04-03 11:25:33','0'),(109717,'ob_pckts_16apsk9p10','2019-04-03 11:25:33','0'),(109718,'ob_pckts_32apsk3p4','2019-04-03 11:25:33','0'),(109719,'ob_pckts_32apsk4p5','2019-04-03 11:25:33','0'),(109720,'ob_pckts_32apsk5p6','2019-04-03 11:25'
04/03/2019 11:25:46 AM - SPINE: Poller[0] ERROR: SQL Failed! Error:'2013', Message:'Lost connection to MySQL server during query', SQL Fragment:'INSERT INTO poller_output (local_data_id, rrd_name, time, output) VALUES (110148,'ib_lock_time','2019-04-03 11:25:34','91900'),(110149,'ob_lock_time','2019-04-03 11:25:34','91924'),(110150,'cpu_util','2019-04-03 11:25:34','8'),(110151,'tot_ob_packets','2019-04-03 11:25:34','9925685'),(110152,'total_OB_KBs','2019-04-03 11:25:34','8756296'),(110153,'total_IB_bytes','2019-04-03 11:25:34','1013845162'),(110154,'ob_current_esn0','2019-04-03 11:25:34','1396'),(110155,'ib_current_power','2019-04-03 11:25:34','15'),(110156,'ob_pckts_16apsk2p3','2019-04-03 11:25:34','53762'),(110157,'ob_pckts_16apsk3p4','2019-04-03 11:25:34','276693'),(110158,'ob_pckts_16apsk4p5','2019-04-03 11:25:34','463820'),(110159,'ob_pckts_16apsk5p6','2019-04-03 11:25:34','4035414'),(110160,'ob_pckts_16apsk8p9','2019-04-03 11:25:34','0'),(110161,'ob_pckts_16apsk9p10','2019-04-03 11:25:34','0'),(110162,'ob_pckts_32apsk3p4','2019-04-03 11:25:34','0'),(110163,'ob_pckts_32apsk4p5','2019-04-03 11:25:34','0'),(110164,'ob_pckts_32apsk5p6','2019-04-03 '
04/03/2019 11:25:47 AM - SPINE: Poller[0] ERROR: SQL Failed! Error:'2013', Message:'Lost connection to MySQL server during query', SQL Fragment:'UPDATE host SET status='3', status_event_count='0', status_fail_date='2019-03-28 12:45:00', status_rec_date='2019-03-28 12:30:00', status_last_error='Host did not respond to SNMP, UDP: Ping timed out', min_time='0.000000', max_time='0.000000', cur_time='0.000000', avg_time='0.000000', total_polls='1249', failed_polls='2', availability='99.8399' WHERE id='4404''
04/03/2019 11:25:47 AM - SPINE: Poller[0] ERROR: SQL Failed! Error:'2013', Message:'Lost connection to MySQL server during query', SQL Fragment:'UPDATE host SET status='3', status_event_count='0', status_fail_date='0000-00-00 00:00:00', status_rec_date='2019-03-27 13:05:00', status_last_error='Host did not respond to SNMP, UDP: Ping timed out', min_time='0.000000', max_time='0.000000', cur_time='0.000000', avg_time='0.000000', total_polls='1496', failed_polls='1', availability='99.9332' WHERE id='4402''
```


mysql config 
```
#
# The MySQL database server configuration file.
#
# You can copy this to one of:
# - "/etc/mysql/my.cnf" to set global options,
# - "~/.my.cnf" to set user-specific options.
#
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.
#
# For explanations see
# http://dev.mysql.com/doc/mysql/en/server-system-variables.html

# This will be passed to all mysql clients
# It has been reported that passwords should be enclosed with ticks/quotes
# escpecially if they contain "#" chars...
# Remember to edit /etc/mysql/debian.cnf when changing the socket location.
[client]
port            = 3306
socket          = /var/run/mysqld/mysqld.sock

# Here is entries for some specific programs
# The following values assume you have at least 32M ram

# This was formally known as [safe_mysqld]. Both versions are currently parsed.
[mysqld_safe]
socket          = /var/run/mysqld/mysqld.sock
nice            = 0

[mysqld]
#
# * Basic Settings
#
back_log                        = 300
open-files-limit        = 8192
# open-files                    = 1024
user            = mysql
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
port            = 3306
basedir         = /usr
datadir         = /var/lib/mysql
tmpdir          = /tmp
lc-messages-dir = /usr/share/mysql
skip-external-locking
skip-name-resolve

#
# Instead of skip-networking the default is now to listen only on
# localhost which is more compatible and is not less secure.
bind-address            = 127.0.0.1
#
# * Fine Tuning
#
key_buffer              = 1M #global buffer
thread_cache_size               = 100 #recommend 5% of max_connections

myisam_sort_buffer_size         = 128M  #index buffer size for creating/altering indexes
myisam_max_sort_file_size       = 256M  #max file size for tmp table when creating/alering indexes
myisam_repair_threads           = 4     #thread quantity when running repairs
myisam_recover                  = BACKUP        #repair mode, recommend BACKUP

# This replaces the startup script and checks MyISAM tables if needed
# the first time they are touched
#max_connections        = 100
#table_cache            = 64
thread_concurrency     = 16
#
# * Query Cache Configuration
#
query_cache_size                = 32M   #global buffer
query_cache_limit               = 512K  #max query result size to put in cache
#
# * Logging and Replication
#
# Both location gets rotated by the cronjob.
# Be aware that this log type is a performance killer.
# As of 5.1 you can enable the log at runtime!
# general_log_file        = /var/log/mysql/mysql.log
# general_log             = 1
#
# Error log - should be very few entries.
#
log_error = /var/log/mysql/error.log
#
# Here you can see queries with especially long duration
log_slow_queries       = /var/log/mysql/mysql-slow.log
long_query_time = 2
#log-queries-not-using-indexes
#
# The following can be used as easy to replay backup logs or for replication.
# note: if you are setting up a replication slave, see README.Debian about
#       other settings you may need to change.
#server-id              = 1
#log_bin                        = /var/log/mysql/mysql-bin.log
expire_logs_days        = 10
max_binlog_size         = 256M  #max size for binlog before rolling
#binlog_do_db           = include_database_name
#binlog_ignore_db       = include_database_name
#
# * InnoDB
#
# InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.
# Read the manual for more InnoDB related options. There are many!
#
# * Security Features
#
# Read the manual, too, if you want chroot!
# chroot = /var/lib/mysql/
#
# For generating SSL certificates I recommend the OpenSSL GUI "tinyca".
#
# ssl-ca=/etc/mysql/cacert.pem
# ssl-cert=/etc/mysql/server-cert.pem
# ssl-key=/etc/mysql/server-key.pem

## Per-Thread Buffers * (max_connections) = total per-thread mem usage
thread_stack                    = 256K    #default: 32bit: 192K, 64bit: 256K
sort_buffer_size                = 1M      #default: 2M, larger may cause perf issues
read_buffer_size                = 1M      #default: 128K, change in increments of 4K
read_rnd_buffer_size            = 1M      #default: 256K
join_buffer_size                = 134217728 #default: 128K
binlog_cache_size               = 64K     #default: 32K, size of buffer to hold TX queries
## total per-thread buffer memory usage: 8832000K = 8.625GB

## Connections
max_connections                 = 2000  #multiplier for memory usage via per-thread buffers
max_connect_errors              = 100   #default: 10
concurrent_insert               = 2     #default: 1, 2: enable insert for all instances
connect_timeout                 = 30    #default -5.1.22: 5, +5.1.22: 10

max_heap_table_size = 1073741824
max_allowed_packet              = 16777216   #max size of incoming data to allow
tmp_table_size = 134217728

[mysqldump]
quick
quote-names
max_allowed_packet      = 16M

[mysql]
#no-auto-rehash # faster start of mysql but no tab completition

[isamchk]
key_buffer              = 16M

#
# * IMPORTANT: Additional settings that can override those from this file!
#   The files must end with '.cnf', otherwise they'll be ignored.
#
!includedir /etc/mysql/conf.d/
```

**Comment by netniV** [comment] 2019-04-03 11:03
Check your mysql logs, but as a warning, spine 0.8.8 is no longer supported.

**Comment by pavinthan** [comment] 2019-04-04 00:50
@netniV this is my mysql log fine and sorry for cause issue for old version but this is our old system so we can't upgrade it to new version so could you please give any solution to fix this in 0.8.8

```190404 11:25:47 [Note] /usr/sbin/mysqld: Normal shutdown

190404 11:25:47 [Note] Event Scheduler: Purging the queue. 0 events
190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 159191  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 159122  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 159060  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 158971  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 158966  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 158965  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 158964  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 158958  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 158957  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 158956  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 158955  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 158954  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 158951  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 158950  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 158948  user: 'root'

190404 11:25:49 [Warning] /usr/sbin/mysqld: Forcing close of thread 158920  user: 'root'
```

**Comment by netniV** [comment] 2019-04-04 06:26
Well, you have just posted the problem, for some reason MySQL is terminating the threads.  Probably should check out slow query log or locking etc, but this is not something we can resolve.

**Comment by pavinthan** [comment] 2019-04-05 01:47
```root@optus-S2400EP:~# spine -V 5 -R
SPINE: Using spine config file [/etc/spine.conf]
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The path_php_server variable is /usr/share/cacti/site/script_server.php
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The path_cactilog variable is /var/log/cacti/cacti.log
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The log_destination variable is 1 (FILE)
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The path_php variable is /usr/bin/php
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The availability_method variable is 4
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The ping_recovery_count variable is 3
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The ping_failure_count variable is 2
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The ping_method variable is 1
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The ping_retries variable is 1
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The ping_timeout variable is 700
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The snmp_retries variable is 3
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The log_perror variable is 1
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The log_pwarn variable is 1
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The boost_redirect variable is 0
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The log_pstats variable is 1
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The threads variable is 10
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The polling interval is 10 seconds
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The number of concurrent processes is 100
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The script timeout is 180
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The number of php script servers to run is 10
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: StartHost='-1', EndHost='-1', TotalPHPScripts='0'
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The PHP Script Server is Not Required
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The Maximum SNMP OID Get Size is 10
04/05/2019 12:41:11 PM - SPINE: Poller[0] Version 0.8.8b starting
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: MySQL is Thread Safe!
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Spine is running asroot.
04/05/2019 12:41:11 PM - SPINE: Poller[0] SPINE: Initializing Net-SNMP API
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Issues with SNMP Header Version information, assuming old version of Net-SNMP.
04/05/2019 12:41:11 PM - SPINE: Poller[0] SPINE: Initializing PHP Script Server(s)
04/05/2019 12:41:11 PM - SPINE: Poller[0] NOTE: Spine will support multithread device polling.
04/05/2019 12:41:11 PM - SPINE: Poller[0] NOTE: Spine is behaving in a 0.8.7g+ manner
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Initial Value of Active Threads is 0
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Valid Thread to be Created
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: In Poller, About to Start Polling of Host
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The Value of Active Threads is 1
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Valid Thread to be Created
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The Value of Active Threads is 2
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: In Poller, About to Start Polling of Host
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Valid Thread to be Created
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: In Poller, About to Start Polling of Host
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The Value of Active Threads is 3
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Valid Thread to be Created
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The Value of Active Threads is 4
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: In Poller, About to Start Polling of Host
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Valid Thread to be Created
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The Value of Active Threads is 5
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: In Poller, About to Start Polling of Host
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Valid Thread to be Created
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The Value of Active Threads is 6
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: In Poller, About to Start Polling of Host
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Valid Thread to be Created
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: In Poller, About to Start Polling of Host
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The Value of Active Threads is 7
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Valid Thread to be Created
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: In Poller, About to Start Polling of Host
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The Value of Active Threads is 8
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[1986] PING Result: PING: Host does not require ping
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2039] DEBUG: Entering ICMP Ping
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2040] DEBUG: Entering ICMP Ping
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[1986] SNMP Result: SNMP not performed due to setting or ping result
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[0] TH[1] Total Time: 0.0015 Seconds
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Valid Thread to be Created
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The Value of Active Threads is 9
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2047] DEBUG: Entering UDP Ping
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[0] TH[1] DEBUG: HOST COMPLETE: About to Exit Host Polling Thread Function
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[1986] TH[1] RECACHE: Processing 1 items in the auto reindex cache for 'localhost'
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: In Poller, About to Start Polling of Host
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2049] DEBUG: Entering ICMP Ping
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2050] DEBUG: Entering ICMP Ping
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Valid Thread to be Created
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2040] DEBUG: Received EINTR
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2048] DEBUG: Entering ICMP Ping
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[1986] TH[1] Recache DataQuery[6] OID: .1.3.6.1.2.1.1.3.0, output: 78578509
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The Value of Active Threads is 10
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: In Poller, About to Start Polling of Host
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The Value of Active Threads is 9
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2039] DEBUG: Received EINTR
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2055] DEBUG: Entering ICMP Ping
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2040] DEBUG: Received EINTR
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2050] DEBUG: Received EINTR
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2039] DEBUG: Received EINTR
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: Valid Thread to be Created
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2040] DEBUG: Received EINTR
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: The Value of Active Threads is 10
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2050] DEBUG: Received EINTR
04/05/2019 12:41:11 PM - SPINE: Poller[0] DEBUG: In Poller, About to Start Polling of Host
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2039] DEBUG: Received EINTR
04/05/2019 12:41:11 PM - SPINE: Poller[0] Host[2049] DEBUG: Received EINTR
04/05/2019 12:41:11 PM - SPINE: Poller[0] FATAL: MySQL Error:'2013', Message:'Lost connection to MySQL server during query' (Spine thread)
04/05/2019 12:41:11 PM - SPINE: Poller[0] FATAL: MySQL Error:'2013', Message:'Lost connection to MySQL server during query' (Spine thread)```

MySQL error 
```
2019-04-05 12:41:11 706 [Warning] Aborted connection 706 to db: 'cacti' user: 'root' host: 'localhost' (Got an error reading communication packets)
2019-04-05 12:41:11 705 [Warning] Aborted connection 705 to db: 'cacti' user: 'root' host: 'localhost' (Got an error reading communication packets)
2019-04-05 12:41:11 707 [Warning] Aborted connection 707 to db: 'cacti' user: 'root' host: 'localhost' (Got an error reading communication packets)
2019-04-05 12:41:13 721 [Warning] Aborted connection 721 to db: 'cacti' user: 'root' host: 'localhost' (Got an error reading communication packets)
2019-04-05 12:41:13 719 [Warning] Aborted connection 719 to db: 'cacti' user: 'root' host: 'localhost' (Got an error reading communication packets)
2019-04-05 12:41:13 716 [Warning] Aborted connection 716 to db: 'cacti' user: 'root' host: 'localhost' (Got an error reading communication packets)
2019-04-05 12:41:13 720 [Warning] Aborted connection 720 to db: 'cacti' user: 'root' host: 'localhost' (Got an error reading communication packets)
2019-04-05 12:41:23 874 [Warning] Aborted connection 874 to db: 'cacti' user: 'root' host: 'localhost' (Got an error reading communication packets)
2019-04-05 12:41:23 844 [Warning] Aborted connection 844 to db: 'cacti' user: 'root' host: 'localhost' (Got an error reading communication packets)
2019-04-05 12:41:23 831 [Warning] Aborted connection 831 to db: 'cacti' user: 'root' host: 'localhost' (Got an error reading communication packets)
2019-04-05 12:41:23 870 [Warning] Aborted connection 870 to db: 'cacti' user: 'root' host: 'localhost' (Got an error reading communication packets)
2019-04-05 12:41:23 760 [Warning] Aborted connection 760 to db: 'cacti' user: 'root' host: 'localhost' (Got an error writing communication packets)
```

mysql slow query log 
```
# User@Host: root[root] @ localhost []
# Thread_id: 1426  Schema: cacti  QC_hit: No
# Query_time: 0.000440  Lock_time: 0.000090  Rows_sent: 1  Rows_examined: 5
# Rows_affected: 0  Bytes_sent: 217
SET timestamp=1554428761;
SELECT 1 AS id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory=ph.name  WHERE ph.status = 1 AND hook = 'config_insert'  AND ph.name IN ('settings', 'boost', 'dsstats')  UNION  SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory=ph.name  WHERE ph.status = 1 AND hook = 'config_insert'  AND ph.name NOT IN ('settings', 'boost', 'dsstats')  ORDER BY id ASC;
# User@Host: root[root] @ localhost []
# Thread_id: 1426  Schema: cacti  QC_hit: No
# Query_time: 0.000559  Lock_time: 0.000114  Rows_sent: 5  Rows_examined: 24
# Rows_affected: 0  Bytes_sent: 401
SET timestamp=1554428761;
SELECT 1 AS id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory=ph.name  WHERE ph.status = 1 AND hook = 'config_arrays'  AND ph.name IN ('settings', 'boost', 'dsstats')  UNION  SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory=ph.name  WHERE ph.status = 1 AND hook = 'config_arrays'  AND ph.name NOT IN ('settings', 'boost', 'dsstats')  ORDER BY id ASC;
# User@Host: root[root] @ localhost []
# Thread_id: 1426  Schema: cacti  QC_hit: No
# Query_time: 0.000153  Lock_time: 0.000032  Rows_sent: 10  Rows_examined: 20
# Rows_affected: 0  Bytes_sent: 1096
SET timestamp=1554428761;
SELECT * FROM plugin_realms ORDER BY plugin, display;
# User@Host: root[root] @ localhost []
# Thread_id: 1428  Schema: cacti  QC_hit: No
# Query_time: 0.000090  Lock_time: 0.000023  Rows_sent: 0  Rows_examined: 0
# Rows_affected: 0  Bytes_sent: 11
SET timestamp=1554428761;
delete from `plugin_skyvno_failed_jobs`;
# User@Host: root[root] @ localhost []
# Thread_id: 1431  Schema: cacti  QC_hit: No
# Query_time: 0.000091  Lock_time: 0.000025  Rows_sent: 0  Rows_examined: 0
# Rows_affected: 0  Bytes_sent: 11
SET timestamp=1554428761;
delete from `plugin_skyvno_failed_jobs`;
# User@Host: root[root] @ localhost []
# Thread_id: 1429  Schema: cacti  QC_hit: No
# Query_time: 0.000132  Lock_time: 0.000021  Rows_sent: 1  Rows_examined: 4
# Rows_affected: 0  Bytes_sent: 72
SET timestamp=1554428761;
select count(*) as aggregate from `plugin_skyvno_networks`;
# User@Host: root[root] @ localhost []
# Thread_id: 1430  Schema: cacti  QC_hit: No
# Query_time: 0.000082  Lock_time: 0.000018  Rows_sent: 1  Rows_examined: 4
# Rows_affected: 0  Bytes_sent: 72
SET timestamp=1554428761;
select count(*) as aggregate from `plugin_skyvno_networks`;
```

**Comment by netniV** [comment] 2019-04-05 07:09
Check your MySQL error log... I see nothing so far that indicates a Cacti-specific problem.

**Comment by jackouille-ch** [comment] 2020-08-05 09:37
I was facing the same kind of issue:
SPINE: Poller[Main Poller] PID[25322] FATAL: MySQL Error:'2013', Message:'Lost connection to MySQL server during query'

From my side I checked my infrastructure and found the root cause: my Disk infrastructure was suffering (other jobs performing many disk I/O, backups/ snapshots), I discover that my hardware I/O was strongly reduced, generating this kind of errors. After migrating to another disk infrastructure, messages disappeared.

Hoping this helps
