### ISSUE TITLE
1.2.0 creating graph with Generic OID Template broken

### ISSUE THREAD

**Issue by rprofijt** [Cacti/cacti#1748] opened 2018-07-24 19:51 UTC
On the latest git version: when I create a graph via device -> Create graphs for this Device and select the "SNMP - Generic OID Template" the datasource gets created but there is no graph. I see a lot of errors in the log:

2018/07/24 21:41:03 - ERROR PHP NOTICE: Undefined index: graph_template_name in file: /opt/cacti/graphs_new.php  on line: 371
2018/07/24 21:41:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 123 host_new_graphs)(/graphs_new.php: 371 CactiErrorHandler)(/lib/functions.php: 4732 cacti_debug_backtrace
)
2018/07/24 21:41:03 - ERROR PHP NOTICE: Undefined index: graph_template_name in file: /opt/cacti/graphs_new.php  on line: 372
2018/07/24 21:41:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 123 host_new_graphs)(/graphs_new.php: 372 CactiErrorHandler)(/lib/functions.php: 4732 cacti_debug_backtrace
)
2018/07/24 21:41:03 - ERROR PHP NOTICE: Undefined variable: host_id in file: /opt/cacti/lib/html_form_template.php  on line: 181
2018/07/24 21:41:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 123 host_new_graphs)(/graphs_new.php: 372 draw_nontemplated_fields_graph_item)(/lib/html_form_template.php:
 181 CactiErrorHandler)(/lib/functions.php: 4732 cacti_debug_backtrace)
2018/07/24 21:41:03 - ERROR PHP NOTICE: Undefined variable: host_id in file: /opt/cacti/lib/html_form_template.php  on line: 181
2018/07/24 21:41:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 123 host_new_graphs)(/graphs_new.php: 372 draw_nontemplated_fields_graph_item)(/lib/html_form_template.php: 181 CactiErrorHandler)(/lib/functions.php: 4732 cacti_debug_backtrace)
2018/07/24 21:41:03 - ERROR PHP NOTICE: Undefined variable: host_id in file: /opt/cacti/lib/html_form_template.php  on line: 181
2018/07/24 21:41:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 123 host_new_graphs)(/graphs_new.php: 372 draw_nontemplated_fields_graph_item)(/lib/html_form_template.php: 181 CactiErrorHandler)(/lib/functions.php: 4732 cacti_debug_backtrace)
......
......
2018/07/24 21:41:47 - DBCALL ERROR: A DB Exec Failed!, Error:1048, SQL:'INSERT INTO graph_templates_graph (`id`, `local_graph_template_graph_id`, `local_graph_id`, `graph_template_id`, `title`, `vertical_label`, `image_format_id`, `height`, `width`, `base_value`, `slope_mode`, `auto_scale`, `auto_scale_opts`, `auto_scale_log`, `scale_log_units`, `auto_scale_rigid`, `upper_limit`, `lower_limit`, `unit_value`, `unit_exponent_value`, `unit_length`, `no_gridfit`, `alt_y_grid`, `right_axis`, `right_axis_label`, `right_axis_format`, `right_axis_formatter`, `left_axis_formatter`, `auto_padding`, `dynamic_labels`, `force_rules_legend`, `tab_width`, `legend_position`, `legend_direction`) VALUES (0, 0, 262, 34, NULL, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON DUPLICATE KEY UPDATE `local_graph_template_graph_id`=VALUES(`local_graph_template_graph_id`), `local_graph_id`=VALUES(`local_graph_id`), `graph_template_id`=VALUES(`graph_template_id`), `title`=VALUES(`title`), `vertical_label`=VALUES(`vertical_label`), `image_format_id`=VALUES(`image_format_id`), `height`=VALUES(`height`), `width`=VALUES(`width`), `base_value`=VALUES(`base_value`), `slope_mode`=VALUES(`slope_mode`), `auto_scale`=VALUES(`auto_scale`), `auto_scale_opts`=VALUES(`auto_scale_opts`), `auto_scale_log`=VALUES(`auto_scale_log`), `scale_log_units`=VALUES(`scale_log_units`), `auto_scale_rigid`=VALUES(`auto_scale_rigid`), `upper_limit`=VALUES(`upper_limit`), `lower_limit`=VALUES(`lower_limit`), `unit_value`=VALUES(`unit_value`), `unit_exponent_value`=VALUES(`unit_exponent_value`), `unit_length`=VALUES(`unit_length`), `no_gridfit`=VALUES(`no_gridfit`), `alt_y_grid`=VALUES(`alt_y_grid`), `right_axis`=VALUES(`right_axis`), `right_axis_label`=VALUES(`right_axis_label`), `right_axis_format`=VALUES(`right_axis_format`), `right_axis_formatter`=VALUES(`right_axis_formatter`), `left_axis_formatter`=VALUES(`left_axis_formatter`), `auto_padding`=VALUES(`auto_padding`), `dynamic_labels`=VALUES(`dynamic_labels`), `force_rules_legend`=VALUES(`force_rules_legend`), `tab_width`=VALUES(`tab_width`), `legend_position`=VALUES(`legend_position`), `legend_direction`=VALUES(`legend_direction`)'
2018/07/24 21:41:47 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'title' cannot be null
2018/07/24 21:41:47 - CMDPHP SQL Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 131 host_new_graphs_save)(/graphs_new.php: 243 create_complete_graph_from_template)(/lib/template.php: 1039 change_graph_template)(/lib/template.php: 711 sql_save)(/lib/database.php: 1073 _db_replace)(/lib/database.php: 1020 db_execute)(/lib/database.php: 155 db_execute_prepared)(/lib/database.php: 228 cacti_debug_backtrace)
2018/07/24 21:41:47 - DBCALL ERROR: SQL Save Failed for Table 'graph_templates_graph'.  SQL:'INSERT INTO graph_templates_graph (`id`, `local_graph_template_graph_id`, `local_graph_id`, `graph_template_id`, `title`, `vertical_label`, `image_format_id`, `height`, `width`, `base_value`, `slope_mode`, `auto_scale`, `auto_scale_opts`, `auto_scale_log`, `scale_log_units`, `auto_scale_rigid`, `upper_limit`, `lower_limit`, `unit_value`, `unit_exponent_value`, `unit_length`, `no_gridfit`, `alt_y_grid`, `right_axis`, `right_axis_label`, `right_axis_format`, `right_axis_formatter`, `left_axis_formatter`, `auto_padding`, `dynamic_labels`, `force_rules_legend`, `tab_width`, `legend_position`, `legend_direction`) VALUES (0, 0, 262, 34, NULL, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON DUPLICATE KEY UPDATE `local_graph_template_graph_id`=VALUES(`local_graph_template_graph_id`), `local_graph_id`=VALUES(`local_graph_id`), `graph_template_id`=VALUES(`graph_template_id`), `title`=VALUES(`title`), `vertical_label`=VALUES(`vertical_label`), `image_format_id`=VALUES(`image_format_id`), `height`=VALUES(`height`), `width`=VALUES(`width`), `base_value`=VALUES(`base_value`), `slope_mode`=VALUES(`slope_mode`), `auto_scale`=VALUES(`auto_scale`), `auto_scale_opts`=VALUES(`auto_scale_opts`), `auto_scale_log`=VALUES(`auto_scale_log`), `scale_log_units`=VALUES(`scale_log_units`), `auto_scale_rigid`=VALUES(`auto_scale_rigid`), `upper_limit`=VALUES(`upper_limit`), `lower_limit`=VALUES(`lower_limit`), `unit_value`=VALUES(`unit_value`), `unit_exponent_value`=VALUES(`unit_exponent_value`), `unit_length`=VALUES(`unit_length`), `no_gridfit`=VALUES(`no_gridfit`), `alt_y_grid`=VALUES(`alt_y_grid`), `right_axis`=VALUES(`right_axis`), `right_axis_label`=VALUES(`right_axis_label`), `right_axis_format`=VALUES(`right_axis_format`), `right_axis_formatter`=VALUES(`right_axis_formatter`), `left_axis_formatter`=VALUES(`left_axis_formatter`), `auto_padding`=VALUES(`auto_padding`), `dynamic_labels`=VALUES(`dynamic_labels`), `force_rules_legend`=VALUES(`force_rules_legend`), `tab_width`=VALUES(`tab_width`), `legend_position`=VALUES(`legend_position`), `legend_direction`=VALUES(`legend_direction`)'

**Comment by netniV** [comment] 2018-07-25 07:47
First, thanks for the bug report and it's not good when you can't create a graph since that's what Cacti's all about 👍 

Second, when saying "latest git version" can you include the branch and commit hash that you are working from as changes occur all the time so from the time you post to the time we look at something, things could have changed.

Thirdly, I really do want the information from my second point because there were some changes made to the form posting code and we temporarily broke something which should now be fixed.  If you are on the version latest commit, then it means we've missed something else and will investigate a.s.a.p

**Comment by rprofijt** [comment] 2018-07-25 08:00
Hi! Of course: its commit b64213aa7653d176dd92003cd2986ceedcbfb1d2 on the develop branch.

**Comment by netniV** [comment] 2018-07-25 08:34
Thanks for that.  Yeah, that is with the supposed 'fix' so I guess we'll have to revisit this and see why it's broken.

**Comment by netniV** [comment] 2018-07-25 09:08
So I've tracked this down to commit 377dfb708f7123e570e38f1c268a1b5ffe446989 and the problem is that the function is being called with no local_data_id but then attempts to find a default value using the host id which is only found when there is a local_data_id

**Comment by netniV** [comment] 2018-07-25 09:08
Oh and the graphs do seem to be created, not sure it's 100% right though.

**Comment by netniV** [comment] 2018-07-25 09:14
So I've created PR for a potential fix for the issue.  If you want to patch your version and see what happens, but be warned that this may be something where my understanding of the code isn't quite accurate so it'll could be changed before it's finally committed.

**Comment by cigamit** [comment] 2018-07-26 00:54
This is working fine now.  Closing.

**Closed by cigamit** 2018-07-26 00:54 UTC

**Comment by rprofijt** [comment] 2018-07-26 12:43
Hmm, I still get the exact same errors on 026e63bb0000ebe9d5f2b3321844d59eb65d21ba even if I only open up "SNMP - Generic OID Template" without creating the graph..

**Comment by cigamit** [comment] 2018-07-28 13:47
Please update to the latest develop.  Let us know what you find.

**Comment by Berserk04** [comment] 2019-02-19 10:46
Hello! i need help! 

DBCALL ERROR: SQL Save Failed for Table 'graph_templates_graph'. SQL:'INSERT INTO graph_templates_graph (`id`, `local_graph_template_graph_id`, `local_graph_id`, `graph_template_id`, `title`, `vertical_label`, `image_format_id`, `height`, `width`, `base_value`, `slope_mode`, `auto_scale`, `auto_scale_opts`, `auto_scale_log`, `scale_log_units`, `auto_scale_rigid`, `upper_limit`, `lower_limit`, `unit_value`, `unit_exponent_value`, `unit_length`, `no_gridfit`, `alt_y_grid`, `right_axis`, `right_axis_label`, `right_axis_format`, `right_axis_formatter`, `left_axis_formatter`, `auto_padding`, `dynamic_labels`, `force_rules_legend`, `tab_width`, `legend_position`, `legend_direction`) VALUES (0, 0, 31, 0, NULL, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON DUPLICATE KEY UPDATE `local_graph_template_graph_id`=VALUES(`local_graph_template_graph_id`), `local_graph_id`=VALUES(`local_graph_id`), `graph_template_id`=VALUES(`graph_template_id`), `title`=VALUES(`title`), `vertical_label`=VALUES(`vertical_label`), `image_format_id`=VALUES(`image_format_id`), `height`=VALUES(`height`), `width`=VALUES(`width`), `base_value`=VALUES(`base_value`), `slope_mode`=VALUES(`slope_mode`), `auto_scale`=VALUES(`auto_scale`), `auto_scale_opts`=VALUES(`auto_scale_opts`), `auto_scale_log`=VALUES(`auto_scale_log`), `scale_log_units`=VALUES(`scale_log_units`), `auto_scale_rigid`=VALUES(`auto_scale_rigid`), `upper_limit`=VALUES(`upper_limit`), `lower_limit`=VALUES(`lower_limit`), `unit_value`=VALUES(`unit_value`), `unit_exponent_value`=VALUES(`unit_exponent_value`), `unit_length`=VALUES(`unit_length`), `no_gridfit`=VALUES(`no_gridfit`), `alt_y_grid`=VALUES(`alt_y_grid`), `right_axis`=VALUES(`right_axis`), `right_axis_label`=VALUES(`right_axis_label`), `right_axis_format`=VALUES(`right_axis_format`), `right_axis_formatter`=VALUES(`right_axis_formatter`), `left_axis_formatter`=VALUES(`left_axis_formatter`), `auto_padding`=VALUES(`auto_padding`), `dynamic_labels`=VALUES(`dynamic_labels`), `force_rules_legend`=VALUES(`force_rules_legend`), `tab_width`=VALUES(`tab_width`), `legend_position`=VALUES(`legend_position`), `legend_direction`=VALUES(`legend_direction`)'

**Comment by Berserk04** [comment] 2019-02-19 11:01
DBCALL ERROR: SQL Save Failed for Table 'graph_templates_graph'. SQL:'INSERT INTO graph_templates_graph (`id`, `local_graph_template_graph_id`, `local_graph_id`, `graph_template_id`, `title`, `vertical_label`, `image_format_id`, `height`, `width`, `base_value`, `slope_mode`, `auto_scale`, `auto_scale_opts`, `auto_scale_log`, `scale_log_units`, `auto_scale_rigid`, `upper_limit`, `lower_limit`, `unit_value`, `unit_exponent_value`, `unit_length`, `no_gridfit`, `alt_y_grid`, `right_axis`, `right_axis_label`, `right_axis_format`, `right_axis_formatter`, `left_axis_formatter`, `auto_padding`, `dynamic_labels`, `force_rules_legend`, `tab_width`, `legend_position`, `legend_direction`) VALUES (0, 0, 31, 0, NULL, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON DUPLICATE KEY UPDATE `local_graph_template_graph_id`=VALUES(`local_graph_template_graph_id`), `local_graph_id`=VALUES(`local_graph_id`), `graph_template_id`=VALUES(`graph_template_id`), `title`=VALUES(`title`), `vertical_label`=VALUES(`vertical_label`), `image_format_id`=VALUES(`image_format_id`), `height`=VALUES(`height`), `width`=VALUES(`width`), `base_value`=VALUES(`base_value`), `slope_mode`=VALUES(`slope_mode`), `auto_scale`=VALUES(`auto_scale`), `auto_scale_opts`=VALUES(`auto_scale_opts`), `auto_scale_log`=VALUES(`auto_scale_log`), `scale_log_units`=VALUES(`scale_log_units`), `auto_scale_rigid`=VALUES(`auto_scale_rigid`), `upper_limit`=VALUES(`upper_limit`), `lower_limit`=VALUES(`lower_limit`), `unit_value`=VALUES(`unit_value`), `unit_exponent_value`=VALUES(`unit_exponent_value`), `unit_length`=VALUES(`unit_length`), `no_gridfit`=VALUES(`no_gridfit`), `alt_y_grid`=VALUES(`alt_y_grid`), `right_axis`=VALUES(`right_axis`), `right_axis_label`=VALUES(`right_axis_label`), `right_axis_format`=VALUES(`right_axis_format`), `right_axis_formatter`=VALUES(`right_axis_formatter`), `left_axis_formatter`=VALUES(`left_axis_formatter`), `auto_padding`=VALUES(`auto_padding`), `dynamic_labels`=VALUES(`dynamic_labels`), `force_rules_legend`=VALUES(`force_rules_legend`), `tab_width`=VALUES(`tab_width`), `legend_position`=VALUES(`legend_position`), `legend_direction`=VALUES(`legend_direction`)'

**Comment by netniV** [comment] 2019-02-19 11:49
Please create a new issue and fill in all the relevant detail as the above is simply not enough.  Also, you may refer back to this issue by pasting the link in the references/additional info part.
