### ISSUE TITLE
AUTOM8 Silently creates graphs without required user input

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2993] opened 2019-10-01 08:06 UTC
I have a device template which includes 6 associated graph templates. These 6 graph templates use 2 data source templates. Both data source templates have the following items set to override:
Data Source Name
Internal Data Source Name
OID

When creating the graph manually, the following dialog appears:
![image](https://user-images.githubusercontent.com/12864741/65944769-b1baa980-e3ef-11e9-8e7c-3214d5aa770a.png)

And if I select more than one graph to create, this is the resulting dialog, which is correct:
![image](https://user-images.githubusercontent.com/12864741/65944882-e7f82900-e3ef-11e9-9b28-56c39977f8c2.png)

But alas, when I create the device, AUTOM8 sweeps in but doesn't flash up any prompts at all, and proceeds to make an awful mess of all sorts of invalid graphs and data sources :(

**Comment by netniV** [comment] 2019-10-01 11:38
I'm sure you can setup a rule within autom8 to ignore that device template if you know it's one that shouldn't be automatically created.

**Comment by eschoeller** [comment] 2019-10-01 14:09
I completely agree. But should I need to be explicitly doing this for all those cases and how would a user know to do that? 

Eric.

**Comment by netniV** [comment] 2019-10-01 15:33
Well, you either default the values or you prompt the user, but as AUTOM8 is behind the scenes, it has no user to prompt so to use AUTOM8 you must give it the default values to use.  That likely won't work with the templates given they are asking for info so you'd simply have to stop AUTOM8 doing it and make it a manual process of creating that graph, etc.

**Comment by cigamit** [comment] 2019-10-02 09:45
Marking duplicate of #2992.  Then closing.

**Closed by cigamit** 2019-10-02 09:45 UTC
