### ISSUE TITLE
Unable to create the 1.1.38 version of cacti for aggregate image 95 billing

### ISSUE THREAD

**Issue by AliceLiddelll** [Cacti/cacti#2198] opened 2018-12-03 02:57 UTC
I have no way to create 95 chargeable aggregate images on version 1.1.38 of cacti,When I try to create it,There is no way to check the billing option,What should I do
![image](https://user-images.githubusercontent.com/45548261/49350519-3f533d00-f6ea-11e8-9f73-59b1e95a8852.png)

**Comment by cigamit** [comment] 2018-12-03 12:35
This is by design.  Some aspects have been enabled in Cacti 1.2, but I believe there remain other related and non-related issues.  However, you can select these items in 1.2, so I'm going to close this ticket.

**Closed by cigamit** 2018-12-03 12:35 UTC
