### ISSUE TITLE
Settings lost by clicking tabs

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1672] opened 2018-06-18 14:16 UTC
As people are used to working with software that automatically saves settings as they go and this isn't implemented yet in Cacti (planned for the future), it would be wise to offer a warning if a used clicks a tab within the settings area other than the one they are on.  

I clicked away today and instantly remembered I hadn't saved and expected that they were lost, which they were.  A more novice user, might miss this fact as they still see themselves modifying settings, and end up frustrated believing something to be set and not seeing the functionality or flow that they expected.

Other websites I've used do prompt me if I happen to modify something but then click to go to another page.  Presumably using the loss of focus to trigger the warning.

**Comment by cigamit** [comment] 2018-07-14 19:58
Seems easy enough to pull off in the settings page.  100% JS.

**Comment by cigamit** [comment] 2018-07-22 16:03
Resolved.  Duplicate of #1731.

**Closed by cigamit** 2018-07-22 16:03 UTC
Labels: enhancement
