### ISSUE TITLE
Allow adding a Non-Existing Data Source to an Existing Graph when the Template is Updated

### ISSUE THREAD

**Issue by unguzov** [Cacti/cacti#1836] opened 2018-08-15 11:37 UTC
I get a bug when trying to add a new element to Graph Template. Interestingly, it happens when the browser session is over (for example, the next day) and I'm trying to add a new Graph Template Item to existing Graph Template.

After adding the new Graph Template Item (AREA, LINE1, GPRINT...), the graph stops running and there is an error:

`ERROR: is not a vname nor a number`

The strange thing is that while I create a Graph Template I can add as much as I want Graph Template Items, as long as they are added at once.

Here's the result after breaking the chart (missing **:e:** in `LINE1:#C04000FF:'FTP Users'`):

`RRDtool Command:
/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start='-86400' \
--end='-60' \
--pango-markup  \
--title='Rittal: RNAS - Users' \
--vertical-label='Users' \
--slope-mode \
--base=1000 \
--height=150 \
--width=480 \
--alt-autoscale-max \
--lower-limit='0' \
--color BACK#F3F3F3 \
--color CANVAS#FDFDFD \
--color SHADEA#CBCBCB \
--color SHADEB#999999 \
--color FONT#000000 \
--color AXIS#2C4D43 \
--color ARROW#2C4D43 \
--color FRAME#2C4D43 \
--border 1 --font TITLE:11:'Arial' \
--font AXIS:8:'Arial' \
--font LEGEND:8:'Courier' \
--font UNIT:8:'Arial' \
--font WATERMARK:6:'Arial' \
--slope-mode \
--watermark 'Monitoring' \
DEF:a='/var/www/html/rra/rittal_rnas_synology_nas_cifs_139.rrd':'synology_nas_cifs':AVERAGE \
DEF:b='/var/www/html/rra/rittal_rnas_synology_nas_nfs_141.rrd':'synology_nas_nfs':AVERAGE \
DEF:c='/var/www/html/rra/rittal_rnas_synology_nas_https_140.rrd':'synology_nas_https':AVERAGE \
DEF:d='/var/www/html/rra/rittal_rnas_synology_nas_ssh_142.rrd':'synology_nas_ssh':AVERAGE \
AREA:a#41A3177F:'CIFS     '  \
GPRINT:a:LAST:'Current\:%8.0lf'  \
GPRINT:a:AVERAGE:'Average\:%8.0lf'  \
GPRINT:a:MAX:'Max\:%8.0lf\n'  \
AREA:b#B041FF66:'NFS      ':STACK \
GPRINT:b:LAST:'Current\:%8.0lf'  \
GPRINT:b:AVERAGE:'Average\:%8.0lf'  \
GPRINT:b:MAX:'Max\:%8.0lf\n'  \
AREA:c#0020C266:'HTTPS    ':STACK \
GPRINT:c:LAST:'Current\:%8.0lf'  \
GPRINT:c:AVERAGE:'Average\:%8.0lf'  \
GPRINT:c:MAX:'Max\:%8.0lf\n'  \
AREA:d#F880177F:'SSH      ':STACK \
GPRINT:d:LAST:'Current\:%8.0lf'  \
GPRINT:d:AVERAGE:'Average\:%8.0lf'  \
GPRINT:d:MAX:'Max\:%8.0lf\n'  \
LINE1:#C04000FF:'FTP Users' 
RRDtool Says:
ERROR:  is not a vname nor a number`

**Comment by cigamit** [comment] 2018-08-15 23:38
Delete the existing graph, and re-create it.  Looks like you added something to a graph template, which will invalidate the existing graph.

**Comment by unguzov** [comment] 2018-08-16 19:49
If I delete and re-create graph with exact same data it works just fine. I test this with 3 graphs - create graph, add items - it works fine, then add more data on the next day and broke it, then delete and recreate again - works perfect.

**Comment by cigamit** [comment] 2018-08-18 02:16
Right, once you have created a graph, certain edit's to the Graph Template (like adding new data sources) will not cascade to the existing graphs.  The moral of the story is don't add new Data Sources to Graph Templates once graphs have been created.  Does that make sense in your specific case?

**Comment by unguzov** [comment] 2018-08-18 16:01
Yes, now it is clear whats happend when I added a new data sources to existing Graph Template. Maybe this will be a nice feature. Thank you @cigamit!

**Comment by cigamit** [comment] 2018-08-18 17:11
Yea, I've thought about that.  We should then add it to the list.  It's not overly long, but it is long.  So, no promises on timing.

**Comment by cigamit** [comment] 2018-08-19 23:56
Duplicate of https://github.com/Cacti/cacti/issues/1364

**Closed by cigamit** 2018-08-19 23:56 UTC
Labels: enhancement, templates
