### ISSUE TITLE
Cacti Not graphing appropraitely (NAN/Breaking/Empty)

### ISSUE THREAD

**Issue by Babat28119** [Cacti/cacti#3946] opened 2020-11-24 13:09 UTC
Dear Community,

We experience some performance issue on our cacti platform and we went ahead to upgrade to  latest cacti 1.2.14 but below are still our observations:
a. Most graph are empty
b. Some graphs are showing NAN
c. Some graphs are breaking 

See attached the cacti health status.

Await your swift response on what i can check further to fully optimize the performance.

Regards.

![sample graph](https://user-images.githubusercontent.com/69158129/100098213-045ded00-2e5e-11eb-805b-9d0be7377b95.JPG)
![sample graph1](https://user-images.githubusercontent.com/69158129/100098469-60c10c80-2e5e-11eb-8b91-c683376d6a00.JPG)

![poller](https://user-images.githubusercontent.com/69158129/100098005-ad581800-2e5d-11eb-98e3-38fb17fcc42a.JPG)

![cacti health](https://user-images.githubusercontent.com/69158129/100097998-aa5d2780-2e5d-11eb-9bb2-61ac124a0bb5.JPG)

**Comment by xmacan** [comment] 2020-11-24 13:14
Check this
https://forums.cacti.net/viewtopic.php?f=2&t=61380&p=284562&hilit=intropage#p284562

**Comment by Babat28119** [comment] 2020-11-24 14:15
We currently don't run on Spine poller as in the thread you shared.

**Comment by cigamit** [comment] 2020-11-24 16:07
This is not a bug.  You are overrunning your poller cycle, so it doesn't have time to process everything.  Increase the number of cmd.php processes.  You can do 1-2 per CPU core your system has.
Closing this, as it should have been posted in the forums instead.

**Closed by cigamit** 2020-11-24 16:07 UTC
