### ISSUE TITLE
Nav Menu missing when selecting device on Chrome

### ISSUE THREAD

**Issue by ahouston** [Cacti/cacti#543] opened 2017-04-09 08:47 UTC
The nav menu disappears when you click into a device of the Devices menu.

It looks like the  `overflow-y: auto !important;` and `overflow-x: auto` CSS on the `.cactiConsoleNavigationArea` class are the problem, if I untick them in the chrome dev console the menu reappears.

It works fine in Firefox, affecting Chrome Version 57.0.2987.133 (64-bit).

![image](https://cloud.githubusercontent.com/assets/1083694/24836035/cdcf47ea-1d11-11e7-89fd-ef5ea1fe506b.png)

![image](https://cloud.githubusercontent.com/assets/1083694/24836047/f35cb4d4-1d11-11e7-94dc-bc1fe2962af1.png)

**Comment by cigamit** [comment] 2017-04-09 12:43
This issue has been resolved in the development branch.  If you grab the latest <path_cacti>/include/themes/classic/main.js and clear your browser cache, this issue will be resolved.  The reason for the issue is that it appears that the latest Chrome does not publish the document.body.scrollHeight variable which has broken rendering in Chrome.

**Closed by cigamit** 2017-04-09 12:43 UTC
