### ISSUE TITLE
develop branch: search page issue

### ISSUE THREAD

**Issue by vinnyg16** [Cacti/cacti#1524] opened 2018-04-06 15:46 UTC
I just upgraded to Cacti 1.1.37.  After I do a search in graphs or data source.  When I click page 2 
it puts this "z{*kMZ" in the search field.

**Comment by netniV** [comment] 2018-04-06 21:01
I presume you meant Console -> Management -> Graphs?

**Comment by netniV** [comment] 2018-04-06 21:04
I've just tested this myself and can't get it to reproduce.  How did you upgrade to 1.1.37? There had previously been an issue a version or two ago with the search filters especially those that used regular expressions but these have since been fixed (certainly in 1.1.37).

**Comment by anarkia1976** [comment] 2018-04-09 06:29
If you change graphs per page here:
![image](https://user-images.githubusercontent.com/1744639/38482543-135da2e2-3bd0-11e8-88ec-4d39dda4a785.png)
we can't revert to stock configuration and we have these errors into log file:

2018/04/09  08:28:26 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 320  grow_right_pane_tree)(/lib/html_tree.php: 1158  html_nav_bar)(/lib/html.php: 412 get_page_list)(/lib/html_utility.php:  917 CactiErrorHandler)(/lib/functions.php: 4594 cacti_debug_backtrace)
2018/04/09 08:28:26 - ERROR PHP WARNING: Division by zero in file: /usr/share/cacti/lib/html_utility.php  on line: 917

thanks a lot.

**Comment by cigamit** [comment] 2018-04-09 12:09
Open your browsers debug window, and then goto the Param's page, and post what you see when you are able to re-produce this.  Also, what browser are you using?

**Comment by anarkia1976** [comment] 2018-04-09 13:00
I'm using mozilla firefox Quantum 59.0.2 (64-bit).
I have attached graph_view from debugger console.
thanks.
[graph_view.txt](https://github.com/Cacti/cacti/files/1889973/graph_view.txt)

**Comment by cigamit** [comment] 2018-04-11 02:00
Please accept my apologies, but I was not clear enough.  You need to do the following:
1) Open the Debug Panel
2) Goto the Network tab
3) Make the page generate the error
4) Look for a 'graph_view.php' call in the mix with all the graph_json.php.  Select the 'graph_view.php' call
5) Goto the parameters page and make a screen shot.

Firefox is great.  The image will look like the one below.

![debugwindow](https://user-images.githubusercontent.com/957322/38592518-240f9716-3d02-11e8-9869-9f3c11815946.PNG)

**Comment by anarkia1976** [comment] 2018-04-11 07:01
Thanks for the guide:
![image](https://user-images.githubusercontent.com/1744639/38601181-f5bd8052-3d66-11e8-9038-7022aded61b8.png)

**Comment by pautiina** [comment] 2018-04-11 14:49
Hello. I have the latest develop branch and also have this error on cacti.log:

```
2018/04/11 17:45:14 - CMDPHP PHP ERROR WARNING Backtrace: (/graph_view.php: 320 grow_right_pane_tree)(/lib/html_tree.php: 1158 html_nav_bar)(/lib/html.php: 412 get_page_list)(/lib/html_utility.php: 917 CactiErrorHandler)(/lib/functions.php: 4594 cacti_debug_backtrace)
--
2018/04/11 17:45:14 - ERROR PHP WARNING: Division by zero in file: /var/www/cacti/lib/html_utility.php on line: 917
```
This happens when I enter some kind of filter to search for graphics, or choose the type of graph.

![image](https://user-images.githubusercontent.com/11805503/38624429-b6a6e2c4-3db0-11e8-9955-d4a59a926c21.png)

**Comment by cigamit** [comment] 2018-04-12 01:13
Very odd.  Please do me a favor:

1) Goto the graph page and pick a default graphs per page and save that.  Then test some more.
2) Let me know of any plugins that you have installed that provide links to the graphs page.

Lastly, post the output of the following SQL command:

`select  * from settings_user where user_id = ?;`

Replace the question mark with your user account.

**Comment by cigamit** [comment] 2018-04-12 01:15
Note that 1.2 is tree broken as stated.  Sorry about that.

**Comment by anarkia1976** [comment] 2018-04-12 05:37
My user is "admin".
MariaDB [cacti]> select * from settings_user where user_id = 1;
+---------+-----------------------------------+--------+
| user_id | name                              | value  |
+---------+-----------------------------------+--------+
|       1 | allow_graph_dates_in_future       | on     |
|       1 | axis_font                         |        |
|       1 | axis_size                         | 8      |
|       1 | custom_fonts                      |        |
|       1 | day_shift_end                     | 18:00  |
|       1 | day_shift_start                   | 07:00  |
|       1 | default_datechar                  | 1      |
|       1 | default_date_format               | 4      |
|       1 | default_height                    | 100    |
|       1 | default_rra_id                    | 1      |
|       1 | default_timeshift                 | 7      |
|       1 | default_timespan                  | 7      |
|       1 | default_tree_id                   | 1      |
|       1 | default_view_mode                 | 1      |
|       1 | default_width                     | 300    |
|       1 | expand_hosts                      | on     |
|       1 | first_weekdayid                   | 1      |
|       1 | hide_disabled                     | on     |
|       1 | intropage_autorefresh             | 0      |
|       1 | intropage_display_important_first |        |
|       1 | intropage_display_level           | 2      |
|       1 | intropage_favouritegraph_1        | 336    |
|       1 | intropage_favouritegraph_2        | 81     |
|       1 | legend_font                       |        |
|       1 | legend_size                       | 10     |
|       1 | monitor_legend                    |        |
|       1 | monitor_mute                      | false  |
|       1 | monitor_sound                     | 0      |
|       1 | num_columns                       | 2      |
|       1 | num_columns_tree                  | 2      |
|       1 | page_refresh                      | 300    |
|       1 | preview_graphs_per_page           | 10     |
|       1 | realtime_mode                     | 1      |
|       1 | selected_theme                    | modern |
|       1 | show_graph_title                  |        |
|       1 | thumbnail_section_preview         | on     |
|       1 | thumbnail_section_tree_2          |        |
|       1 | title_font                        |        |
|       1 | title_size                        | 12     |
|       1 | treeview_graphs_per_page          |        |
|       1 | unit_font                         |        |
|       1 | unit_size                         | 8      |
|       1 | user_language                     | en-US  |
+---------+-----------------------------------+--------+
I have these plugins installed:
![image](https://user-images.githubusercontent.com/1744639/38658191-5d7b2a9c-3e24-11e8-8769-f0fc808873eb.png)
thanks

**Comment by netniV** [comment] 2018-04-12 08:06
If a setting is read as zero (blank) then the default should be used which is 10.  However, because this is a user setting, then the default is not used if the entry is found in the database.  This is because things like the on/off commands used blank as off and 'on' as on.  

A simple fix for this would be to add a setting that requires an entry to have a value, not be null.  For now, I would either remove that row or set a value against it (the default is 10).

**Comment by netniV** [comment] 2018-04-12 08:10
This affects [user_setting_exists()](https://github.com/Cacti/cacti/blob/develop/lib/functions.php#L123), [read_default_user_setting()](https://github.com/Cacti/cacti/blob/develop/lib/functions.php#L143) and [read_user_setting](https://github.com/Cacti/cacti/blob/develop/lib/functions.php#L166)

**Comment by cigamit** [comment] 2018-04-13 02:28
Should be resolved now.

**Comment by anarkia1976** [comment] 2018-04-13 05:37
Good, very good. Resolved we can close this issue. thanks a lot.

**Closed** 2018-04-20 03:05 UTC
Labels: unverified
