### ISSUE TITLE
[Cacti-1.1.25] Graph tree with 300 headers not showing elements after upgrade from 0.8.8c 

### ISSUE THREAD

**Issue by kaf3773** [Cacti/cacti#1012] opened 2017-10-04 22:50 UTC
I have one graph tree that has about 300 headers and each one of these headers has subsequent headers and graphs like below.

So graph tree AWIP_GMS has a subheader Customer(SL__) and this subheader has header ALB__.
There are about 300 headers like ALB__ with each one breaking out similar to what is under ALB__.

After upgrading from 0.8.8c to 1.1.25 all graph trees show up with their various elements with the exception of Customer(SL__). 

Customer(SL__) branch is the only one with about 300 headers. This is also happening with earlier versions of Cacti-1.1.*

**Before**

![image](https://user-images.githubusercontent.com/16928454/31202815-2f222376-a932-11e7-995f-c5f55e9cf1b4.png)

**After**

![image](https://user-images.githubusercontent.com/16928454/31203139-c1860c18-a933-11e7-8619-e1ff83bbb1bb.png)

Secondly, new graph trees do not show up on graphs tab after upgrading even though it indicates successfully added. I tried both from the Console UI and Cacti CLI.

Help will be very much appreciated on the above two issues.

Thanks

**Comment by cigamit** [comment] 2017-10-12 00:30
To resolve this, you need to dump the two tables graph_tree and graph_tree_items from your last database backup prior to upgrading and post to this page.

Command to dump would be:

`mysqldump cacti graph_tree graph_tree_items > /tmp/tree_issue.sql`

Also, were there any errors in your cacti log at the time of upgrade?  If you can't disclose the contents of those two tables, simply close this ticket.

**Comment by kaf3773** [comment] 2017-10-16 19:30
Cigamit,

Closing the ticket without a solution is not an option for me at this point.

I can share a dump of those two tables with you via unicast email if you can give me an email address to send to.

**Comment by cigamit** [comment] 2017-10-17 02:50
jimmy at sqmail dot org

**Comment by kaf3773** [comment] 2017-10-19 20:05
I have sent the dumps to you via email address you provided.

**Comment by cigamit** [comment] 2017-10-27 01:35
The dumps were never received.

**Comment by kaf3773** [comment] 2017-10-27 19:11
I have resent it again.

It is surprising because I did not get any message that it bounced or it was not delivered. Below see details about when sent both for the first one and the recent one.

 
![image](https://user-images.githubusercontent.com/16928454/32121073-0a5147da-bb29-11e7-8a18-8270894e429d.png)

![image](https://user-images.githubusercontent.com/16928454/32121080-124f341a-bb29-11e7-815c-9c588d5bfd15.png)

**Comment by cigamit** [comment] 2017-10-28 20:02
Can you please send the entire dump.  I was unable to reproduce with just the two tables.  Please also note that if may be a permission issue.  We do not show tree branches that are:

1) Empty
2) You don't have permission to

Also, please note that permissions were horribly inconsistent in Cacti 0.8.x, and we've resolved that, though there is an outstanding bug around some group permissions.

This is very different than what we did in the past.  So, having the full dump will allow me to go deeper.

**Comment by kaf3773** [comment] 2017-10-30 15:09
I sent the entire dump to you. It is about 98MB so I believe it will be sent to you as a link to google drive.

![image](https://user-images.githubusercontent.com/16928454/32178269-b4da09fe-bd62-11e7-908f-4ec3967c38c9.png)

**Comment by cigamit** [comment] 2017-11-04 17:44
Okay, got the dump and though I did find a few bugs, the root cause of your issue is that your devices are disabled.  So, in that case, we hide the devices that are disabled.  I'll keep this open for the moment in that, when you are editing the tree, you should see all devices, even if they are disabled.

**Comment by cigamit** [comment] 2017-11-04 18:22
Marking this resolved.  If you wish to view the disabled devices from the tree, there is a user level settings called 'Hide Disabled'.  Uncheck it.

**Closed by cigamit** 2017-11-04 18:22 UTC
Labels: unverified
