### ISSUE TITLE
GPRINT Text - 2 %% markers showing on graphs - Bug?

### ISSUE THREAD

**Issue by kmcdan3944k** [Cacti/cacti#3194] opened 2020-01-16 08:24 UTC
Via GPRINT Presets [edit: Percentage as Decimal] - **%** marker is printed twice via default entry of %6.2lf%%. Graphs that have percentages such as Advanced ping all have their values with 2 trailing %% markers. I would assume this should be only one by default but could be mistaken.

**To Reproduce**
Generate any graph that works with Percentage numbers (Advanced Ping)
See visual obscurity.

**Expected behavior**
1 percentage symbol on graph

 - Seen in both Firefox/Chrome
 - Version 1.2.8

![DualPercent](https://user-images.githubusercontent.com/27192699/72506291-75705500-37f6-11ea-939d-4d835b5a72e3.JPG)

**Comment by netniV** [comment] 2020-01-16 20:13
No, this is not a bug but rather the result of a bug fix.  Simply use a single percentage sign now and all should be well I believe.

**Comment by cigamit** [comment] 2020-01-17 00:40
Ah, we should probably enhance the advanced ping template to remove the second percent sign.

**Comment by cigamit** [comment] 2020-01-17 00:41
I don't think that Advanced Ping is a part of our standard packages.  So, I'm thinking we either incorporate it somehow, or close this.

**Closed** 2020-02-22 01:51 UTC
Labels: bug, templates
