### ISSUE TITLE
Improve PHP 8.1 support when adding devices

### ISSUE THREAD

**Issue by asd0109** [Cacti/cacti#5483] opened 2023-09-08 01:10 UTC
![2023-09-08 09 02 53](https://github.com/Cacti/cacti/assets/37428027/e923dfd7-ca01-469c-bf13-4639f1d80f30)

add new device very very slow

![2023-09-08 09 00 35](https://github.com/Cacti/cacti/assets/37428027/01d35b66-d2d2-4062-9cc1-93c880ecb544)

After adding, it was found  device status is unknown.

![2023-09-08 09 01 17](https://github.com/Cacti/cacti/assets/37428027/79484375-787f-442e-8c36-3abf1a647aa4)

logpage show error message.

i test cacti in ubuntu 20.04.6  php7.4 is ok no this error .

**Comment by TheWitness** [comment] 2023-09-08 02:14
Good catch.  What happens if you edit `lib/snmp.php` and add the following after `global $banned_snmp_strings;`?

```php
    global $banned_snmp_strings;

    if ($string === null) {
        return '';
    }
```

**Comment by TheWitness** [comment] 2023-09-08 02:15
PHP8 deprecations drive me nuts.

**Comment by asd0109** [comment] 2023-09-08 05:18
![2023-09-08 13 15 56](https://github.com/Cacti/cacti/assets/37428027/a7c35a0a-5a0b-4577-87af-334c1ed64d68)

![2023-09-08 13 16 31](https://github.com/Cacti/cacti/assets/37428027/967de77b-f14d-4ced-a65e-9402305c8f23)


i try , but fail :(

> Good catch. What happens if you edit `lib/snmp.php` and add the following after `global $banned_snmp_strings;`?
> 
> ```
>     global $banned_snmp_strings;
> 
>     if ($string === null) {
>         return '';
>     }
> ```

i try it ,but failed .

**Comment by asd0109** [comment] 2023-09-08 05:20
<html><body>


2023-09-08 13:13:43 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
--
2023-09-08 13:13:43 - ERROR PHP ERROR: Uncaught TypeError: dechex():  Argument #1 ($num) must be of type int, string given in  /var/www/html/cacti/lib/data_query.php:1378 Stack trace: #0  /var/www/html/cacti/lib/data_query.php(1378): dechex() #1  /var/www/html/cacti/lib/data_query.php(106): query_snmp_host() #2  /var/www/html/cacti/lib/api_device.php(1289): run_data_query() #3  /var/www/html/cacti/lib/api_device.php(1131):  api_device_update_host_template() #4 /var/www/html/cacti/host.php(286):  api_device_save() #5 /var/www/html/cacti/host.php(62): form_save() #6  {main} thrown in file: /var/www/html/cacti/lib/data_query.php on line:  1378
2023-09-08 13:13:43 - CMDPHP PHP ERROR Backtrace:   (/host.php[62]:form_save(), /host.php[286]:api_device_save(),  /lib/api_device.php[1131]:api_device_update_host_template(),  /lib/api_device.php[1289]:run_data_query(),  /lib/data_query.php[106]:query_snmp_host(),  /lib/data_query.php[1231]:cacti_snmp_session_walk(),  /lib/snmp.php[499]:format_snmp_string(), /lib/snmp.php[745]:trim(),  CactiErrorHandler())
2023-09-08 13:13:43 - ERROR PHP DEPRECATED: trim(): Passing null to  parameter #1 ($string) of type string is deprecated in file:  /var/www/html/cacti/lib/snmp.php  on line: 745


</body>
</html>

**Comment by TheWitness** [comment] 2023-09-08 10:13
I forgot to tell you what line to put that code block on.  That's why is didn't work.

**Comment by TheWitness** [comment] 2023-09-08 10:15
Go to line 745, go up till you find the global again and paste there instead.  You need to remove the first one you did too.

**Comment by asd0109** [comment] 2023-09-08 11:40
> Go to line 745, go up till you find the global again and paste there instead. You need to remove the first one you did too.

thank you ! i will feedback after i test it .

**Comment by TheWitness** [comment] 2023-09-09 00:01
Download the lib/snmp.php from the 1.2.x branch.  Should be fixed.

**Comment by asd0109** [comment] 2023-09-11 00:11
![2023-09-11 08 06 24](https://github.com/Cacti/cacti/assets/37428027/32dbff20-704b-4dbc-90dc-de35980bb914)

![2023-09-11 08 08 13](https://github.com/Cacti/cacti/assets/37428027/e8abb618-6edd-4ad0-a5f1-32451949fe8a)


<html><body>


2023-09-11 08:05:51 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
--
2023-09-11 08:05:51 - ERROR PHP ERROR: Uncaught TypeError: dechex():  Argument #1 ($num) must be of type int, string given in  /var/www/html/cacti/lib/data_query.php:1378 Stack trace: #0  /var/www/html/cacti/lib/data_query.php(1378): dechex() #1  /var/www/html/cacti/lib/data_query.php(106): query_snmp_host() #2  /var/www/html/cacti/lib/api_device.php(1289): run_data_query() #3  /var/www/html/cacti/lib/api_device.php(1131):  api_device_update_host_template() #4 /var/www/html/cacti/host.php(286):  api_device_save() #5 /var/www/html/cacti/host.php(62): form_save() #6  {main} thrown in file: /var/www/html/cacti/lib/data_query.php on line:  1378


</body>
</html>


I have tested it and cannot solve the problem.

add device page very very slow .

**Comment by TheWitness** [comment] 2023-09-22 15:34
Okay, I've made another change.  The reason it's slow is that your re-index is failing on one of the Data Queries as Cacti is attempting to re-index them and they are failing.  Remove the broken Data Query from the Device Template until the issue is resolved.  What is the Data Query?  If you enable Data Source Trace, you will get some more metrics.  Under `Console > Configuration > Settings > General > Logging`.

**Comment by asd0109** [comment] 2023-09-23 01:10
> Okay, I've made another change. The reason it's slow is that your re-index is failing on one of the Data Queries as Cacti is attempting to re-index them and they are failing. Remove the broken Data Query from the Device Template until the issue is resolved. What is the Data Query? If you enable Data Source Trace, you will get some more metrics. Under `Console > Configuration > Settings > General > Logging`.

the same code , same device , why in php 7.4 no problem ?

**Closed** 2023-09-23 15:42 UTC
Labels: bug, resolved, type:bug

**Comment by TheWitness** [comment] 2023-09-24 20:38
It's more about PHP 8 I think.  But I can not be certain as there are too many degree's of freedom.  You you do stand alone and separate installs, and can show a distinct difference using the SNMP trace, the would be help.  If you get the snmp community string wrong, or any of the Data Queries for the Device Template are invalid, the timeouts could be excessive and adding devices can be slowed too.

**Comment by asd0109** [comment] 2023-09-25 02:02
![2023-09-25 10 01 11](https://github.com/Cacti/cacti/assets/37428027/5831f64f-0fb0-46bd-96ba-abcba79c25fa)

i test it today , all fixed !  nice job !

add device fast and device status online .
