### ISSUE TITLE
Upgrade to 1.2.0 Failing - ALTER IGNORE TABLE version DROP PRIMARY KEY

### ISSUE THREAD

**Issue by chrisc980** [Cacti/cacti#2561] opened 2019-03-22 16:24 UTC
When attempting to upgrade to 1.2.2, I get stopped at 1.1.34 with an error:

ALTER IGNORE TABLE version DROP PRIMARY KEY  [Fail]

If I manually update the version information in the database to 1.2.2, Cacti loads in the browser, but it appears there is an issue with several tables; devices list is blank, and no charts.

Process log is as follows:

2019/03/22 15:15:38 - INSTALL: always: Installation was started at 2019-03-22 15:15:11, completed at 2019-03-22 15:15:38 
2019/03/22 15:15:38 - INSTALL: always: WARNING: One or more upgrades failed to install correctly 
2019/03/22 15:15:38 - INSTALL: always: Finished UPGRADE Process for v1.2.2 
2019/03/22 15:15:37 - INSTALL: always: Upgrading from v1.1.31 (DB 1.1.31) to v1.1.34 
2019/03/22 15:15:36 - INSTALL: always: Upgrading from v1.1.28 (DB 1.1.28) to v1.1.31 
2019/03/22 15:15:36 - INSTALL: always: Upgrading from v1.1.27 (DB 1.2.2 (DB: 1.1.27)) to v1.1.28 
2019/03/22 15:15:36 - INSTALL: always: NOTE: Using temporary file for db cache: /tmp/cdu9QFmMG 
2019/03/22 15:15:36 - INSTALL: always: Switched from to /tmp/cdu9QFmMG 
2019/03/22 15:15:36 - INSTALL: always: Converting Table #114 'version' 
2019/03/22 15:15:35 - INSTALL: always: Converting Table #113 'vdef_items' 
2019/03/22 15:15:35 - INSTALL: always: Converting Table #112 'vdef' 
2019/03/22 15:15:35 - INSTALL: always: Converting Table #111 'user_log' 
2019/03/22 15:15:35 - INSTALL: always: Converting Table #110 'user_domains_ldap' 
2019/03/22 15:15:35 - INSTALL: always: Converting Table #109 'user_domains' 
2019/03/22 15:15:35 - INSTALL: always: Converting Table #108 'user_auth_realm' 
2019/03/22 15:15:34 - INSTALL: always: Converting Table #107 'user_auth_perms' 
2019/03/22 15:15:34 - INSTALL: always: Converting Table #106 'user_auth_group_realm' 
2019/03/22 15:15:34 - INSTALL: always: Converting Table #105 'user_auth_group_perms' 
2019/03/22 15:15:34 - INSTALL: always: Converting Table #104 'user_auth_group_members' 
2019/03/22 15:15:34 - INSTALL: always: Converting Table #103 'user_auth_group' 
2019/03/22 15:15:33 - INSTALL: always: Converting Table #102 'user_auth_cache' 
2019/03/22 15:15:33 - INSTALL: always: Converting Table #101 'user_auth' 
2019/03/22 15:15:33 - INSTALL: always: Converting Table #100 'snmpagent_notifications_log' 
2019/03/22 15:15:33 - INSTALL: always: Converting Table #99 'snmpagent_mibs' 
2019/03/22 15:15:33 - INSTALL: always: Converting Table #98 'snmpagent_managers_notifications' 
2019/03/22 15:15:33 - INSTALL: always: Converting Table #97 'snmpagent_managers' 
2019/03/22 15:15:33 - INSTALL: always: Converting Table #96 'snmpagent_cache_textual_conventions' 
2019/03/22 15:15:32 - INSTALL: always: Converting Table #95 'snmpagent_cache_notifications' 
2019/03/22 15:15:32 - INSTALL: always: Converting Table #94 'snmpagent_cache' 
2019/03/22 15:15:32 - INSTALL: always: Converting Table #93 'snmp_query_graph_sv' 
2019/03/22 15:15:31 - INSTALL: always: Converting Table #92 'snmp_query_graph_rrd_sv' 
2019/03/22 15:15:31 - INSTALL: always: Converting Table #91 'snmp_query_graph_rrd' 
2019/03/22 15:15:31 - INSTALL: always: Converting Table #90 'snmp_query_graph' 
2019/03/22 15:15:31 - INSTALL: always: Converting Table #89 'snmp_query' 
2019/03/22 15:15:31 - INSTALL: always: Converting Table #88 'sites' 
2019/03/22 15:15:31 - INSTALL: always: Converting Table #87 'settings_user_group' 
2019/03/22 15:15:31 - INSTALL: always: Converting Table #86 'settings_user' 
2019/03/22 15:15:30 - INSTALL: always: Converting Table #85 'settings_tree' 
2019/03/22 15:15:30 - INSTALL: always: Converting Table #84 'settings_graphs' 
2019/03/22 15:15:30 - INSTALL: always: Converting Table #83 'settings' 
2019/03/22 15:15:30 - INSTALL: always: Converting Table #82 'sessions' 
2019/03/22 15:15:30 - INSTALL: always: Converting Table #81 'reports_items' 
2019/03/22 15:15:30 - INSTALL: always: Converting Table #80 'reports' 
2019/03/22 15:15:29 - INSTALL: always: Converting Table #79 'poller_time' 
2019/03/22 15:15:29 - INSTALL: always: Converting Table #78 'poller_resource_cache' 
2019/03/22 15:15:29 - INSTALL: always: Converting Table #77 'poller_reindex' 
2019/03/22 15:15:29 - INSTALL: always: Converting Table #76 'poller_output_realtime' 
2019/03/22 15:15:29 - INSTALL: always: Converting Table #75 'poller_output_boost_processes' 
2019/03/22 15:15:29 - INSTALL: always: Converting Table #74 'poller_output_boost' 
2019/03/22 15:15:29 - INSTALL: always: Converting Table #73 'poller_output' 
2019/03/22 15:15:28 - INSTALL: always: Converting Table #72 'poller_item' 
2019/03/22 15:15:28 - INSTALL: always: Converting Table #71 'poller_data_template_field_mappings' 
2019/03/22 15:15:28 - INSTALL: always: Converting Table #70 'poller_command' 
2019/03/22 15:15:28 - INSTALL: always: Converting Table #69 'poller' 
2019/03/22 15:15:27 - INSTALL: always: Converting Table #68 'plugin_realms' 
2019/03/22 15:15:27 - INSTALL: always: Converting Table #67 'plugin_hooks' 
2019/03/22 15:15:27 - INSTALL: always: Converting Table #66 'plugin_db_changes' 
2019/03/22 15:15:27 - INSTALL: always: Converting Table #65 'plugin_config' 
2019/03/22 15:15:27 - INSTALL: always: Converting Table #64 'plugin_autom8_tree_rules' 
2019/03/22 15:15:27 - INSTALL: always: Converting Table #63 'plugin_autom8_tree_rule_items' 
2019/03/22 15:15:27 - INSTALL: always: Converting Table #62 'plugin_autom8_match_rule_items' 
2019/03/22 15:15:26 - INSTALL: always: Converting Table #61 'plugin_autom8_graph_rules' 
2019/03/22 15:15:26 - INSTALL: always: Converting Table #60 'plugin_autom8_graph_rule_items' 
2019/03/22 15:15:26 - INSTALL: always: Converting Table #59 'host_template_snmp_query' 
2019/03/22 15:15:26 - INSTALL: always: Converting Table #58 'host_template_graph' 
2019/03/22 15:15:26 - INSTALL: always: Converting Table #57 'host_template' 
2019/03/22 15:15:25 - INSTALL: always: Converting Table #56 'host_snmp_query' 
2019/03/22 15:15:22 - INSTALL: always: Converting Table #55 'host_snmp_cache' 
2019/03/22 15:15:22 - INSTALL: always: Converting Table #54 'host_graph' 
2019/03/22 15:15:22 - INSTALL: always: Converting Table #53 'host' 
2019/03/22 15:15:22 - INSTALL: always: Converting Table #52 'graph_tree_items' 
2019/03/22 15:15:21 - INSTALL: always: Converting Table #51 'graph_tree' 
2019/03/22 15:15:20 - INSTALL: always: Converting Table #50 'graph_templates_item' 
2019/03/22 15:15:20 - INSTALL: always: Converting Table #49 'graph_templates_graph' 
2019/03/22 15:15:20 - INSTALL: always: Converting Table #48 'graph_templates_gprint' 
2019/03/22 15:15:20 - INSTALL: always: Converting Table #47 'graph_templates' 
2019/03/22 15:15:20 - INSTALL: always: Converting Table #46 'graph_template_input_defs' 
2019/03/22 15:15:19 - INSTALL: always: Converting Table #45 'graph_template_input' 
2019/03/22 15:15:19 - INSTALL: always: Converting Table #44 'graph_local' 
2019/03/22 15:15:19 - INSTALL: always: Converting Table #43 'external_links' 
2019/03/22 15:15:18 - INSTALL: always: Converting Table #42 'data_template_rrd' 
2019/03/22 15:15:18 - INSTALL: always: Converting Table #41 'data_template_data' 
2019/03/22 15:15:18 - INSTALL: always: Converting Table #40 'data_template' 
2019/03/22 15:15:17 - INSTALL: always: Converting Table #39 'data_source_stats_yearly' 
2019/03/22 15:15:17 - INSTALL: always: Converting Table #38 'data_source_stats_weekly' 
2019/03/22 15:15:17 - INSTALL: always: Converting Table #37 'data_source_stats_monthly' 
2019/03/22 15:15:17 - INSTALL: always: Converting Table #36 'data_source_stats_hourly_last' 
2019/03/22 15:15:17 - INSTALL: always: Converting Table #35 'data_source_stats_hourly_cache' 
2019/03/22 15:15:17 - INSTALL: always: Converting Table #34 'data_source_stats_hourly' 
2019/03/22 15:15:17 - INSTALL: always: Converting Table #33 'data_source_stats_daily' 
2019/03/22 15:15:16 - INSTALL: always: Converting Table #32 'data_source_purge_temp' 
2019/03/22 15:15:16 - INSTALL: always: Converting Table #31 'data_source_purge_action' 
2019/03/22 15:15:16 - INSTALL: always: Converting Table #30 'data_source_profiles_rra' 
2019/03/22 15:15:16 - INSTALL: always: Converting Table #29 'data_source_profiles_cf' 
2019/03/22 15:15:16 - INSTALL: always: Converting Table #28 'data_source_profiles' 
2019/03/22 15:15:16 - INSTALL: always: Converting Table #27 'data_local' 
2019/03/22 15:15:15 - INSTALL: always: Converting Table #26 'data_input_fields' 
2019/03/22 15:15:15 - INSTALL: always: Converting Table #25 'data_input_data' 
2019/03/22 15:15:15 - INSTALL: always: Converting Table #24 'data_input' 
2019/03/22 15:15:15 - INSTALL: always: Converting Table #23 'colors'

**Comment by netniV** [comment] 2019-03-22 16:33
No, you should not alter the version yourself.  If you are upgrading, I would recommend the 1.2.2 rather than 1.2.0:
[code]   1.2.3 - Features:   3, Bugs:  46
   1.2.2 - Features:   4, Bugs:  30
   1.2.1 - Features:   0, Bugs:  24
   1.2.0 - Features:  78, Bugs: 117[/code]

We have actually fixed this issue already as it's a duplicate of #2482 which corrected the issue introduced in #2358

**Comment by netniV** [comment] 2019-03-22 16:34
Duplicate of #2482

**Closed** 2019-03-22 16:35 UTC
Labels: duplicate

**Comment by chrisc980** [comment] 2019-03-22 16:57
To be clear, I did revert the version information to 1.1.31 after the brief experiment.

**Comment by netniV** [comment] 2019-03-22 16:59
That's OK, I just like to make sure people don't forget things like that as there are other changes that would be missed leading to other problems.

**Comment by chrisc980** [comment] 2019-03-22 17:15
Thanks for the link to the duplicate - I did try searching first before opening a new issue.   I made the change to the 1_1_34.php file.   Please excuse my ignorance - I'm a network guy, not a database/web guy - how to I restart/unstick the upgrade process once I've done that?   Thanks! :)

**Comment by netniV** [comment] 2019-03-22 18:09
It should just try and pick up where it left off.  Is it still having an issue?

**Comment by chrisc980** [comment] 2019-03-22 18:16
Yes, unfortunately.   Screenshot attached - now it doesn't tell me what the error is, but says there is one.
![cacti](https://user-images.githubusercontent.com/48836357/54844287-e44f5100-4cac-11e9-83ce-9e7e5712d053.PNG)

Here's the latest from the log file:

2019/03/22 18:15:01 - ERROR PHP NOTICE: Undefined index: processes in file: /usr/share/cacti/poller.php  on line: 218
2019/03/22 18:15:01 - CMDPHP PHP ERROR NOTICE Backtrace:  (/poller.php[218]:CactiErrorHandler())
2019/03/22 18:15:01 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'deleted' in 'where clause'
2019/03/22 18:15:01 - CMDPHP SQL Backtrace:  (/poller.php[370]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())
2019/03/22 18:15:01 - ERROR PHP WARNING: array_merge(): Argument #2 is not an array in file: /usr/share/cacti/poller.php  on line: 370
2019/03/22 18:15:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[370]:array_merge(), CactiErrorHandler())
2019/03/22 18:15:01 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/poller.php  on line: 582
2019/03/22 18:15:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[582]:CactiErrorHandler())
2019/03/22 18:15:01 - SYSTEM STATS: Time:0.0221 Method:spine Processes:1 Threads:15 Hosts:-1 HostsPerProcess:-1 DataSources:8014 RRDsProcessed:0
2019/03/22 18:15:01 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'last_sync' in 'where clause'
2019/03/22 18:15:01 - CMDPHP SQL Backtrace:  (/poller.php[787]:poller_replicate_check(), /poller.php[847]:db_fetch_assoc(), /lib/database.php[450]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())
2019/03/22 18:15:01 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/poller.php  on line: 849
2019/03/22 18:15:01 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[787]:poller_replicate_check(), /poller.php[849]:CactiErrorHandler())
2019/03/22 18:15:02 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.data_debug' doesn't exist
2019/03/22 18:15:02 - CMDPHP SQL Backtrace:  (/poller.php[791]:dsdebug_poller_bottom(), /lib/dsdebug.php[148]:db_fetch_assoc(), /lib/database.php[450]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())
2019/03/22 18:15:02 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'deleted' in 'where clause'
2019/03/22 18:15:02 - CMDPHP SQL Backtrace:  (/poller_maintenance.php[146]:api_device_purge_deleted_devices(), /lib/api_device.php[113]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())

**Comment by netniV** [comment] 2019-03-22 18:30
Most of that is the rest of the system running, nothing to do with the installer.  So, lets try this... 
```sql
delete from settings where name like 'install_%';
```
Then attempt the upgrade again, this should continue from 1.1.31 to 1.2.2

**Comment by chrisc980** [comment] 2019-03-22 18:56
That did the trick.   I'm up and running on 1.2.2.   Thanks for all your help!

**Comment by carboxste** [comment] 2019-03-28 16:27
I had the same problem attempting the upgrade from 0.8.8g to 1.2.2.
Giving the delete string it seems work fine now. Hope.

Thanks a lot!

**Comment by netniV** [comment] 2019-03-28 17:19
Hmm, I am going to have to do a full upgrade test again.  I don't suppose either @chrisc980 or @carboxste has a backup dump of the database that you would be willing to share so I can see why it went wrong?  We may have already fixed the issue.
