### ISSUE TITLE
Boost Status - Running 1x per only

### ISSUE THREAD

**Issue by zuka1337** [Cacti/cacti#3867] opened 2020-10-16 10:56 UTC
# Describe the bug

Poller boost ignore process setthings.
Polling 5 minutes

**Settings:**

![image](https://user-images.githubusercontent.com/57998098/96249556-44030080-0fa5-11eb-9bc1-2ac898d1d711.png)

**Boost stats:**
```
2020-10-16 11:18:04 - SYSTEM BOOST STATS: Time:1.5000 RRDUpdates:4568
2020-10-16 10:18:04 - SYSTEM BOOST STATS: Time:0.3400 RRDUpdates:576
2020-10-16 09:13:04 - SYSTEM BOOST STATS: Time:0.0500 RRDUpdates:384
2020-10-16 08:13:03 - SYSTEM BOOST STATS: Time:0.0600 RRDUpdates:384
2020-10-16 07:13:03 - SYSTEM BOOST STATS: Time:0.0600 RRDUpdates:384
2020-10-16 06:13:03 - SYSTEM BOOST STATS: Time:0.0600 RRDUpdates:384
2020-10-16 05:13:03 - SYSTEM BOOST STATS: Time:0.0600 RRDUpdates:384
2020-10-16 04:13:03 - SYSTEM BOOST STATS: Time:0.2700 RRDUpdates:416
2020-10-16 03:08:04 - SYSTEM BOOST STATS: Time:0.0600 RRDUpdates:384
2020-10-16 02:08:04 - SYSTEM BOOST STATS: Time:0.0700 RRDUpdates:384
2020-10-16 01:08:03 - SYSTEM BOOST STATS: Time:0.0500 RRDUpdates:416
2020-10-16 00:03:04 - SYSTEM BOOST STATS: Time:0.0600 RRDUpdates:384
```

**SYSTEM STATS**
```
2020-10-16 11:43:03 - SYSTEM STATS: Time:1.2482 Method:spine Processes:1 Threads:1 Hosts:13 HostsPerProcess:13 DataSources:502 RRDsProcessed:0
2020-10-16 11:38:03 - SYSTEM STATS: Time:1.2270 Method:spine Processes:1 Threads:1 Hosts:13 HostsPerProcess:13 DataSources:502 RRDsProcessed:0
2020-10-16 11:33:04 - SYSTEM STATS: Time:1.3977 Method:spine Processes:1 Threads:1 Hosts:13 HostsPerProcess:13 DataSources:502 RRDsProcessed:0
2020-10-16 11:28:03 - SYSTEM STATS: Time:1.2273 Method:spine Processes:1 Threads:1 Hosts:13 HostsPerProcess:13 DataSources:502 RRDsProcessed:0
2020-10-16 11:23:03 - SYSTEM STATS: Time:1.2271 Method:spine Processes:1 Threads:1 Hosts:13 HostsPerProcess:13 DataSources:502 RRDsProcessed:0
2020-10-16 11:18:03 - SYSTEM STATS: Time:1.2353 Method:spine Processes:1 Threads:1 Hosts:13 HostsPerProcess:13 DataSources:502 RRDsProcessed:0
2020-10-16 11:13:03 - SYSTEM STATS: Time:1.2280 Method:spine Processes:1 Threads:1 Hosts:13 HostsPerProcess:13 DataSources:502 RRDsProcessed:0
2020-10-16 11:08:03 - SYSTEM STATS: Time:1.2274 Method:spine Processes:1 Threads:1 Hosts:13 HostsPerProcess:13 DataSources:502 RRDsProcessed:0
```

**Question**:  What am I doing wrong?

- **Docker:** Centos 8
- **Cacti Version:** 1.2.14
 

__________________________________________________________________________________________________________________________________________________

```
2020/10/16 12:04:01 - SYSTEM BOOST STATS: Time:471.0200 RRDUpdates:906622
2020/10/16 11:53:46 - SYSTEM BOOST STATS: Time:456.1300 RRDUpdates:906604
2020/10/16 11:43:44 - SYSTEM BOOST STATS: Time:453.3600 RRDUpdates:906636
2020/10/16 11:33:40 - SYSTEM BOOST STATS: Time:449.5700 RRDUpdates:908013
2020/10/16 11:23:57 - SYSTEM BOOST STATS: Time:466.4600 RRDUpdates:905298
2020/10/16 11:13:38 - SYSTEM BOOST STATS: Time:444.2500 RRDUpdates:908258
2020/10/16 11:03:55 - SYSTEM BOOST STATS: Time:464.7300 RRDUpdates:908256
2020/10/16 10:53:59 - SYSTEM BOOST STATS: Time:469.5000 RRDUpdates:908259
```
> On the other hand Cacti 1.2.7 is ok:

**Comment by netniV** [comment] 2020-10-16 16:42
Sorry but i'm gonna need a bit more detail to understand what your issue is as a quick glance and I was confused 👍

**Comment by zuka1337** [comment] 2020-10-16 17:01
I just want to know why system boost only update the rrds once per hour if processes is set higher the 1..

**Comment by TheWitness** [comment] 2020-10-17 14:35
The concurrent processes setting is not implemented right now.  Was a small accident to release the setting prior to it being implemented.

**Comment by TheWitness** [comment] 2020-10-17 14:36
As long as you are running on InnoDB, and you have a well tuned database, you should not have problems.  With the latest version of Cacti, in your case 1.2.14, all the big performance problems bottlenecks have been eliminated as far as I'm concerned.

**Comment by TheWitness** [comment] 2020-10-17 14:36
Though, we will implement the parallel threads in the near future as some people have slower storage, that would benefit from multiple threads.

**Comment by zuka1337** [comment] 2020-10-19 12:37
Well That's explain the "issue", thought I was doing something wrong.
Thank you !!

**Comment by TheWitness** [comment] 2020-10-19 13:34
Not a problem.

**Comment by TheWitness** [comment] 2020-10-28 20:28
Marking this duplicate of #2200

**Closed** 2020-10-28 20:28 UTC
Labels: bug, duplicate
