### ISSUE TITLE
Cacti: 1.2.2 List of columns in Managemt -> Devices should be configurable

### ISSUE THREAD

**Issue by stefanbrudny** [Cacti/cacti#2558] opened 2019-03-22 00:13 UTC
**Describe the bug**
This is really a show stopper, again, for me. 

List should be configurable and include selection of fields as to user expectations. This is  important for business related new Cacti additions such as Location, poller association, site, external id (but all other fields should be considered)

This is very important at scale. When Cacti hosts 100k devices and I need to select only 300 with wrong snmp settings.  Search result schould be eligible for bulk action. Currently one have to use SQL for searching and introducing changes, as using Cacti bulk action requires execution on all devices, which is, btw, completely impossible at the volume.

In addition, this should include complete rewrite of bulk actions to not consume 32G of PHP when changing timeout on SNMP at volume....

**Expected behavior**
Configurable table instead of current inflexible approach
Reset to default list item should be implemented
Search by item in the column is expected (eg. All devices having wrong snmp community string).

**Comment by netniV** [comment] 2019-03-22 00:50
Duplicate of #1401

**Closed by netniV** 2019-03-22 00:50 UTC
