### ISSUE TITLE
Realtime graph in new window

### ISSUE THREAD

**Issue by stivnnik** [Cacti/cacti#429] opened 2017-03-15 08:51 UTC
Hello,

The new realtime view is really neat, but in some cases the old-school style is more convenient.
Could you please consider adding an option (button) to display realtime graphs in a separate window?
Now this button exists only from 'Time Graph View' pages. I would really appreciate something similar directly from tree view and preview view.

Kind regards,
Stefan Nikolov

**Comment by jhonnyx82** [comment] 2017-03-15 10:13
I agree on this request, pop up window for realtime graph are bery useful.

Actually the idea may be extended with a graph "basket" of realtime graphs

**Comment by cigamit** [comment] 2017-03-15 11:57
This is a duplicate of another ticket.  Agreed that the popup window can still be relevant.  The functionality is mostly still there.  It's on the list of things to do.

**Closed** 2017-03-15 11:57 UTC
Labels: duplicate, enhancement
