### ISSUE TITLE
Boost status is incorrect in log file 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#3777] opened 2020-08-31 02:53 UTC
# Describe the bug

Boost status in log incorrect 

## To Reproduce

Enable boost and check log file

## Screenshots
![boost](https://user-images.githubusercontent.com/47589910/91678426-1b02e980-eb78-11ea-8b41-2d93141157be.gif)

## Desktop (please complete the following information)

- OS: rhel7 x64 

- Browser  FF

- Version cacti 1.2.13

**Comment by TheWitness** [comment] 2020-08-31 12:12
@yingbaiibm, this is a duplicate of this https://github.com/Cacti/cacti/issues/3656 which was solved over the weekend.

**Closed** 2020-09-06 23:54 UTC
Labels: bug, duplicate, resolved
