### ISSUE TITLE
Can not add mutiple graphs in a new tree

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#2614] opened 2019-04-04 08:25 UTC
**Describe the bug**
Can not add mutiple graphs in a new tree.

**To Reproduce**
1. Go to 'Console -> trees'
2. Click on '+' to add a new tree. then input 'ttt' as name. click 'Create'
3. Click 'Edit tree'. Then drag a graph 'load average' into the tree item.
4. But can not drag another one 'Memory usage' into the tree item.
5, Cannot add a second graph even after save.

**Expected behavior**
Can add mutiple graphs in a new tree.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [RHEL7]
 - Browser [FF 60.5.1esr]
 - Version [cacti 1.2.3]

**Additional context**

**Comment by cigamit** [comment] 2019-06-22 15:21
Can you please upload a Screen2Gif animation of what you have found?

**Comment by cigamit** [comment] 2019-06-30 01:09
Duplicate of https://github.com/Cacti/cacti/issues/2524

**Closed by cigamit** 2019-06-30 01:09 UTC
Labels: bug, duplicate
