### ISSUE TITLE
Navigation array causing error when viewing log file

### ISSUE THREAD

**Issue by hxbzh021** [Cacti/cacti#2789] opened 2019-07-01 08:52 UTC
Cacti version 1.2.4
Mysql Server version: 8.0.15

2019/07/01 16:48:32 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php[40]:clog_view_logfile(), /lib/clog_webapi.php[207]:general_header(), /lib/functions.php[3236]:include_once(), /include/top_general_header.php[43]:draw_navigation_text(), /lib/functions.php[2587]:CactiErrorHandler())
--
2019/07/01 16:48:32 - ERROR PHP NOTICE: Array to string conversion in file: /usr/share/cacti/lib/functions.php on line: 2587
2019/07/01 16:48:32 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php[40]:clog_view_logfile(), /lib/clog_webapi.php[207]:general_header(), /lib/functions.php[3236]:include_once(), /include/top_general_header.php[27]:draw_navigation_text(), /lib/functions.php[2587]:CactiErrorHandler())
2019/07/01 16:48:32 - ERROR PHP NOTICE: Array to string conversion in file: /usr/share/cacti/lib/functions.php on line: 2587

**Comment by netniV** [comment] 2019-07-01 21:49
The normal reason for this error is due to a plugin.  What plugins do you have enabled?

**Comment by cigamit** [comment] 2019-07-01 22:53
Also, what PHP version are you using?  Looking at the code, we are making checks for everything that could be an array.  So, this is one of those gremlins.

**Comment by netniV** [comment] 2019-07-01 23:03
Yeah I have to agree that the code looks right.  We may have to see if we can do a check to make sure that it is only a string in some way (not just whether its an array and fail it).

**Comment by netniV** [comment] 2019-07-11 18:46
If you can get me access to the system were this error occurs and give them the exact steps to reproduce it everytime then I will reinvestigate.  But for now, I can't find any issue with this so I'm going to go ahead and close it.

**Closed by netniV** 2019-07-11 18:46 UTC
Labels: unverified

**Comment by kaba1ah** [comment] 2019-08-08 11:50
Hi,

I think I'm getting the same errors with Cacti 1.2.5 running on Debian Buster with MariaDB 10.3.15 and PHP 7.3.4. There is only one plugin installed -- Thold 1.3.2.

`2019/08/08 13:47:40 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php[40]:clog_view_logfile(), /lib/clog_webapi.php[207]:general_header(), /lib/functions.php[3244]:include_once(), /include/top_general_header.php[27]:draw_navigation_text(), /lib/functions.php[2595]:CactiErrorHandler())`

`2019/08/08 13:47:40 - ERROR PHP NOTICE: Array to string conversion in file: /var/www/html/cacti/lib/functions.php on line: 2595`

**Comment by netniV** [comment] 2019-08-08 18:39
Since the stack trace is different I would open that as a separate issue.
