### ISSUE TITLE
Suspected bug when using CDEF of "Average all data sources"

### ISSUE THREAD

**Issue by chtay** [Cacti/cacti#1049] opened 2017-10-27 08:31 UTC
I unable to locate where is the fault yet.
This is the finding.
When creating a graph template (e.g. multiple cpu) and when use CDEF of "Average of all data sources",
each time when creating a graph using the above template, the RRTool shows/says: "ERROR: don't understand ',,/'

When enable "Turn on Graph Debug Mode", I can see that the: CDEF:cdeda=',,/'.
When edit the graph template to switch from "Average of all data sources" to anything else, and then save, and then switch it back again to "Average of all data sources", the graph will work.
The CDEF:cdeda now is not ',,/' anymore.

**Comment by cigamit** [comment] 2017-10-27 11:58
Note the cdef id and then look at your graph_templates_item table and see if there are multiple templates in use there.  Then, take a look in the original template XML if the cdef is defined differently.  Some people reuse CDEF's and then export that information, which can cause problems when they are used by others.  It's an annoyance.  Once you have confirmed that this is or is not a problem, we can goto the next step.  Here is the query.

`select distinct graph_template_id from graph_templates_item where cdef_id=?`

**Comment by cigamit** [comment] 2018-01-16 01:43
These is likely a sequence issue with the CDEF.  We found a problem with organization CDEF items.  Please update your cdef.php from develop, or wait for 1.1.31.  Then, check the sequences in the cdef table using the query below:

`select * from cdef_items where id = <you_id> order by sequence;`

Do that for every CDEF, and if you find one that is not ordered from 1...n, either manually adjust them, or use the 'fixed' Drag and Drop interface in the latest cdef.php.

If that fixes this, then please close the ticket.

**Comment by cigamit** [comment] 2018-02-10 18:28
No feedback.  Suspect that this is resolved in any case in 1.1.35.  Likely due to the issues that we were experiencing editing cdef's.

**Closed by cigamit** 2018-02-10 18:28 UTC
Labels: unverified
