### ISSUE TITLE
[Cacti 1.1.27] 64 bit counter for 1/10/100 Gig interfaces

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#1089] opened 2017-11-19 01:38 UTC
Hi everyone,

I remember reading in this forum that 64 bit counters is a must for interface traffic that exceeds 100 Mbit or 1 Gbit.

On old posts I remember user not getting more than 114 Mbit/s reading out of their interface and I just realized I am using "normal" interface traffic data source in my current cacti installation.

I went on checking and I noticed that I do get more than 114 Mbit/s reading out of my intercaces (exhibit below), so my quesion is:

Should I drop my current data source and move it all to 64 bit counters or somehow Cacti bundled data source have been modified and can support interfaces 1/10/100 Gig ?

![image](https://user-images.githubusercontent.com/26431888/32986477-a27bb940-ccd2-11e7-9d8e-9965dff194b1.png)

PS: I could not find such info in the manual, this is why I posted here.

**Comment by jhonnyx82** [comment] 2017-11-19 13:32
Update: 

In case anyone was in my same situation: I ran a test with some Data sources that I expected to reach to over 500 Mbit traffic and I created a parallel 64 bit traffic data source.

Result is that below 500 Mbit the data source records properly, while **over 500 Mbit** it behaves very differently, not recording at all for continuous data and for the spike of traffc stopping at 500 Mbit.

Interesting is that below those values the data is quite the same (see below image).

My questions are : 

- Changing to 64 bit traffic for all data source is going to give an impact in terms of disk space or traffic from remote pollers to main poller?
- Is it possible to "easily" change the **Output type ID** without losing data? or should I recreate all traffic interface graphs? 
![image](https://user-images.githubusercontent.com/26431888/32991155-71626084-cd36-11e7-9758-be9c22cef30d.png)

 




![image](https://user-images.githubusercontent.com/26431888/32991130-067b7738-cd36-11e7-8910-8a90438d7b75.png)

**Comment by cigamit** [comment] 2017-11-19 22:50
You have to understand the correlation between ifHighSpeed and the RRDfile maximum value, and that you should 'ALWAYS' use 64bit counters if the device supports them.  As long as you create the Graphs in Cacti 0.8.8h+ and you have a 'sane' ifHighSpeed value for the interface, the graphs will be okay.

The cases where this breaks down are for several interface types (like 'bond' interfaces), where the ifHighSpeed is often times not accurate.  Once you verify that a device has 64bit counters, you can change the Template in Cacti to a 64bit one (from the GUI), and it will properly change the value queried from snmp.  However, you have to manually update the max value in the RRDfiles.  You do not change the "output type", but rather the template.

Since this is really not a bug, but rather a training issue, I'll go ahead and  close this now.

**Closed by cigamit** 2017-11-19 22:50 UTC
