### ISSUE TITLE
V1.2.13 - Nectar Aggregate 95th emailed report broken

### ISSUE THREAD

**Issue by iskandarbasman** [Cacti/cacti#3733] opened 2020-07-29 03:22 UTC
# Describe the bug

Created a Nectar Report.
Type is Tree and it is made up of 4 Aggregate 95th Percentile reports.
Everything looks normal in preview. HRULE is okay and 95th percentile values is okay.
![image](https://user-images.githubusercontent.com/67727557/88751480-3d28d680-d18a-11ea-8eeb-15c24281f758.png)
![image](https://user-images.githubusercontent.com/67727557/88751541-647fa380-d18a-11ea-82e8-af7e365df5ea.png)

## To Reproduce

Send the Nectar report via email.

HRULE missing on graph 2 and 4.
The 95th percentile on graph 2-4 is copied from graph 1. This is wrong.
The problem only appears in the emailed report.

![image](https://user-images.githubusercontent.com/67727557/88752723-3485cf80-d18d-11ea-96d4-8907b310824f.png)
![image](https://user-images.githubusercontent.com/67727557/88752768-4d8e8080-d18d-11ea-9dd5-0847de07f791.png)
![image](https://user-images.githubusercontent.com/67727557/88752801-5da66000-d18d-11ea-9961-b0e8c9074171.png)
![image](https://user-images.githubusercontent.com/67727557/88752837-6dbe3f80-d18d-11ea-988e-bb7e6e677dcd.png)

Believe the same bug was reported by someone else before. (Okay found it same as issue #3702)
Not sure how to further debug this.

**Comment by TheWitness** [comment] 2020-09-07 01:10
You may need to sync your template, but before you do, there was a recent patch to solve an issue with an undefined function causing the sync process to fail.  Just check the last few weeks or simply grab the 1.2.x branch, and sync from there.

**Comment by iskandarbasman** [comment] 2020-09-11 02:50
> 
> 
> You may need to sync your template, but before you do, there was a recent patch to solve an issue with an undefined function causing the sync process to fail. Just check the last few weeks or simply grab the 1.2.x branch, and sync from there.

Hmmm... Might a bit tricky for me to do this on my production cacti.
The is the fix in the 1.2.14 release ?

**Comment by TheWitness** [comment] 2020-09-12 14:37
Well, you should then wait till the 1.2.15 release, then edit each of your templates to ensure that they will visually render in a more appealing way, and once you have done that, sync the templates.

In a future version of Cacti, there will be a fairly large reduction in data that can cause Graphs to get out of sync with their templates.

**Comment by TheWitness** [comment] 2020-10-17 16:45
https://github.com/Cacti/cacti/issues/3702 Related to..

**Comment by TheWitness** [comment] 2020-10-17 16:45
Closing this one as it's a duplicate of the above.

**Closed by TheWitness** 2020-10-17 16:45 UTC
Labels: bug, duplicate
