### ISSUE TITLE
When turning on/off datasource debug, sql error

### ISSUE THREAD

**Issue by FlorianneRaven** [Cacti/cacti#2484] opened 2019-03-04 14:31 UTC
**Describe the bug**
2019/03/04 15:25:42 - DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:'SELECT  dspc.consolidation_function_id AS cf,  dsp.x_files_factor AS xff,  dspr.steps AS steps,  dspr.rows AS rows  FROM data_source_profiles AS dsp  INNER JOIN data_source_profiles_cf AS dspc  ON dsp.id=dspc.data_source_profile_id  INNER JOIN data_source_profiles_rra AS dspr  ON dsp.id=dspr.data_source_profile_id  WHERE dsp.id = ?  ORDER BY dspc.consolidation_function_id, dspr.steps'

2019/03/04 15:25:42 - DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows  FROM data_source_profiles AS dsp  INNER JOIN data_source_profiles_cf AS ds' at line 1
2019/03/04 15:25:42 - CMDPHP SQL Backtrace: (/data_sources.php: 77 ds_edit)(/data_sources.php: 1065 rrdtool_cacti_compare)(/lib/rrd.php: 2459 db_fetch_assoc_prepared)(/lib/database.php: 402 cacti_debug_backtrace) 

centos 7 php 7.3 cacti 1.1.38

**To Reproduce**
1. Go to datasource
2. Click on turn on/off debug
3. See error on error log

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: CentOS 7.6
 - Firefox
 - Version Windows 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by netniV** [comment] 2019-03-04 14:34
This error is not reproducible under Cacti 1.2.x

**Comment by FlorianneRaven** [comment] 2019-03-04 14:37
yum info cacti.noarch
Available Packages
Name        : cacti
Arch        : noarch
Version     : 1.1.38
Release     : 3.el7
Size        : 6.9 M
Repo        : epel
Summary     : An rrd based graphing tool
URL         : https://www.cacti.net/
License     : GPLv2+
Description : Cacti is a complete frontend to RRDTool. It stores all of the
            : necessary information to create graphs and populate them with
            : data in a MySQL database. The frontend is completely PHP
            : driven.
 
Cacti avalaible on epel

**Comment by netniV** [comment] 2019-03-04 14:39
@mortenstevens I thought Cacti 1.2.2 was in the EPEL ?

**Comment by mortenstevens** [comment] 2019-03-04 14:42
@netniV 
cacti-1.2.2 is in EPEL7 testing and will be pushed to stable in around 7-8 days.

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-86aaad0a53

**Comment by netniV** [comment] 2019-03-04 14:52
Are none of the 1.2.x packages in stable currently?

**Comment by mortenstevens** [comment] 2019-03-04 14:55
@netniV 
Yes, the latest stable package is cacti-1.1.38-3.el7. 1.2.x was delayed because of the SELinux related issues.

**Comment by netniV** [comment] 2019-03-04 14:57
OK, makes sense 👍

**Comment by mortenstevens** [comment] 2019-03-04 15:02
@netniV 
Btw I have also improved the RPM spec file for Fedora and EPEL to avoid most of the SELinux issues. 
See:
https://src.fedoraproject.org/rpms/cacti/c/066a68d1eab43b5b7596946daf8a52aab5c06f0a?branch=epel7

All major SELinux related issues should be fixed now.

**Comment by FlorianneRaven** [comment] 2019-03-04 15:04
Thank you for the answers :)

My colleague will try the unstable rpm :)

**Comment by netniV** [comment] 2019-03-06 15:46
I have just been notified that 1.2.2 has now hit stable.

> cacti-1.2.2-1.fc28, cacti-spine-1.2.2-1.fc28 has been pushed to the Fedora 28 stable repository. If problems still persist, please make note of it in this bug report.

**Comment by cigamit** [comment] 2019-03-07 12:49
Cool cool cool.

**Comment by cigamit** [comment] 2019-03-10 20:53
I can confirm that this was resolved in 1.2 specifically for more recent versions of MySQL / MariaDB where the name "rows" was moved to a reserved word status.

**Closed by cigamit** 2019-03-10 20:53 UTC
Labels: unverified
