### ISSUE TITLE
Data Query XML field method 'rewrite_index' does not correctly query for value

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#1921] opened 2018-09-13 08:16 UTC
forum link : [https://forums.cacti.net/viewtopic.php?f=12&t=59102](url)

Hi Everyone,I need to query a specific OID using the value from another input as index, I understand that <rewrite_index> is an option for this.In my code I am calling up to CPUIndexcpuPhysIndex from cpuName

```
<interface>
        <name>Cisco IOS XE cpu usage</name>
        <description>Get CPU usage for IOS XE stacks</description>
        <index_order_type>numeric</index_order_type>
        <oid_index>.1.3.6.1.4.1.9.9.109.1.1.1.1.2</oid_index>
        <oid_index_parse>OID/REGEXP:.*\.([0-9]+)$</oid_index_parse>

        <fields>
                <CPUIndexcpuPhysIndex>
                        <name>CPU Index</name>
                        <method>get</method>
                        <source>value</source>
                        <direction>input</direction>
                        <oid>.1.3.6.1.4.1.9.9.109.1.1.1.1.2</oid>
                </CPUIndexcpuPhysIndex>
                <cpuName>
                        <name>Switch Name</name>
                        <method>get</method>
                        <source>value</source>
                        <direction>input</direction>
                        <rewrite_index>|query_CPUIndexcpuPhysIndex|</rewrite_index>
                        <oid>.1.3.6.1.2.1.47.1.1.1.1.7</oid>
                </cpuName>
                <cpuFiveSec>
                        <name>CPU usage 5 sec</name>
                        <method>get</method>
                        <source>value</source>
                        <direction>output</direction>
                        <oid>.1.3.6.1.4.1.9.9.109.1.1.1.1.6</oid>
                </cpuFiveSec>
                <cpuOneMin>
                        <name>CPU usage 1 min</name>
                        <method>get</method>
                        <source>value</source>
                        <direction>output</direction>
                        <oid>.1.3.6.1.4.1.9.9.109.1.1.1.1.7</oid>
                </cpuOneMin>
                <cpuFiveMin>
                        <name>CPU usage 5 min</name>
                        <method>get</method>
                        <source>value</source>
                        <direction>output</direction>
                        <oid>.1.3.6.1.4.1.9.9.109.1.1.1.1.8</oid>
                </cpuFiveMin>
        </fields>
</interface>
```

This is the outcome :

Data Query Debug Information 
Total: 0.000000, Delta: 0.000000, Running data query [15].
Total: 0.000000, Delta: 0.000000, Found type = '3' [SNMP Query].
Total: 0.000000, Delta: 0.000000, Found data query XML file at '/var/www/html/cacti/resource/snmp_queries/cisco_xe_cpu.xml'
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.000000, Delta: 0.000000, <oid_num_indexes> missing in XML file, 'Index Count Changed' emulated by counting oid_index entries
Total: 0.040000, Delta: 0.040000, Executing SNMP walk for list of indexes @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2' Index Count: 2
Total: 0.040000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' value: '1000'
Total: 0.040000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' value: '2000'
Total: 0.040000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' results: '19'
Total: 0.040000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' results: '20'
Total: 0.040000, Delta: 0.000000, Located input field 'CPUIndexcpuPhysIndex' [get]
Total: 0.080000, Delta: 0.040000, Executing SNMP get for data @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' [value='1000']
Total: 0.110000, Delta: 0.040000, Executing SNMP get for data @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' [value='2000']
Total: 0.110000, Delta: 0.000000, Located input field 'cpuName' [get]
Executing SNMP get for 2 oids
**Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.1000' [value=''] (index: 19)
Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.2000' [value=''] (index: 20)**
Total: 0.120000, Delta: 0.010000, Update data query sort cache complete
Total: 0.120000, Delta: 0.000000, Updated data query index ordering
Total: 0.160000, Delta: 0.040000, Update re-index cache complete
Total: 0.160000, Delta: 0.010000, Update graph data query cache complete
Total: 0.170000, Delta: 0.000000, Update data source data query cache complete
Total: 0.170000, Delta: 0.000000, Update data query cache complete
Total: 0.180000, Delta: 0.010000, Update poller cache from query complete
Total: 0.190000, Delta: 0.010000, Automation execute data query complete
Total: 0.190000, Delta: 0.000000, Plugin hooks complete

**below the snmpget that should be the result of the query :**

.1.3.6.1.2.1.47.1.1.1.1.7.1000 = STRING: "Switch 1"

So as you can see (highlighted) the OID looks manipulated correctly (on the debug) but produce no value, my guess is that it only shows the manipulation but applies anyway the same original index, in my case it shows using **1000 and 2000** as indexes but in real it may be using **19 and 20** I forgot to verify with a packet capture but let me know in case it would be necessary

@cigamit  and @netniV  : do you know if this function is not operative in CACTI 1.x (honestly is the first time I use it)

**Comment by jhonnyx82** [comment] 2018-09-13 11:40
Thanks for the explanation,

I think that I got more or less how it works and from some tests I ran I could see that if I remove the **<rewrite_index>** then the outcome is that the OID is parsed using the "main" index of the function (in this case **19 and 20**) if instead I apply the <rewrite_index> function then I can see the OID is built correctly (using the value from input values of **CPUIndexcpuPhysIndex** that are 1000 and 2000).

The problem is that even with the rewrite, the snmpget function is not probably applied correctly because I can see that the value returned is NULL (as it would use still indexes 19 and 20) and I can see that the snmpget manually instead returns corrects values


So, breakdown:

This is the test when <rewrite_index> is not included, index 19 and 20 from the main oid_index are used, value returned for **cpuName** is empty (because of the wrong OID index)

Data Query Debug Information  
Total: 0.000000, Delta: 0.000000, Running data query [15].
Total: 0.000000, Delta: 0.000000, Found type = '3' [SNMP Query].
Total: 0.000000, Delta: 0.000000, Found data query XML file at '/var/www/html/cacti/resource/snmp_queries/cisco_xe_cpu.xml'
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.000000, Delta: 0.000000, <oid_num_indexes> missing in XML file, 'Index Count Changed' emulated by counting oid_index entries
Total: 0.050000, Delta: 0.050000, Executing SNMP walk for list of indexes @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2' Index Count: 2
Total: 0.050000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' value: '1000'
Total: 0.050000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' value: '2000'
Total: 0.050000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' results: **'19'**
Total: 0.050000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' results: **'20'**
Click to show Data Query output for field 'CPUIndexcpuPhysIndex'
Total: 0.060000, Delta: 0.000000, Located input field 'CPUIndexcpuPhysIndex' [walk]
Total: 0.110000, Delta: 0.050000, Executing SNMP walk for data @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2'
Found item [CPUIndexcpuPhysIndex='1000'] index: 19 [from value]
Found item [CPUIndexcpuPhysIndex='2000'] index: 20 [from value]
Total: 0.110000, Delta: 0.000000, Located input field 'cpuName' [get]
Total: 0.160000, Delta: 0.050000, Executing SNMP get for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.**19**' [value='']
Total: 0.220000, Delta: 0.060000, Executing SNMP get for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.**20**' [value='']
Total: 0.220000, Delta: 0.000000, Update data query sort cache complete
Total: 0.220000, Delta: 0.000000, Updated data query index ordering
Total: 0.290000, Delta: 0.060000, Update re-index cache complete
Total: 0.290000, Delta: 0.000000, Update graph data query cache complete
Total: 0.300000, Delta: 0.000000, Update data source data query cache complete
Total: 0.300000, Delta: 0.000000, Update data query cache complete
Total: 0.310000, Delta: 0.010000, Update poller cache from query complete
Total: 0.320000, Delta: 0.010000, Automation execute data query complete
Total: 0.320000, Delta: 0.000000, Plugin hooks complete



This is instead when I use the **<rewrite_index>** , **cpuName** indexes used are the values of **CPUIndexcpuPhysIndex** at least on the debug but the values are not returned

Everything is highlighted in **bold** character

Data Query Debug Information
Total: 0.000000, Delta: 0.000000, Running data query [15].
Total: 0.000000, Delta: 0.000000, Found type = '3' [SNMP Query].
Total: 0.000000, Delta: 0.000000, Found data query XML file at '/var/www/html/cacti/resource/snmp_queries/cisco_xe_cpu.xml'
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.000000, Delta: 0.000000, <oid_num_indexes> missing in XML file, 'Index Count Changed' emulated by counting oid_index entries
Total: 0.040000, Delta: 0.040000, Executing SNMP walk for list of indexes @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2' Index Count: 2
Total: 0.040000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' value: '1000'
Total: 0.040000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' value: '2000'
Total: 0.040000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' results: '19'
Total: 0.040000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' results: '20'
Total: 0.040000, Delta: 0.000000, Located input field 'CPUIndexcpuPhysIndex' [get]
Total: 0.080000, Delta: 0.040000, Executing SNMP get for data @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' **[value='1000']**
Total: 0.110000, Delta: 0.040000, Executing SNMP get for data @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' **[value='2000']**
Total: 0.110000, Delta: 0.000000, Located input field 'cpuName' [get]
Executing SNMP get for 2 oids
Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.**1000**' [value=''] (index: 19)
Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.**2000**' [value=''] (index: 20)
Total: 0.120000, Delta: 0.010000, Update data query sort cache complete
Total: 0.120000, Delta: 0.000000, Updated data query index ordering
Total: 0.160000, Delta: 0.040000, Update re-index cache complete
Total: 0.160000, Delta: 0.010000, Update graph data query cache complete
Total: 0.170000, Delta: 0.000000, Update data source data query cache complete
Total: 0.170000, Delta: 0.000000, Update data query cache complete
Total: 0.180000, Delta: 0.010000, Update poller cache from query complete
Total: 0.190000, Delta: 0.010000, Automation execute data query complete
Total: 0.190000, Delta: 0.000000, Plugin hooks complete


And if I ran manually an SNMP get on those OIDs:

.1.3.6.1.2.1.47.1.1.1.1.7.1000 = STRING: "Switch 1"
.1.3.6.1.2.1.47.1.1.1.1.7.2000 = STRING: "Switch 2"

**Comment by netniV** [comment] 2018-09-13 11:52
This is the diff between what you've provided, would you say that's accurate?

```diff
diff --git a/tmp/1 b/tmp/2
index 19035eb..9308532 100644
--- a/tmp/1
+++ b/tmp/2
@@ -9,14 +9,13 @@ Total: 0.000000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.
 Total: 0.000000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' value: '2000'
 Total: 0.000000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' results: '19'
 Total: 0.000000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' results: '20'
-Click to show Data Query output for field 'CPUIndexcpuPhysIndex'
-Total: 0.000000, Delta: 0.000000, Located input field 'CPUIndexcpuPhysIndex' [walk]
-Total: 0.000000, Delta: 0.000000, Executing SNMP walk for data @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2'
-Found item [CPUIndexcpuPhysIndex='1000'] index: 19 [from value]
-Found item [CPUIndexcpuPhysIndex='2000'] index: 20 [from value]
+Total: 0.000000, Delta: 0.000000, Located input field 'CPUIndexcpuPhysIndex' [get]
+Total: 0.000000, Delta: 0.000000, Executing SNMP get for data @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' [value='1000']
+Total: 0.000000, Delta: 0.000000, Executing SNMP get for data @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' [value='2000']
 Total: 0.000000, Delta: 0.000000, Located input field 'cpuName' [get]
-Total: 0.000000, Delta: 0.000000, Executing SNMP get for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.19' [value='']
-Total: 0.000000, Delta: 0.000000, Executing SNMP get for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.20' [value='']
+Executing SNMP get for 2 oids
+Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.1000' [value=''] (index: 19)
+Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.2000' [value=''] (index: 20)
 Total: 0.000000, Delta: 0.000000, Update data query sort cache complete
 Total: 0.000000, Delta: 0.000000, Updated data query index ordering
 Total: 0.000000, Delta: 0.000000, Update re-index cache complete
```

**Comment by jhonnyx82** [comment] 2018-09-13 12:09
Yes,

I can comment on this hold on:

What you need to look at is that the **main indexes** of the SNMP query are 
- 19
- 20

**CPUIndexcpuPhysIndex** walk values out of this OID: .1.3.6.1.4.1.9.9.109.1.1.1.1.2
Found item [CPUIndexcpuPhysIndex='1000'] index: 19 [from value]
Found item [CPUIndexcpuPhysIndex='2000'] index: 20 [from value]
- values returned : 1000 and 2000 (using  main indexes 19 and 20)

**cpuName** without <rewrite_index> would run this OID : .1.3.6.1.2.1.47.1.1.1.1.7 against
- main indexes **19 and 20**
  - wrong OIDs: .1.3.6.1.2.1.47.1.1.1.1.7.**19** and .1.3.6.1.2.1.47.1.1.1.1.7**.20** does not exist

**cpuName**  WITH <rewrite_index> would run this OID : .1.3.6.1.2.1.47.1.1.1.1.7 against
- CPUIndexcpuPhysIndex VALUES
  - correct OIDs:  .1.3.6.1.2.1.47.1.1.1.1.7.**1000** and .1.3.6.1.2.1.47.1.1.1.1.7.**2000** that should produce the name of the switches

If you look back at the outputs of the debug, this substitution happens but I think the resulting snmpget is still using the main indexes instead of applying the substitution

**Comment by jhonnyx82** [comment] 2018-09-13 12:32
Let me share with you the outcome of a packet capture, on the **left** the OIDs pulled without <rewrite_index> on the **right** WITH <rewrite_index>

![image](https://user-images.githubusercontent.com/26431888/45488476-cfc05800-b761-11e8-8af6-b6a6da7dde32.png)

**Comment by netniV** [comment] 2018-09-13 13:16
OK, so I think this has to do with the rewrite function, but to be clear if you are seeing:

```
+Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.1000' [value=''] (index: 19)
+Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.2000' [value=''] (index: 20)
```
These are entries found in the `$values` array.  Copy your current `lib/data_query.php` somewhere safe, then try applying the following patch:

```diff
diff --git a/lib/data_query.php b/lib/data_query.php
index a592121c..0226647d 100644
--- a/lib/data_query.php
+++ b/lib/data_query.php
@@ -587,7 +587,7 @@ function query_snmp_host($host_id, $snmp_query_id) {
                                                $oids[] = $value['oid'];
                                        }

-                                       debug_log_insert('data_query', __('Executing SNMP get for %s oids' , count($oids)));
+                                       debug_log_insert('data_query', __('Executing SNMP get for %s oids (%s)' , count($oids), implode(', ', $oids)));

                                        if (isset($field_array['output_format'])) {
                                                if ($field_array['output_format'] == 'hex') {
@@ -599,19 +599,43 @@ function query_snmp_host($host_id, $snmp_query_id) {
                                                }

                                                foreach ($oids as $oid) {
-                                                       $results[$oid] = cacti_snmp_get($host['hostname'], $host['snmp_community'], $oid, $host['snmp_version'],
-                                                               $host['snmp_username'], $host['snmp_password'], $host['snmp_auth_protocol'],
-                                                               $host['snmp_priv_passphrase'], $host['snmp_priv_protocol'], $host['snmp_context'],
-                                                               $host['snmp_port'], $host['snmp_timeout'], SNMP_POLLER, $host['snmp_engine_id'],
+                                                       $results[$oid] = cacti_snmp_get(
+                                                               $host['hostname'],
+                                                               $host['snmp_community'],
+                                                               $oid,
+                                                               $host['snmp_version'],
+                                                               $host['snmp_username'],
+                                                               $host['snmp_password'],
+                                                               $host['snmp_auth_protocol'],
+                                                               $host['snmp_priv_passphrase'],
+                                                               $host['snmp_priv_protocol'],
+                                                               $host['snmp_context'],
+                                                               $host['snmp_port'],
+                                                               $host['snmp_timeout'],
+                                                               SNMP_POLLER,
+                                                               $host['snmp_engine_id'],
                                                                $value_output_format);
                                                }
                                        } else {
                                                $results = cacti_snmp_session_walk($session, $oids);
                                        }

+                                       foreach ($results as $key => $value) {
+                                               debug_log_insert('data_query',
+                                                       __('Found result for data @ \'%s\' [value=\'%s\']',
+                                                       $key, $value));
+                                       }
+
                                        foreach (array_keys($values) as $key){
                                                if (isset($results[$values[$key]['oid']])) {
                                                        $values[$key]['value'] = $results[$values[$key]['oid']];
+                                                       debug_log_insert('data_query',
+                                                               __('Setting result for data @ \'%s\' [key=\'%s\', value=\'%s\']',
+                                                               $values[$key]['oid'], $key, $values[$key]['value']));
+                                               } else {
+                                                       debug_log_insert('data_query',
+                                                               __('Skipped result for data @ \'%s\' [key=\'%s\', value=\'%s\']',
+                                                               $values[$key]['oid'], $key, $values[$key]['value']));
                                                }
                                        }
```

This should give us more debug information on what is occurring with the reindex.

**Comment by jhonnyx82** [comment] 2018-09-13 13:49
not sure I will have time today to try on the test server i have but in case I will let you know the outcome

**Comment by netniV** [comment] 2018-09-13 13:50
Please ;-)

**Comment by jhonnyx82** [comment] 2018-09-13 16:09
I applied it
but do I need to open up the debugs ?

**Comment by jhonnyx82** [comment] 2018-09-13 16:18
when I run a verbose query i get these logs in CACTI

```

2018/09/13  16:17:20 - CMDPHP PHP ERROR WARNING Backtrace: (/host.php: 110  host_reload_query)(/host.php: 576 run_data_query)(/lib/data_query.php:  88 query_snmp_host)(/lib/data_query.php: 619  cacti_snmp_session_walk)(/lib/snmp.php: 435  walk)(CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)
--
2018/09/13 16:17:20 - ERROR PHP WARNING: SNMP::walk(): Multi OID  walks are not supported! in file: /var/www/html/cacti/lib/snmp.php  on  line: 435


```

**Comment by netniV** [comment] 2018-09-13 19:34
Were you getting those before?  Can you copy and paste the full verbose query output for me?

**Comment by jhonnyx82** [comment] 2018-09-13 20:38
hold on, I am getting the output for you

**Comment by jhonnyx82** [comment] 2018-09-13 20:40
```
Data Query Debug Information
Total: 0.000000, Delta: 0.000000, Running data query [7].
Total: 0.010000, Delta: 0.010000, Found type = '3' [SNMP Query].
Total: 0.020000, Delta: 0.010000, Found data query XML file at '/var/www/html/cacti/resource/snmp_queries/cisco_xe_cpu.xml'
Total: 0.030000, Delta: 0.010000, XML file parsed ok.
Total: 0.030000, Delta: 0.000000, <oid_num_indexes> missing in XML file, 'Index Count Changed' emulated by counting oid_index entries
Total: 0.080000, Delta: 0.050000, Executing SNMP walk for list of indexes @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2' Index Count: 2
Total: 0.080000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' value: '1000'
Total: 0.080000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' value: '2000'
Total: 0.080000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' results: '19'
Total: 0.080000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' results: '20'
Click to show Data Query output for field 'CPUIndexcpuPhysIndex'
Total: 0.080000, Delta: 0.000000, Located input field 'CPUIndexcpuPhysIndex' [walk]
Total: 0.120000, Delta: 0.040000, Executing SNMP walk for data @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2'
Found item [CPUIndexcpuPhysIndex='1000'] index: 19 [from value]
Found item [CPUIndexcpuPhysIndex='2000'] index: 20 [from value]
Total: 0.120000, Delta: 0.000000, Located input field 'cpuName' [get]
Executing SNMP get for 2 oids (.1.3.6.1.2.1.47.1.1.1.1.7.1000, .1.3.6.1.2.1.47.1.1.1.1.7.2000)
Skipped result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.1000' [key='0', value='']
Skipped result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.2000' [key='1', value='']
Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.1000' [value=''] (index: 19)
Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.2000' [value=''] (index: 20)
Total: 0.130000, Delta: 0.010000, Update data query sort cache complete
Total: 0.140000, Delta: 0.020000, Updated data query index ordering
Total: 0.200000, Delta: 0.050000, Update re-index cache complete
Total: 0.200000, Delta: 0.000000, Update graph data query cache complete
Total: 0.200000, Delta: 0.000000, Update data source data query cache complete
Total: 0.200000, Delta: 0.000000, Update data query cache complete
Total: 0.200000, Delta: 0.000000, Update poller cache from query complete
Total: 0.220000, Delta: 0.020000, Automation execute data query complete
Total: 0.220000, Delta: 0.000000, Plugin hooks complete
```

**Comment by jhonnyx82** [comment] 2018-09-13 21:10
I just gave it a try, on the top of my ignorance and I changed line **619** (from the modified **data_query.php** on the original 1.1.38 version is at line **609** )

from
`$results = cacti_snmp_session_walk($session, $oids);`
to
`$results = cacti_snmp_session_get($session, $oids);`


and seems that it works now, simply I don't know if it means breaking something to change the calling function from ***_walk to** ***_get**

here the difference:

WRONG  : 

Data Query Debug Information
Total: 0.000000, Delta: 0.000000, Running data query [7].
Total: 0.000000, Delta: 0.000000, Found type = '3' [SNMP Query].
Total: 0.000000, Delta: 0.000000, Found data query XML file at '/var/www/html/cacti/resource/snmp_queries/cisco_xe_cpu.xml'
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.000000, Delta: 0.000000, <oid_num_indexes> missing in XML file, 'Index Count Changed' emulated by counting oid_index entries
Total: 0.050000, Delta: 0.050000, Executing SNMP walk for list of indexes @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2' Index Count: 2
Total: 0.050000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' value: '1000'
Total: 0.050000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' value: '2000'
Total: 0.050000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' results: '19'
Total: 0.050000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' results: '20'
Click to show Data Query output for field 'CPUIndexcpuPhysIndex'
Total: 0.050000, Delta: 0.000000, Located input field 'CPUIndexcpuPhysIndex' [walk]
Total: 0.090000, Delta: 0.050000, Executing SNMP walk for data @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2'
Found item [CPUIndexcpuPhysIndex='1000'] index: 19 [from value]
Found item [CPUIndexcpuPhysIndex='2000'] index: 20 [from value]
Total: 0.090000, Delta: 0.000000, Located input field 'cpuName' [get]
Executing SNMP get for 2 oids
**Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.1000' [value=''] (index: 19)
Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.2000' [value=''] (index: 20)**
Total: 0.100000, Delta: 0.010000, Update data query sort cache complete
Total: 0.100000, Delta: 0.000000, Updated data query index ordering
Total: 0.160000, Delta: 0.050000, Update re-index cache complete
Total: 0.160000, Delta: 0.010000, Update graph data query cache complete
Total: 0.160000, Delta: 0.000000, Update data source data query cache complete
Total: 0.160000, Delta: 0.000000, Update data query cache complete
Total: 0.200000, Delta: 0.030000, Update poller cache from query complete
Total: 0.200000, Delta: 0.000000, Automation execute data query complete
Total: 0.200000, Delta: 0.000000, Plugin hooks complete

CORRECT : 

Data Query Debug Information
Total: 0.000000, Delta: 0.000000, Running data query [7].
Total: 0.000000, Delta: 0.000000, Found type = '3' [SNMP Query].
Total: 0.000000, Delta: 0.000000, Found data query XML file at '/var/www/html/cacti/resource/snmp_queries/cisco_xe_cpu.xml'
Total: 0.000000, Delta: 0.000000, XML file parsed ok.
Total: 0.000000, Delta: 0.000000, <oid_num_indexes> missing in XML file, 'Index Count Changed' emulated by counting oid_index entries
Total: 0.050000, Delta: 0.050000, Executing SNMP walk for list of indexes @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2' Index Count: 2
Total: 0.050000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' value: '1000'
Total: 0.050000, Delta: 0.000000, Index found at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' value: '2000'
Total: 0.050000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.19' results: '19'
Total: 0.050000, Delta: 0.000000, index_parse at OID: '.1.3.6.1.4.1.9.9.109.1.1.1.1.2.20' results: '20'
Click to show Data Query output for field 'CPUIndexcpuPhysIndex'
Total: 0.050000, Delta: 0.000000, Located input field 'CPUIndexcpuPhysIndex' [walk]
Total: 0.090000, Delta: 0.050000, Executing SNMP walk for data @ '.1.3.6.1.4.1.9.9.109.1.1.1.1.2'
Found item [CPUIndexcpuPhysIndex='1000'] index: 19 [from value]
Found item [CPUIndexcpuPhysIndex='2000'] index: 20 [from value]
Total: 0.090000, Delta: 0.000000, Located input field 'cpuName' [get]
Executing SNMP get for 2 oids
**Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.1000' [value='Switch 1'] (index: 19)
Got SNMP get result for data @ '.1.3.6.1.2.1.47.1.1.1.1.7.2000' [value='Switch 2'] (index: 20)**
Total: 0.150000, Delta: 0.050000, Update data query sort cache complete
Total: 0.150000, Delta: 0.000000, Updated data query index ordering
Total: 0.200000, Delta: 0.050000, Update re-index cache complete
Total: 0.210000, Delta: 0.010000, Update graph data query cache complete
Total: 0.210000, Delta: 0.000000, Update data source data query cache complete
Total: 0.210000, Delta: 0.000000, Update data query cache complete
Total: 0.240000, Delta: 0.030000, Update poller cache from query complete
Total: 0.240000, Delta: 0.000000, Automation execute data query complete
Total: 0.240000, Delta: 0.000000, Plugin hooks complete

**Comment by netniV** [comment] 2018-09-13 22:20
It's the "Skipped result" that i'm most interested in.  That means it didn't find the OID in the list of results.  So we are going to have to debug that section next.

**Comment by jhonnyx82** [comment] 2018-09-13 22:49
I got the test vm here if you need anything otherwise I can resume this discussion from tuesday

**Comment by netniV** [comment] 2018-09-13 23:03
Live it till Tuesday then. If I get chance I’ll see if I can replicate it in the meantime using some custom NetSNMP scrips

**Comment by jhonnyx82** [comment] 2018-09-13 23:06
ok, thanks a lot for your help

**Comment by jhonnyx82** [comment] 2018-09-17 20:27
Hi @netniV 

Let me know how can I help in case you need some tests, thanks!

**Comment by netniV** [comment] 2018-09-17 21:39
Sorry haven’t got to this. Kinda broke a few things at the weekend so had to create patches.  Then more QA. Tomorrow, Wednesday and Thursday, preparing, updating and recovering after an all nighter doing server update patches. 

I will get back to this as soon as I can. Alex has an issue with reindexing (interface index rather than your XML reindex) that I was also looking into. Time just keeps slipping away.

**Comment by jhonnyx82** [comment] 2018-09-17 23:09
Thank you,

didn't mean to put pressure on you, take your time

**Comment by netniV** [comment] 2018-09-20 14:55
Try this, see if it works for you. It's a 1.1.38-modified data_query.php.
[data_query.php](https://github.com/Cacti/cacti/files/2401839/data_query.txt)

**Comment by jhonnyx82** [comment] 2018-09-20 23:38
tested and working good on the _**input**_ fields

So my original problem is fixed, thanks (_really really_) but I tested by applying the **rewrite_index** function on the **_output_** fields and I expected to have wrong data (it would have appended the wrong index to the snmpget) instead data was OK, this means that the _**rewrite_index**_ function is not evaluated on the output fields and follows up always the original index.

Let me know if this is maybe by design (I believe not), and whenever you can apply a patch for it I will be ready to test

**Comment by gadzet21** [comment] 2018-09-21 05:19
Hi,
It seems to me that the problem is also related to the topic #1252 
it would be great if it was resolved :)

**Comment by netniV** [comment] 2018-09-21 05:51
OK, so the above patch needs to be applied to 1.2.  For output fields, I think that the resolution of #1252 applies here but I would like to double check that.  Could you do the same diagnosis as above so I can follow the logic through?

**Comment by netniV** [comment] 2018-09-21 09:28
You :)

**Comment by jhonnyx82** [comment] 2018-09-21 09:40
OK, will snoop into that as soon as I can

**Comment by netniV** [comment] 2018-09-21 18:28
I'm going to close this, please open a separate issue or update the other one listed above for the output part.

**Closed by netniV** 2018-09-21 18:28 UTC
