### ISSUE TITLE
Poller generates false positive for recache event when SNMP Quick Print default changes

### ISSUE THREAD

**Issue by i3o** [Cacti/cacti#1634] opened 2018-05-12 17:24 UTC
Running latest Cacti from git on FreeBSD 11.1-REL and it appeared that a random cross-section of my graphs were not reporting any data (one device, for instance, only the "load averages" graph was working, so it's definitely not an SNMP issue or connection issue. Switching to Spine fixed the problem, but it seems like this is probably a bug, so I wanted to report it. If you need me to switch back to cmd.php to get some more information to debug, I'll be happy to help (it's more for dev than production purposes). The only log lines in common were these:

05/10/2018 21:55:08 - POLLER: Poller[1] ASSERT: '2275922<0:6:24:16.00' failed. Recaching host 'x.x.x.179', data query #1
05/10/2018 21:55:08 - POLLER: Poller[1] ASSERT: '2275944<0:6:24:16.04' failed. Recaching host 'x.x.x.179', data query #3
05/10/2018 21:55:08 - POLLER: Poller[1] ASSERT: '2276136<0:6:24:16.08' failed. Recaching host 'x.x.x.179', data query #4
05/10/2018 21:55:08 - POLLER: Poller[1] ASSERT: '2276249<0:6:24:16.13' failed. Recaching host 'x.x.x.179', data query #5
05/10/2018 21:55:08 - POLLER: Poller[1] ASSERT: '2276266<0:6:24:16.17' failed. Recaching host 'x.x.x.179', data query #6
05/10/2018 21:55:08 - POLLER: Poller[1] ASSERT: '2276279<0:6:24:16.21' failed. Recaching host 'x.x.x.179', data query #7
05/10/2018 21:55:09 - POLLER: Poller[1] ASSERT: '2599046<0:7:18:04.25' failed. Recaching host 'x.x.x.8', data query #1
05/10/2018 21:55:09 - POLLER: Poller[1] ASSERT: '2599060<0:7:18:04.30' failed. Recaching host 'x.x.x.8', data query #3
05/10/2018 21:55:09 - POLLER: Poller[1] ASSERT: '2599227<0:7:18:04.34' failed. Recaching host 'x.x.x.8', data query #4
05/10/2018 21:55:09 - POLLER: Poller[1] ASSERT: '2599302<0:7:18:04.38' failed. Recaching host 'x.x.x.8', data query #5
05/10/2018 21:55:09 - POLLER: Poller[1] ASSERT: '2599320<0:7:18:04.43' failed. Recaching host 'x.x.x.8', data query #6
05/10/2018 21:55:09 - POLLER: Poller[1] ASSERT: '2599334<0:7:18:04.47' failed. Recaching host 'x.x.x.8', data query #7
05/10/2018 21:55:00 - POLLER: Poller[1] ASSERT: '251826<0:0:46:38.23' failed. Recaching host 'x.x.x.46', data query #1
05/10/2018 21:55:00 - POLLER: Poller[1] ASSERT: '251828<0:0:46:38.23' failed. Recaching host 'x.x.x.46', data query #3
05/10/2018 21:55:00 - POLLER: Poller[1] ASSERT: '251921<0:0:46:38.24' failed. Recaching host 'x.x.x.46', data query #4
05/10/2018 21:55:00 - POLLER: Poller[1] ASSERT: '251982<0:0:46:38.24' failed. Recaching host 'x.x.x.46', data query #5
05/10/2018 21:55:00 - POLLER: Poller[1] ASSERT: '251983<0:0:46:38.24' failed. Recaching host 'x.x.x.46', data query #6
05/10/2018 21:55:00 - POLLER: Poller[1] ASSERT: '251984<0:0:46:38.24' failed. Recaching host 'x.x.x.46', data query #7

**Comment by cigamit** [comment] 2018-05-12 20:40
Uninstall php-snmp.  Can you please let me know your php version?

**Comment by axcviii** [comment] 2018-05-12 20:41
Oops sorry, forgot to mention that - PHP 7.2.4

Removed php-snmp, I'll switch back to cmd.php and see if that helps.

**Comment by cigamit** [comment] 2018-05-12 20:44
Good to know.  What Cacti version?

**Comment by axcviii** [comment] 2018-05-12 20:52
Cacti version 1.2.0, straight from github

Removing php72-snmp seems to have solved it. Is this a known issue that Cacti and php72-snmp are incompatible, or just something that has yet to be addressed in part of updating it to work with php72?

Thank you!

**Comment by rprofijt** [comment] 2018-05-13 18:11
Also have this issue:

POLLER: Poller[1] ASSERT: '494854<0:1:23:24.85' failed.

PHP version: v7.0.27-0+deb9u1 on the latest git 1.2.0 checkout. Removing php-snmp does not help, spine is working fine :)

**Comment by samip5** [comment] 2018-05-15 23:02
I'm experiencing a similar problem.

 it can't generate the graphs at all, any of them.

Cacti version: 1.1.38
Linux Distro and version: Ubuntu 16.04
PHP Version: 7.0.30-0ubuntu0.16.04.1, FPM mode

Log:
```
05/14/2018 04:26:16 - POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues: 48, DS[13, 13, 12, 12, 11, 11, 1, 2, 4, 2, 5, 6, 7, 6, 9, 14, 9, 8, 7, 8], Additional Issues Remain.  Only showing first 20
05/14/2018 04:26:17 - SYSTEM STATS: Time:1.7352 Method:cmd.php Processes:10 Threads:N/A Hosts:3 HostsPerProcess:1 DataSources:2 RRDsProcessed:1
05/14/2018 04:26:18 - PCOMMAND Device[2] WARNING: Recache Event Detected for Device
05/14/2018 04:26:20 - RECACHE STATS: Poller: RecacheTime:1.7455 DevicesRecached:1
05/14/2018 04:33:27 - POLLER: Poller[1] ASSERT: '1409067<3' failed. Recaching host '192.168.2.20', data query #1
```

**Comment by SjonHortensius** [comment] 2018-05-18 11:06
This seems to be caused by a conflict between this query which inserts the formatted part of the uptime (in `d:h:m:s.s` format) https://github.com/Cacti/cacti/blob/9fae81a959df50d87478695814e92aa45408811e/cmd.php#L645

and the poller which inserts integer values (seconds only) https://github.com/Cacti/cacti/blob/27c8f958ba97a69926debe0d1617f36a1dcaa64a/lib/poller.php#L309

This might also be related to #1501

**Comment by samip5** [comment] 2018-05-21 22:19
What's the version that works at this time and what's the current status of this issue?

**Comment by SjonHortensius** [comment] 2018-05-24 11:31
I've gone for the quick fix, instead of looking at uptime I switched to index-count as reindex method:

```sql
update host_snmp_query set reindex_method=2;
```

**Comment by capncrunch** [comment] 2018-05-30 15:20
I have the same issue.

Cacti: 1.1.38+ds1-1~bpo9+1 (Stretch Backports)
Linux: Debian Stretch (with Backports only used for Cacti)
PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )

Removing php-snmp makes no difference.

Additionally, all my graphs stay at NaN, might be related. I haven't yet looked further into this.

Log:
`05/30/2018 15:00:33 - RECACHE STATS: Poller: RecacheTime:10.0547 DevicesRecached:4`
`05/30/2018 15:00:28 - PCOMMAND Device[5] Device[sw1] WARNING: Recache Event Detected for Device`
`05/30/2018 15:00:28 - PCOMMAND Device[4] Device[sw2] WARNING: Recache Event Detected for Device`
`05/30/2018 15:00:24 - PCOMMAND Device[3] Device[sw3] WARNING: Recache Event Detected for Device`
`05/30/2018 15:00:23 - PCOMMAND Device[1] Device[ap1] WARNING: Recache Event Detected for Device`
`05/30/2018 15:00:22 - SYSTEM STATS: Time:19.9516 Method:cmd.php Processes:1 Threads:N/A Hosts:5 HostsPerProcess:5 DataSources:174 RRDsProcessed:70`
`05/30/2018 15:00:22 - POLLER: Poller[Main Poller] ASSERT: '1870732<0:5:17:00.52' failed. Recaching host '172.16.42.12', data query #2`
`05/30/2018 15:00:20 - POLLER: Poller[Main Poller] ASSERT: '1870735<0:5:16:59.49' failed. Recaching host '172.16.42.11', data query #2`
`05/30/2018 15:00:15 - POLLER: Poller[Main Poller] ASSERT: '1868490<0:5:16:32.48' failed. Recaching host '172.16.42.10', data query #2`
`05/30/2018 15:00:07 - POLLER: Poller[Main Poller] ASSERT: '1050021<0:3:00:00.93' failed. Recaching host '172.16.42.9', data query #2`

Manual snmpget:
`root:~# snmpwalk -v2c -c XXXXXXXX 172.16.42.9 .1.3.6.1.2.1.1.3.0
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1110761) 3:05:07.61`
`root:~# snmpwalk -v2c -c XXXXXXXX 172.16.42.10 .1.3.6.1.2.1.1.3.0
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1929360) 5:21:33.60`
`root:~# snmpwalk -v2c -c XXXXXXXX 172.16.42.11 .1.3.6.1.2.1.1.3.0
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1931811) 5:21:58.11`
`root:~# snmpwalk -v2c -c XXXXXXXX 172.16.42.12 .1.3.6.1.2.1.1.3.0
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1931997) 5:21:59.97`

**Comment by capncrunch** [comment] 2018-05-31 15:42
I have now switched to spine using the default setting from the Debian packet. This fixed all of my issues.

**Comment by cigamit** [comment] 2018-06-02 16:28
This one is so OS dependent.  Have to git it some thought.

**Comment by cigamit** [comment] 2018-06-02 17:19
This should be resolved now.  Looks like the default value for snmp_get_quick_print() changed from false to true.  Simply updating lib/snmp.php should resolve this issue.  There was one additional change, but it was formatting only.

**Closed as completed** 2018-06-03 19:25 UTC
Labels: bug
