### ISSUE TITLE
Automation rules aren't run for new devices on remote data collectors

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#3261] opened 2020-02-13 05:23 UTC
When adding a new device through the main data collector, but specifying it to be associated with a remote data collector, the device is created, but none of the automation rules are run. Once I select 'apply automation rules' all the graphs are created.

For the past several months I have been creating new devices on the main data collector and having it associated with the main data collector. Then I move the device to the collector I want it on. 

Granted the way I use 'remote data collectors' is different than how they are intended - I use them as load balancers.

**Comment by TheWitness** [comment] 2020-02-22 15:24
I thought this was fixed in 1.2.9.  Can you try it there?

**Comment by TheWitness** [comment] 2020-03-14 14:01
No feedback.

**Comment by bmfmancini** [comment] 2020-03-14 14:03
Hey guys

I noticed the same thing and I opend an issue on it

On 1.2.9 same behaviour is present but in my case autom8 doesn't create
interface graphs

**Comment by TheWitness** [comment] 2020-03-14 18:56
Can you see if the host_snmp_cache on the remote data collector is populated with the most up-to-date information?

**Comment by TheWitness** [comment] 2020-03-14 19:11
Also, run this query on both the remote data collector and the main collector.  See that their output is the same:

```sql
SELECT sq.*,
hsq.reindex_method
FROM snmp_query AS sq
INNER JOIN host_snmp_query AS hsq
ON sq.id=hsq.snmp_query_id
WHERE hsq.host_id = ?
```

Replacing the ? with the host_id in question.

**Comment by bmfmancini** [comment] 2020-03-14 19:27
Yep here you go 

I did the following 

-Added a Cisco switch
Here is the device template 

![image](https://user-images.githubusercontent.com/13388748/76688935-fa65c800-6607-11ea-9520-3b5fd42eb0e8.png)

Here is the db output

MariaDB [cacti]> SELECT sq.*, hsq.reindex_method FROM snmp_query AS sq INNER JOIN host_snmp_query AS hsq ON sq.id=hsq.snmp_query_id WHERE hsq.host_id = 4;
+----+----------------------------------+--------------------------------------------------+-----------------------------+-----------------------------------------------------+-------------------+---------------+----------------+
| id | hash                             | xml_path                                         | name                        | description                                         | graph_template_id | data_input_id | reindex_method |
+----+----------------------------------+--------------------------------------------------+-----------------------------+-----------------------------------------------------+-------------------+---------------+----------------+
|  1 | d75e406fdeca4fcef45b8be3a9a63cbc | <path_cacti>/resource/snmp_queries/interface.xml | SNMP - Interface Statistics | Queries a host for a list of monitorable interfaces |                 0 |             2 |              1 |
+----+----------------------------------+--------------------------------------------------+-----------------------------+-----------------------------------------------------+-------------------+---------------+----------------+
1 row in set (0.00 sec)

these are the graphs created 


2020/03/14 14:21:09 - AUTOM8 NOTE: Graph Added - Device[MANCINi-SW.mancini.com], Graph[MANCINi-SW.mancini.com - Uptime], DS[MANCINi-SW.mancini.com - Uptime] Graphs[MANCINi-SW.mancini.com - Uptime]
--
2020/03/14 14:21:09 - AUTOM8 NOTE: Graph Added - Device[MANCINi-SW.mancini.com], Graph[MANCINi-SW.mancini.com - Polling Time], DS[MANCINi-SW.mancini.com - Polling Time] Graphs[MANCINi-SW.mancini.com - Polling Time]
2020/03/14 14:21:09 - AUTOM8 NOTE: Graph Added - Device[MANCINi-SW.mancini.com], Graph[MANCINi-SW.mancini.com - CPU Usage], DS[MANCINi-SW.mancini.com - 5 Minute CPU] Graphs[MANCINi-SW.mancini.com - CPU Usage]


This is what I get when I hit apply automation rules 


2020/03/14 14:27:10 - AUTOM8 NOTE: Graph Added - Device[MANCINi-SW.mancini.com], Graph[MANCINi-SW.mancini.com - Traffic - 192.168.1.253 (Vlan1)], DS[MANCINi-SW.mancini.com - Traffic - 192.168.1.253 - Vl1] Graphs[MANCINi-SW.mancini.com - Traffic - 192.168.1.253 (Vlan1)], Rule[interfaces]
--
2020/03/14 14:27:10 - AUTOM8 NOTE: Graph Added - Device[MANCINi-SW.mancini.com], Graph[MANCINi-SW.mancini.com - Traffic - Null0/27], DS[MANCINi-SW.mancini.com - Traffic - Nu0] Graphs[MANCINi-SW.mancini.com - Traffic - Null0/27], Rule[interfaces]
2020/03/14 14:27:10 - AUTOM8 NOTE: Graph Added - Device[MANCINi-SW.mancini.com], Graph[MANCINi-SW.mancini.com - Traffic - FastEthernet0/23/23], DS[MANCINi-SW.mancini.com - Traffic - Fa0/23] Graphs[MANCINi-SW.mancini.com - Traffic - FastEthernet0/23/23], Rule[interfaces]
2020/03/14 14:27:10 - AUTOM8 NOTE: Graph Added - Device[MANCINi-SW.mancini.com], Graph[MANCINi-SW.mancini.com - Traffic - gibson], DS[MANCINi-SW.mancini.com - Traffic - Fa0/22] Graphs[MANCINi-SW.mancini.com - Traffic - gibson], Rule[interfaces]
2020/03/14 14:27:09 - AUTOM8 NOTE: Graph Added - Device[MANCINi-SW.mancini.com], Graph[MANCINi-SW.mancini.com - Traffic - HOME-MONITORING], DS[MANCINi-SW.mancini.com - Traffic - Fa0/15] Graphs[MANCINi-SW.mancini.com - Traffic - HOME-MONITORING], Rule[interfaces]
2020/03/14 14:27:09 - AUTOM8 NOTE: Graph Added - Device[MANCINi-SW.mancini.com], Graph[MANCINi-SW.mancini.com - Traffic - WAN], DS[MANCINi-SW.mancini.com - Traffic - Fa0/1] Graphs[MANCINi-SW.mancini.com - Traffic - WAN], Rule[interfaces]

**Comment by bmfmancini** [comment] 2020-03-14 19:28
BTW I am using 1.2.10

**Comment by bmfmancini** [comment] 2020-03-14 19:41
Here is the output on the remote collector 

+----+----------------------------------+--------------------------------------------------+-----------------------------+-----------------------------------------------------+-------------------+---------------+----------------+
| id | hash                             | xml_path                                         | name                        | description                                         | graph_template_id | data_input_id | reindex_method |
+----+----------------------------------+--------------------------------------------------+-----------------------------+-----------------------------------------------------+-------------------+---------------+----------------+
|  1 | d75e406fdeca4fcef45b8be3a9a63cbc | <path_cacti>/resource/snmp_queries/interface.xml | SNMP - Interface Statistics | Queries a host for a list of monitorable interfaces |                 0 |             2 |              1 |
+----+----------------------------------+--------------------------------------------------+-----------------------------+-----------------------------------------------------+-------------------+---------------+----------------+
1 row in set (0.00 sec)

MariaDB [cacti]>

**Comment by bmfmancini** [comment] 2020-03-14 19:44
I forgot to run the host_snmp_cache check first let me delete the device and re-add it

**Comment by bmfmancini** [comment] 2020-03-14 19:51
Here is the host_snmp_cache output on the main poller

+----+----------------------------------+--------------------------------------------------+-----------------------------+-----------------------------------------------------+-------------------+---------------+----------------+
| id | hash                             | xml_path                                         | name                        | description                                         | graph_template_id | data_input_id | reindex_method |
+----+----------------------------------+--------------------------------------------------+-----------------------------+-----------------------------------------------------+-------------------+---------------+----------------+
|  1 | d75e406fdeca4fcef45b8be3a9a63cbc | <path_cacti>/resource/snmp_queries/interface.xml | SNMP - Interface Statistics | Queries a host for a list of monitorable interfaces |                 0 |             2 |              1 |
+----+----------------------------------+--------------------------------------------------+-----------------------------+-----------------------------------------------------+-------------------+---------------+----------------+
1 row in set (0.00 sec)

MariaDB [cacti]>

**Comment by bmfmancini** [comment] 2020-03-14 19:52
Here it is on the remote poller 


MariaDB [cacti]> select * from host_snmp_cache where host_id = '5' LIMIT 10;
Empty set (0.00 sec)

**Comment by TheWitness** [comment] 2020-03-14 20:08
Ah, that's interesting.

**Comment by TheWitness** [comment] 2020-03-14 20:47
Okay, I just made an update, there are three files.  lib/data_query.php, lib/poller.php, poller_recovery.php.  I'm kind of guessing at this one.  Update, and then rerun the test.

**Comment by TheWitness** [comment] 2020-03-14 20:48
I closed the other ticket.

**Comment by bmfmancini** [comment] 2020-03-14 21:21
Cool let me test and let you know

**Comment by bmfmancini** [comment] 2020-03-14 21:49
grabbed the new files from the 1.2.x branch
No go so far

**Comment by TheWitness** [comment] 2020-03-15 18:08
This is fixed now.  It turns out it was disabled by design.  I've done some testing and it works just fine.  So, now everything should work.  Make sure you run a full sync before testing.  I don't think it'll make a difference, but do it anyway.

**Comment by eschoeller** [comment] 2020-03-15 18:36
Hey there! Sorry I haven’t had a chance to catch up on this ... but I’ve got a lot of free time ahead so stay tuned! 

Eric.

**Comment by TheWitness** [comment] 2020-03-15 19:46
Sure @eschoeller.  Welcome back.  We are all at home for the Karachi marathon.  Stay well.

**Comment by bmfmancini** [comment] 2020-03-15 20:47
Awsome! works great 

Thanks !!

**Comment by TheWitness** [comment] 2020-03-16 22:53
Thanks for the heads up.

**Closed** 2020-03-16 22:53 UTC
Labels: bug, resolved

**Comment by bmfmancini** [comment] 2020-03-26 18:09
Hey @TheWitness  I found an issue 

Got some errors spitting out while running automation I didn't notice them before 

ERROR PHP ERROR: Uncaught Error: Call to undefined function poller_push_reindex_data_to_main() in /var/www/html/cacti/lib/data_query.php:385

**Comment by bmfmancini** [comment] 2020-03-26 18:09
when I revert the files back from backup everything works fine

**Comment by bmfmancini** [comment] 2020-03-26 18:17
nevermind I forgot to grab the new data_query.php
