### ISSUE TITLE
[1.2.20] - Ping Latency has hostname override enabled by default 

### ISSUE THREAD

**Issue by seanmancini** [Cacti/cacti#4648] opened 2022-03-28 18:48 UTC
On a fresh install of 1.2.20, I noticed that when adding the UNIX ping host graph template to a host that automation would error 
Looking into this further I found that the hostname override is enabled by default with no default value

Errors

```
2022-03-28 14:11:24 - AUTOM8 NOTE: Device[a.b.c.d], GT[PING - Advanced Ping] Graph not added due to no default value for overridable field.

```

the template looks like this by default

![image](https://user-images.githubusercontent.com/69045419/160466058-6c375959-ee91-467b-ac53-ef56ad02aa2a.png)

Turning off the hostname override fixes the issue

**Comment by netniV** [comment] 2022-03-29 09:36
You removed the ping template from the PR, was that by design?

**Comment by TheWitness** [comment] 2022-03-29 10:21
The error is a bug as it's a special type code and takes the hostname by default.

So, the behavior is an unchecked case.

CASE:  By default, take the hostname, but don't prevent the user from changing it.

Seems I missed that case. So, it's not the package, it's the logic behind the scenes.

**Comment by TheWitness** [comment] 2022-03-29 11:49
Duplicate of #4649

**Closed by TheWitness** 2022-03-29 11:49 UTC
Labels: bug, unverified
