### ISSUE TITLE
[1.3 QA] -  Poller maintenance SQL issue

### ISSUE THREAD

**Issue by seanmancini** [Cacti/cacti#5600] opened 2023-11-28 15:34 UTC
After Install you see the following  errors

<html><body>

2023-11-28 10:33:12 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'graphs' in 'field list'
--
2023-11-28 10:33:12 - SQL Backtrace:   (/poller_maintenance.php[127]:update_graphs_data_source_templates_totals(),  /poller_maintenance.php[166]:object_cache_update_graph_totals(),  /lib/utility.php[2865]:db_execute_prepared())
2023-11-28 10:33:12 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'graphs' in 'field list'
2023-11-28 10:33:12 - SQL Backtrace:   (/poller_maintenance.php[127]:update_graphs_data_source_templates_totals(),  /poller_maintenance.php[166]:object_cache_update_graph_totals(),  /lib/utility.php[2865]:db_execute_prepared())
2023-11-28 10:33:12 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'graphs' in 'field list'
2023-11-28 10:33:12 - SQL Backtrace:   (/poller_maintenance.php[127]:update_graphs_data_source_templates_totals(),  /poller_maintenance.php[166]:object_cache_update_graph_totals(),  /lib/utility.php[2865]:db_execute_prepared())
2023-11-28 10:33:12 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'graphs' in 'field list'
2023-11-28 10:33:12 - SQL Backtrace:   (/poller_maintenance.php[127]:update_graphs_data_source_templates_totals(),  /poller_maintenance.php[166]:object_cache_update_graph_totals(),  /lib/utility.php[2865]:db_execute_prepared())

</body>
</html>

**Comment by TheWitness** [comment] 2023-11-28 21:56
This was fixed in the maintenance develop branch a few days ago by @xmacan

**Comment by bmfmancini** [comment] 2023-11-28 22:14
Oh shoot I missed that ok let me check

**Comment by xmacan** [comment] 2023-11-29 08:46
No, I fixed something else (ambiguous columns). Cannot reproduce this but problem is with your database. @bmfmancini please show "show create table colors;" It seems that you missing columns graphs and templates. 
These columns are in cacti.sql. Fresh install works well. Did you do update from older 1.3.0?

**Comment by TheWitness** [comment] 2023-12-02 13:39
Run the `audit_database.php --report` too.

**Comment by TheWitness** [comment] 2023-12-02 14:37
Okay, just reproduced this.  Fixing it shortly.

**Closed** 2023-12-02 14:42 UTC
Labels: bug, resolved, confirmed, QA, type:bug, status:confirmed
