### ISSUE TITLE
Re-Index Method not maintained after migration from 8.8h to 1.1.36

### ISSUE THREAD

**Issue by DigitalPackrat** [Cacti/cacti#1449] opened 2018-03-06 05:14 UTC
After migration from 8.8h to a new server running 1.1.36 Re-Index Method was not functioning properly for devices with the Win32 Monitor Running Processes script https://forums.cacti.net/about6661.html.

For this script, index value in the data source is changed to the process.exe and Index Type set to hrSWRunName. In the device, Re-Index Method is changed from Uptime to Index Count.

After migration to 1.1.36 the data query was not being re indexed causing the graph to not populate and a U message in the log if the monitored device was restarted and the process.exe pid changed. The original 8.8h install was running at the same time on the old server and had no issue.

On the 1.1.36 server running a Verbose Query under the device Data Query Name would temporary allow the graph to populate until the monitored device was restarted again.

Changing the Re-Index Method to Verify All under device worked even with the monitored device restarted.

Changing the Re-Index Method back to Index Count from Verify All on the monitored device also works after the device is restarted.

Index Count is the option selected on the 8.8h server and showed selected on 1.1.36 server.

I have verified on over 30 devices that Index Count was selected in 1.1.36 but not re indexing until the option was changed to Verify All then back to Index Count.

Its not an issue for me anymore but a minor bug for migration for other people.

**Comment by netniV** [comment] 2018-03-06 07:01
It's a shame that you have now moved all the devices over because it would have been useful to see what the state was in the database against a device that was exhibiting the problem.  I would say it sounds like it could be a default value issue, but the default is Uptime so in order to be displaying "Index Count" generally means that the value in the database must be the value for Index Count.

**Comment by cigamit** [comment] 2018-03-09 01:43
We did not change the re-index method in the upgrade process.  Have you enabled automation on the networks that hold these devices?

**Comment by JSchuricht** [comment] 2018-03-09 20:44
There is no automation yet. This was an issue right after migration from 8.8h to 1.1.36 before I had a chance to change anything.

**Comment by DigitalPackrat** [comment] 2018-03-09 20:47
There is no automation yet. This was an issue right after migration from 8.8h to 1.1.36 before I had a chance to change anything.

**Comment by cigamit** [comment] 2018-03-11 18:14
Okay, well this is the first we have heard of this issue, and the upgrade does not touch this table.  So, I think we will just close it for now unless you can find some way to consistently reproduce it.  If so, open a new ticket.

**Closed by cigamit** 2018-03-11 18:14 UTC
Labels: unverified
