### ISSUE TITLE
Totals in Aggregate graphs

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#69] opened 2016-10-26 14:58 UTC
I am unable to get totals to display on any of the aggregate graphs I am creating with the latest dev branch. Switching between "Total All Data Sources" and "Total Similar Data Sources" has no effect, neither are showing totals.

**Comment by smiles1969** [comment] 2016-11-22 19:08
Some of my older aggregate graphs are still showing totals, but none of the newly created ones will.

**Comment by cigamit** [comment] 2016-11-23 00:48
The last batch of patches should help the problem.  Just re-edit the Aggregate Template and 'Save' it.  Let us know if this fixes the problem.

**Comment by smiles1969** [comment] 2016-11-23 16:15
Still having the same issues with totaling and color templates being applied.

I've also noticed strange behavior when I click on save from the Management->Aggregates form. It says "save successful" within a second or two, then a few seconds later, it says "save successful" again.

**Comment by cigamit** [comment] 2016-12-14 05:04
806d61a34345675138f8aa1ea99d09b456680d97
This should fix the double saving.  Totaling seems to be working for me without any issues, as are applying color templates.  I will play around some more to see if I can reproduce it.

**Comment by cigamit** [comment] 2016-12-14 05:59
A few more minor fixes tonight.  Creating aggregates without a template is still majorly broken, but I will work through more of the issues tomorrow.

**Comment by smiles1969** [comment] 2016-12-14 16:02
Double saving is fixed. Still seeing issues with totaling and color templates on some agg graphs. I'd be happy to share my console if you can not reproduce.

**Comment by cigamit** [comment] 2016-12-18 22:30
You may have to resave the templates to fix the graphs.  Do that with the latest build and let us know if the issue is resolved.  If the issue is not resolved, we will need some examples including screen capture of template edit, the graph, and the graph preview.

**Comment by cigamit** [comment] 2016-12-20 13:18
Closing due to no feedback.  If you find that this issue continues after re-saving your template, please open a new issue.

**Closed by cigamit** 2016-12-20 13:18 UTC
