### ISSUE TITLE
Boost debug log not functional

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#1606] opened 2018-05-05 00:26 UTC
I have enabled a boost debug log in the configuration, but the log is always empty. I just ran the poller_boost by hand (to address a separate problem) and saw plenty of output and errors that I would have liked to see in the boost output log. Does anyone have this log working? What problem could I be encountering where my log is always empty?

**Comment by netniV** [comment] 2018-05-05 15:33
The boost log contains the console output from poller_boost.php as long as it's been set.  So things like warnings or notices that would display if run from command line would appear there.  Anywhere that boost expects to record things, it would be in the cacti.log file.

**Comment by eschoeller** [comment] 2018-05-06 05:55
I have it defined:
<pre>
mysql> select * from settings where name like '%path_boost_log%';
+----------------+--------------------------+
| name           | value                    |
+----------------+--------------------------+
| path_boost_log | /var/log/cacti/boost.log |
+----------------+--------------------------+
1 row in set (0.00 sec)
</pre>

And I have it writable/owned by the correct user:
<pre>
/cacti> ls -la /var/log/cacti/boost.log
-rw-r--r-- 1 apache apache 0 Apr 29 03:50 /var/log/cacti/boost.log
</pre>

**Comment by cigamit** [comment] 2018-05-08 11:32
Well that is wrong.  It's likely due to some changes that were made some time ago to support the rrdproxy which did break a few things as it merged some of the boost rrdfunctions into the base.

**Comment by eschoeller** [comment] 2018-05-08 13:03
Not sure, any ideas to keep troubleshooting? Running poller_boost from the command line produces plenty of output but I never see any of it in the log file

**Comment by cigamit** [comment] 2018-05-10 02:08
I'll leave open for now.  Hate these little regressions.

**Comment by cigamit** [comment] 2018-05-10 12:57
I just reviewed the code.  The debug log will be written for major sweeps of the poller_output_boost table and not the individual browser transactions.  This I believe is as designed behavior at this point.  I don't want to mess with the individual update transactions at this point.

**Comment by eschoeller** [comment] 2018-05-10 16:44
Well I guess I don't understand your comment entirely. It seems like there is really useful output (which I would consider "debug") from poller_boost.php. I would expect this output to go into boost.log, but it doesn't. Can it be redirected somewhere else if boost.log isn't the right place for it?

**Comment by cigamit** [comment] 2018-05-10 22:39
Hmm.  Going to test then.  Weird.

**Comment by cigamit** [comment] 2018-05-10 23:10
Okay, resolved now.

**Closed by cigamit** 2018-05-10 23:10 UTC
Labels: boost

**Comment by eschoeller** [comment] 2018-05-11 04:37
Well, I did my best to snag the files I needed to get this commit, and now I see an "s" in the boost.log each time it runs. But that's it. I also recall seeing an "s" each time I ran the poller_boost.php from the command line.

**Comment by netniV** [comment] 2018-05-11 18:36
It's an S for Schoeller ;-)

**Comment by eschoeller** [comment] 2018-05-11 21:32
lol
