### ISSUE TITLE
When the Data Template contains more Data Sources than the Graph Template RRDfiles won't update

### ISSUE THREAD

**Issue by WirthmU** [Cacti/cacti#5259] opened 2023-03-06 10:37 UTC
I am using a perl script for data input which works perfectly fine. If there is only one item in the ds it is working, If I add more than one item rrd is no longer updated.

If the data template consists of only the temperature it is working. If the data template contains two or more items it is no longer functioning. All values in the ds file and temperature graph are NaN.

## To Reproduce

perl script:
`sudo perl /usr/share/cacti/site/scripts/fhem-getstate.pl -s 'localhost' -d 'uRadMonitor_AC3' 
01_altitude:600.26 01_ch2o:10 01_co2:458 01_cpm:18 01_duty:180 01_humidity:56.01 01_latitude:46.9167 01_longitude:7.4667 01_noise:42 01_pm25:55 01_pressure:94320 01_temperature:17.43 01_time:1678098947 01_timelocal:965700 01_voc:484736 01_voltage:382 
`
## Expected behavior

The different parameters in the ds should be available for graphing. For now I only can do this if the ds contains just one parameter

## Screenshots
Working:
![image](https://user-images.githubusercontent.com/27740335/223088458-c7be7f5f-d42f-4437-8cdb-c4965edcf74c.png)

Not working:
![image](https://user-images.githubusercontent.com/27740335/223088699-082cf7d0-59a7-4587-9412-7721b9039f8a.png)

## Desktop (please complete the following information)

- OS: ubuntu

- Browser firefox

- cacti Version 1.2.24

## Additional context

![image](https://user-images.githubusercontent.com/27740335/223167670-910d2931-62b4-44fe-9c02-db77357a38a1.png)

**Comment by TheWitness** [comment] 2023-03-07 02:19
If using spine, you have to output the entire output in one print.  If you are using multiple print's inside the script, it will fail.  This is a known and documented behavior of spine.

**Comment by WirthmU** [comment] 2023-03-07 08:36
This is the script I am using:

`#!/usr/bin/perl -w
#
# fhem-getstate.pl script for reading / writing FHEM values
# Copyright (C) 2009 Martin Fischer <m_fischer@gmx.de>. All rights reserved.
#
# License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This source is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

use Getopt::Std;
use IO::Socket;
use strict;

use vars qw{%opt};
use vars qw{$host};
use vars qw{$port};

sub usage;
sub longhelp;
sub version;

$host = "localhost";
$port = "7072";

main();
exit;

sub main {
	getopts("s:p:d:hv",\%opt) or usage();
	longhelp() if $opt{h};
	version()  if $opt{v};

	my $device  = $opt{d};
	my $command = "getstate $device\n";
	my $result  = "";

	my $socket = new IO::Socket::INET("$host:$port") or die "Can't connect to $host:$port : $!\n";
	$socket->send($command);
	$result = <$socket>;
	$socket->close();

	print $result;
}

sub usage {
	print STDERR "Usage: fhem-getstate.pl [-s <server>] [-p <port>] -d <devspec> [-h] [-v]";
	exit;
}

sub longhelp {
	print STDERR << "EOF";
Usage: fhem-getstate.pl [OPTION] DEVICE

Connect to a FHEM-Server running on 'localhost 7072' and print the status for
the given DEVICE as a space seperated list for use in e.g. Cacti.

Mandatory arguments:
  -d DEVICE   print the status for DEVICE as defined in FHEM

Optional:
  -s SERVER   Resolvable Hostname or IP address of FHEM (default: localhost)
  -p PORT     Listening Port of FHEM (default: 7072)
  -q          quiet mode
  -h          show this help
  -v          show version

Reports bugs to <m_fischer\@gmx.de>.
EOF
	exit;
}

sub version {
	print STDERR << "EOF";
fhem-getstate.pl, Version 1.0
Copyright (C) 2009 Martin Fischer <m_fischer\@gmx.de>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Martin Fischer
EOF
	exit;
}
`

How would I change it to use it with spine? What would be the output sequence with just one single print look like?

**Comment by TheWitness** [comment] 2023-03-07 13:26
This should work.  Post a screen shot of your Data Template and Data Input Method, or simply export your Graph Template and post the XML here GZIPed of course.

**Comment by WirthmU** [comment] 2023-03-08 09:39
Here are the screenshots:


Graph template working:
/home/uw/Downloads/cacti_data_template_uradmonitor_nn.xml
/home/uw/Downloads/cacti_data_template_uradmonitor_n.xml
/home/uw/Downloads/cacti_graph_template_fhem_uradmonitor_temperature_template.xml
/home/uw/Downloads/cacti_graph_template_fhem_uradmonitor_humidity_template.xml

**Comment by TheWitness** [comment] 2023-03-08 23:46
Can you enable boost and then collect about 30 minutes of data and then query the poller_output_boost table for the local_data_id?  Send the output:

```sql
SELECT * FROM poller_output_boost
WHERE local_data_id = ?
```

**Comment by TheWitness** [comment] 2023-03-09 00:23
Last thing, turn logging to HIGH for one poller cycle and review the Cacti log for your Data Sources.  You should be able to search for `[map` and find what you are looking for.

**Comment by WirthmU** [comment] 2023-03-13 09:03
I think I did enable boost but the query did not give anything:

```
MariaDB [cacti]> SELECT * FROM poller_output_boost WHERE local_data_id = ?
    -> 
```


![image](https://user-images.githubusercontent.com/27740335/224654494-998d9916-f9e8-4ff6-9cb3-378ca67cb0ae.png)

**Comment by WirthmU** [comment] 2023-03-13 09:07
I did set logging to high but I cannot search for [map

![image](https://user-images.githubusercontent.com/27740335/224655836-37d13783-4a98-4796-ba5b-310e28a64d85.png)

**Comment by TheWitness** [comment] 2023-03-13 11:47
You have to put a backslash in front of the square bracket.

**Comment by WirthmU** [comment] 2023-03-13 12:31
It looks like both DS are ok:

Temperature:
```
13-03-2023 13:29:05 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_temperature:18.21' [map 01_temperature->temperature]
13-03-2023 13:29:05 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_temperature:18.21' [map 01_temperature->temperature]
13-03-2023 13:29:04 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_temperature:25.91' [map 01_temperature->temperature]
13-03-2023 13:28:08 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_temperature:25.91' [map 01_temperature->temperature]
13-03-2023 13:28:08 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_temperature:18.21' [map 01_temperature->temperature]
13-03-2023 13:28:08 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_temperature:18.21' [map 01_temperature->temperature]
13-03-2023 13:27:07 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_temperature:18.21' [map 01_temperature->temperature]
13-03-2023 13:27:07 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_temperature:18.21' [map 01_temperature->temperature]
13-03-2023 13:27:03 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_temperature:25.91' [map 01_temperature->temperature]
13-03-2023 13:26:05 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_temperature:18.21' [map 01_temperature->temperature]
13-03-2023 13:26:05 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_temperature:18.21' [map 01_temperature->temperature]
13-03-2023 13:26:04 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_temperature:25.91' [map 01_temperature->temperature]
13-03-2023 13:25:06 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_temperature:18.21' [map 01_temperature->temperature] 
```

Humidity:
```
13-03-2023 13:27:03 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_humidity:34.76' [map 01_humidity->humidity]
13-03-2023 13:26:04 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_humidity:34.76' [map 01_humidity->humidity]
13-03-2023 13:25:03 - POLLER: Poller[Main Poller] PID[569427] Parsed MULTI output field '01_humidity:34.76' [map 01_humidity->humidity]
13-03-2023 13:24:07 - POLLER: Poller[Main Poller] PID[556603] Parsed MULTI output field '01_humidity:34.76' [map 01_humidity->humidity]
13-03-2023 13:23:05 - POLLER: Poller[Main Poller] PID[556603] Parsed MULTI output field '01_humidity:34.76' [map 01_humidity->humidity]
13-03-2023 13:22:05 - POLLER: Poller[Main Poller] PID[556603] Parsed MULTI output field '01_humidity:34.76' [map 01_humidity->humidity]
13-03-2023 13:21:04 - POLLER: Poller[Main Poller] PID[556603] Parsed MULTI output field '01_humidity:34.76' [map 01_humidity->humidity]
13-03-2023 13:20:04 - POLLER: Poller[Main Poller] PID[556603] Parsed MULTI output field '01_humidity:34.76' [map 01_humidity->humidity] 
```

But as I said only the DS with one single parameter is graphing. The one with two is not.

**Comment by TheWitness** [comment] 2023-03-13 13:31
Are you seeing any "[map" for those data sources?

**Comment by TheWitness** [comment] 2023-03-13 13:32
Next thing to do is to put the one of the devices into debug mode, put the general debug level to LOW, and then look at the output generated by the poller for that specific device.

**Comment by WirthmU** [comment] 2023-03-13 13:56
How do I put a device into debug mode?

**Comment by TheWitness** [comment] 2023-03-13 14:00
Edit the device and you will find a link in upper right hand corner.

**Comment by WirthmU** [comment] 2023-03-13 14:01
I found it:
![image](https://user-images.githubusercontent.com/27740335/224724090-59e23d59-4bf3-40bf-a33f-1614f4ce2ff0.png)
But where do I set the general debug level to LOW

**Comment by bmfmancini** [comment] 2023-03-13 14:12
Console >> configuration >> settings

**Comment by WirthmU** [comment] 2023-03-14 10:54
This is the output of the DS which is not working:

```
2023-03-14 11:43:04 - SPINE: Poller[Main Poller] PID[3109035] PT[140320218428992] Device[uRadMonitor Industrial] HT[1] DS[uRadMonitor_NN] Graphs[FHEM uRadMonitor Humidity] TT[107.67] SCRIPT: perl /usr/share/cacti/site/scripts/fhem-getstate.pl -s 'localhost' -d 'uRadMonitor_Industrial', output: 01_altitude:576 01_gas1:0.22 01_gas2:0.09 01_gas3:0.1 01_gas4:1.6 01_humidity:34.76 01_latitude:46.9167 01_longitude:7.4667 01_noise:37.54 01_pm1:0 01_pm10:0 01_pm25:3.35 01_pressure:94499 01_temperature:25.91 01_time:1678555340 01_timelocal:46800 01_voc:607187
2023-03-14 11:42:03 - SPINE: Poller[Main Poller] PID[3105925] PT[140436584072768] Device[uRadMonitor Industrial] HT[1] DS[uRadMonitor_NN] Graphs[FHEM uRadMonitor Humidity] TT[88.75] SCRIPT: perl /usr/share/cacti/site/scripts/fhem-getstate.pl -s 'localhost' -d 'uRadMonitor_Industrial', output: 01_altitude:576 01_gas1:0.22 01_gas2:0.09 01_gas3:0.1 01_gas4:1.6 01_humidity:34.76 01_latitude:46.9167 01_longitude:7.4667 01_noise:37.54 01_pm1:0 01_pm10:0 01_pm25:3.35 01_pressure:94499 01_temperature:25.91 01_time:1678555340 01_timelocal:46800 01_voc:607187
14-03-2023 11:41:58 - WEBLOG CACTI2RRD: /usr/bin/rrdtool graph /tmp/cacti-ftp-temp-1/graphs/graph_1003_17.png --imgformat=PNG --start='1647254458' --end='1678790458' --pango-markup --title='FHEM uRadMonitor Humidity' --vertical-label='Relative Humidity (%)' --slope-mode --base=1000 --height=200 --width=700 --alt-autoscale COMMENT:"From 14-03-2022 11\:40\:58 To 14-03-2023 11\:40\:58\c" COMMENT:" \n" --color BACK#F3F3F3 --color CANVAS#FDFDFD --color SHADEA#CBCBCB --color SHADEB#999999 --color FONT#000000 --color AXIS#2C4D43 --color ARROW#2C4D43 --color FRAME#2C4D43 --border 1 --font TITLE:11:'Arial' --font AXIS:8:'Arial' --font LEGEND:8:'Courier' --font UNIT:8:'Arial' --font WATERMARK:6:'Arial' --slope-mode --watermark 'Generated by Cacti®' DEF:a='/usr/share/cacti/site/rra/uradmonitor_industrial_temperature_1345.rrd':'humidity':AVERAGE COMMENT:'\t\t\t Current\t\tMinimum\t\t Average\t\t Maximum\n' COMMENT:' \n' COMMENT:'-------------------------------------------------------------------------------\n' LINE1:a#00DAFFFF:'AC3' GPRINT:a:LAST:' \t %8.2lf%s' GPRINT:a:MIN:' \t%12.2lf' GPRINT:a:AVERAGE:' \t%12.2lf' GPRINT:a:MAX:' \t%12.2lf\n'
14-03-2023 11:41:58 - WEBLOG CACTI2RRD: /usr/bin/rrdtool graph /tmp/cacti-ftp-temp-1/graphs/graph_1003_16.png --imgformat=PNG --start='1676171674' --end='1678790458' --pango-markup --title='FHEM uRadMonitor Humidity' --vertical-label='Relative Humidity (%)' --slope-mode --base=1000 --height=200 --width=700 --alt-autoscale COMMENT:"From 12-02-2023 04\:14\:34 To 14-03-2023 11\:40\:58\c" COMMENT:" \n" --color BACK#F3F3F3 --color CANVAS#FDFDFD --color SHADEA#CBCBCB --color SHADEB#999999 --color FONT#000000 --color AXIS#2C4D43 --color ARROW#2C4D43 --color FRAME#2C4D43 --border 1 --font TITLE:11:'Arial' --font AXIS:8:'Arial' --font LEGEND:8:'Courier' --font UNIT:8:'Arial' --font WATERMARK:6:'Arial' --slope-mode --watermark 'Generated by Cacti®' DEF:a='/usr/share/cacti/site/rra/uradmonitor_industrial_temperature_1345.rrd':'humidity':AVERAGE COMMENT:'\t\t\t Current\t\tMinimum\t\t Average\t\t Maximum\n' COMMENT:' \n' COMMENT:'-------------------------------------------------------------------------------\n' LINE1:a#00DAFFFF:'AC3' GPRINT:a:LAST:' \t %8.2lf%s' GPRINT:a:MIN:' \t%12.2lf' GPRINT:a:AVERAGE:' \t%12.2lf' GPRINT:a:MAX:' \t%12.2lf\n'
14-03-2023 11:41:58 - WEBLOG CACTI2RRD: /usr/bin/rrdtool graph /tmp/cacti-ftp-temp-1/graphs/graph_1003_15.png --imgformat=PNG --start='1678185658' --end='1678790458' --pango-markup --title='FHEM uRadMonitor Humidity' --vertical-label='Relative Humidity (%)' --slope-mode --base=1000 --height=200 --width=700 --alt-autoscale COMMENT:"From 07-03-2023 11\:40\:58 To 14-03-2023 11\:40\:58\c" COMMENT:" \n" --color BACK#F3F3F3 --color CANVAS#FDFDFD --color SHADEA#CBCBCB --color SHADEB#999999 --color FONT#000000 --color AXIS#2C4D43 --color ARROW#2C4D43 --color FRAME#2C4D43 --border 1 --font TITLE:11:'Arial' --font AXIS:8:'Arial' --font LEGEND:8:'Courier' --font UNIT:8:'Arial' --font WATERMARK:6:'Arial' --slope-mode --watermark 'Generated by Cacti®' DEF:a='/usr/share/cacti/site/rra/uradmonitor_industrial_temperature_1345.rrd':'humidity':AVERAGE COMMENT:'\t\t\t Current\t\tMinimum\t\t Average\t\t Maximum\n' COMMENT:' \n' COMMENT:'-------------------------------------------------------------------------------\n' LINE1:a#00DAFFFF:'AC3' GPRINT:a:LAST:' \t %8.2lf%s' GPRINT:a:MIN:' \t%12.2lf' GPRINT:a:AVERAGE:' \t%12.2lf' GPRINT:a:MAX:' \t%12.2lf\n'
14-03-2023 11:41:58 - WEBLOG CACTI2RRD: /usr/bin/rrdtool graph /tmp/cacti-ftp-temp-1/graphs/graph_1003_14.png --imgformat=PNG --start='1678704058' --end='1678790458' --pango-markup --title='FHEM uRadMonitor Humidity' --vertical-label='Relative Humidity (%)' --slope-mode --base=1000 --height=200 --width=700 --alt-autoscale COMMENT:"From 13-03-2023 11\:40\:58 To 14-03-2023 11\:40\:58\c" COMMENT:" \n" --color BACK#F3F3F3 --color CANVAS#FDFDFD --color SHADEA#CBCBCB --color SHADEB#999999 --color FONT#000000 --color AXIS#2C4D43 --color ARROW#2C4D43 --color FRAME#2C4D43 --border 1 --font TITLE:11:'Arial' --font AXIS:8:'Arial' --font LEGEND:8:'Courier' --font UNIT:8:'Arial' --font WATERMARK:6:'Arial' --slope-mode --watermark 'Generated by Cacti®' DEF:a='/usr/share/cacti/site/rra/uradmonitor_industrial_temperature_1345.rrd':'humidity':AVERAGE COMMENT:'\t\t\t Current\t\tMinimum\t\t Average\t\t Maximum\n' COMMENT:' \n' COMMENT:'-------------------------------------------------------------------------------\n' LINE1:a#00DAFFFF:'AC3' GPRINT:a:LAST:' \t %8.2lf%s' GPRINT:a:MIN:' \t%12.2lf' GPRINT:a:AVERAGE:' \t%12.2lf' GPRINT:a:MAX:' \t%12.2lf\n'
14-03-2023 11:41:58 - WEBLOG CACTI2RRD: /usr/bin/rrdtool graph /tmp/cacti-ftp-temp-1/graphs/graph_1003_13.png --imgformat=PNG --start='1678768858' --end='1678790458' --pango-markup --title='FHEM uRadMonitor Humidity' --vertical-label='Relative Humidity (%)' --slope-mode --base=1000 --height=200 --width=700 --alt-autoscale COMMENT:"From 14-03-2023 05\:40\:58 To 14-03-2023 11\:40\:58\c" COMMENT:" \n" --color BACK#F3F3F3 --color CANVAS#FDFDFD --color SHADEA#CBCBCB --color SHADEB#999999 --color FONT#000000 --color AXIS#2C4D43 --color ARROW#2C4D43 --color FRAME#2C4D43 --border 1 --font TITLE:11:'Arial' --font AXIS:8:'Arial' --font LEGEND:8:'Courier' --font UNIT:8:'Arial' --font WATERMARK:6:'Arial' --slope-mode --watermark 'Generated by Cacti®' DEF:a='/usr/share/cacti/site/rra/uradmonitor_industrial_temperature_1345.rrd':'humidity':AVERAGE COMMENT:'\t\t\t Current\t\tMinimum\t\t Average\t\t Maximum\n' COMMENT:' \n' COMMENT:'-------------------------------------------------------------------------------\n' LINE1:a#00DAFFFF:'AC3' GPRINT:a:LAST:' \t %8.2lf%s' GPRINT:a:MIN:' \t%12.2lf' GPRINT:a:AVERAGE:' \t%12.2lf' GPRINT:a:MAX:' \t%12.2lf\n'
14-03-2023 11:41:58 - WEBLOG CACTI2RRD: /usr/bin/rrdtool graph /tmp/cacti-ftp-temp-1/graphs/graph_1003.png --imgformat=PNG --start='-86400' --end='-300' --pango-markup --title='FHEM uRadMonitor Humidity' --vertical-label='Relative Humidity (%)' --slope-mode --base=1000 --height=200 --width=700 --alt-autoscale COMMENT:"From 13-03-2023 11\:41\:58 To 14-03-2023 11\:36\:58\c" COMMENT:" \n" --color BACK#F3F3F3 --color CANVAS#FDFDFD --color SHADEA#CBCBCB --color SHADEB#999999 --color FONT#000000 --color AXIS#2C4D43 --color ARROW#2C4D43 --color FRAME#2C4D43 --border 1 --font TITLE:11:'Arial' --font AXIS:8:'Arial' --font LEGEND:8:'Courier' --font UNIT:8:'Arial' --font WATERMARK:6:'Arial' --slope-mode --watermark 'Generated by Cacti®' DEF:a='/usr/share/cacti/site/rra/uradmonitor_industrial_temperature_1345.rrd':'humidity':AVERAGE COMMENT:'\t\t\t Current\t\tMinimum\t\t Average\t\t Maximum\n' COMMENT:' \n' COMMENT:'-------------------------------------------------------------------------------\n' LINE1:a#00DAFFFF:'AC3' GPRINT:a:LAST:' \t %8.2lf%s' GPRINT:a:MIN:' \t%12.2lf' GPRINT:a:AVERAGE:' \t%12.2lf' GPRINT:a:MAX:' \t%12.2lf\n'
14-03-2023 11:41:58 - WEBLOG CACTI2RRD: /usr/bin/rrdtool graph /tmp/cacti-ftp-temp-1/graphs/thumb_1003.png --imgformat=PNG --start='-86400' --end='-300' --pango-markup --title='FHEM uRadMonitor Humidity' --vertical-label='Relative Humidity (%)' --slope-mode --base=1000 --height=100 --width=300 --alt-autoscale --no-legend COMMENT:"From 13-03-2023 11\:41\:58 To 14-03-2023 11\:36\:58\c" COMMENT:" \n" --color BACK#F3F3F3 --color CANVAS#FDFDFD --color SHADEA#CBCBCB --color SHADEB#999999 --color FONT#000000 --color AXIS#2C4D43 --color ARROW#2C4D43 --color FRAME#2C4D43 --border 1 --font TITLE:7.7:'Arial' --font AXIS:8:'Arial' --font LEGEND:8:'Courier' --font UNIT:8:'Arial' --font WATERMARK:6:'Arial' --slope-mode --watermark 'Generated by Cacti®' DEF:a='/usr/share/cacti/site/rra/uradmonitor_industrial_temperature_1345.rrd':'humidity':AVERAGE LINE1:a#00DAFFFF: GPRINT:a:LAST:'%8.2lf%s' GPRINT:a:MIN:'%12.2lf' GPRINT:a:AVERAGE:'%12.2lf' GPRINT:a:MAX:'%12.2lf'
14-03-2023 11:41:58 - WEBLOG CACTI2RRD: /usr/bin/rrdtool info /usr/share/cacti/site/rra/uradmonitor_industrial_temperature_1345.rrd
14-03-2023 11:41:58 - BOOST CACTI2RRD: /usr/bin/rrdtool update /usr/share/cacti/site/rra/uradmonitor_industrial_temperature_1345.rrd --skip-past-updates --template humidity:temperature 1678789923:34.76:25.91 1678789982:34.76:25.91 1678790042:34.76:25.91 1678790102:34.76:25.91 1678790162:34.76:25.91 1678790223:34.76:25.91 1678790282:34.76:25.91 1678790342:34.76:25.91 1678790402:34.76:25.91 1678790462:34.76:25.91
14-03-2023 11:41:58 - BOOST The RRDpath is /usr/share/cacti/site/rra/uradmonitor_industrial_temperature_1345.rrd
2023-03-14 11:41:04 - SPINE: Poller[Main Poller] PID[3102260] PT[140382669989440] Device[uRadMonitor Industrial] HT[1] DS[uRadMonitor_NN] Graphs[FHEM uRadMonitor Humidity] TT[281.21] SCRIPT: perl /usr/share/cacti/site/scripts/fhem-getstate.pl -s 'localhost' -d 'uRadMonitor_Industrial', output: 01_altitude:576 01_gas1:0.22 01_gas2:0.09 01_gas3:0.1 01_gas4:1.6 01_humidity:34.76 01_latitude:46.9167 01_longitude:7.4667 01_noise:37.54 01_pm1:0 01_pm10:0 01_pm25:3.35 01_pressure:94499 01_temperature:25.91 01_time:1678555340 01_timelocal:46800 01_voc:607187
2023-03-14 11:40:06 - SPINE: Poller[Main Poller] PID[3099814] PT[140102253090368] Device[uRadMonitor Industrial] HT[1] DS[uRadMonitor_NN] Graphs[FHEM uRadMonitor Humidity] TT[68.81] SCRIPT: perl /usr/share/cacti/site/scripts/fhem-getstate.pl -s 'localhost' -d 'uRadMonitor_Industrial', output: 01_altitude:576 01_gas1:0.22 01_gas2:0.09 01_gas3:0.1 01_gas4:1.6 01_humidity:34.76 01_latitude:46.9167 01_longitude:7.4667 01_noise:37.54 01_pm1:0 01_pm10:0 01_pm25:3.35 01_pressure:94499 01_temperature:25.91 01_time:1678555340 01_timelocal:46800 01_voc:607187
2023-03-14 11:39:03 - SPINE: Poller[Main Poller] PID[3098570] PT[139958942598720] Device[uRadMonitor Industrial] HT[1] DS[uRadMonitor_NN] Graphs[FHEM uRadMonitor Humidity] TT[115.53] SCRIPT: perl /usr/share/cacti/site/scripts/fhem-getstate.pl -s 'localhost' -d 'uRadMonitor_Industrial', output: 01_altitude:576 01_gas1:0.22 01_gas2:0.09 01_gas3:0.1 01_gas4:1.6 01_humidity:34.76 01_latitude:46.9167 01_longitude:7.4667 01_noise:37.54 01_pm1:0 01_pm10:0 01_pm25:3.35 01_pressure:94499 01_temperature:25.91 01_time:1678555340 01_timelocal:46800 01_voc:607187
2023-03-14 11:38:06 - SPINE: Poller[Main Poller] PID[3097327] PT[140250663867968] Device[uRadMonitor Industrial] HT[1] DS[uRadMonitor_NN] Graphs[FHEM uRadMonitor Humidity] TT[66.33] SCRIPT: perl /usr/share/cacti/site/scripts/fhem-getstate.pl -s 'localhost' -d 'uRadMonitor_Industrial', output: 01_altitude:576 01_gas1:0.22 01_gas2:0.09 01_gas3:0.1 01_gas4:1.6 01_humidity:34.76 01_latitude:46.9167 01_longitude:7.4667 01_noise:37.54 01_pm1:0 01_pm10:0 01_pm25:3.35 01_pressure:94499 01_temperature:25.91 01_time:1678555340 01_timelocal:46800 01_voc:607187
2023-03-14 11:37:04 - SPINE: Poller[Main Poller] PID[3096119] PT[140046497384000] Device[uRadMonitor Industrial] HT[1] DS[uRadMonitor_NN] Graphs[FHEM uRadMonitor Humidity] TT[194.59] SCRIPT: perl /usr/share/cacti/site/scripts/fhem-getstate.pl -s 'localhost' -d 'uRadMonitor_Industrial', output: 01_altitude:576 01_gas1:0.22 01_gas2:0.09 01_gas3:0.1 01_gas4:1.6 01_humidity:34.76 01_latitude:46.9167 01_longitude:7.4667 01_noise:37.54 01_pm1:0 01_pm10:0 01_pm25:3.35 01_pressure:94499 01_temperature:25.91 01_time:1678555340 01_timelocal:46800 01_voc:607187
2023-03-14 11:36:03 - SPINE: Poller[Main Poller] PID[3094932] PT[139900721550912] Device[uRadMonitor Industrial] HT[1] DS[uRadMonitor_NN] Graphs[FHEM uRadMonitor Humidity] TT[68.50] SCRIPT: perl /usr/share/cacti/site/scripts/fhem-getstate.pl -s 'localhost' -d 'uRadMonitor_Industrial', output: 01_altitude:576 01_gas1:0.22 01_gas2:0.09 01_gas3:0.1 01_gas4:1.6 01_humidity:34.76 01_latitude:46.9167 01_longitude:7.4667 01_noise:37.54 01_pm1:0 01_pm10:0 01_pm25:3.35 01_pressure:94499 01_temperature:25.91 01_time:1678555340 01_timelocal:46800 01_voc:607187
2023-03-14 11:35:04 - SPINE: Poller[Main Poller] PID[3093721] PT[139843819296320] Device[uRadMonitor Industrial] HT[1] DS[uRadMonitor_NN] Graphs[FHEM uRadMonitor Humidity] TT[69.57] SCRIPT: perl /usr/share/cacti/site/scripts/fhem-getstate.pl -s 'localhost' -d 'uRadMonitor_Industrial', output: 01_altitude:576 01_gas1:0.22 01_gas2:0.09 01_gas3:0.1 01_gas4:1.6 01_humidity:34.76 01_latitude:46.9167 01_longitude:7.4667 01_noise:37.54 01_pm1:0 01_pm10:0 01_pm25:3.35 01_pressure:94499 01_temperature:25.91 01_time:1678555340 01_timelocal:46800 01_voc:607187
2023-03-14 11:34:05 - SPINE: Poller[Main Poller] PID[3092502] PT[140479837877824] Device[uRadMonitor Industrial] HT[1] DS[uRadMonitor_NN] Graphs[FHEM uRadMonitor Humidity] TT[99.23] SCRIPT: perl /usr/share/cacti/site/scripts/fhem-getstate.pl -s 'localhost' -d 'uRadMonitor_Industrial', output: 01_altitude:576 01_gas1:0.22 01_gas2:0.09 01_gas3:0.1 01_gas4:1.6 01_humidity:34.76 01_latitude:46.9167 01_longitude:7.4667 01_noise:37.54 01_pm1:0 01_pm10:0 01_pm25:3.35 01_pressure:94499 01_temperature:25.91 01_time:1678555340 01_timelocal:46800 01_voc:607187 
```

**Comment by TheWitness** [comment] 2023-03-14 11:46
Cool.  No map[ for those guys?

**Comment by WirthmU** [comment] 2023-03-14 12:50
Only what I have already listed above.

**Comment by TheWitness** [comment] 2023-03-14 13:04
You good for a quick zoom?

**Comment by WirthmU** [comment] 2023-03-14 13:44
Thats a good idea - maybe tomorrow?

**Comment by TheWitness** [comment] 2023-03-14 22:00
8:00 AM EST.  I'll be looking for your update to this ticket before starting it.

**Comment by WirthmU** [comment] 2023-03-15 08:13
This is fine with me.

**Comment by TheWitness** [comment] 2023-03-15 12:00
https://us06web.zoom.us/j/89950278384?pwd=Q3pjanlvdllkeldwa2FHV0xxWWNWZz09

**Comment by TheWitness** [comment] 2023-03-15 12:18
Run the following query replacing ? with the local_data_id:

```sql
SELECT dtr.data_source_name, dif.data_name
                                    FROM data_template_rrd AS dtr
                                    INNER JOIN data_input_fields AS dif
                                    ON dtr.data_input_field_id = dif.id
                                    WHERE dtr.local_data_id = ?
```

**Comment by TheWitness** [comment] 2023-03-15 14:06
Urs,

In `/use/share/cacti/site` revert the change.  So, add to the GROUP BY at the end `, dif.data_name`.  The query should look as follows:

```sql
INSERT IGNORE INTO poller_data_template_field_mappings
SELECT dtr.data_template_id, dif.data_name,
GROUP_CONCAT(dtr.data_source_name ORDER BY dtr.data_source_name) AS data_source_names, NOW()
FROM data_template_rrd AS dtr
INNER JOIN data_input_fields AS dif
ON dtr.data_input_field_id = dif.id
WHERE dtr.local_data_id = 0
GROUP BY dtr.data_template_id, dif.data_name
```

Then, manually run the TRUNCATE command:

```sql
TRUNCATE TABLE poller_data_template_field_mappings;
```

Then in `lib/poller.php`, in the block that we were working on change to the following:

```php
                            foreach($fields as $field) {
                                cacti_log("Parsed MULTI output field '" . $matches[0] . ':' . $matches[1] . "' [map " . $matches[0] . '->' . $field . ']' , true, 'POLLER', ($debug ? POLLER_VERBOSITY_NONE:POLLER_VERBOSITY_HIGH));
                                $rrd_update_array[$rrd_path]['times'][$unix_time][$field] = $matches[1];
                            }
```

Which was the original data.

In the end, the root cause of the issue is that the table "poller_data_template_field_mappings" in your case needed to simply be truncated.  You can do this on your own, or we can just follow the original plan.

**Comment by TheWitness** [comment] 2023-03-19 15:52
Urs, this is fixed now.  Just going to let it run a day or so on your system before closing.  Tested with boost on and off.

**Comment by TheWitness** [comment] 2023-03-23 01:17
@WirthmU, everything good on your end?

**Comment by WirthmU** [comment] 2023-03-23 11:27
I did let it run for a few days and it looks good. Also did create new graphs of the devices in question and this is working as well.

Thank you for your support!

**Closed** 2023-04-01 15:02 UTC
Labels: bug, resolved, confirmed
