### ISSUE TITLE
Cannot delete vdef and cdef item (in theme paw) - php error

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5006] opened 2022-11-14 20:22 UTC
Create new cdef or vdef, add any item and try to delete the item. I got:
(/vdef.php[75]:vdef_edit(),  /vdef.php[539]:get_filter_request_var(),  /lib/html_utility.php[493]:die_html_input_error(),  /lib/html_validate.php[64]:cacti_debug_backtrace())

(/cdef.php[85]:cdef_edit(),  /cdef.php[565]:get_filter_request_var(),  /lib/html_utility.php[493]:die_html_input_error(),  /lib/html_validate.php[64]:cacti_debug_backtrace())

It is connected with themes. With PAW I got error,in midwinter without error.

1.2.23

**Comment by TheWitness** [comment] 2022-11-16 00:37
I'm unable to reproduce.  Go to the Debug windows Network tab and show the post values.

**Comment by xmacan** [comment] 2022-11-16 15:08
![cacti_cdef](https://user-images.githubusercontent.com/26485719/202217706-bfae9499-2bf5-4716-8428-316dc0acae66.png)

**Comment by xmacan** [comment] 2022-11-16 15:19
Tested with firewfox and edge

**Comment by TheWitness** [comment] 2022-11-16 21:30
Highlight the POST and show the request subtab.

**Comment by xmacan** [comment] 2022-11-17 17:11
[17/Nov/2022:17:29:07 +0100] "GET /cdef.php?action=item_remove_confirm&id=106&cdef_id=205 HTTP/1.1" 200 3580
[17/Nov/2022:17:29:12 +0100] "POST /cdef.php?action=item_remove HTTP/1.1" 200 846
[17/Nov/2022:17:29:12 +0100] "GET /cdef.php?action=edit&header=false&id=t HTTP/1.1" 200 792

![post](https://user-images.githubusercontent.com/26485719/202512064-f89a528a-d7d2-4ca4-8d25-85040e9e35d5.png)

This?

**Comment by TheWitness** [comment] 2022-11-18 01:42
Can you capture me a `screen2gif` of this?  Those two post variables don't make sense.

**Comment by TheWitness** [comment] 2022-11-18 01:42
Wait, CDEF **ITEM** damn.  Wake me up.

**Comment by TheWitness** [comment] 2022-11-18 02:42
Fixed now.

**Closed** 2022-11-20 18:12 UTC
Labels: bug, resolved, unverified, confirmed
