### ISSUE TITLE
When i save, The style of PHP is missing

### ISSUE THREAD

**Issue by aliuzzz** [Cacti/cacti#5750] opened 2024-05-15 07:06 UTC
![image](https://github.com/Cacti/cacti/assets/43594093/62383767-09ef-426b-a342-cc5e2f3829ff)
when i save，The style of the page's PHP will be lost

![image](https://github.com/Cacti/cacti/assets/43594093/46be15e7-1440-4475-85cd-eca717fdf84e)

**Comment by aliuzzz** [comment] 2024-05-15 07:07
![image](https://github.com/Cacti/cacti/assets/43594093/fa0c4709-245a-4890-8a7d-1dec516c19da)
this page

**Comment by aliuzzz** [comment] 2024-05-15 07:09
Including creating new images, styles will also be lost after clicking on create      graphs_new.php

**Comment by xmacan** [comment] 2024-05-15 07:20
Cannot reproduce on actual 1.2.27? What cacti version?

**Comment by aliuzzz** [comment] 2024-05-15 09:20
rocky9.4+php8.2.13+cacti1.2.27+mariadb10.5.22+net-snmp5.9.1+httpd2.4.57

**Comment by aliuzzz** [comment] 2024-05-15 09:33
i this the question is here, "header=false" show be "header=true"
![image](https://github.com/Cacti/cacti/assets/43594093/70609f31-9744-4745-b06f-fa49493abb4a)

**Comment by xmacan** [comment] 2024-05-15 10:03
last screenshot has different url. Still cannot reproduce. Please describe all steps, something like:
1) go to templates -> graphs
2) choose any graph
3) click save...

**Comment by aliuzzz** [comment] 2024-05-16 01:18
Management-->Device-->Create Graphs for this Device-->Create graphs
After clicking Create, the image was successfully added, but the style was lost
![image](https://github.com/Cacti/cacti/assets/43594093/6367ccac-d3ca-4416-9d75-054b1cddbec7)

![image](https://github.com/Cacti/cacti/assets/43594093/ebbae85c-a763-4432-9a53-e72939e32861)

**Comment by aliuzzz** [comment] 2024-05-16 01:57
![image](https://github.com/Cacti/cacti/assets/43594093/254451dc-f9b4-42aa-a3b2-3a5f8add3431)
In version 1.2.26, this bug was not found after clicking "Create"

**Comment by xmacan** [comment] 2024-05-16 08:50
still cannot reproduce. Try clear browser cache, try another browser

**Comment by aliuzzz** [comment] 2024-05-17 07:51
I changed devices and browsers and the problem recurred.This problem occurs every time
Apache/2.4.57 +PHP 8.2.13 (cli)+mysql  Ver 15.1 Distrib 10.5.22-MariaDB+
NET-SNMP version:  5.9.1+RRDtool 1.8.0   

Maybe it has something to do with it?

**Comment by aliuzzz** [comment] 2024-05-17 07:53
Maybe I'm trying to use an older version of which file? For example graphs_new？

**Comment by TheWitness** [comment] 2024-05-17 10:50
Any JavaScript errors?  Where is header=true set?

**Comment by aliuzzz** [comment] 2024-05-18 01:31
I'm not sure, but the fact is that changing the header=false to true in the link can restore it. However, in version 1.2.26, when performing the above operation, the "header" will not be seen in the link

**Comment by TheWitness** [comment] 2024-05-18 13:05
Pull the latest graphs_new.php and see if it's reproducible.

**Comment by TheWitness** [comment] 2024-05-18 13:05
Are you using MacTrack also?

**Comment by aliuzzz** [comment] 2024-05-20 02:27
I did not use mactrack
I replaced the latest graphs new. php, but it did not fix this bug

But I found a problem, which occurs when I use Chinese as my GUI language. When using other languages (such as English and Spanish), it works fine

**Comment by aliuzzz** [comment] 2024-05-25 03:16
In Chinese language, it is also not possible to create aggregation templates

**Comment by TheWitness** [comment] 2024-05-25 11:29
Maybe that's the source of the issue.  Is it fine if English?

**Comment by aliuzzz** [comment] 2024-05-27 02:20
Yes,it is fine in English、French 、German， I'm curious, is this influenced by UTF-8?

**Comment by linqianye** [comment] 2024-06-07 02:50
It doesn't seem to solve the problem. In fact, after submitting data on any page that requires submission, the style will be lost. It seems to be a global setting issue.

**Comment by aliuzzz** [comment] 2024-06-11 01:19
Yes， It is a global setting issue.But in Chinese state, this issue does not exist.
I really hope the author will also consider Chinese users.
Here, Cacti is a widely recognized monitoring platform, which is why I have always insisted on using platforms such as Zabbix to replace Cacti

**Comment by TheWitness** [comment] 2024-06-11 09:46
Did you pull the latest graphs_new.php?

**Comment by aliuzzz** [comment] 2024-06-12 04:02
Yes, I download the latest graphs_new.php in version 1.2.x and i have restarted the system and services, but the issue has not been resolved in the Chinese environment.

**Comment by TheWitness** [comment] 2024-06-16 15:24
Show the latest URL that generates the error.

**Comment by aliuzzz** [comment] 2024-06-17 06:18
![image](https://github.com/Cacti/cacti/assets/43594093/20884d77-6d58-4407-b77d-43f2645b156a)
For example, when I put the newly added switch on the tree .Then i click  confirm and the URL chagne to  this
I don't know where the problem is,but other languages are fine, only Chinese has such poor display status

**Comment by TheWitness** [comment] 2024-06-17 19:01
Can you provide the exact steps to reproduce from the time you sign in till the time the issue occurs?

**Comment by aliuzzz** [comment] 2024-06-19 08:21
It happens in a lot of places, and I'll just give you one quick example.
1. Log in
2. Click "Manage" -- "Devices"
3. Select a device and select "Put it on the tree".
4. Click OK.
5. Click "Continue" directly in the pop-up dialog box.
And then Lost the style

**Comment by hljtql** [comment] 2024-06-19 14:17
Yes, this issue only occurs in the Chinese environment, and it almost always appears in any submission section. At this point, a dialog box indicating successful operation should have popped up, but it did not appear. Instead, a page with header=false appears

**Comment by hljtql** [comment] 2024-06-19 14:52
I found the reason, because only the Chinese environment had this problem, so I suspected Chinese translation problem, so I replaced the zh-CN.mo of 1.2.27 with the zh-CN.mo of 1.2.26 and the problem was solved...... But, how exactly did this come about?

**Comment by TheWitness** [comment] 2024-06-20 00:22
Goto https://translate.cacti.net and see if you can contribute to the Cacti Translation for Chinese.  There are a few string patterns that Google and Microsoft can not figure out.  Also, please try to build from the latest zh-CN.po in GitHub.  You can find it in the 1.2.x branch at locales/po/zh-CN.po.  Once you download that file, in the `locales` directory there is a build_gettext.sh.  Run that script and Chinese will be rebuilt.

Below is a screenshot using POEDIT for Windows showing all the errors in translation.  If you create an account at https://translate.cacti.net you can simply find the strings that need work, and make the changes on the fly.  We need the help.

![image](https://github.com/Cacti/cacti/assets/1439914/0b3ae142-ec74-4b54-bf33-011ffd8139af)

**Comment by TheWitness** [comment] 2024-06-20 00:28
I uploaded an updated zh-CN.po file that has all the errors untranslated again.  Need help.  Closing this one.

**Closed by TheWitness** 2024-06-20 00:28 UTC
Labels: bug, unverified, type:bug, status:needs-verification
