### ISSUE TITLE
Missing SNMP value for Disk-C

### ISSUE THREAD

**Issue by amprantino** [Cacti/cacti#559] opened 2017-04-12 09:58 UTC
Graphs for Disk C are missing values; all other partitions are OK!!!
This applies to mutiple servers; check images:

![capture1](https://cloud.githubusercontent.com/assets/1978223/24952350/d478298e-1f7f-11e7-9cd2-07667827dcc6.JPG)

![capture2](https://cloud.githubusercontent.com/assets/1978223/24952246/93b7738c-1f7f-11e7-9b06-215c3a187dff.JPG)

Debug:
![capture3](https://cloud.githubusercontent.com/assets/1978223/24952385/f1ed15e2-1f7f-11e7-8c20-21316c6c699a.JPG)

**Comment by cigamit** [comment] 2017-04-19 12:49
This might be a duplicate of issue #454

**Closed by cigamit** 2017-04-19 12:49 UTC
