### ISSUE TITLE
Wrong Cacti version on hotfix/1.1.37_fixes branch

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#1540] opened 2018-04-16 01:23 UTC
Hi @ronytomen ,

Your latest comit 0e115a7a70dd9b3baac9f9d008b0ab9f27c33659 changed the cacti version on the hotfix branch to 1.1.38 and that causes the patched installation to prompt you with the Upgrade procedure.

I manually reverted the changes to those 2 files and it's all good.

**Comment by ronytomen** [comment] 2018-04-16 01:42
That was intended as this was merged to master to create the `1.1.28` release.  

Is there something wrong?

**Comment by jpobeda** [comment] 2018-04-16 02:12
Well I though that branch was specifically for the 1.1.37 hotfixes not for 1.1.38 release, maybe I'm wrong an misc interpreted the use of that branch.

**Closed as completed** 2018-04-16 12:22 UTC

**Comment by netniV** [comment] 2018-04-16 20:45
@jpobeda The branch itself was labelled as hotfixes for 1.1.37 because no new features were introduced and only those fixes deemed important were ported backwards from 1.2 to 1.1.37.  It was labelled as such to prevent people from thinking there would be any feature updates that people have been asking/waiting for.  It also gave people something to watch or update from if they wished to do so early or to test the fixes.

In order to make sure that people know where they are patched up to, the version is incremented on a release so you know which version you are running against and although these were just important fixes it helps to know that people are patched to that level. Any future 1.1.x releases will technically be hotfixes only for important/breaking fixes.
