### ISSUE TITLE
Graph Zoom overlay shifts to the left causing wrong zoom factors

### ISSUE THREAD

**Issue by hoswfh** [Cacti/cacti#3700] opened 2020-07-17 01:48 UTC
Thanks for the advice. I had upgraded to cacti version 1.2.12 and still facing the same problem. 
Any more advice on how to solve this zoom in problem. I attached the graph image for your reference. Thank you.
<img width="1514" alt="zoom issue" src="https://user-images.githubusercontent.com/64879630/87382957-d1ac0a00-c5ca-11ea-97b5-04fbb951e808.PNG">

_Originally posted by @hoswfh in https://github.com/Cacti/cacti/issues/3602#issuecomment-657955074_

_Updated with new detail from @hoswfh in https://github.com/Cacti/cacti/issues/3700#issuecomment-669666351_

I want to clarify my problem again. When I click at the left y axis of the graph, I got the below display. The zoom in window is out of the range of the graph window. This is my problem. There is nothing to do with the look of the graph. I am not sure if there is anything to do with the jquery.zoom.js in cacti include/js folder. When I release the click, the zoom in range is not what I want.

<img width="1512" alt="zoom in problem" src="https://user-images.githubusercontent.com/64879630/89488034-85bf4000-d7d9-11ea-9be3-655bad212660.png">

**Comment by TheWitness** [comment] 2020-07-17 16:01
Well, I have no idea what your problem is to be honest.  I guess that's the first problem.

**Comment by hoswfh** [comment] 2020-07-21 07:38
Thanks for the response. I hope that the next CACTI version will resolve this zoom in issue in preview list and graph details zooming view. Thanks again for all the new features in the latest version of CACTI.

**Comment by netniV** [comment] 2020-07-31 17:01
I think I see it now, you are wondering why you have a larger Y axis and the answer is to the far right of your graph between 04:00 and 06:00 where there appears to be an unprecedented spike.  If you use the Spike Kill options, this may remove that and make your graph appear more normal.

**Comment by hoswfh** [comment] 2020-08-03 08:52
Thanks, Mark, for the response.

I capture the below CACTI graphs for your reference. These graphs have no spike but has zoom in issue. CACTI version is 1.2.12.

Graph in preview list portal. The ‘+’ pointer is out of the y axis. There is no spike in the traffic. There is no issue if the graph title is turned off. It seems that the zoom issue is something got to do with the graph title.
[Image]


The same graph but in CACTI 0.8.8b has no issue in the zoom graph view. The ‘+’ pointer is at the edge of the y axis and so when you zoom in, there is no problem. Graph title is turned on.
[Image]



Graph in graph detail and zoom view. The ‘+’ pointer is out of the graph frame and so zoom in will not work as expected. There is no spike in the traffic. CACTI version is 1.2.12. There is no issue if the graph title is turned off. It seems that the zoom issue is something got to do with the graph title.
[Image]

Thanks.

**Comment by netniV** [comment] 2020-08-03 17:14
I think you may be being misled, as I can clearly see a spike at around 5am.  If you say that tall vertical green line is not a spike... I'd be interested to know what it is.

**Comment by hoswfh** [comment] 2020-08-04 01:52
Thanks for the reply. I agree it is a spike traffic, but this spike traffic is genuine and it is within the physical port limit. I cannot remove this spike traffic as this is the traffic trend in this circuit. If I turn off the graph tittle, I have no issue with the zoom in.  The same circuit graph in 0.8.8b has no zoom in issue with graph tittle turn on. I am considering downgrade from 1.2.12 to 0.8.8b to resolve the zoom in issue. Thank you for the support and response.

**Comment by cigamit** [comment] 2020-08-04 03:17
Closing this, as its not a bug.  Its working exactly as it should and we will not be changing it.  You have valid traffic up to 100 M, so RRDTool is going to show the Y Axis up to the maximum.  Older versions of Cacti did the exact same thing, this is nothing new.

**Comment by hoswfh** [comment] 2020-08-04 03:25
Thank you for the reply and noted the comment below. Thank you.

**Comment by TheWitness** [comment] 2020-08-04 11:38
What you need to do is attach the Poller Cache, and the Data Source Info mode entries for this graph in question (which is essentially RRDtool info).  It would also be nice to compare those two things between 1.2.x and 0.8.x RRDfiles.  Once you have done that, we'll be closer to understanding the root of the problem.

The reason that we close these so quickly is for a few reasons.  

1. You are only providing 'qualitative' data (aka "Its broken, wah!"), that is not a response.
2. You did not think through the problem, or understand how Cacti works enough to provide the 'quantitative' data (aka "Its broken as you can see that the maximum value for this interface should be A, but it's set to B").
3. We've see so many of these through the years, going on 20 now, that we just close them.

I hope you understand the differences between 1. and 2.

Examples from 1.2.x, you will have to run ```rrdtool info rrdfile.rrd``` for 0.8.x.

Poller Cache Noting the OID's.
![image](https://user-images.githubusercontent.com/1439914/89289275-f3763b00-d624-11ea-812c-f624be6fdd41.png)

Data Source Info Mode:
![image](https://user-images.githubusercontent.com/1439914/89289372-23bdd980-d625-11ea-9048-e60edb613c25.png)

**Comment by TheWitness** [comment] 2020-08-04 11:40
BTW, looking at my Data Source, I see some problems with my Template :).  The bonus question, is can you see what is wrong with it.

**Comment by netniV** [comment] 2020-08-04 17:06
Please sir, I can see it, pick me pick me 👍  Don't make me `last` ;)

**Comment by TheWitness** [comment] 2020-08-04 18:43
Lol.

**Comment by bmfmancini** [comment] 2020-08-04 19:52
Haha !

**Comment by hoswfh** [comment] 2020-08-06 03:47
I want to clarify my problem again. When I click at the left y axis of the graph, I got the below display. The zoom in window is out of the range of the graph window. This is my problem. There is nothing to do with the look of the graph. I am not sure if there is anything to do with the jquery.zoom.js in cacti include/js folder. When I release the click, the zoom in range is not what I want.
Thank you.

<img width="1512" alt="zoom in problem" src="https://user-images.githubusercontent.com/64879630/89488034-85bf4000-d7d9-11ea-9be3-655bad212660.png">

**Comment by netniV** [comment] 2020-08-06 09:46
Right, now I think we can all see the issue is not what any of us where interpreting it as. To me, that will be a little tricky to diagnose without having access to your browser to verify what it believes it is seeing.  Can you confirm the OS and browser you are using for this?  Are there other graphs on the page?

**Comment by TheWitness** [comment] 2020-08-06 10:35
Oh, god, I'm blind.  Can you tell that I'm distracted with other things right now.  Here is what we need:

1) Browser version
2) Cacti version
3) Installed from source or a package
4) Image format PNG/SVG
5) Screen2Gif animation of how this occurred.

**Comment by TheWitness** [comment] 2020-08-06 10:37
Removing some meaningless comments.

**Comment by netniV** [comment] 2020-08-06 16:40
<details>
<summary>Joke</summary>
<i>I really felt like doing that to the previous comment too as a joke heh</i>

</details>

Can you also check if there are any errors in your browser console window? That may explain an offset failure.

**Comment by hoswfh** [comment] 2020-08-07 03:23
Thank you for the reply. I am glad that you all could see my problem. Actually it is very easy to simulate the problem. As long as the graph title exceeds 250 characters, you will see the zoom in problem. It happens in graph preview list mode and also graph utility view. In graph preview mode, the zoom in problem is very obvious if you select 1 or 2 columns. As I said before, when you turn off the graph tittle, the zoom in works perfectly well in both preview list mode and graph utility view(click the little wheel icon of a selected graph)

Display 2 columns in preview list mode.

<img width="1837" alt="graph zoom problem" src="https://user-images.githubusercontent.com/64879630/89604050-085d0380-d89d-11ea-8623-8d2b0cdd905a.png">

In graph utility view of a selected graph.

<img width="1517" alt="graph view zoom issue" src="https://user-images.githubusercontent.com/64879630/89604708-676f4800-d89e-11ea-88a7-2775db0f617c.png">


Below are my answers to your queries.
Browser version: Google **Chrome Version 80.0.3987.122 (Official Build) (64-bit). I use IE11 and get the same problem too**.
Cacti version: **1.2.12**
Installed from source or a package: **install from cacti-1.2.12.tar.gz**
What Image format PNG/SVG?: **PNG**
What Cacti Theme?: **classic. It happens to all themes.**
Upload Screen2Gif animation of how this occurred.: **I am sorry that I am not allow to share my company portal.**

There is no error in the browser console window of the graph utility view. I only manage to get one error, after many times of trying to zoom in. I am sorry that I did not manage to capture that error for you.

Thank you.

**Comment by netniV** [comment] 2020-08-07 11:50
Thanks for the update, leave it with us and we will investigate/try to replicate.  We may struggle without your environment though, so it would be useful if at some point we could screen share if we are unable to reproduce.  Would that be allowed ?

**Comment by hoswfh** [comment] 2020-08-08 01:26
Yes, I am glad to help if required.  Thank you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by netniV** [comment] 2020-08-08 09:39
So I set an insanely long description but that did not make much of a difference.  Certainly not under develop (1.3.x) anyway.  Since the zoom code is the same between both 1.2.x and 1.3.x I can only surmise that something else is triggering your issue.

Out of interest, the grey box appears at that location as you start your selection on mouse down?  One other thing to note, on my system whilst I was highlighting the correct time slots and the zoom was drilling down to the correct time slot, my from/to date ranges showed an hour out (and at the moment I'm presuming that's a UTC vs BST issue).

**Comment by netniV** [comment] 2020-08-08 09:41
If you can do a screengif and make the rectangle cover the areas were no names are mentioned, that should be OK since all the other data is simply time and value?

**Comment by hoswfh** [comment] 2020-08-11 01:42
Thanks for the reply. May I have your simulated graph with its long descriptions in preview and graph details utilities? I just want to compare your graph with mine.
The grey line appears out of location of the graph rectangle box as I start my selection on mouse down. See below.

[cid:image002.jpg@01D66FC3.91FB4E00]

I manage to capture the below error too after I click and drag the selection.

[cid:image006.jpg@01D66FC3.91FB4E00]

I hope the above is useful to you.
Thank you.

**Comment by hoswfh** [comment] 2020-08-11 06:13
Hi Mark,
I attached the screengif file for your reference. Thanks.

**Comment by netniV** [comment] 2020-08-11 19:40
Unfortunately, that hasn't made it through to the issue tracker, can you try pasting it here instead?  GitHub allows you to paste images directly into the comment box and magically converts them for you 👍

**Comment by hoswfh** [comment] 2020-08-12 01:35
By the way, I just realize that CACTI 0.8.8b does not display graph title both in preview list and zoom graph portal. This is why I don't have this zoom in issue. 
I had uploaded the screengif file and the zoom in error here for your reference.
![zoom in fails](https://user-images.githubusercontent.com/64879630/89964587-294a9d80-dc7d-11ea-886b-44de00797413.gif)
<img width="989" alt="zoom in issue" src="https://user-images.githubusercontent.com/64879630/89965244-edb0d300-dc7e-11ea-9f8a-898ba5b602b1.png">

**Comment by netniV** [comment] 2020-08-12 23:46
Can you try access the cacti site in incognito mode?  I just want to rule out any plugins or extensions on the browser.

**Comment by hoswfh** [comment] 2020-08-13 03:12
My chrome and IE11 browser does not support incognito mode and so I cannot do it.  Thanks.

**Comment by netniV** [comment] 2020-08-13 17:50
Both support that though IE calls in InPrivate mods. Chrome may have reworded the menu item to be similar to IE but when the window opens I'm pretty sure it says incognito. Either that or they've now completely reworded it and I haven't been paying attention lol

**Comment by hoswfh** [comment] 2020-08-14 01:08
I am using company laptop and recently for security reasons, they have removed the incognito feature in all of my browsers. I am sorry that I cannot help you. May I know if your long graph title wordings extend outside of the graph box? If no, then you will not have the zoom in problem. All of my graphs with long graph title wordings extend out of the graph box will have this issue. The rest of the graphs with graph tittles fall within the graph box will not have zoom in issue. This is what I have observed.

**Comment by netniV** [comment] 2020-08-14 05:48
That reminds me, there is a variable from graph title truncation, I presume you have set that to a large value?

**Comment by hoswfh** [comment] 2020-08-14 06:29
Yes I set it to 400. Is there a limit to the tittle length?
<img width="881" alt="tittle length" src="https://user-images.githubusercontent.com/64879630/90220253-6f009500-de3a-11ea-883a-42bad4b3773f.PNG">

**Comment by TheWitness** [comment] 2020-08-14 12:23
That all depends on how big your graphs are.  I think 400 is way too long.  For the Data Source field length, this is for the primary key.  A key that long would indicated that you are making some bad decisions on how you are indexing your Data Queries.

**Comment by netniV** [comment] 2020-08-14 15:57
I would agree 400 is a long length, but I'll take a look as it highlights some dodgy code potentially.

**Comment by netniV** [comment] 2020-08-14 16:05
I've tried to replicate this under 1.2.14 and been unable to.  This leads me to suspect it's an environmental issue rather than a code issue.  Maybe a third party plugin or proxy server is causing issues with the scripts or layout but without being able to use developer tools against your server, we'd be struggling to identify the root cause.

**Comment by hoswfh** [comment] 2020-08-17 01:41
I am using proxy server or jump server to access to the cacti server. Either method is giving me the same zoom in issue. My colleagues are also having the same issue using their laptop and browsers. I am not sure if the proxy or jump servers is causing this problem, but the developer tools in my browser did not show any error when the zoom in fails.

**Comment by TheWitness** [comment] 2020-10-17 16:40
Andi (@browniebraun) made an update recently.  I'm going to assume that this update as well as others will be resolved in the 1.2.15 release pending.

**Closed by TheWitness** 2020-10-17 16:40 UTC
Labels: gui, outdated, unable to reproduce

**Comment by hoswfh** [comment] 2020-10-18 04:05
Thanks everyone for the update and kind support. I still have the same zoom in problem. I hope the latest release 1.2.15 will resolve this problem. Once again, thanks a lot.
