### ISSUE TITLE
snmp bad index cannot be fixed

### ISSUE THREAD

**Issue by gzivdo** [Cacti/cacti#2570] opened 2019-03-26 06:43 UTC
Cacti was upgraded from 0.8 to dev version. Upgrade to ubuntu 18.04 packaged version fails, upgrade to latest stable fails.
Now I have in the log a few devices (very strange that not all) "You have N Devices with bad SNMP Indexes". All of them have bad indexes with snmp interface statistics, index type ifdescr. 
I tried reindex it by verbose query and got 
```
Total: 2.830000, Delta: 1.150000, Detected New Sort Field: 'ifName' Old Sort Field 'ifDescr'
--
Total: 2.830000, Delta: 0.000000, New Sort Field validated.  Sort Field be updated.
Total: 2.830000, Delta: 0.000000, WARNING: Sort Field Association has Changed.  Re-mapping issues may occur!
Total: 2.830000, Delta: 0.000000, Update Data Query Sort Cache complete
Total: 3.230000, Delta: 0.400000, Index Association with Local Data complete
Total: 3.230000, Delta: 0.000000, No Index Changes Detected, Skipping Re-Index and Poller Cache Re-population
Total: 4.290000, Delta: 1.060000, Automation Executing for Data Query complete
Total: 4.290000, Delta: 0.000000, Plugin hooks complete
```
I tried rebuild poller cache after.
The warning in the log is still present.
I can recreate graphs, but i need to save old data in rrd. Its about 200 datasources.
I do not want to do it manually.

here one of "bad" datasources:
![изображение](https://user-images.githubusercontent.com/13568002/54985273-90e94580-4fc1-11e9-8bcb-d3b7f5446ea0.png)
old was
D-Link DGS-3420-26SC R1.00.B03 Port 13 on Unit 1
new one
D-Link DGS-3420-26SC R3.01.R00 Port 13 on Unit 1
And when i do verbose re-query it now detects index by ifindex and cannot match to old ones.
Is there any method to auto convert them somehow?

**Comment by cigamit** [comment] 2019-03-26 23:14
This is intentional so that the Graph will continue to work.  The workaround for you is to find the ifName for this interface, and then change the sort column to ifName, and then type in the correct ifName value.  The reason that it was done this way was so that old graphs would not break in case the sort column returned.

So, it's not a bug, just an interface that must no longer exist is my guess.

**Comment by cigamit** [comment] 2019-03-26 23:15
By the way, if you are not at 1.2.2, get there right away as there were bugs in 1.2.0 and 1.2.1 around this issue.  If not at 1.2.2, reindex all the Devices after you upgrade.

**Comment by cigamit** [comment] 2019-03-26 23:16
Ope, you are on develop.  So disregard the last comment.

**Comment by cigamit** [comment] 2019-03-26 23:17
Closing, but type away.  This should be archived on the Cacti forums if you get the chance.

**Closed by cigamit** 2019-03-26 23:17 UTC
Labels: question

**Comment by gzivdo** [comment] 2019-03-27 06:09
If such case can exists, there should be some interface to map datasources. I tring now to do with sql query and rrd merge script. This is very bad. And I should be able to choose which type to use for index (ifindex, ifname or whatever) it should not be automatic because exists cases where it fails.

**Comment by gzivdo** [comment] 2019-04-02 10:57
I've coded a script to do remap. My be for someone it will be useful. Anyway, I strongly suggest to do:  1) Allow to select  to select what to use for index in device template and in device edit dialog. 
2) Mass change index field for hosts and/or datasources per query.
3) Make remapping ui dialog in cacti   when re-mapping issue occurs.

[sql-fix.py.gz](https://github.com/Cacti/cacti/files/3033553/sql-fix.py.gz)
