### ISSUE TITLE
Add search capability to the Configuration>Settings form and its tabs

### ISSUE THREAD

**Issue by jab60** [Cacti/cacti#5533] opened 2023-10-14 22:09 UTC
# Feature Request

## Describe the solution you'd like

There are rather a lot of settings available.
Would it be possible to have a text search box to find a setting across all the settings tabs.
Search in the field description and its associated tooltip and possibly its current value.
If a plugin adds extra fields to existing tab or a new tab could it also search in those as well.

Click Go to execute search (same as used in other headers with search box).
Display on header count of search matching items
I can think of 3 possible ways to complete the search, probably depends on implementation complexity and what is possible. 
Option 3 is probably most similar to other forms where a search is available.
1:- Keep existing tab and form layout but move the focus
      After search item is found place focus on first matching field.
      Have next>previous buttons to move to other matching fields. Loop back to first after last.
2:- Display all matching items on 1 new form effectively merging the options from all the tabs.
3:- On each tab filter the list of displayed fields to just those matched, (some tabs might be blank)

**Comment by TheWitness** [comment] 2023-10-14 22:18
This is a duplicate one I think.

**Comment by TheWitness** [comment] 2023-10-14 22:19
I thought I already had it prototyped and then somehow lost it.

**Comment by xmacan** [comment] 2023-10-15 09:14
@TheWitness you prepared it for 1.2.x. Vinten revert it because we planned it to 1.3.

**Comment by jab60** [comment] 2023-10-15 10:23
Yes just found it under #5316 You can close this as a duplicate.

just to also mention that filtering the changelog by the types in the GUI may also help in viewing changes by category aka #3590 to view feature requests.

**Comment by netniV** [comment] 2023-10-15 10:42
It was original done for 1.2.x, but I asked for that to be removed from there as it's a feature, not a bug fix.  It was supposed to make its way into 1.3.x, but is taking the long way around it seems ;-)

**Comment by TheWitness** [comment] 2023-10-15 14:29
It's pretty easy to reproduce, I just need a bit of time to do the callbacks.

**Comment by TheWitness** [comment] 2023-10-15 20:19
Now, I have to find it.

**Comment by TheWitness** [comment] 2023-10-15 21:03
Duplicate of #5316

**Closed** 2023-10-15 21:03 UTC
Labels: duplicate, enhancement, type:enhancement

**Comment by TheWitness** [comment] 2023-10-17 01:31
This was fixed in this commit: eb3c3905327e8363f3b73d5775f6f4a5fdf3a5f4

**Comment by TheWitness** [comment] 2023-10-17 01:31
Today.
