### ISSUE TITLE
[1.2.0] Unsaved changes warning appearing when no changes made

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1826] opened 2018-08-12 16:16 UTC
![aug-12-2018 17-08-40](https://user-images.githubusercontent.com/9052188/44003954-e133a7cc-9e52-11e8-9968-f6e94757b448.gif)

System is incorrectly reporting that changes may be lost when no changes were made.

**Comment by cigamit** [comment] 2018-08-12 17:36
Have something to do with some local changes.  I can not reproduce with the latest stable.  Have you modified this network from the default?

**Comment by netniV** [comment] 2018-08-12 17:37
I don't believe so.  Not the only page I had it though.

**Comment by netniV** [comment] 2018-08-12 20:40
Locations I experienced this were:

- Templates -> Data Sources
- Automation -> Networks

Interestingly enough, I didn't get it when adding a new item and changing nothing.

**Comment by pautiina** [comment] 2018-08-12 21:02
It's also happings on some plugin config

**Comment by pautiina** [comment] 2018-08-13 06:41
![cacti](https://user-images.githubusercontent.com/11805503/44016259-03788192-9edd-11e8-96ba-24a36ad89e51.gif)

**Comment by netniV** [comment] 2018-08-13 07:53
Thanks for the screengrab. It showed that the problem appears to be with the Mail/DNS tab.  Specifically, if you have ever set anything for the SMTP fields, this seems to be flagging as a constant change.  So, it would appear to be when we have a dynamic form this issue is being seen.

**Comment by netniV** [comment] 2018-08-13 07:53
I replicated it by going to my mail tab, and setting it to SMTP, then filling in the fields.  As soon as I had done that, clicking away caused the issue.

**Comment by cigamit** [comment] 2018-08-13 10:35
On the Mail/DNS settings page, this is due to the sendmail binary being altered to prevent warnings like "file not found", on main pages/tables, it's due to the form name not being named 'chk' and having some items checked.  I have not been able to reproduce the Automation Networks.

**Comment by netniV** [comment] 2018-08-13 10:54
So, I created a new network and that worked fine by populating only the description and range. No problem.  Set all other options I could find bar a schedule, and fine. 

Once I set a schedule, then the prompt appears.

**Comment by cigamit** [comment] 2018-08-18 14:16
Right now, if you find these and would rather they be ignored, use the second option of the form_start() function and set it to 'chk'.  Forms with the id of 'chk', are not scanned for field changes.  It's sub-optimal, and should be a form_start() option to ignore, but for now that will work.  Should be done as an option, but I don't want to have to update all the pages at the moment.

**Comment by cigamit** [comment] 2018-08-18 17:14
Let's have everyone look for these when we get into Beta.

**Comment by netniV** [comment] 2018-08-20 18:31
This happens in Threshold plugin when you try to add a new template, select a data source and instantly you get:
![image](https://user-images.githubusercontent.com/9052188/44359394-ab999000-a4af-11e8-8ea2-72d768eed924.png)

**Comment by cigamit** [comment] 2018-08-21 00:08
Use form_start(page, 'chk').  That form id will ignore changes before going off form.  I'm open to other suggestions.

**Comment by netniV** [comment] 2018-08-23 14:07
Another location is Management -> Aggregate -> Aggregate Graph -> Preview, then click other tabs

**Comment by cigamit** [comment] 2018-09-25 01:56
> 
> 
> Another location is Management -> Aggregate -> Aggregate Graph -> Preview, then click other tabs

This one is fixed.

**Comment by cigamit** [comment] 2018-09-25 01:57
> 
> 
> On the Mail/DNS settings page, this is due to the sendmail binary being altered to prevent warnings like "file not found", on main pages/tables, it's due to the form name not being named 'chk' and having some items checked. I have not been able to reproduce the Automation Networks.

This one is fixed.

**Comment by cigamit** [comment] 2018-09-25 01:58
> 
> 
> Locations I experienced this were when editing an item in:
> 
>     * Templates -> Data Sources
> 
>     * Automation -> Networks
> 
> 
> Interestingly enough, I didn't get it when adding a new item and changing nothing.

These should be fixed.

**Comment by cigamit** [comment] 2018-09-25 02:11
Plugins will be out of scope for now.

**Comment by cigamit** [comment] 2018-09-25 02:11
Re-open if you find more non-plugin issues like this.

**Closed by cigamit** 2018-09-25 02:11 UTC
Labels: beta

**Comment by pautiina** [comment] 2018-10-04 10:12
On plugin routerconfigs when try compare configs:
![image](https://user-images.githubusercontent.com/11805503/46467672-045e8700-c7d7-11e8-9ca5-67ed9f1502ae.png)

**Comment by interduo** [comment] 2018-11-01 08:51
Just click Settings--> MailReporting and then some other panel for example "General".

**Comment by interduo** [comment] 2018-11-01 08:59
Please reopen this issue as it's not fully resolved.

**Comment by pautiina** [comment] 2018-11-01 09:13
resolved on https://github.com/Cacti/cacti/commit/a96f06067be004df25be95efc93a996a49e34844

**Comment by netniV** [comment] 2018-11-01 16:04
@interduo if you are running Beta 1, this should have been resolved with 9fc07c2a436aa125f3bcfdf7cc81bdf4f0b179a7
