### ISSUE TITLE
[1.2.0] Table 'cacti.data_debug' doesn't exist in cacti.sql

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1791] opened 2018-08-06 09:25 UTC
I have taken the Cacti-develop from today (August 6th), copied it and perform an Cacti install.
Now I got plenty of following errors:
![image](https://user-images.githubusercontent.com/35721406/43708684-506bd408-996b-11e8-8a40-ef60847a38b9.png)

How can I create this table that was not created during install?

**Comment by netniV** [comment] 2018-08-06 09:28
This is a new table recently added this weekend as part of integrating the debug plugin.  You should run the following after updating code to make sure any database functionality is up to date:

```bash
sudo -u <website user> php -q <cacti_path>/cli/upgrade_database.php --forcever=1.1.38
```

This will run through any database level upgrades again to ensure that they are at the 1.2.0 state.

**Comment by jackouille-ch** [comment] 2018-08-06 09:34
Great, that works fine, thanks.
May could you add this table to 1.2.0 install script in order to avoid this kind of issue.

**Comment by netniV** [comment] 2018-08-06 09:36
It is in there.  But only as of this weekend.

**Comment by jackouille-ch** [comment] 2018-08-06 09:37
Ok but I took the full zip today at 10:53, and it's now 11:37

**Comment by netniV** [comment] 2018-08-06 09:37
Wait I just realised you said you did a full install?  I think I know what the issue is.  It's not in the cacti.sql file if you did a reimport of that.

**Comment by netniV** [comment] 2018-08-06 09:38
Can you confirm that you emptied and reinstalled the database ?

**Comment by jackouille-ch** [comment] 2018-08-06 09:38
Nope I didn't emptied DB, simply copy new files and run install

**Comment by netniV** [comment] 2018-08-06 09:55
OK, in that case, you will get the above problem.  As I said before, if you update the code and it expects a database to existing, a fresh install does not install the database, that is done prior to starting the install so it should already exist.  As you've kept your existing structure, you have manually re-upgrade.

However, you have highlighted the missing table from the cacti.sql file so even if you had done it correctly, you'd have had the same problem.

**Comment by jackouille-ch** [comment] 2018-08-06 10:00
Great, thanks !

**Comment by netniV** [comment] 2018-08-06 10:02
Closing this now as I've added it to the sql file (once the PR is commited).

**Closed by netniV** 2018-08-06 10:02 UTC

**Comment by hanifbhuiyan** [comment] 2019-04-18 05:40
Hi,
I have the same issue. I had run it .. but it did not changed anything and did not solved the issue.
php -q /usr/share/cacti/cli/upgrade_database.php --forcever=1.1.38
Your Cacti is already up to date.
