### ISSUE TITLE
[1.1.38] Poller interval from 5min to 1min == POLLER: Poller[cacti-XXX] WARNING: Poller Output Table not Empty. Issues NN

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#1578] opened 2018-04-27 23:05 UTC
Hi everyone,

I am moving from 5min **Poller Interval** to 1min and since I configured the setting I am seeing every polling cycle the following warning:

POLLER: Poller[cacti-XXX] WARNING: Poller Output Table not Empty. Issues N ( where N is a variable number)

I tried rebuilding the polling cache but nut much luck with that, any suggestion ?

**Comment by cigamit** [comment] 2018-04-28 07:08
Well, did you re-populate the poller cache after the change?  Also what is your runtime averaging?  Are you starting off with fresh RRDfiles too, or did you manually repopulate them?

**Comment by jhonnyx82** [comment] 2018-04-28 10:55
Thanks for replying

These are the runtime for each poller

![image](https://user-images.githubusercontent.com/26431888/39395754-ea0ac600-4ae2-11e8-8edf-54a6c93817d6.png)

I repopulated the poller cache with the command:
`php -q /var/www/html/cacti/cli/rebuild_poller_cache.php`

I didn't touch RRDfiles, as I thought these would not be changing since I have all data sources now at 5 minutes.

Actually every 5 minutes I can see the Warning and the amount of data sources listed in the warning is quite variable (around 400 now).

What do you suggest ? I would like to not drop all RRDfiles but if necessary I will do that.

**Comment by netniV** [comment] 2018-04-28 11:01
Hi @jhonnyx82, any help with documentation would be appreciated.  There is a documentation repo where we are trying to get that updated slowly but surely.

https://github.com/cacti/documentation/

**Comment by cigamit** [comment] 2018-04-28 12:00
As long as you do not change the collection sampling (aka Data Source Profile). Repopulating the Poller Cache should get you there.  I have debated overnight putting a wrapper in place to replay the RRDfiles so that you could change the Data Source Profile on the fly, but large changes of thousands of RRDfiles would take minutes to complete.  So, still not committed and would be a separate issue.

**Comment by cigamit** [comment] 2018-04-28 12:02
So, you are still seeing the warning?  Hmm.  How long does that last data collector run for now?  The number of rows will be variable.  That is by design.  Check the Remote Data Collector for runtime warnings, and post the unemptied poller_output table.

**Comment by jhonnyx82** [comment] 2018-04-28 12:12
Apparently I totally broke my cacti installation, I tried recovering from a backup of both database and folder I had but nothing works anymore

**Comment by cigamit** [comment] 2018-04-28 12:13
Wow, show some log details.  I just have a few minutes before I go off for an errand.

**Comment by jhonnyx82** [comment] 2018-04-28 12:28
Getting to see what happens, by a series of unfortunate events I lost the rrd files as I forgot to make a copy but that's on me, I restored the last actual backup I had before the one that was 1 week old

so now it's recreating the rrd files and well, I will let you know how it is

PS : all of this back on 5 minute polling so I guess this whole operation is a minus rather than a plus in the best case scenario and not for myself : never try again to move to 1 minute polling :D

**Comment by jhonnyx82** [comment] 2018-04-28 12:44
Seems I am back in business (well besides the historical data :( ) but anyway...

If you feel like writing down some guidelines about moving from one polling time to another it would be great, even if I don't think I will get brave enough to attempt this any soon after today but who knows...

+ Any guideline on how to properly backup and restore a multipoller CACTI installation, when I restored an old backup with an old database on the main poller it started all possible nasty logs (on the main poleller only...) then I restored the folder from my last backup and left the database from 1 week ago and everything looks fine now.

Thanks in advance

**Comment by cigamit** [comment] 2018-04-28 20:47
Well, first thing is that a database dump should be separated from RRDfile backups.  So, if you hose your database, you just restore it and not the RRDfiles.  Sorry to hear that you lost them.  Backup and restore should make sense.  If you did not modify any PHP files, don't restore, etc.

**Closed by cigamit** 2018-04-28 20:47 UTC
Labels: unverified

**Comment by jhonnyx82** [comment] 2018-04-29 11:01
Yes, the RRD files I lost because of a wrong script (too late I realized that)

But practically it would be good to know a safe approach on moving polling time from 5 minutes to 1, currently I have 5 minutes and that's it but my goal would be to:

- move 5 minutes polling to 1
- keep my data source at the beginning to 5 minutes as they are now
- adding data source configured for 1 minute polling (I have duplicated templates for each data source, not practical but works)
- remove in time some 5 minutes data sources

now to achieve this and not lose data and have warnings of "poller empty table output", what do you suggest that would be the process?

Ultimately I can still keep CACTI in 5 minutes, it's not the end of the world, just it looks odd that moving to 1 minute polling while practically my system was working with all 5 minutes DS was such troubles

**Comment by jhonnyx82** [comment] 2018-05-02 09:05
Sorry to ask again, but  the answer I received is about the backup not about the polling time change from 5 minutes to 1 minute :)

I have anyway opened a thread on the CACTI forum, I hope you could contribute to that discussion in order to avoid any problem for my next attempt and for other people too.

https://forums.cacti.net/viewtopic.php?f=21&t=58700
