### ISSUE TITLE
Unable to create Graphs due to one of the following Data Query Issues: permissions, incorrectly formatted, or missing XML file

### ISSUE THREAD

**Issue by alcatron** [Cacti/cacti#4516] opened 2021-12-26 04:03 UTC
Im Running some custom graphs to monitor hard drive temperature on synology NAS device which worked fine in 1.2.17... now when i want to add additional disk temperature graphs in 1.2.19 i am seeing this error..

This happens when clicking on "Create" graphs button. Some bug i suppose in graphs_new.php ?

`
26-12-2021 14:27:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php[68]:graphs(), /graphs_new.php[778]:CactiErrorHandler())
--
26-12-2021 14:27:23 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/graphs_new.php on line: 778
26-12-2021 14:27:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php[68]:graphs(), /graphs_new.php[778]:CactiErrorHandler())
26-12-2021 14:27:23 - ERROR PHP NOTICE: Undefined index: fields in file: /usr/share/cacti/graphs_new.php on line: 778
26-12-2021 14:27:23 - CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php[68]:graphs(), /graphs_new.php[625]:CactiErrorHandler())
26-12-2021 14:27:23 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/graphs_new.php on line: 625
26-12-2021 14:27:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php[68]:graphs(), /graphs_new.php[625]:CactiErrorHandler())
26-12-2021 14:27:23 - ERROR PHP NOTICE: Undefined index: fields in file: /usr/share/cacti/graphs_new.php on line: 625
`

**Comment by TheWitness** [comment] 2021-12-29 16:24
I'm marking this as confirmed, but the source of the problem is likely user error.  Check the renaming of the issue for more clues.

**Comment by TheWitness** [comment] 2021-12-29 16:29
I have updated the error message to help in diagnosis.

**Comment by alcatron** [comment] 2021-12-30 10:15
Still didnt make any difference, updating the new graphs_new.php file

30-12-2021 20:39:33 - CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php[68]:graphs(), /graphs_new.php[778]:CactiErrorHandler())
30-12-2021 20:39:33 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/graphs_new.php on line: 778
30-12-2021 20:39:33 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php[68]:graphs(), /graphs_new.php[778]:CactiErrorHandler())
30-12-2021 20:39:33 - ERROR PHP NOTICE: Undefined index: fields in file: /usr/share/cacti/graphs_new.php on line: 778
30-12-2021 20:39:33 - CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php[68]:graphs(), /graphs_new.php[625]:CactiErrorHandler())
30-12-2021 20:39:33 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/graphs_new.php on line: 625
30-12-2021 20:39:33 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php[68]:graphs(), /graphs_new.php[625]:CactiErrorHandler())
30-12-2021 20:39:33 - ERROR PHP NOTICE: Undefined index: fields in file: /usr/share/cacti/graphs_new.php on line: 625

**Comment by alcatron** [comment] 2021-12-30 10:17
Note, the existing graphs are working fine, its only when new ones to create, ive checked permissions and nothing has changed

**Comment by TheWitness** [comment] 2021-12-30 14:37
Hmm, okay.

**Comment by TheWitness** [comment] 2021-12-30 14:42
Okay, that's quite odd.  For the host in question, can you please verify the XML files for each Data Query and make sure that the XML file has valid syntax and is readable.  Below is an example where you will find "fields".  Every XML file should have it and in your case, there is one Data Query where either the XML file is not correct, or is missing that data.  I can add more 'debug' to more closely isolate the specific data query also.

![image](https://user-images.githubusercontent.com/1439914/147761657-dc514ed8-c82d-4b9c-a9f7-4c080836a892.png)

**Comment by TheWitness** [comment] 2021-12-30 14:47
I updated the graphs_new.php to throw an error and let you know which data query has a bad or missing XML file.  Please apply and report back.

**Comment by alcatron** [comment] 2021-12-31 01:01
ok , what you did is good, keep that debug modification, now it pops up an error

Sorry, we could not process your last action.
Error Parsing Data Query Resource XML file for Data Query 'Synology - disk ID' with id '10'

**Comment by alcatron** [comment] 2021-12-31 01:24
question is whats the reason for the error.. i just tried the same template in 0.8 cacti and it works fine, can it give anymore details why its erroring the parsing ?

**Comment by alcatron** [comment] 2021-12-31 01:38
In cacti 0.8 there is an option on the bottom - (Verbose Query) for debugging under  Associated Data Queries and i can see how it parses all the xml fine.. i cant see that option in cacti 1.2 running a verbose query..
I turned on debug for the individual nas device and now i see errors like this, when i re-index the device

31-12-2021 11:59:16 - ERROR PHP NOTICE: Undefined index: fields in file: /usr/share/cacti/lib/data_query.php on line: 2273
31-12-2021 11:58:44 - REINDEX ERROR: Re-Indexing failed due to a NULL sort field for Device[Synology NAS] and DQ[Synology - disk ID]. Can not continue with Re-Index.
31-12-2021 11:58:44 - CMDPHP PHP ERROR WARNING Backtrace: (/host.php[116]:host_reload_query(), /host.php[574]:run_data_query(), /lib/data_query.php[106]:query_snmp_host(), /lib/data_query.php[917]:CactiErrorHandler())
31-12-2021 11:58:44 - ERROR PHP WARNING: Invalid argument supplied for foreach() in file: /usr/share/cacti/lib/data_query.php on line: 917
31-12-2021 11:58:44 - CMDPHP PHP ERROR NOTICE Backtrace: (/host.php[116]:host_reload_query(), /host.php[574]:run_data_query(), /lib/data_query.php[106]:query_snmp_host(), /lib/data_query.php[917]:CactiErrorHandler())
31-12-2021 11:58:44 - ERROR PHP NOTICE: Undefined index: fields in file: /usr/share/cacti/lib/data_query.php on line: 917
31-12-2021 11:58:44 - CMDPHP PHP ERROR NOTICE Backtrace: (/host.php[116]:host_reload_query(), /host.php[574]:run_data_query(), /lib/data_query.php[106]:query_snmp_host(), /lib/data_query.php[869]:CactiErrorHandler())
31-12-2021 11:58:44 - ERROR PHP NOTICE: Undefined index: oid_index in file: /usr/share/cacti/lib/data_query.php on line: 869
31-12-2021 11:58:44 - ERROR PHP NOTICE: Undefined index: oid_index in file: /usr/share/cacti/lib/data_query.php on line: 813
31-12-2021 11:58:43 - CMDPHP PHP ERROR NOTICE Backtrace: (/host.php[116]:host_reload_query(), /host.php[574]:run_data_query(), /lib/data_query.php[106]:query_snmp_host(), /lib/data_query.php[813]:CactiErrorHandler())
31-12-2021 11:58:43 - ERROR PHP NOTICE: Undefined index: oid_index in file: /usr/share/cacti/lib/data_query.php on line: 813

**Comment by TheWitness** [comment] 2021-12-31 13:08
Upload the device template and xml file.

**Comment by TheWitness** [comment] 2021-12-31 15:04
So, to be clear, you will upload >= 2 XML files.

**Comment by alcatron** [comment] 2022-01-01 07:39
Here they are:

cacti_host_template_synology_nas.txt = is the main template

these sit in /cacti/resource/snmp_queries
synology_snmp_diskid.txt 
synology_disk_temp.txt

[synology_disk_temp.txt](https://github.com/Cacti/cacti/files/7797454/synology_disk_temp.txt)
[cacti_host_template_synology_nas.txt](https://github.com/Cacti/cacti/files/7797455/cacti_host_template_synology_nas.txt)
[synology_snmp_diskid.txt](https://github.com/Cacti/cacti/files/7797456/synology_snmp_diskid.txt)

**Comment by TheWitness** [comment] 2022-01-03 14:39
Worked find for me.  You have placed the wrong file into the <path_cacti>/resource/snmp_queries/ directory.  The file in your uploads `synology_disk_temp.txt` should be in that directory with the name `snmplofy_snmp_diskid.xml`.  So, it's a simple error to fix.  I have a Synology NAS and once all the files are correctly in place, everything works.  So, this is a PEBKAC.  Closing now.  We have better error handling now anyway.

**Comment by TheWitness** [comment] 2022-01-03 14:45
There appear to be other issues.  I'm going a little further down the rabbit hole.

**Comment by TheWitness** [comment] 2022-01-03 14:47
Here is the second big issue.  Goto this page on your system.  Do you see the same thing?

![image](https://user-images.githubusercontent.com/1439914/147944268-4ac09431-9e4f-4d8a-bfd6-669d17497c3a.png)

**Comment by TheWitness** [comment] 2022-01-03 14:47
I guess we should disable the "checkboxes" when this problem is encountered.

**Comment by TheWitness** [comment] 2022-01-03 15:11
Going to make another commit to help users when they encounter these basket of issues.

**Comment by TheWitness** [comment] 2022-01-03 15:14
Okay, think this is good enough now.  Closing.

**Closed by TheWitness** 2022-01-03 15:14 UTC
Labels: bug, resolved

**Comment by alcatron** [comment] 2022-01-04 10:29
Hi Witness,

In the path <path_cacti>/resource/snmp_queries/ I have both files synology_disk_temp.xml and synology_snmp_diskid.xml , I just renamed the above to .txt so I can upload the files.
I have disks 1 - 5 graphing fine with this setup for past 2 years, the problem is when I wanted to add disk 6 to graph temperature cacti doesn't want to create the graph and creates the above error. The same in 0.8 cacti doesn't experience the issue. 

The screenshot above of yours is the same as mine.

With your setup how many disks are you graphing ? 

I still can't get it to work but 0.8 works fine same setup.

**Comment by TheWitness** [comment] 2022-01-04 13:33
Not sure how it works in that your device template export did not include all the components.  Did you export from 0.8.x or did you export from 1.x?  Also, your file `synology_disk_diskid.xml` is NOT a resource XML.  Open a few of them and you will see what I'm talking about.

**Comment by TheWitness** [comment] 2022-02-20 23:58
@alcatron, FYI.  I've added the Synology NAS (my version with two of your Templates) to the 1.2.20 release.  You should look for it.
