### ISSUE TITLE
Hi all, I deleted the host DISK data template DS can not be restored

### ISSUE THREAD

**Issue by ybbpgkfdn** [Cacti/cacti#1001] opened 2017-09-26 02:36 UTC
Hello everyone, I lead to the need to put cacti to get the data, by nagios, i use nagios pnp4nagios plugin to achieve! But pnp4nagios and cacti to create rrd file DS number of different columns, (pnp4nagios DS: 1.cacti DS: 2) Then I think to modify cacti -> console -> data templates -> Host MIB - Hard Drive Space -> Deleted hdd_total with hdd_used -> re-created traffic_in (DS). Then I want to restore hdd_total with hdd_used and manually fill in the finished save. The The However, the graphics are not showing up.
Want to get help thanks
![qq 20170925174010](https://user-images.githubusercontent.com/32284882/30839762-695d048a-a2a6-11e7-8ecd-3d49bf193bd0.png)
![qq 20170926103507](https://user-images.githubusercontent.com/32284882/30839761-695a36ba-a2a6-11e7-9ccd-c631a1ec4e5b.png)

**Comment by cigamit** [comment] 2017-10-11 23:53
You should never manually re-add things to a template.  Re-import it from the package that is provided in the install/templates directory.  You can run the cli script import_package.php --help on how to do that.  After that, you have to delete then recreate the graph.  You should delete the existing data template though, which means the graphs that go along with it.

Since this is a usage problem and not a bug, I am closing this issue.  You can still post comments, but I think I've been clear enough.

**Closed by cigamit** 2017-10-11 23:53 UTC
