### ISSUE TITLE
AutoM8 does not create graphs when devices are added to remote poller

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#3315] opened 2020-03-03 19:41 UTC
Hey Guys 

I have noticed as far back as 1.2.7 then when you add devices via AUTOM8 on remote poller 
the device shows in unknown state on the main poller which is fine until the poller sync 

however, the graphs are not created automatically you have to go back and manually run automation rules 

I have run the apply_automation_rules.php file in a cron afterward to create the graphs in a interval but I would think autom8 should be able to do this on its own 

Thanks !

**Comment by cigamit** [comment] 2020-03-08 16:25
This was, or should have been resolved in 1.2.10.  Please check again.

**Comment by bmfmancini** [comment] 2020-03-08 16:28
Cool will check and let you know

**Comment by cigamit** [comment] 2020-03-08 16:29
Cool.  I'll be at this for a while.  So, update away.

**Comment by bmfmancini** [comment] 2020-03-08 20:21
Hey Jimmy I tried 1.2.10 same deal AUTOM8 will create graphs based on the graph templated but wont create interface graphs however if you apply automation rules works great

**Comment by TheWitness** [comment] 2020-03-14 20:48
This ticket is duplicate of this: https://github.com/Cacti/cacti/issues/3261

**Closed by TheWitness** 2020-03-14 20:48 UTC
Labels: duplicate
