### ISSUE TITLE
why the aggregated graph cannot add 95th Percentile to Allow Aggregate Graphs  Sum Bandwidth and Percentile COMMENTS

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#1600] opened 2018-05-02 10:54 UTC
![95zhi](https://user-images.githubusercontent.com/31933126/39519615-0dd56784-4e3a-11e8-8bf3-1c2ddd306294.png)
![95](https://user-images.githubusercontent.com/31933126/39519618-0f8af3d2-4e3a-11e8-82b1-85b3b4b1e3e3.png)

why the aggregated graph cannot add 95th Percentile to Allow Aggregate Graphs  Sum Bandwidth and Percentile COMMENTS??

**Comment by netniV** [comment] 2018-05-02 12:25
Actually a duplicate of #431 (the original original 👍 ) so for now I will close this but you can add any comments you might have on that post.

**Closed by netniV** 2018-05-02 12:25 UTC
