### ISSUE TITLE
database FAIL when upgrading

### ISSUE THREAD

**Issue by dsclassen** [Cacti/cacti#238] opened 2017-01-30 17:30 UTC
one error when upgrading cacti DB.

```
[Fail] ALTER TABLE `colors` ADD UNIQUE INDEX hex(hex)
```

and from cacti.log:

```
2017-01-30 09:27:21 - CMDPHP SQL Backtrace: (/install/index.php: 416 upgrade_to_1_0_0)(/install/0_8_8h_to_1_0_0.php: 1214 db_install_add_key)(/install/functions.php: 80 db_install_execute)(/install/functions.php: 48 db_execute)(/lib/database.php: 112 db_execute_prepared)(/lib/database.php: 176 cacti_debug_backtrace)
2017-01-30 09:27:21 - 5 ERROR: A DB Exec Failed!, Error: Duplicate key name 'hex'
2017-01-30 09:27:21 - CMDPHP SQL Backtrace: (/install/index.php: 416 upgrade_to_1_0_0)(/install/0_8_8h_to_1_0_0.php: 1214 db_install_add_key)(/install/functions.php: 77 db_execute)(/lib/database.php: 112 db_execute_prepared)(/lib/database.php: 176 cacti_debug_backtrace)
2017-01-30 09:27:21 - 5 ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UNIQUE INDEX hex' at line 1
```

**Comment by ronytomen** [comment] 2017-01-30 18:54
The updated should have continued past that failed step.  Seems they key already exists on the table, which is an ignoble error.

**Comment by dsclassen** [comment] 2017-01-30 19:04
Yes. The update did complete. I just thought I'd let you know of the error.

**Comment by cigamit** [comment] 2017-02-01 18:49
The 0.8.8h_to_1_0_0.php script has been updated to remove duplicates before adding the new UNIQUE KEY now.  It will only help people who have not updated yet.  Do you need a repair script?

**Comment by cigamit** [comment] 2017-02-01 23:24
I'm closing this.  If you would like a migration script, just let me know.

**Closed by cigamit** 2017-02-01 23:24 UTC

**Comment by cigamit** [comment] 2017-02-04 19:41
If found another root cause for this.  It should be fixed properly now.  It was not a duplicate color but a failure to drop the index if it already existed due to an assumption in one of the database functions.
