### ISSUE TITLE
Imported data source template problems

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#992] opened 2017-09-18 07:56 UTC
First problem, I created a data source template with 9 data sources. They were numbered sequentially, and thus Cacti created a file name with the first data source name in the filename. 
Here is an rrdtool info output to show the correct ordering:
<pre>$ rrdtool info something_1.rrd | grep -i heart
ds[BankPeakCurrent1].minimal_heartbeat = 600
ds[BankPeakCurrent2].minimal_heartbeat = 600
ds[BankPeakCurrent3].minimal_heartbeat = 600
ds[BankPeakCurrent4].minimal_heartbeat = 600
ds[BankPeakCurrent5].minimal_heartbeat = 600
ds[BankPeakCurrent6].minimal_heartbeat = 600
ds[BankPeakCurrent7].minimal_heartbeat = 600
ds[BankPeakCurrent8].minimal_heartbeat = 600
ds[BankPeakCurrent9].minimal_heartbeat = 600</pre>

Now I exported this via device template export and then re-imported it into a different Cacti instance. I also changed the Data Profile for the data source. Here is what happened:
<pre>$ rrdtool info something_2.rrd | grep -i heart
ds[BankPeakCurrent2].minimal_heartbeat = 120
ds[BankPeakCurrent6].minimal_heartbeat = 120
ds[BankPeakCurrent3].minimal_heartbeat = 120
ds[BankPeakCurrent8].minimal_heartbeat = 120
ds[BankPeakCurrent4].minimal_heartbeat = 120
ds[BankPeakCurrent1].minimal_heartbeat = 600
ds[BankPeakCurrent5].minimal_heartbeat = 120
ds[BankPeakCurrent7].minimal_heartbeat = 120
ds[BankPeakCurrent9].minimal_heartbeat = 120</pre>

First off, the ordering of my data source objects is completely all over the place. Sadly that really bugs me ... I go through great lengths to get these ordered right when I build these templates. It also causes Cacti to make a different filename. 
Second ... somehow my heartbeat changed for all the data source objects *except* for the one I would have expected to be first in the list! 
Now, I can't tell whether this re-ordering/heartbeat issue was triggered by the import or the Data Profile change.. But I can tell from all the filenames created that almost none of them are right, and I only changed the Data Profile on half of them.

**Comment by cigamit** [comment] 2017-09-21 12:15
It's reordering due to a real old behavior in Cacti that has to do with the lack of an order statement on export.  If we fix it, everything will maintain order, but for a short period of time, your file names will all be wrong.  The upside is that they will remain consistent thereafter.

BTW, many people use structured paths to reduce the naming to an ID and provide sub directories to prevent inode and performance issues.  But for a someone who operates from the command line, it makes things arguably more difficult.

I don't know if you are averse to getting me a Database dump in the broken condition, or if I should just figure out what is happening in the code.  Seems the latter will be the best approach.

**Comment by eschoeller** [comment] 2017-10-15 02:36
Hey there. I'm back to working on Cacti again for awhile. Where do you stand with this one? I'm in a bit of a holding pattern on a few things waiting for this one to get resolved. I don't quite understand what you mean by "everything will maintain order, but for a short period of time, your file names will all be wrong". 
I am aware of the structured paths, just haven't gotten around to implementing that. I have numerous dependencies on using a single directory that would take awhile to unravel unfortunately. I currently have 25331 files in the single RRA directory which lives on some PCIe SSDs. Not sure if I would be experiencing a performance hit or not in this situation.

**Comment by cigamit** [comment] 2017-10-15 12:32
Yea, with local disk, never a problem I would say.  To be honest, I'm busy on other things right now.  We've been attempting to just keep the core as stable as possible for the last few months.

**Comment by eschoeller** [comment] 2017-10-15 20:00
OK, I'll see if I can futz around with the database to fix the ordering just for these imported templates so I can move forward with bringing in these devices

**Comment by eschoeller** [comment] 2017-10-15 21:36
Well I've tried re-ordering the hash, data_source_name and data_input_field_id around within the data_template_rrd table. I've corrected the file name issue and the data sources are ordered properly in the RRD file, but now the graph is displaying the data in the incorrect order. So I'm trying to dig around in the graph template now to figure out what's wrong. Tedious and frustrating to say the least.

**Comment by eschoeller** [comment] 2017-10-16 02:55
For anyone else wanting to do this, it's very involved - at least the way I did it. 
First re-order everything from this query (where '703' is your id)
`mysql> select id,hash,data_source_name,data_input_field_id from data_template_rrd where data_template_id=703;
+--------+----------------------------------+------------------+---------------------+
| id     | hash                             | data_source_name | data_input_field_id |
+--------+----------------------------------+------------------+---------------------+
| 162786 | 1048441ae0177e6aab63fb4092a8cb6b | BankCurrent2     |                 758 |
| 162787 | 26197d8e7d6e1bf4e67937bcb224b92e | BankCurrent1     |                 754 |
| 162788 | 7979f255e13028613b4fd9d1e57759bc | BankCurrent8     |                 763 |
| 162789 | 8a8a5f46fc8cfc31ae21725fecaa11dd | BankCurrent9     |                 760 |
| 162790 | 988cce81fbdfa640b08ecc8396e6db81 | BankCurrent3     |                 751 |
| 162791 | a5cf60e94a9c9140750f42f61a1ef8b7 | BankCurrent4     |                 753 |
| 162792 | c5600e6f4ac4334e517aa143db8cc49b | BankCurrent6     |                 761 |
| 162793 | cb22bbd0b60b1997e828ca494255b85a | BankCurrent7     |                 749 |
| 162794 | eeb365c3974df2a0414770928f4c7465 | BankCurrent5     |                 768 |
+--------+----------------------------------+------------------+---------------------+

+--------+----------------------------------+------------------+---------------------+
| id     | hash                             | data_source_name | data_input_field_id |
+--------+----------------------------------+------------------+---------------------+
| 162786 | 26197d8e7d6e1bf4e67937bcb224b92e | BankCurrent1     |                 754 |
| 162787 | 1048441ae0177e6aab63fb4092a8cb6b | BankCurrent2     |                 758 |
| 162788 | 988cce81fbdfa640b08ecc8396e6db81 | BankCurrent3     |                 751 |
| 162789 | a5cf60e94a9c9140750f42f61a1ef8b7 | BankCurrent4     |                 753 |
| 162790 | eeb365c3974df2a0414770928f4c7465 | BankCurrent5     |                 768 |
| 162791 | c5600e6f4ac4334e517aa143db8cc49b | BankCurrent6     |                 761 |
| 162792 | cb22bbd0b60b1997e828ca494255b85a | BankCurrent7     |                 749 |
| 162793 | 7979f255e13028613b4fd9d1e57759bc | BankCurrent8     |                 763 |
| 162794 | 8a8a5f46fc8cfc31ae21725fecaa11dd | BankCurrent9     |                 760 |
+--------+----------------------------------+------------------+---------------------+
`
Then you need to do the same thing over here:
`
mysql> select id,hash,name from graph_template_input where graph_template_id=716;
+------+----------------------------------+----------------------------+
| id   | hash                             | name                       |
+------+----------------------------------+----------------------------+
| 1824 | 3a5864ed6b52d39e80518ff528b43a30 | Data Source [BankCurrent1] |
| 1825 | 3e0b6b31329c9b623a7b1589a1310255 | Data Source [BankCurrent2] |
| 1826 | 3ebcc4225701b0effaaf34c9d8fc85a9 | Data Source [BankCurrent9] |
| 1827 | 479c5804845e358217bfd8f4c394b149 | Data Source [BankCurrent7] |
| 1828 | 4aaafb3df6a9a0fbe3334a51a8b2f024 | Data Source [BankCurrent5] |
| 1829 | 7a591df6ea6c0c789aac0bca4155309d | Data Source [BankCurrent8] |
| 1830 | 8a8ec15e7f964ce07f8a6b5e0f38a786 | Data Source [BankCurrent4] |
| 1831 | df1385dd6706ad9b93cf79d4fcd798eb | Data Source [BankCurrent6] |
| 1832 | fbd0565bd92b918b8a5a78b87d16bccf | Data Source [BankCurrent3] |
+------+----------------------------------+----------------------------+

+------+----------------------------------+----------------------------+
| id   | hash                             | name                       |
+------+----------------------------------+----------------------------+
| 1824 | 3a5864ed6b52d39e80518ff528b43a30 | Data Source [BankCurrent1] |
| 1825 | 3e0b6b31329c9b623a7b1589a1310255 | Data Source [BankCurrent2] |
| 1826 | fbd0565bd92b918b8a5a78b87d16bccf | Data Source [BankCurrent3] |
| 1827 | 8a8ec15e7f964ce07f8a6b5e0f38a786 | Data Source [BankCurrent4] |
| 1828 | 4aaafb3df6a9a0fbe3334a51a8b2f024 | Data Source [BankCurrent5] |
| 1829 | df1385dd6706ad9b93cf79d4fcd798eb | Data Source [BankCurrent6] |
| 1830 | 479c5804845e358217bfd8f4c394b149 | Data Source [BankCurrent7] |
| 1831 | 7a591df6ea6c0c789aac0bca4155309d | Data Source [BankCurrent8] |
| 1832 | 3ebcc4225701b0effaaf34c9d8fc85a9 | Data Source [BankCurrent9] |
+------+----------------------------------+----------------------------+
`
The last part is tricky. You have to do some mapping between the old task_item_id and the new one. I ended up with hundreds of queries to run. But in the above example, task_item_id 162786 would need to be replaced with 162787.
Here are some commands that I ran which I can't really explain too well:
`/usr/local/mysql/bin/mysql --disable-column-names --silent -B -u apache -pPASS cacti -e "select id from graph_templates_item where task_item_id=162786;" > 162786`
`for i in `cat 162786`; do /usr/local/mysql/bin/mysql --disable-column-names --silent -B -u apache -pcActipW cacti -e "update graph_templates_item set task_item_id=162787 where id=$i;"; done`

Somehow, I've fixed the ordering. I hope I never have to do this again. I'd suggest not relying on import/export until the ordering issue can be resolved. Better to just re-develop the template directly in Cacti.

**Comment by cigamit** [comment] 2017-10-16 11:33
I think the reason for this is that we added 'ORDER' to the export and import since it was never really consistent before from system to system.  If the only thing affected is the rrdfile name, I'm a little dubious to change, though there 'may' be a workaround.  Let me know.

**Comment by cigamit** [comment] 2017-10-29 14:43
This issue happens when you export the template from one cacti system, and import it on another.  The issue is with the export and not the import.  I have resolved by taking the two statements that previously did not have an order statement, and added the order of ID to them, which is the default that MySQL will use (which is the original insert order).

**Closed by cigamit** 2017-10-29 14:43 UTC
