### ISSUE TITLE
Graph - Title (--title) dont work

### ISSUE THREAD

**Issue by DFlexy** [Cacti/cacti#3674] opened 2020-07-09 12:38 UTC
My graphics dont work titles and graph with proVirtual 
Cacti version 1.2.12

If i apply Reapply Suggested Names works in some and others don't

Configured here 
![image](https://user-images.githubusercontent.com/50220928/87040706-7db6b500-c1c7-11ea-84b7-df202e72251e.png)

Configured here too
![image](https://user-images.githubusercontent.com/50220928/87041006-eef66800-c1c7-11ea-98c0-d38ce0ea9f2f.png)

Dont work here
![image](https://user-images.githubusercontent.com/50220928/87041602-d8044580-c1c8-11ea-9103-c2a8ddfd5be0.png)

**Comment by DFlexy** [comment] 2020-07-09 12:50
I recreate another graph with ieee8023adlag and work
More proVirtual dont work graph and names too

![image](https://user-images.githubusercontent.com/50220928/87042109-945e0b80-c1c9-11ea-8e38-209880c41162.png)

**Comment by TheWitness** [comment] 2020-07-12 14:45
By default, unless 'all' the replacement values have a non-null entry, the suggested values will not work.  So, what that means is that one of the |query_blah| that you have in the suggested name does not have a match in the host_snmp_cache table.  You should add second and third less complete suggested values that can be used when there is not a complete match.

So, this is not a bug presently.

**Comment by cigamit** [comment] 2020-08-10 03:16
Not a bug, so closing out.

**Closed by cigamit** 2020-08-10 03:16 UTC
Labels: not a bug, question
