### ISSUE TITLE
When a page is rendered and user does not have permission errorimage should show reasonable output

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#2262] opened 2019-01-03 11:35 UTC
![2019-01-03_12-25-16](https://user-images.githubusercontent.com/25581728/50635646-4bcdee00-0f53-11e9-86f7-a8ab9b185853.gif)

After i get the "Permission Denied" Error (#2259) and i want to go back over the tree menu on the left side. In this situation i cant do anything in the webinterface until i reload the whole site.

If i go back over the "Return" Button in the "Permission Denied" Message i have no problems.

**Comment by cigamit** [comment] 2019-01-04 10:38
Duplicate of #2259

**Comment by netniV** [comment] 2019-01-04 12:30
I believe that whilst issue #2259 did cause this issue to be shown, the underlying problem still exists were a permission denied page will cause the UI to break.

**Comment by TheWitness** [comment] 2020-03-17 01:40
This is fixed isn't it?  @DavidLiedke can you confirm on the 1.2.x branch?

**Comment by TheWitness** [comment] 2022-10-17 02:08
This one has been resolved for a while.

**Closed by TheWitness** 2022-10-17 02:08 UTC
Labels: enhancement, gui
