### ISSUE TITLE
1.2.8 with #3157 - Install loop on Path page

### ISSUE THREAD

**Issue by Susanin63** [Cacti/cacti#3218] opened 2020-01-26 07:41 UTC
Clear new install 1.2.8 with path #3157  - loop on Path page.
After deleting patch #3157 (only 73091b8 part) - all work.

**Comment by netniV** [comment] 2020-01-27 15:15
That makes no sense to me, as far as I am aware the two are not really related.

**Comment by cigamit** [comment] 2020-02-01 18:28
Use the latest 1.2.x branch.  That patch was not complete at the time.  Going to close this as we know the root cause was that there were multiple changes around this feature from day one till the time it was finalized.

**Closed by cigamit** 2020-02-01 18:28 UTC
Labels: unverified

**Comment by cigamit** [comment] 2020-02-02 15:26
Okay, just made an update.  Installer is functional again.

**Comment by cigamit** [comment] 2020-02-02 15:27
I did not add a changelog entry for this as it was created between releases.
