### ISSUE TITLE
Cacti Location field hides devices from Cacti device list.

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#3501] opened 2020-04-24 18:12 UTC
The device Location field is supposed to be a free form field, however after entering anything into that field the device is not seen in Cacti device list. You have to manually clear that field from the host table in the database.

I personally had about 20 devices that somehow had that field hard coded to "None" which I never set. After clearing this field the devices showed up in the device list. I then tested with other text and the result is the same.

**Comment by TheWitness** [comment] 2020-04-24 19:34
It's a known issue with the classic theme.  Use one of the others.

**Comment by jdcoats** [comment] 2020-04-24 20:06
I guess both Modern & Classic :/ I just spent 2 days customizing the Modern theme :/

Dan

**Comment by TheWitness** [comment] 2020-04-24 20:32
Cool, but when you use the modern theme, you should by able to edit the device and change the location, it's just a little awkward.  Select2 will like be put in place when we get back into feature mode.

**Comment by jdcoats** [comment] 2020-04-24 20:38
I just tested with sunrise and the result is the same. If you enter a location the device is gone from the device list and you have to clear the field from the database to get the device back in cacti

**Comment by TheWitness** [comment] 2020-04-24 22:50
Are you talking about Device > Edit or the list of devices?

**Comment by TheWitness** [comment] 2020-04-24 22:54
Rereading now.  Update host.php from the 1.2.x branch.  This is a known issue.

**Comment by TheWitness** [comment] 2020-04-25 15:01
Duplicate of https://github.com/Cacti/cacti/issues/3424

**Closed by TheWitness** 2020-04-25 15:01 UTC
Labels: duplicate
