### ISSUE TITLE
Cacti 1.2.10 500 Internal Server Error

### ISSUE THREAD

**Issue by martinlegionowo** [Cacti/cacti#3321] opened 2020-03-04 15:23 UTC
After clicked - Rebuild Poller Cache -
we have 500 Internal Server Error.

![cacti_1_2_10_500_internal_server_error](https://user-images.githubusercontent.com/61698203/75893942-c9c9a580-5e33-11ea-84c8-8cda00470372.jpg)

And in clog we have - 
2020/03/04 16:07:17 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2020/03/04 16:07:17 - ERROR PHP ERROR: Call to undefined function xml_parser_create() in file: /var/www/html/cacti-1.2.10/lib/xml.php on line: 29

After that we can add device but -  Reload Query for device - circles infinitive.
Shutdown system not solved it.

How we resolve it ?

 - OS: CentOS 7.8 - 3.10.0-1062.12.1.el7.x86_64
 - Browser: Firefox 73.0.1 64bit
 - Version: PHP 5.6.40 (cli) (built: Feb 18 2020 08:36:40)

**Comment by netniV** [comment] 2020-03-04 21:47
I'm not sure how you managed to get Cacti installed without the XML modules as that is checked for during the installation wizard.  Check the Technical Support's PHP tab and ensure that XML support is enabled.

**Comment by martinlegionowo** [comment] 2020-03-05 05:27
Hello Mark,

I'm not sure if it is -
libxml
------------------------------
libXML support active
libXML Compiled Version 2.9.1
libXML Loaded Version 20901
libXML streams enabled

I changed PHP from 5.4. to 5.6 after installation Cacti - maybe it is a
problem ?


regards,
Marcin





śr., 4 mar 2020 o 22:47 Mark Brugnoli-Vinten <notifications@github.com>
napisał(a):

**Comment by netniV** [comment] 2020-03-05 12:39
Compare your 5.4 and 5.6 php.ini files.

**Comment by martinlegionowo** [comment] 2020-03-05 14:38
Hi,
the timezone is correct and the error_log = syslog.
What exactly I have to check ?

Regards,
Marcin

**Comment by netniV** [comment] 2020-03-05 20:29
What modules are enabled.

**Comment by cigamit** [comment] 2020-03-08 16:10
This is resolved in the 1.2.x branch as of this morning.

**Comment by cigamit** [comment] 2020-03-08 16:13
Spoke too soon.  This is due to the XML module not being included in your updated install.  It's a required module.  So, this is not a bug.  Going to close in just a minute.

**Closed** 2020-03-08 16:15 UTC
Labels: environment, not a bug

**Comment by netniV** [comment] 2020-03-08 22:18
I think it is a bug, because they shouldn't have been able to install without that module...correct me if I'm wrong on that?

**Comment by TheWitness** [comment] 2020-03-08 22:21
Yea, I'm just wondering how he/she did it.  If you took a database backup, restored it on the new server, and then rsync'd the RRDfiles, you could have missed this.

**Comment by TheWitness** [comment] 2020-03-08 22:21
I think the installer blocks.
