### ISSUE TITLE
Input variables can't be replaced in page Graphs.php

### ISSUE THREAD

**Issue by horizonlin** [Cacti/cacti#1165] opened 2018-01-03 02:18 UTC
Input variables can't be replaced in page Graphs.php.   such as  |input_para|.
Cacti zsIDC-Process |input_proc_name|-|input_exec_path|

**Comment by cigamit** [comment] 2018-01-03 03:02
You need to provide pictures of the page where the variables are not being replaced and then the output from the host_snmp_query table for the Data Query and Device in question.  My guess is that this has less to do about Cacti and more to do with your data or the Data Query.

**Comment by horizonlin** [comment] 2018-01-04 02:11
It work fine  in Graph_view.php, but Graphs.php.
![20180104100901](https://user-images.githubusercontent.com/26472990/34547629-8d3b7d34-f137-11e7-8578-024c1aa01883.jpg)
![20180104101034](https://user-images.githubusercontent.com/26472990/34547637-952a54fc-f137-11e7-9af6-8b51ab4699c1.jpg)

**Comment by netniV** [comment] 2018-01-04 16:28
That is by design so that you can change the variable used within the graph.  If you look back at the list, that variable is replaced with the correct value.

### During edit (Graph.php?action=graph_edit)
![image](https://user-images.githubusercontent.com/9052188/34573452-1f71bcca-f16c-11e7-87f1-d59754d6dd27.png)

### During list (Graph.php?)
![image](https://user-images.githubusercontent.com/9052188/34573489-40ac639a-f16c-11e7-953c-b6004df4d555.png)

**Comment by netniV** [comment] 2018-01-04 16:32
The above was on my 1.1.29 test system.  What version of Cacti are you running?

**Comment by horizonlin** [comment] 2018-01-05 01:14
Yes,the graph on editing page had the right name ,but the list.

I had upgraded to 1.1.30 yesterday,  but it is the same to pervious version.

**Comment by netniV** [comment] 2018-01-05 09:04
OK, lets try to see if we can work out what's causing the translation not to occur then.  Can you tell me the following?

- For the device in question, what is the device template used for the device in question and what are the associated data queries?
- For the graph, what is the graph template used and what does the "Title" field contain (presumably the same as the list)?
- For the graph template, what does the "Title" field contain? 

If all these match what is expected, then we may have to insert some debug code to work out why it's not being triggered.  In the meantime, I'll have a glance of the graph.php code and see if anything obvious jumps out.

**Comment by cigamit** [comment] 2018-01-05 13:44
What happens when your "Re-apply suggested names" on the graphs?  There was something that I decontented from Cacti 1.x when migrating from Cacti 0.x, that I think might need to be re-added.

Also, please output the data from the following query as I had asked previously:

`select * from host_snmp_cache where host_id=? AND snmp_query_id=?;`

Replace the ? with the correct values.

**Comment by cigamit** [comment] 2018-01-05 13:45
Looking at this, if the 'index' value is the PID, this will never work.  The index will need to be the path and not the pid.  The output of the query will make this clear.

**Comment by netniV** [comment] 2018-01-05 13:56
That's true because a given process can change its index, the process name should be the index.

**Comment by horizonlin** [comment] 2018-01-08 01:51
I used data input . This template is added by myself.  when the graph was created , must filled some parameters . such as process name、process path、process para(hrSWRunName、hrSWRunPath、hrSWRunParameters）

**Comment by horizonlin** [comment] 2018-01-08 01:57
For the device in question, what is the device template used for the device in question and what are the associated data queries?
A：Using Data input, not Date query.(hrSWRunName、hrSWRunPath、hrSWRunParameters）

For the graph, what is the graph template used and what does the "Title" field contain (presumably the same as the list)?
For the graph template, what does the "Title" field contain?
A：|host_description|-Process  |input_proc_name|-|input_exec_path|.  I guess that it happend because of the secendary "_“。

**Comment by horizonlin** [comment] 2018-01-12 00:46
It is OK now after upgrade to 1.1.30 a few days later. Do not change anything.

**Comment by cigamit** [comment] 2018-01-12 23:25
You still have not answered my question.

**Comment by netniV** [comment] 2018-01-12 23:27
I think he's said that with the latest update, he doesn't need any more assistance.

**Comment by cigamit** [comment] 2018-01-12 23:34
Okay, closing.  Was looking for that host_snmp_cache output.  But will close then.  Thanks!!

**Closed by cigamit** 2018-01-12 23:34 UTC
