### ISSUE TITLE
[1.2.0 Beta 1] Issue with Realtime on new login

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#2052] opened 2018-10-11 09:27 UTC
Cacti 1.1.37 
MariaBD 10.2.18

I updated MariaDB to 10.2.18 from 10.2.17 and got this erorr

CMDPHP Validation Error, Variable:graph_start, Value:-undefined Backtrace: (/graph_realtime.php: 44 get_filter_request_var)(/lib/html_utility.php: 443 die_html_input_error)(/lib/html_validate.php: 64 cacti_debug_backtrace)

**Comment by netniV** [comment] 2018-10-11 10:11
Just to be clear, you downgrade MariaDB and this now fails?

**Comment by cigamit** [comment] 2018-10-11 11:16
Is this the only place where this has occurred.  I suspect that this the database is a red herring.  The issue is that the time value needs to be in seconds, and it's undefined.  That means that the defaults were not set when you opened realtime.  This is the pop-out realtime new window feature correct?

**Comment by Izmenoff** [comment] 2018-10-11 11:29
Yes, realtime works well

**Comment by cigamit** [comment] 2018-10-11 11:52
Should be resolved now.  Thanks for reporting.  Clone your environment and if you can not longer reproduce, please close.

**Comment by Izmenoff** [comment] 2018-10-11 11:56
How I can add this change in my Cacti 1.1.37 ?

**Comment by cigamit** [comment] 2018-10-11 11:58
Well, take the diff and hand edit the three files.  Not too difficult. I think you can take graph_realtime.php in it's entirety.  The other two files are light hand edits.  Simple enough.

**Comment by Izmenoff** [comment] 2018-10-11 12:06
Thanks, I'll replace graph_realtime.php
But what other two files need to edit?

**Comment by cigamit** [comment] 2018-10-11 12:07
Click on the Resolving ... link on this page.  It'll take you to the commit.

**Comment by Izmenoff** [comment] 2018-10-11 12:12
thanks a lot

**Comment by Izmenoff** [comment] 2018-10-11 12:27
11-Oct-2018 15:27:23 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4628 cacti_debug_backtrace)
--
thrown in file: /var/www/html/cacti/graph_realtime.php on line: 130
#0 {main}
Stack trace:
11-Oct-2018 15:27:23 - ERROR PHP ERROR: Uncaught Error: Call to undefined function cacti_sizeof() in /var/www/html/cacti/graph_realtime.php:130

**Closed** 2018-10-11 12:30 UTC
