### ISSUE TITLE
WEEKLY AND MONTHLY GRAPHS SHOWING AS DAILY GRAPH

### ISSUE THREAD

**Issue by jsmalisa** [Cacti/cacti#4204] opened 2021-03-30 03:36 UTC
Can someone help me figure why my monthly and weekly graphs are showing my daily graphs?

Appreciate the help.

![image](https://user-images.githubusercontent.com/53674811/112930051-f0ecc680-915c-11eb-9b2f-cea525055901.png)

**Comment by cigamit** [comment] 2021-03-30 03:41
I assume your Cacti version (since you don't bother to tell us) is a bit older than ~1.2.14, as that was fixed a while ago.

**Comment by jsmalisa** [comment] 2021-03-30 04:29
Sorry,

Here it is

[image: image.png]


Kind regards

**Comment by cigamit** [comment] 2021-03-30 04:32
You might try that again, or simply just tell us the version.

**Comment by jsmalisa** [comment] 2021-03-30 05:20
Date Tue, 30 Mar 2021 15:19:20 +1000
Cacti Version 1.2.8
Cacti OS unix
RSA Fingerprint fe:7c:26:34:f7:24:de:fa:c0:d9:14:79:57:c9:23:77
NET-SNMP Version NET-SNMP version: 5.7.3
RRDtool Version Configured 1.7.2+
RRDtool Version Found 1.7.2
Devices 36
Graphs 2,372
Data Sources Script/Command: 13
SNMP Get: 35
SNMP Query: 1,977
Script Server: 70
Total: 2,095

**Comment by TheWitness** [comment] 2021-03-30 11:53
Upgrade to 1.2.15+  This is a duplicate of https://github.com/Cacti/cacti/issues/3823 and others.

**Closed by TheWitness** 2021-03-30 11:53 UTC
