### ISSUE TITLE
Graph Permissions Issue

### ISSUE THREAD

**Issue by mattymrm** [Cacti/cacti#275] opened 2017-02-06 14:44 UTC
created a new user, restrictive is set as the policy. Seems user has access by default to effective policy Granted so can view all graphs. Would have thought this should all be restricted (red) by default and then allow per graph permissions (green).

Also when user has access to only one graph or none they can still select the drop down to show ALL devices in cacti under Graph Preview Filters.

setting default graph policy to deny does not change the effective policy either.

cacti version 1.0.1

**Comment by pautiina** [comment] 2017-02-06 16:52
I think you need read my Issue first: #235

**Comment by mattymrm** [comment] 2017-02-06 17:30
I have read it, I'm using version 1.0.1, I have restrictive set, I have Default Graph Policy for this user set to deny under Graph Perms. I can't enable permissions for selected graphs because they all already have Granted as the effective policy which makes no sense.

Selecting over 1700 graphs and setting to revoke access under Graph Perms tab just kills the page.

Also shouldn't be allowed to see all the devices in the drop down under graph preview filters, I don't see any graphs but seeing all the devices listed is a no no as a standard user.

**Comment by cigamit** [comment] 2017-02-06 18:27
The way that restrictive works is that if the user has access to either 1) Graph or a combination of 2) Device & Graph Template, they will gain access to the graph.  If you goto the Graph Permissions, please copy and paste what you see there.  Anything in Green means that they will have access due to that rule.  Let us know what you come up with.

Also, please note that this is a behavioral change between earlier version of Cacti and the modern Cacti.  The permissions system in Cacti 0.8x was horribly broken, and so the new design is where we landed.

**Comment by mattymrm** [comment] 2017-02-06 18:36
I'm seeing -

Granted: Graph:(User), Device+Template:(User)

against all the graphs yet under the other tabs such as Device perms, Template perms its all saying Access restricted in red.

oddly and I don't know if it means anything the drop down Devices says Default> and the Template drop down says Default> apart from Graph perms where it just says Default in the drop down.

**Comment by mattymrm** [comment] 2017-02-06 18:45
think I managed to totally upset it now -

Warning: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: no parameters were bound in /var/www/html/cacti/lib/database.php on line 227

:)

**Comment by cigamit** [comment] 2017-02-06 23:08
MattyMRM,

I need the second half of that error.  There should be a stack trace just before/after that error.  Please post it here.

Please update the user_admin.php and see if it's more sane now.  Silly me, I only tested using 'admin' account which this enhancement would worked perfectly for.  It was not till I started testing with another user that I said 'geeze this was working just yesterday'.  Simple fix.

**Comment by mattymrm** [comment] 2017-02-06 23:25
hi,

hah will let you off as you have clearly been really busy :)

Works a treat now thanks :) However in graph preview filters I can drop down a list of all my cacti devices even though its been restricted still :(

as for that other error I see nothing else on the screen apart from what I pasted.

**Comment by mattymrm** [comment] 2017-02-06 23:30
if you want to re-create the issue, as a standard user that is restricted by everything, tree, devices etc but has access to say one graph, then under User Settings set it to Default View Mode Tree View. Then log in as that user.

**Comment by cigamit** [comment] 2017-02-06 23:31
The was the permission screen works is that if you have at least access to one graph for a device, you can see the device.  That is a change in behavior that was mandated.  We might be able to add an option if you have a need to restrict access to the device because of it's name, but right now, if you have access to at least one graph on the device, you can see the device.

**Comment by mattymrm** [comment] 2017-02-06 23:38
yeah I understand with say one device if that was in the drop down but I can literally see all devices even ones that the graph is not linked to.

**Comment by cigamit** [comment] 2017-02-06 23:46
Well, then that is a bug.  Let me squash it.

**Comment by cigamit** [comment] 2017-02-06 23:48
Wait, are you talking about Console -> Management -> Devices?

**Comment by mattymrm** [comment] 2017-02-06 23:55
nope, create a user, let it have access to one graph, deny it access to devices, trees, etc. Log in as that user then click preview view. Then you see Graph Preview Filters > Device.

**Comment by cigamit** [comment] 2017-02-07 00:06
So,I tested that, I set the policy for the user to Deny, Deny, Deny, Restrictive, then grant Access to one Graph, goto preview and it's right 'None' + the one Device.  You should attach some screen shots.

**Comment by mattymrm** [comment] 2017-02-07 00:08
hmm odd as im definitely not getting that. I can't really attach a screenshot as it gives away a lot of info :/

**Comment by mattymrm** [comment] 2017-02-07 00:11
i can PM you a login if I can even do it through this :)

**Comment by cigamit** [comment] 2017-02-07 00:19
Nah, I've confirmed with two separate user accounts and can not reproduce.  If you would attach screen shots of Graph Permissions, Device Perms, and Template Perms.  If uncheck the Exceptions each screen should be blank.  Which out the Graphs names if it's important.

**Comment by mattymrm** [comment] 2017-02-07 00:21
its all public facing devices as im an ISP so shows the names of the routers and IP addresses so unless I mask the whole lot out it will end up not showing you anything apart from a long box :)

**Comment by cigamit** [comment] 2017-02-07 00:22
Well, if the Device Perms are defaulted to Deny, then that screen will be empty, same for Templates, and on the Graphs page, Just white out the Graph names and show me the 'Effective Permissions' column.

**Comment by cigamit** [comment] 2017-02-07 00:27
This is all I want to see on the graphs page.  Of course it should say Restricted except for one which is the exact opposite as you see here.

<img width="353" alt="effectivepermissions" src="https://cloud.githubusercontent.com/assets/957322/22672471/d3fea848-ec99-11e6-8dd9-5e46ca36bc2c.png">

**Comment by mattymrm** [comment] 2017-02-07 00:34
<img width="1685" alt="screen shot 2017-02-07 at 00 24 43" src="https://cloud.githubusercontent.com/assets/25553853/22672635/13fab742-eccd-11e6-9adf-837753e05048.png">
<img width="1688" alt="screen shot 2017-02-07 at 00 25 08" src="https://cloud.githubusercontent.com/assets/25553853/22672636/14133f56-eccd-11e6-9e62-1567d6933e55.png">
<img width="1687" alt="screen shot 2017-02-07 at 00 25 20" src="https://cloud.githubusercontent.com/assets/25553853/22672639/14143578-eccd-11e6-99ed-6abe4140675e.png">
<img width="1685" alt="screen shot 2017-02-07 at 00 25 38" src="https://cloud.githubusercontent.com/assets/25553853/22672637/1413d858-eccd-11e6-9718-b3dfac2cf12c.png">
<img width="1689" alt="screen shot 2017-02-07 at 00 25 55" src="https://cloud.githubusercontent.com/assets/25553853/22672640/141d55a4-eccd-11e6-886c-476ef3231249.png">
<img width="1681" alt="screen shot 2017-02-07 at 00 30 00" src="https://cloud.githubusercontent.com/assets/25553853/22672638/1413d790-eccd-11e6-8f41-2f1bd58bda63.png">

**Comment by cigamit** [comment] 2017-02-07 00:37
That all looks right.  Let me see if I missed a commit.

**Comment by mattymrm** [comment] 2017-02-07 00:38
![image001](https://cloud.githubusercontent.com/assets/25553853/22672724/942129ba-eccd-11e6-943c-777b2b68ee3a.png)

that list which you can see ive blanked out shows all the devices when logged in as the user.

**Comment by cigamit** [comment] 2017-02-07 00:39
Hmm.  There must be a fly in the ointment.  Let me try this using the 'classic' skin.  That might be the issue.  We kept Classic for people who like looking at blue tombstones.  But it's less interesting.  I'm a fan of Dark.

**Comment by cigamit** [comment] 2017-02-07 00:40
Ding ding ding, we have a winner.  Classic theme!

**Comment by mattymrm** [comment] 2017-02-07 00:43
haha I don't mind too much what it looks like, to be honest im still crying over why my thold doesn't work so I went a bit crazy and just upgraded everything to no avail. :(

**Comment by cigamit** [comment] 2017-02-07 00:58
Did you open a ticket under the thold plugin area?

**Comment by cigamit** [comment] 2017-02-07 01:00
Resolved.  Closing this one.  Thanks for testing.  Open a thold issue if you can't figure things out.

**Closed by cigamit** 2017-02-07 01:00 UTC

**Comment by mattymrm** [comment] 2017-02-07 01:01
yeah and posted in the forum a while back. Literally re-installed it so many times and dropped the tables out. I thought it was CentOS 7 so started again with CentOS 6, a fresh install solved the problem so started re-creating everything and pulling templates in from old install then it stopped working again. :(

awesome thanks for sorting those other issues out! :)

**Comment by cigamit** [comment] 2017-02-07 01:06
Well, we have been doing truck loads of changes, and did not officially support an upgrade.  Things are working pretty well right now.  There were a few missing options that worked themselves out over the later parts of last week, and you may have noted some additional commits this morning from Browniebraun who has a big > 20k thold setup.  Also, in the 1.0.1 release we had a nasty bug that was corrected at noon today.

**Comment by cigamit** [comment] 2017-02-07 01:08
Can you get me the errors around that PDOStatement::execute() SQLSTATE[HY093] error.  That one is pretty important.

**Comment by mattymrm** [comment] 2017-02-07 01:11
it went bust in the last version of 0.8.x with 0.6.1 I think was the thold version. Used to work absolutely fine then I checked one day and it stopped. I trashed out the thold tables and started from scratch, reads value fine when going to create the template, seems to populate the tables in the database ok but when poller runs thold just shows 0 processed.

I have the latest code at the moment as I keep updating it in the hope it would start working again but alas no :(

**Comment by mattymrm** [comment] 2017-02-07 01:13
I can't see anything else on the page apart from that error message. Leave classic theme on and you should be able to see the same thing. Deny everything then under user settings set it to tree view. Then log in as a user.

If you need me to provide more info then ill do that if I know how?

**Comment by cigamit** [comment] 2017-02-07 01:15
In the Github version of thold we renamed a number of columns to be consistent with the Cacti schema.  This is the reason that we don't support upgrade.  There are several dev's that could pull it off, but this is something that we just don't want to get into.  It should be easy enough to recreate them in 1.0.x though.

**Comment by cigamit** [comment] 2017-02-07 01:16
That should be enough to reproduce it.  At least I know where in the code it is now.

**Comment by mattymrm** [comment] 2017-02-07 01:19
yeah but me dropping the tables would start it from scratch?

**Comment by mattymrm** [comment] 2017-02-07 01:27
also I can't now recreate that SQLSTATE error :( Tried everything.

**Comment by cigamit** [comment] 2017-02-07 01:27
Just uninstall, and re-install.  It'll do the dropping for you.

**Comment by mattymrm** [comment] 2017-02-07 01:27
nope its not dropping the tables like it used to, it leaves them there.

**Comment by mattymrm** [comment] 2017-02-07 01:36
figured it out on how to make it error. deny the lot but this first page is important to have it like the image.

![image002](https://cloud.githubusercontent.com/assets/25553853/22674059/c44f8840-ecd5-11e6-9288-2e7722a6f291.png)

**Comment by mattymrm** [comment] 2017-02-07 01:48
scratch that, its now dropping the tables when uninstalled :) It definitely wasn't doing that before.
