### ISSUE TITLE
Chart cannot view historical data，but it can view in realtime。

### ISSUE THREAD

**Issue by Yyp1gg** [Cacti/cacti#4979] opened 2022-10-26 08:58 UTC
- OS: centos8

- Version 1.2.22
Chart cannot view historical data，but it can view in realtime。

![image](https://user-images.githubusercontent.com/33254958/197982496-4f06c8e2-9d18-49e0-9a75-ee962feddc9a.png)
![image](https://user-images.githubusercontent.com/33254958/197982598-4828e53d-4c40-4c99-898d-4d4cd4600bf0.png)

**Comment by Yyp1gg** [comment] 2022-10-26 09:06
wanna cry

**Comment by TheWitness** [comment] 2022-11-02 02:24
I'm assuming that since there has been no communication on this that the problem is resolved.  Correct?

**Comment by Yyp1gg** [comment] 2022-11-07 08:13
> I'm assuming that since there has been no communication on this that the problem is resolved. Correct?

sorry,i missed the massage. the problem continues these days. T . T

**Comment by Yyp1gg** [comment] 2022-11-07 08:53
> I'm assuming that since there has been no communication on this that the problem is resolved. Correct?

FATAL: File '/var/www/html/cacti/rra/waf_traffic_in_243.rrd' is not writeable by 'apache'.   
is this the  'Make sure your permissions are set on the rra files correctly (should be the same as the Webserver user)'   ?
 how can i modify it

**Comment by bmfmancini** [comment] 2022-11-07 10:52
Chown - R rra/ apache:apache

(assuming your Webserver user is Apache)

**Comment by TheWitness** [comment] 2022-11-07 12:15
Could be SE Linux too.

**Comment by TheWitness** [comment] 2022-11-07 12:17
Closing, as this is more a support request for the forums.

**Closed** 2022-11-07 12:16 UTC
Labels: question
