### ISSUE TITLE
Undefined variable: remote_good in file: /usr/share/cacti/install/index.php on line: 689

### ISSUE THREAD

**Issue by mortenstevens** [Cacti/cacti#750] opened 2017-05-26 12:40 UTC
Hello,

I got this warning in the cacti.log after upgrading from 1.1.6 to 1.1.7:

2017-05-26 03:31:54 - CMDPHP PHP ERROR NOTICE Backtrace: (/install/index.php: 689 CactiErrorHandler)(/lib/functions.php: 4339 cacti_debug_backtrace)
2017-05-26 03:31:54 - ERROR PHP NOTICE: Undefined variable: remote_good in file: /usr/share/cacti/install/index.php on line: 689

PHP: 7.0.19

Any ideas? But my installation and the upgrade still works fine.

**Comment by reboot1983** [comment] 2017-05-26 15:50
Duplicate and solved in #726

**Comment by cigamit** [comment] 2017-05-27 12:43
Resolved, duplicate of #726

**Closed by cigamit** 2017-05-27 12:43 UTC
