### ISSUE TITLE
Undefined variable:  graph_start rrd.php  on  line: 823

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#2404] opened 2019-02-11 19:08 UTC
2019/02/11  13:47:13 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/thold/thold.php[135]:thold_edit(),  /plugins/thold/thold.php[1195]:get_current_value(),  /plugins/thold/thold_functions.php[3612]:rrdtool_function_fetch(),  /lib/rrd.php[823]:CactiErrorHandler())
--
2019/02/11 13:47:13 - ERROR PHP NOTICE: Undefined variable:  graph_start in file: /var/www/localhost/htdocs/cacti/lib/rrd.php  on  line: 823

**Comment by cigamit** [comment] 2019-02-21 04:12
This is resolved now according to @netniV.  Please update lib/rrd.php and if the issue is resolved, can you close the ticket?

**Comment by netniV** [comment] 2019-02-21 09:06
Correct, this was resolved in issue #2432 which appears to be a duplicate of this.

**Closed by netniV** 2019-02-21 09:06 UTC
Labels: resolved
