### ISSUE TITLE
Pressing Back often fails to work as expected

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1301] opened 2018-02-03 13:00 UTC
When browsing through screens, I'm often finding that pressing back keeps me on the screen I was just on.  When this happens, I noticed that quite often it is because there is a `nostate=true` on the address bar.

I'm looking at why and this seems to revolve around the `pushState` `handlePopState` functions but if there's any guidance can be given, I'd appreciate it.

**Comment by cigamit** [comment] 2018-02-03 14:10
The back button behavior has been broken for a while.  We have to have some history management functions to properly remove URL's from the history from callbacks.  I had attempted a hack, but obviously, it did not work so well and was not fully tested.  There is a closed bug that has been getting some strikes on this as well.

**Comment by cigamit** [comment] 2018-02-06 01:26
Duplicate of Issue #430

**Closed by cigamit** 2018-02-06 01:26 UTC
