### ISSUE TITLE
When a Data Query has a space, indexes may not be properly escaped

### ISSUE THREAD

**Issue by prottoy396** [Cacti/cacti#5768] opened 2024-05-30 16:37 UTC
**Describe the bug**
Mikrotik Queue Traffic dont show in graph (also real time) if the Queue name has a space & ( _ ) inside

**To Reproduce**
1. Linux Cent OS 7, Tried several versions of cacti. 
2. Add a queue in mikrotik ex: XYZ ABC _ XY - which include space & ( _ ) inside the queue name
3. Add a queue in mikrotik ex: XYZABC - which include no space & ( _ ) inside the queue name
4. Now if I add queue graph for both queue; "XYZABC" will show traffic with no issue, Where as " XYZ ABC _ XY" will not show any data.
5. Also I have noticed, the larger name of a queue graph, dont show the traffic, I am little confused actually, what is causing no traffic visible in queue.

**Expected behavior**
Queue name with a space & ( _ ) should behave the same and get traffic info.

**Screenshots**
![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/a7f73d1a-41b9-4a23-a8da-b5b7b228d5fc)
![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/99fe8a3d-a8f8-40a0-b822-b1c7ac73e9aa)
![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/94b74ca1-0697-4ebd-b75a-c74725c42798)
The Queue has traffic, but shows traffic_in & out 0 during troubleshoot, where another queue with no space always getting some value here instead of 0 always
![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/3f6ce581-7883-4a98-9ede-3d3d849a8f3a)

![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/eb0bbb57-5643-49d3-a3d4-22ee2b07b048)
Notice the RED and Green mark, I am pretty confused is it facing issue showing graph for the Queue Name which is a "larger name" or "Space and Special Character" in queue name. 
All these three queue has traffic in mikrotik, but only the smaller name maybe showing graph value in cacti, please check this bug

**Plugin (please complete the following information):**
 - Version: [2.4, 2.3, 3.1]
 - Source: [github]
 - Identifer: [yum package name]

**Desktop (please complete the following information):**
 - OS: [Cent OS 7 & 8]
 - Browser [chrome, firefox]
 - Version [latest]

**Additional context**
I am facing a issue for long. I have installed cacti 1.2.24 and 1.2.27 in a Cent OS 7 server. Tried installing each mikrotik plugin version on each server. My problem is

When I can creating any graph for Mikrotik Queue, it gets data if the Queue name has no (space & ( _ )  ) inside, but if there is any space & ( _ ) in the Queue name, there i got no graph at all in 5 min or 1 min even in real time. everything works fine with the queue name not having space & ( _ ).

Please suggest me what can i do now, already checked from several Mikrotik, tried to install several version of cacti and mikrotik plugin also.

**Comment by TheWitness** [comment] 2024-06-07 03:42
Can you show the poller cache for the entries with the space.  Post the image here.

Also, search the table "graph_local" for the "snmp_index" with the queue name and confirm that it includes the space.

**Comment by TheWitness** [comment] 2024-06-07 03:43
Example poller cache entries:

![image](https://github.com/Cacti/plugin_mikrotik/assets/1439914/56d4a9ad-db66-4642-a82c-9666f206c442)

**Comment by prottoy396** [comment] 2024-06-10 03:09
![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/12eb0581-b28d-4e55-8ccd-9486fffc09ba)
![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/4a934161-242c-4885-90d4-c95cc485e12e)
![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/397e7c2a-f14d-42be-8f04-b5df714cc848)

Mikrotik Real time - there is traffic
![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/accb3450-29d7-429c-94ac-67f619e86d83)

Here what I am getting difference is CAPITAL and SMALL Letter, also this queue has no space - Still getting no graph, debug is also attached.


And I didnt get this - Also, search the table "graph_local" for the "snmp_index" with the queue name and confirm that it includes the space....

**Comment by TheWitness** [comment] 2024-06-10 11:44
Reindex the device. It should fix the issue.  It's a good thing to schedule reindexed periodically to pick up changes that are not uptime related.

**Comment by prottoy396** [comment] 2024-06-10 11:50
I have already done it from edit Device > Reindex

Didn't solved

**Comment by TheWitness** [comment] 2024-06-10 11:59
Okay, interesting.

**Comment by TheWitness** [comment] 2024-06-10 12:00
What is stored in the queues table?

**Comment by prottoy396** [comment] 2024-06-10 12:01
You mean mysql data table?

**Comment by TheWitness** [comment] 2024-06-10 12:15
Yes.  So, I think I know this is happening, and the workaround is no longer required.  I'll propose a change in the next day or so.  I just need to find enough time to write it.

**Comment by prottoy396** [comment] 2024-06-10 15:02
okay then, I am waiting 🫡

**Comment by TheWitness** [comment] 2024-06-10 20:07
[MikroTik_Device.xml.gz](https://github.com/user-attachments/files/15778512/MikroTik_Device.xml.gz)

Here is the updated Device Template.  The files of interest are: 

ss_mikrotik_interfaces.php
ss_mikrotik_qtrees.php
ss_mikrotik_queues.php

Everything else should be default.  You should re-index as soon as you update the Device Package.  Also, the Data Sources for the Objects that include spaces will need to be Edited and you will have to manually update the Index Value when editing the Data Sources for those with a space.

**Comment by prottoy396** [comment] 2024-06-11 07:44
I have downloaded the New Template to cacti/plugin/mikrotik/templete/ and imported it from cacti/cli/ > php import_package.php MikroTik_Device.xml.gz


Then I deleted the old graph, reindexed the device with verify all - then added the graph again. But getting null value yet, Sharing DataSRC debug and graph with Mikrotik Queue Live status.. If I am missing anything?

![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/97e954ab-f04d-4d43-9008-e6fbc987cae5)
![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/166d0b16-082d-4572-8aaa-4ffdb1449aa4)

**Comment by TheWitness** [comment] 2024-06-11 09:42
Upload an image of the polar cache entries.

**Comment by prottoy396** [comment] 2024-06-11 10:56
![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/bca360d6-63b8-44aa-9fcd-69fca682ee07)

Note : You may find the QsName diff, cause I have shorted it to give a try. This should be a issue I guess, I have deleted old graph, deleted that row from SQL table (plugin_mikrotik_queue), then Reindexed and added graph for the Brand new Short Name. 

I notice that there is space in Data src name, Do I have to remote it?

**Comment by TheWitness** [comment] 2024-06-11 11:01
There should be a space.  The question is, is data streaming into the rrdfile?

**Comment by prottoy396** [comment] 2024-06-11 11:02
If I update a QueueName from Mikrotik, I need to manually delete the data from SQL plugin_mikrotik_queue, then re-index can bring the new QueueName, othewise it get duplicated in data query table from Device-Mikrotik Queue Traffic

**Comment by TheWitness** [comment] 2024-06-11 11:05
I also need to review the data collectors themselves too.

**Comment by TheWitness** [comment] 2024-06-11 11:07
Did the database entry not include the space?  If so, I need to update the collector too.

**Comment by prottoy396** [comment] 2024-06-11 11:08
![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/9ac816ea-478a-494b-bce4-b51eef1d928c)

![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/f0d722b4-2ccc-4b98-bec2-c1b66ad88ac8)

**Comment by prottoy396** [comment] 2024-06-11 11:09
> Did the database entry not include the space? If so, I need to update the collector too.

Database entry also have the space
![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/1ae0430e-d313-4c74-b1f3-a70be5229093)

**Comment by TheWitness** [comment] 2024-06-11 11:50
I don't see a space there. I see underscores.

**Comment by prottoy396** [comment] 2024-06-11 11:54
You can try to zoom in, there is a space after _ EDxxx

**Comment by TheWitness** [comment] 2024-06-11 11:59
Okay good.  Can you test the script output?  Go to the documentation and lookup testing the script server and follow those instructions.  Let's see what output it generates.

**Comment by prottoy396** [comment] 2024-06-12 04:04
Maybe I am confused about which documentation you are talking about, I have already search for it but no luck. Can you please share the document reference here, I will check further

**Comment by prottoy396** [comment] 2024-06-12 04:11
Am I doing the right?
![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/b4ca8d84-1397-41c4-bd83-f0adb81fca46)

**Comment by prottoy396** [comment] 2024-06-12 04:17
See What I found, I have added " " around the Queue name border and its getting value now. Any Line with space is working after I am adding the "". Maybe editing the code can solve it for good, There will be no Space/Special Character combination issue anymore

Actually the script is dividing the Single Queue name to Separate name due to Space. 

![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/b02bc882-199c-4cd8-8faa-4b6975e8f664)

**Comment by TheWitness** [comment] 2024-06-12 10:27
> Am I doing the right?
> ![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/b4ca8d84-1397-41c4-bd83-f0adb81fca46)
> 

Yes, this is correct.  This tells us that the reindex is causing an issue.  So, that's in the three scripts. I'll look again into it today.

**Comment by TheWitness** [comment] 2024-06-12 10:28
> See What I found, I have added " " around the Queue name border and its getting value now. Any Line with space is working after I am adding the "". Maybe editing the code can solve it for good, There will be no Space/Special Character combination issue anymore
> 
> Actually the script is dividing the Single Queue name to Separate name due to Space. 
> 
> ![image](https://github.com/Cacti/plugin_mikrotik/assets/171273049/b02bc882-199c-4cd8-8faa-4b6975e8f664)
> 

You should not have to do this ..

**Comment by prottoy396** [comment] 2024-06-12 10:56
> > Am I doing the right?
> > ![image](https://private-user-images.githubusercontent.com/171273049/338820127-b4ca8d84-1397-41c4-bd83-f0adb81fca46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODk5NTQsIm5iZiI6MTcxODE4OTY1NCwicGF0aCI6Ii8xNzEyNzMwNDkvMzM4ODIwMTI3LWI0Y2E4ZDg0LTEzOTctNDFjNC1iZDgzLWYwYWRiODFmY2E0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxMDU0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGE0NTAyZTVjYTQ5MDhlMDhiYTg4NWZlMDVhNWZmMzEzNjY0ZGJjZjgzYjI3OTM1NTM1NTQ4ZTJiZDU3NDg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.53Ut1_KOvoQUY0o5p8J9M3ikVpYE1OUHO7DrSsaujRk)
> 
> Yes, this is correct. This tells us that the reindex is causing an issue. So, that's in the three scripts. I'll look again into it today.

Great!!! I will be waiting

**Comment by TheWitness** [comment] 2024-06-12 13:17
Okay, I've tracked this one down.  Transferring to a Cacti Issue, and I will be renaming it.  If you are at 1.2.27, there are 4 files to update.  Thanks for pushing me to get this resolved.  I'm also removing the upper case conversion for the Queue Names, but separately.

**Comment by TheWitness** [comment] 2024-06-12 13:20
@prottoy396, the issue is fixed now.  Update and don't forget to re-populate the poller cache.

**Comment by prottoy396** [comment] 2024-06-12 17:39
> @prottoy396, the issue is fixed now. Update and don't forget to re-populate the poller cache.

Yet its solved now, Working fine here too. Cheers 🍻

**Closed** 2024-06-13 03:34 UTC
Labels: bug, resolved, confirmed, type:bug, status:confirmed
