### ISSUE TITLE
Regarding #1617, and editing the Suggested Values still not working

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#1751] opened 2018-07-25 11:22 UTC
I apply the patch proposed int this Issue #1617, it's still not working, same error message, but now no error in any log

And I'm on 1.1.38

**Comment by netniV** [comment] 2018-07-26 11:07
Did you set your t_title fields to blank where they are currently '0' ?  1.1.38 doesn't pick up on the fact that they are zero and considers them non-empty.

**Comment by netniV** [comment] 2018-07-26 11:56
What I mean is that If you look at that previous issue, you need to run the SQL that sets t_title to blank when it's zero.

**Comment by cigamit** [comment] 2018-07-27 01:39
We will need a screen show of the error.  First, suggested values are not editable.  That would be a nice feature enhancement.  But, I can confirm that everything is working properly in the develop branch.  Once we have your output, we can decide what needs or can be done, but we are focusing on 1.2.

**Comment by netniV** [comment] 2018-07-27 07:53
Note, when taking screenshots, you can paste directly into the input box on GitHub and it will automatically upload and link the image directly into your post (see above).

**Comment by netniV** [comment] 2018-07-27 08:33
OK, so looking at your device, you've got a custom graph template you are using (**In/Out Bits with plus/minus** is not a standard one).  Can you post a screenshot of the graph templates suggested values, and then the data source template's suggested values too.

**Comment by arno-st** [comment] 2018-07-27 09:12
I can do it with another graph template:
![image](https://user-images.githubusercontent.com/25684899/43312466-a898ad12-918d-11e8-8774-876171dabe4c.png)

![image](https://user-images.githubusercontent.com/25684899/43312475-adc69aec-918d-11e8-9d9d-1859183c69fc.png)

Standard one in this case

**Comment by netniV** [comment] 2018-07-27 09:46
When you do this, are there any errors appear in the log files?

**Comment by netniV** [comment] 2018-07-27 10:48
Your version of data_queries and mine aren't the same.  Different day, different data_queries ;-)

**Comment by arno-st** [comment] 2018-07-27 11:36
Don't log the time stamp of the error message i give, you i didn't have the old one, but the message was that
ERROR PHP NOTICE: Undefined variable: header in file: /usr/share/cacti/site/data_queries.php on line: 255

now the line should be different, I think now it's 260

And glad you can see the version and date from my print screen.

**Comment by netniV** [comment] 2018-07-27 12:14
That is interesting, because I've just checked through form_save() and it all appears correct.  Everywhere it uses $header, it's been primed before it.  Are you running from all the latest 1.2 sources? Or have you cherry picked some parts?

**Comment by arno-st** [comment] 2018-07-27 12:19
I'm still running 1.1.38, and I just copy the patch who was provided into the bug fix 1751
but since I'm running this server as test server, maybee I should go to 1.2 right a way

is that the best far all of us ;) ?

**Comment by netniV** [comment] 2018-07-27 12:56
if it's a test server, go for it 👍   We're going to be hitting beta-lockdown soon anyway so there shouldn't be too much different between now and then.

**Comment by cigamit** [comment] 2018-07-27 23:01
I'm going to close this for now.  Keep talking though.  The issue is resolved in 1.2.

**Closed by cigamit** 2018-07-27 23:01 UTC

**Comment by TakeMeNL** [comment] 2018-08-29 20:52
Just ran in this problem today, i need to add the the field. Is there a workaround?

**Comment by cigamit** [comment] 2018-08-31 02:10
There is an open pull request with a patch for 1.1.38.  Check it out.
