### ISSUE TITLE
graph filtering not working

### ISSUE THREAD

**Issue by ansarian1601** [Cacti/cacti#3857] opened 2020-10-13 11:50 UTC
# Describe the bug

## Expected behavior

![image](https://user-images.githubusercontent.com/72037735/95857484-88ee2380-0d68-11eb-9dc7-6996c92c249c.png)

**Comment by cigamit** [comment] 2020-10-13 14:26
Duplicate of https://github.com/Cacti/cacti/issues/3797

**Closed by cigamit** 2020-10-13 14:26 UTC
Labels: duplicate

**Comment by netniV** [comment] 2020-10-13 15:33
I'm glad you understood that 👍

**Comment by cigamit** [comment] 2020-10-13 15:39
At first it was confusing, because it was a screen shot of a screen shot pasted over another screen shot into MS Paint.   But then I just looked at what the preset was set to versus the graph and knew it was the same thing that people have posted about in the forums 50 different times.
