### ISSUE TITLE
Strange poller errors

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#1103] opened 2017-11-26 18:54 UTC
snmpwalk: Unknown host (.1.3.6.1.4.1.14988.1.1.1.2.1.3.76.94.12.2.19.25.2)
snmpwalk: Unknown host (.1.3.6.1.4.1.14988.1.1.1.2.1.3.76.94.12.2.19.25.2)

I did a search over database and I cant see that host in column hostname.
How to debug this?

**Comment by netniV** [comment] 2017-11-27 08:28
Try temporarily increasing your logging levels to see what is occurring around the same time.  You are added / updating hosts when these errors occur?  Are they occurring roughly in time with your polling intervals?

**Comment by interduo** [comment] 2017-11-27 10:11
> Are they occurring roughly in time with your polling intervals?
Yes

I will try to find more in debug log.

**Comment by netniV** [comment] 2017-11-27 10:29
Then I would ordinarily say, the chances are, you have specified an FQDN against a host and that name is not resolving correctly or you've specified an IP address that is invalid.  However, if you do try a command line SNMPWALK with a bad hostname, it echos the hostname:

```
root# snmpwalk badhost.doesnotexistatall.com
snmpwalk: Unknown host (badhost.doesnotexistatall.com)

```
So, this would suggest you have no hostname given, as the OID (the numbers in brackets) are displayed, this is being interpreted as the hostname (the OID usually comes after the hostname on the command line).  Try running the following query:

```
select local_data_id, description, host_id, pi.hostname as poller_hostname, h.hostname from poller_item pi left join host h on h.id = pi.host_id where trim(coalesce(pi.hostname,'')) = '' or trim(coalesce(h.hostname,'')) = '';
+---------------+-------------+---------+-----------------+------------+
| local_data_id | description | host_id | poller_hostname | hostname   |
+---------------+-------------+---------+-----------------+------------+
|           101 | mytesthost  |      12 |                 | 10.10.80.8 |
|           101 | mytesthost  |      12 |                 | 10.10.80.8 |
+---------------+-------------+---------+-----------------+------------+
```

Description and hostname comes from the host table.  The other three columns come from the poller_item table.  If that query returns no results, then it isn't a blank hostname issue and we need to look elsewhere.

**Comment by interduo** [comment] 2017-11-27 10:46
MariaDB [cacti]> select local_data_id, description, host_id, pi.hostname as poller_hostname, h.hostname from poller_item pi left join host h on h.id = pi.host_id where trim(coalesce(pi.hostname,'')) = '' or trim(coalesce(h.hostname,'')) = '';
Empty set (0.02 sec)

Now, I noticed that only occurs when spine is set as a poller.

**Comment by netniV** [comment] 2017-11-27 12:36
What version of Spine are you using?

**Comment by interduo** [comment] 2017-11-27 12:48
# spine --version
SPINE 1.1.21  Copyright 2004-2017 by The Cacti Group

**Comment by netniV** [comment] 2017-11-27 14:15
OK.  It's actually nothing to do with spine, I just asked that in case I could find anything else...

It would appear that with some debugging, I have found:

> cacti_log: no date format set
> lib/database.php at 382
> lib/plugins.php at 62
> include/global_form.php at 2276
> include/global.php at 325
> include/auth.php at 27
> clog.php at 27
> 
> date_time_format(u): using 4
> include/global.php at 335
> include/auth.php at 27
> clog.php at 27

So between those two lines, the dateformat somehow becomes set.  This obviously needs to occur earlier in the schema of things.

**Comment by interduo** [comment] 2017-11-27 14:21
I did a new compilation of spine instead of using packages from debian and readd graphs.
The timestamp inaccuracy still exists."/" instead of "-"

The error:
```
snmpwalk: Unknown host (.1.3.6.1.4.1.14988.1.1.1.2.1.3.76.94.12.2.19.25.2)
snmpwalk: Unknown host (.1.3.6.1.4.1.14988.1.1.1.2.1.3.76.94.12.2.19.25.2)
```
Doesn't exist anymore.

**Comment by netniV** [comment] 2017-11-27 14:26
Thinking about this more.... the 4 is wrong... I was expecting that to be 1.  So let me investigate further.

**Comment by netniV** [comment] 2017-11-27 14:29
Spine is hard coded.  Look for the following line:

> if (strftime(flogmessage, 50, "%Y-%m-%d %H:%M:%S - ", now_ptr) == (size_t) 0) {

Changing that to slashes, will fix spine, but shouldn't that really read from the DB too?

**Comment by netniV** [comment] 2017-11-27 15:04
OK, I've submitted a fix with my existing pull request #1107

**Comment by netniV** [comment] 2017-11-28 09:50
Apologies, I have removed the comments that were not for this issue.  Could you try adding the following code in functions.php around line 1793:

```
if ($err != 0) file_put_contents("/usr/share/cacti/site/log/exec.log","Error " . $err . " " .$command_line, FILE_APPEND);
```

The full function looks like:
```
function exec_into_array($command_line) {
        $out = array();
        $err = 0;
        exec($command_line,$out,$err);
        if ($err != 0) file_put_contents($config['base_path'] . '/log/exec.log","Error " . $err . " " .$command_line, FILE_APPEND);
        return array_values($out);
}
```

Leave the system to run for a while and then check the exec.log for the command line being used.  Note that this only logs the output if an error is returned by the executed command so there should not be a lot in the file.  On my system, snmpwalk returned error 1.

**Comment by netniV** [comment] 2017-11-28 09:51
If the issue is resolved, please close this issue.

**Comment by cigamit** [comment] 2017-12-02 17:37
This to me looks like a data input issue with a script based input method, and likely not a Cacti builtin one.  The script appears to be calling snmpwalk using bad syntax (missing the hostname), and not properly handling stderr, which should be re-directed.

If there is an issue, it's in spine.  We've had some requests in years past to separate stdout from stderr when performing popens and also handling return codes as well.  Those are both spine issues though.

Giving interduo a few days to respond before closing.

**Comment by netniV** [comment] 2017-12-02 18:02
@cigamit if you reread his last comment as I had to when he posted it, the issue no longer exists just the dare format issue. I’ll open a separate issue for that.

**Comment by cigamit** [comment] 2017-12-02 18:18
Okay.  Just going to close then.

**Closed by cigamit** 2017-12-02 18:18 UTC

**Comment by interduo** [comment] 2017-12-03 10:45
Resolved properly. Thanks.
