### ISSUE TITLE
Capability to hide graphs associated with disabled devices at the System level

### ISSUE THREAD

**Issue by riversdev0** [Cacti/cacti#4608] opened 2022-03-11 18:50 UTC
# Feature Request

## Is your feature request related to a problem? Please describe

It happens occasionally for me that I disable a device in Cacti while some design changes are happening on the network, like when a device physically moves locations.  When I disable a device, the graphs associated with that device generate an image that says "unknown rrdtool error".  This has been a point of curiosity for me in the past as to the reason why the graph is "blanked out", rather than just ceasing to receive fresh data.  Additionally, I've noticed that it is not possible to sort the graph's order on a Tree when the associated device is disabled since the graph does not appear in the sorting list.

## Describe the solution you'd like

I think the following three changes would make sense:
1. To have graph images render useful graphs (as normal) despite a device being disabled, versus the error message.
2. To always reveal the existence of a graph on a Tree while editing the Tree, versus hiding graphs attached to disabled devices.
3. To have a checkbox in the Settings that says "Hide graphs for disabled devices".  The default would be "no", to maintain existing functionality.  If enabled, however, all graphs for any disabled device would be hidden while viewing Trees.

## Describe alternatives you've considered

I have not considered alternative options, but I am happy to listen to the perspectives of others who might use Cacti in a different way or environment than I do, or have an alternative solution than mine.

## Additional context

1. I'm interested in hearing any alternative viewpoints on this subject.
2. I'm willing to contribute to the development effort, but I didn't want to start without some type of endorsement from the stakeholders.

**Comment by TheWitness** [comment] 2022-03-11 20:09
There is a setting for this today under a users profile to Hide Disabled devices.  I guess it could also be moved to a system setting.  We would support a pull request that allows the two to be blended.  In order words, if the System Setting were to block, then the users Setting would have to be hidden from the users profile page (via javascript), and the system setting made to override the users.

Does not seem like a lot of work.  The file `auth_profile.php` is where the user level settings is, the `include/global_settings.php` is where you would put the global setting, and then from a logical perspective, just `grep` the code for the current setting.

When doing pull requests, ensure you are using HARD tabs, and follow our PSR guide.

**Comment by riversdev0** [comment] 2022-03-11 20:31
Ha!, I never noticed that setting there, thanks for pointing it out.  I think it makes better sense as a User Setting versus a System Setting, so I would support leaving it alone at this point.

However, I have my Hide Disabled set to Enabled, but the graph image is still present with the error, "Unknown RRDtool Error" embedded in the PNG.  I disabled the setting and now the graph image shows a graph with no data (which is expected, since Cacti has not been polling the device).  So, then I guess the problem is simply that when the setting is enabled (to hide graphs), the graphs don't actually _hide_, they just _show an error_.

So then I guess this is half bug-fix and half feature-request.  Regarding the feature request, I would just want to always reveal the existence of a graph on a Tree while editing the Tree on the Console tab, versus hiding graphs which are attached to disabled devices.  Regarding the bug-fix, would you like me to open a separate issue, use this existing issue, or some alternative option?

**Comment by TheWitness** [comment] 2022-03-11 20:37
Upload a screen shot with both settings and let us know your cacti version.

**Comment by riversdev0** [comment] 2022-03-11 20:58
I'm on Cacti release 1.2.19.

Here is my User Setting, where the option is enabled to hide:
![image](https://user-images.githubusercontent.com/7363202/157961555-19f46823-c2bb-45af-82fd-75a563f33ca1.png)

Here is my Tree where the graph image still appears, but displays the error:
![image](https://user-images.githubusercontent.com/7363202/157962437-e286c2cd-58a0-48f5-866e-404605ad3159.png)

Upon further checking, when I disable the _Hide Disabled_ setting (so that they show), then I am able to change their sort order while editing a Tree on the Console tab, since they do appear.  So that's excellent!

**Comment by TheWitness** [comment] 2022-03-11 21:00
Can you update that setup to 1.2.x branch?  Depending on how you deployed, and the OS, it's pretty easy to pull off.  What OS are you using?

**Comment by TheWitness** [comment] 2022-03-11 21:02
Never mind.  I just reproduced it.

**Comment by TheWitness** [comment] 2022-03-11 21:03
Going to log a new issue...

**Comment by TheWitness** [comment] 2022-03-11 21:11
Logged.  Should be fixed pretty soon.

**Comment by riversdev0** [comment] 2022-03-11 21:12
Wonderful, thank you!  I was going to have to go spelunking to fix it myself.  I'm grateful for your help!

**Comment by TheWitness** [comment] 2022-03-11 21:42
Okay, it';s fixed.  You should be able to cherry pick the two relevant changes in `lib/auth.php`.  Don't use the whole file, just look at the diff from the commit that fixed it and you can modify your `lib/auth.php` directly.  The change in `lib/functions.php` is really intended for 1.2.20 and there were a few PSR changes that are only cosmetic.

**Comment by riversdev0** [comment] 2022-03-17 20:26
Based upon the bug fix, I propose that this issue be closed.  My enhancement request was based upon the assumption that the bug was expected behavior, therefore I don't think we need to proceed with an enhancement.

**Comment by TheWitness** [comment] 2022-03-17 22:54
Cool.

**Closed by TheWitness** 2022-03-17 22:54 UTC
Labels: enhancement
