### ISSUE TITLE
Different Timestamps for SQL DEVEL 

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#1104] opened 2017-11-26 19:18 UTC
Normal is 2017-11-26
DEVEL (only for DBCALL DEVEL) is 2017/11/26.

Is it by design?

**Comment by netniV** [comment] 2017-11-27 08:26
This could be the difference between a date manually formatted by Cacti and a date formatted by the database.  Where are you seeing the differences?

**Comment by interduo** [comment] 2017-11-27 10:12
In clog.

**Comment by netniV** [comment] 2017-11-27 10:13
Do you mean, when comparing the Cacti log using the website vs looking directly at the file?

**Comment by interduo** [comment] 2017-11-27 10:16
In clog and in the logfile there are a different timestamps format (DBCALL devel vs Normal messages Error/Warnings/Statistics).

**Comment by netniV** [comment] 2017-11-27 13:20
OK, I can see that if I put my logs into DEBUG level, there are a mixture of using slashes (/) and hyphens (-). Before I put the system into debug level, I was already seeing that Spine seems to log with hyphens.

The reason for this would appear to be down to cacti_log() function itself and how it checks for **CACTI_DATE_TIME_FORMAT**.  If that is not defined, it uses the hyphenated format that is hard coded.  However, **CACTI_DATE_TIME_FORMAT** is defined within global.php using the **date_time_format** function.  

The **date_time_format** function checks If a session exists for a user, then it uses **read_user_setting** for the date format, otherwise it reverts to the overall configuration setting via **read_config_option**.  Once it has the desired format, it checks that a default date character is set by calling read_config_option, and if not, reverts to a slash.

If you run the following SQL statement, you will probably find that your default character is actually set to a hyphen, not a slash:

```
select * from settings where name = 'default_datechar';                                                                      +------------------+-------+                                                                                                        | name             | value |
+------------------+-------+
| default_datechar | 1     |
+------------------+-------+
1 row in set (0.00 sec)
```

Mine was which should correspond to a slash given the following array:
```
$datechar = array(
        GDC_HYPHEN => '-',
        GDC_SLASH  => '/',
        GDC_DOT    => '.'
);
```

I even checked against several uses on my system, they are all using the slash which I verified against global_constants.php which has "define('GDC_SLASH', 1);".  So, the question remains, how does the date_time_format become managed by different processes?

Are you using SPINE? Because I know that has a hard coded format for the date time set to use the hyphenated version.  It makes me wonder if the format issue is a result of using CMD.PHP so I'm going to check that out next.

**Comment by netniV** [comment] 2017-11-28 09:27
_Originally added on the wrong issue_

Spine is hard coded. Look for the following line in util.c:

if (strftime(flogmessage, 50, "%Y-%m-%d %H:%M:%S - ", now_ptr) == (size_t) 0) {

Changing that to slashes, will fix spine, but shouldn't that really read from the DB too?

OK, I've submitted a fix with my existing pull request #1107 

The 4 was correct as that was the datetime format, and a later value of 1 is the system default separator.  The issue is that the date_time_format isn't called until after all the includes.  By moving the call before the includes, we also need to define the array so I took it from global_arrays.php and put it in its own include.  The other values used by date_time_format are defined in global_constants.php so these are included further above.

Spine probably needs looking at too so that it makes a one time database query for the value of the system default, but I haven't looked properly at spine yet to make sure I wouldn't cause other issues.

**Comment by netniV** [comment] 2017-11-29 15:03
Created a pull request of #1113 which separates out the previous #1107 pull request into individual components.

**Comment by cigamit** [comment] 2017-12-02 16:58
Should be a spine issue logged for this.  If you have not opened it already, please do so.  Thanks!

**Comment by cigamit** [comment] 2017-12-02 17:06
After taking a look at this change, I do not believe there is a case to view the users settings.  That is only for displaying on the output and there is a separate function for that.  I believe that in a future release, we should remove the function from lib/reports.php and use the default.  For now, I'm just going to remove the user portion of the formatting.  I will close the pull request as I'm going to do this just a little bit differently.

**Comment by netniV** [comment] 2017-12-02 17:12
I think thing comment was on the wrong issue @cigamit

**Comment by cigamit** [comment] 2017-12-02 17:18
Marking this resolved now.  Please look at the solution and comment.  It's not perfect, but I just don't want to introduce a new include file for a single item.

**Comment by netniV** [comment] 2017-12-02 17:24
That works. Though the only potential bug maybe if there is ever an unlikely situation where both functions are called? At the moment you don’t actually check the value is already set so could potentially overwrite it with a different value if one is changed. Maybe add a comment to ensure places are updated together.

**Comment by cigamit** [comment] 2017-12-02 17:33
I did a review,  functions are essentially identical with the exception of a single log call.  The original author of the Nectar plugin added quite a bit of logging to his plugins.  Same applies for Aggregate, another of his merged plugins.  At some point, we have to 'prune' some of the excessive logging, though it's not a high priority at the moment.  Merging those 20 plugins was a double edged sword.

**Closed by cigamit** 2017-12-02 17:33 UTC

**Comment by netniV** [comment] 2017-12-07 13:22
For reference, I have added [Issue 39 - spine_log() should obey cacti_log() date/time formatting rules](https://github.com/Cacti/spine/issues/39) and [Pull Request 40](https://github.com/Cacti/spine/pull/40) to the spine repository which should address the spine side of this issue.
