### ISSUE TITLE
New data input method not passing hostname value to script

### ISSUE THREAD

**Issue by wtollett-usgs** [Cacti/cacti#4380] opened 2021-08-27 23:19 UTC
### Description
Data input method created on version 1.2.17 will not pass hostname value to a custom python script. We have other custom scripts going back to version 0.8.8 that are doing the same things and work fine, but this is the first new one I've created on this version.

### How to reproduce
1. Create new data input method with <ip> somewhere in the input string.
2. Create input field with name ip, and Special Type Code of 'hostname'
3. Create new data source template using previously created data input method
4. Create new graph template that uses the just created data source template
5. Create new device with valid IP in the hostname field and try to create the new graph for that device
6. Doing so fails with Graph Not created due to bad data error, and output of script shows no value passed for the IP address

### Other research done
I looked at the other threads around here that seem to have the same issues, but as far as I can tell there's nothing wrong with my setup. Hopefully I just overlooked something obvious.

### Screenshots
Data Input Method:
![1](https://user-images.githubusercontent.com/27027354/131197202-d6a55a40-b2c8-4a56-96c0-c0d025a18d80.png)

Input Field
![2](https://user-images.githubusercontent.com/27027354/131197217-d60ca829-d9a5-4707-b462-1cac5db76ade.png)

Data Source Template
![3](https://user-images.githubusercontent.com/27027354/131197233-f3c5e978-df20-4bae-9961-c40100d33854.png)

Device creation
![4 5](https://user-images.githubusercontent.com/27027354/131197287-3c827963-da74-43ee-a50c-5f037408bfe7.png)

Graph creation attempt
![4](https://user-images.githubusercontent.com/27027354/131197270-4944ef7c-df4b-49cf-9bea-0b3842861c4e.png)

Script output of sys.argv[:] values
![5](https://user-images.githubusercontent.com/27027354/131197309-dab99b22-b177-4191-a366-fe31ec487168.png)

MySQL data_input_field query
![6](https://user-images.githubusercontent.com/27027354/131197369-c1aa143a-1474-4476-9f10-ebbda16c1938.png)

MySQL data_input definition
![7](https://user-images.githubusercontent.com/27027354/131197380-fea18d29-d9c2-4c7e-8211-b1823fbd29b5.png)

**Comment by netniV** [comment] 2021-08-31 02:30
I believe that this may have been correct as part of 1.2.18 because there was a few changes to that data source verification code.

**Comment by TheWitness** [comment] 2021-09-06 15:13
This one is interesting, and deals with the `hostname` special type code.  It's more of a push item though.

**Comment by TheWitness** [comment] 2021-09-06 15:16
Before we get all headlong into fixing this, can you ensure that this dropdown is set for all the Data Sources?

![image](https://user-images.githubusercontent.com/1439914/132237725-89d6720a-799c-417b-8beb-c5c3837605a2.png)

I noticed in your example, it wasn't.  After you have done that, you should re-save the host, or better yet, re-create the graph.

**Comment by TheWitness** [comment] 2021-09-06 15:32
So, there was not much change to the code.  Run this query and see what comes back.

```sql
SELECT data_name, type_code, value FROM data_input_fields LEFT JOIN data_input_data ON (data_input_fields.id = data_input_data.data_input_field_id) WHERE data_input_fields.input_output = 'in' and type_code='hostname';
```

You should see a `data_name` of `ip` for your host when that comes back.

**Comment by wtollett-usgs** [comment] 2021-09-07 18:27
> 
> 
> I believe that this may have been correct as part of 1.2.18 because there was a few changes to that data source verification code.

I'd prefer to wait for the package to make its way to the EPEL8 repo, but if upgrading manually will fix the issue, I can do so.

> 
> 
> Before we get all headlong into fixing this, can you ensure that this dropdown is set for all the Data Sources?
> 
> ![image](https://user-images.githubusercontent.com/1439914/132237725-89d6720a-799c-417b-8beb-c5c3837605a2.png)
> 
> I noticed in your example, it wasn't. After you have done that, you should re-save the host, or better yet, re-create the graph.

I had noticed that too and already corrected it. Not the issue.


> 
> 
> So, there was not much change to the code. Run this query and see what comes back.
> 
> ```sql
> SELECT data_name, type_code, value 
> FROM data_input_fields 
> LEFT JOIN data_input_data 
> ON data_input_fields.id = data_input_data.data_input_field_id
> WHERE data_input_fields.input_output = 'in' 
> AND type_code = 'hostname';
> ```
> 
> You should see a `data_name` of `ip` for your host when that comes back.

Nope, nothing for this specific IP. There are hundreds of rows returned as we're monitoring a decent number of devices. There are a handful of results where the value field is empty -- is that expected?

**Comment by TheWitness** [comment] 2021-09-08 17:33
Did you delete the graph and recreate it afterwards?  Yes, I see them at null from time to time too and I'm not entirely certain.  Upload your graph template so we can muck with it.

**Comment by wtollett-usgs** [comment] 2021-09-09 01:15
Yep, recreated the graph. Just did it again to be sure. Problem is still that the hostname value isn't being passed to the script: (output from piping stderr to php log file)

`[08-Sep-2021 15:12:06] WARNING: [pool www] child 2496032 said into stderr: "['/usr/share/cacti/scripts/tristar_mppt.py', '', '502']"`

That empty string between the script and the 502 should be the IP address.

Graph template with all dependencies attached...
[cacti_graph_template_tristar_mppt_-_current.zip](https://github.com/Cacti/cacti/files/7132623/cacti_graph_template_tristar_mppt_-_current.zip)

**Comment by TheWitness** [comment] 2021-09-15 12:12
I'm going to mark this one as related to #4352.  Please update to the latest 1.2.x branch and see if you can reproduce this there.

**Comment by TheWitness** [comment] 2021-09-15 12:13
Though I did have to create a phantom script to emulate what you did in python, when run, everything populated.  Please remove the old data sources and graphs before creating the new one after you've done the full update.

**Comment by netniV** [comment] 2021-09-25 00:43
So there are several reasons this could fail:

- you try to run a script that is not executable
- you have multiple output fields but have not spaced it correctly
- you have not terminated your output with \r\n
- you have extra spaces at the end of the line
- you have not assigned an output field on the data source template

**Comment by TheWitness** [comment] 2021-09-25 19:48
I was able to reproduce this based upon the information given.  It was due to the bug in test_data_source() in 1.2.18.  It's fixed now.

**Comment by netniV** [comment] 2021-09-26 00:35
My list above still stands with the latest 1.2.18 sources though.  Any of those are enough to leave you scratching your head over potentially issues.  We may want to consider slightly different messages or add a code number to identify which message is being triggered rather than the same generic message.

**Comment by TheWitness** [comment] 2021-10-02 15:04
Let's open a separate ticket in the Documentation repo, and possibly a new Enhancement or Project request for this.  I'm just going to close this one as the issue reported as been addressed.

**Closed by TheWitness** 2021-10-02 15:04 UTC
Labels: bug, duplicate
