### ISSUE TITLE
[1.2.0] Installer - Database Collation detection

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#2048] opened 2018-10-11 05:17 UTC
The pre-installation check page shows the MySQL 5.7.23 config is set with both:
collation_server = utf8mb4_unicode_ci	
character_set_client = utf8mb4
![image](https://user-images.githubusercontent.com/5741811/46782125-c92ded80-ccd9-11e8-9e9c-a17bbc333387.png)

Yet, the Database Collation page, states the default collation is not UTF8.
![image](https://user-images.githubusercontent.com/5741811/46782135-e1057180-ccd9-11e8-92a5-19cad1a97613.png)

Possibly this is occurring because cacti.sql was imported when the collation was latin1 (before my.ini defaults were updated) ?

**Comment by netniV** [comment] 2018-10-11 06:50
The reporting here is correct and not a bug. The default collation for the server has been set and is correct. The default collation for the database as you have said will likely be what the tables are showing as. There probably needs to be one extra piece of code to set the DB coalition if it’s not already there.

**Comment by cigamit** [comment] 2018-10-11 11:56
Yea, there are a few good articles on this out on the interweb.  Looks like we need to set a few more defaults, though I also suspect that they are highly MySQL version dependent.  I think that this is mostly an annoyance.

**Comment by netniV** [comment] 2018-10-11 11:56
![image](https://user-images.githubusercontent.com/9052188/46802333-ea7fef80-cd54-11e8-8981-e7798765e1f6.png)

The reporting will now show as above making a distinction between server and database correctly.  For now, I have left changing the DB to an admin function as the user being used may not have privileges to change at the DB level.

**Comment by netniV** [comment] 2018-10-11 11:57
This has now been committed to the development code.

**Closed by netniV** 2018-10-11 11:57 UTC
Labels: installer
