### ISSUE TITLE
Host state time was not correctly calculated

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#2419] opened 2019-02-15 15:31 UTC
**Describe the bug**
There is a broken sorting in host.php form. "In state" column.
![in_state_sorting](https://user-images.githubusercontent.com/17087236/52866409-e1f25800-313e-11e9-9363-f75e84b2cb93.png)

**To Reproduce**
1. Go to 'host.php'
2. Click on 'In state'

**Expected behavior**
Devices sorted properly by "In state" time.

**Screenshots**
Did that in first point.

**Desktop:**
 - OS: [e.g. iOS] - Ubuntu
 - Browser [e.g. chrome, safari] - Chrome
 - Version [e.g. 22] - Newest

**Comment by netniV** [comment] 2019-02-15 17:01
tbh, sorting by in state is almost pointless without sorting by state first.  Otherwise, you'll get a mismatch of stats dependant on time.  But I can see that you may want to see what device might be constantly changing state.

**Comment by interduo** [comment] 2019-02-15 17:19
Do You say that this (what I see in screenshot) is expected bahavior?

**Comment by netniV** [comment] 2019-02-15 17:33
Nope, i'm saying that column would not normally be sortable in my mind but I'll see if I can fix it over the weekend.

**Comment by interduo** [comment] 2019-02-16 11:58
Ok thanks. Now I get Your point.

**Comment by netniV** [comment] 2019-02-19 10:02
OK, so the problem isn't with the sorting but rather the display.

```sql
 SELECT host.id,host.hostname, graphs, data_sources, IF(status_event_count>0, status_event_count*300, IF(UNIX_TIMESTAMP(status_rec_date)>943916400,UNIX_TIMESTAMP()-UNIX_TIMESTAMP(status_rec_date), IF(snmp_sysUptimeInstance>0 AND snmp_version > 0, snmp_sysUptimeInstance,UNIX_TIMESTAMP()))) AS instate FROM host LEFT JOIN (SELECT host_id, COUNT(*) AS graphs FROM graph_local GROUP BY host_id) AS gl ON host.id=gl.host_id LEFT JOIN (SELECT host_id, COUNT(*) AS data_sources FROM data_local GROUP BY host_id) AS dl ON host.id=dl.host_id WHERE deleted = '' GROUP BY host.id ORDER BY `instate` ASC LIMIT 0,30;

+----+-------------+--------+--------------+-----------+
| id | hostname    | graphs | data_sources | instate   |
+----+-------------+--------+--------------+-----------+
|  2 | 10.0.0.250  |     17 |           17 |   6114900 |
|  3 | 10.0.0.18   |      8 |           15 |   9475516 |
|  4 | 127.0.0.1   |      1 |            1 | 257353877 |
+----+-------------+--------+--------------+-----------+
3 rows in set (0.00 sec)
```

![image](https://user-images.githubusercontent.com/9052188/53006025-545b8480-342c-11e9-9e01-2aab9f67f871.png)

When I looked at the `get_timeinstate()` function, I noticed that it was completely ignoring any calculated time and recalculating it itself.  So, I wondered what would happen if I corrected this using the following diff:

```diff
diff --git a/lib/functions.php b/lib/functions.php
index 8799cc79..62f07146 100644
--- a/lib/functions.php
+++ b/lib/functions.php
@@ -4130,7 +4130,9 @@ function calculate_percentiles($data, $percentile = 95, $whisker = false) {

 function get_timeinstate($host) {
        $interval = read_config_option('poller_interval');
-       if ($host['status_event_count'] > 0) {
+       if (isset($host['instate'])) {
+               $time = $host['instate'];
+       } elseif ($host['status_event_count'] > 0) {
                $time = $host['status_event_count'] * $interval;
        } elseif (strtotime($host['status_rec_date']) > 943916400) {
                $time = time() - strtotime($host['status_rec_date']);
```

And I ended up with

![image](https://user-images.githubusercontent.com/9052188/53006609-6e499700-342d-11e9-9f67-3dbd4ef30df7.png)

So, the functions are not aligned properly.  I will create a patch to rectify that.

**Comment by netniV** [comment] 2019-02-19 10:21
This is now in the main development code, please check and close if issue is resolved.

**Comment by interduo** [comment] 2019-02-20 06:35
I will check that on 29 feb because I am in Jordan.

**Comment by interduo** [comment] 2019-02-26 08:34
It's good right now.

**Comment by netniV** [comment] 2019-02-26 09:11
Thanks @interduo

**Comment by interduo** [comment] 2019-03-01 08:48
I checked it before too less precisely.

It's good right now calculating "in state" field but the sorting is broken as on begining.

![in_state](https://user-images.githubusercontent.com/17087236/53626879-2da90500-3c07-11e9-947c-815a15b3b7af.png)

**Comment by interduo** [comment] 2019-03-01 08:49
We should sort unixtime not the text in field.

**Comment by netniV** [comment] 2019-03-01 09:59
The time is sorted by the value, not the display.

**Comment by interduo** [comment] 2019-03-01 10:35
I've got a commit 299f3298b6d6a49c903d7a467f4cc1038647d85d in my repo so it should work.

**Comment by netniV** [comment] 2019-03-01 11:00
If lib/function.php's get_daysfromtime() doesn't look something like:
```php
function get_daysfromtime($time, $secs = false, $pad = '', $format = DAYS_FORMAT_SHORT, $all = false) {
        global $days_from_time_settings;

        // Ensure we use an existing format or we'll end up with no text at all
        if (!isset($days_from_time_settings['text'][$format])) {
                $format = DAYS_FORMAT_SHORT;
        }

        $mods = $days_from_time_settings['mods'];
        $text = $days_from_time_settings['text'][$format];

        $result = '';
        foreach ($mods as $index => $mod) {
                if ($mod > 0 || $secs) {
                        if ($time >= $mod) {
                                if ($mod < 1) {
                                        $mod = 1;
                                }
                                $val   = floor($time/$mod);
                                $time %= $mod;
                        } else {
                                $val   = 0;
                        }

                        if ($all || $val > 0) {
                                $result .= padleft($pad, $val, 2) . $text['prefix'] . $text[$index] . $text['suffix'];
                                $all = true;
                        }
                }
```

It isn't the latest rendition of it.

**Comment by interduo** [comment] 2019-03-01 11:33
It's the same. Should I clean some cache or rebuild sth?

**Comment by netniV** [comment] 2019-03-01 11:42
Run this:
```sql
SELECT 
   host.id,host.hostname, graphs, data_sources, 
   IF(availability_method = 0, 
      'availability',
      IF(status_event_count > 0 AND status IN (1, 2), 
         'status_event_count',
         IF(UNIX_TIMESTAMP(status_rec_date) < 943916400 AND status IN (0, 3), 
            'total_polls',
            IF(UNIX_TIMESTAMP(status_rec_date) > 943916400, 
               'status_rec_date',
               IF(snmp_sysUptimeInstance>0 AND snmp_version > 0,
                  'sysUptimeInstance', 
                  'current_time'
               )
            )
         )
      )
   ) AS method,
   IF(availability_method = 0, 
      '0',
      IF(status_event_count > 0 AND status IN (1, 2), 
         status_event_count*$poller_interval,
         IF(UNIX_TIMESTAMP(status_rec_date) < 943916400 AND status IN (0, 3), 
            total_polls*$poller_interval,
            IF(UNIX_TIMESTAMP(status_rec_date) > 943916400, 
               UNIX_TIMESTAMP() - UNIX_TIMESTAMP(status_rec_date),
               IF(snmp_sysUptimeInstance>0 AND snmp_version > 0,
                  snmp_sysUptimeInstance/100, 
                  UNIX_TIMESTAMP()
               )
            )
         )
      )
   ) AS instate
FROM host LEFT JOIN (
   SELECT host_id, COUNT(*) AS graphs 
   FROM graph_local 
   GROUP BY host_id
) AS gl 
ON host.id=gl.host_id 
LEFT JOIN (SELECT host_id, COUNT(*) AS data_sources FROM data_local GROUP BY host_id) AS dl ON host.id=dl.host_id WHERE deleted = '' GROUP BY host.id ORDER BY `instate` ASC LIMIT 0,30;

**Comment by netniV** [comment] 2019-03-01 11:46
Just realised I'd left the $poller_interval in there so it now pulls it from the settings table.

**Comment by interduo** [comment] 2019-03-01 11:50
`+-----+----------------+--------+--------------+-----------------+----------+
| id  | hostname       | graphs | data_sources | method          | instate  |
+-----+----------------+--------+--------------+-----------------+----------+
| 778 | 172.20.200.69  |      6 |            6 | status_rec_date | 10021190 |
| 769 | 172.20.200.248 |      9 |           10 | status_rec_date | 10377890 |
| 670 | 172.20.200.94  |      5 |            5 | status_rec_date | 10439090 |
|  85 | 172.20.200.236 |     10 |           11 | status_rec_date | 10439090 |
| 625 | 172.20.201.39  |      4 |            4 | status_rec_date | 10439090 |
| 792 | 172.18.140.200 |     11 |           11 | status_rec_date | 10549190 |
| 596 | 46.151.191.3   |     31 |           37 | status_rec_date | 10564190 |
|  93 | 172.20.200.73  |      7 |            7 | status_rec_date | 1073390  |
| 462 | 172.20.200.72  |      9 |           10 | status_rec_date | 1073690  |
| 467 | 172.20.200.76  |      5 |            5 | status_rec_date | 1073690  |
| 824 | 172.20.200.204 |      9 |           10 | status_rec_date | 1073690  |
| 630 | 10.200.0.58    |     17 |           17 | status_rec_date | 10961390 |
| 450 | 172.20.200.35  |      7 |            8 | status_rec_date | 11149490 |
| 505 | 172.20.200.101 |     14 |           14 | status_rec_date | 11149490 |
|  33 | 172.20.200.197 |      9 |            9 | status_rec_date | 11149490 |
| 506 | 172.20.200.95  |      6 |            6 | status_rec_date | 11149490 |
|  86 | 172.20.200.111 |      4 |            5 | status_rec_date | 11149490 |
| 507 | 172.16.151.2   |      5 |            5 | status_rec_date | 11149490 |
| 544 | 172.20.200.131 |      6 |            6 | status_rec_date | 11149490 |
| 502 | 172.20.200.90  |      6 |            6 | status_rec_date | 11149490 |
|  42 | 172.20.200.21  |      9 |            9 | status_rec_date | 11761190 |
| 366 | 172.20.200.51  |      5 |            5 | status_rec_date | 11916590 |
| 753 | 10.200.0.120   |     18 |           18 | status_rec_date | 12177590 |
| 426 | 172.20.200.68  |      6 |            6 | status_rec_date | 12804890 |
|  35 | 172.20.200.142 |      7 |            7 | status_rec_date | 128090   |
| 555 | 172.20.200.158 |      5 |            5 | status_rec_date | 128090   |
| 822 | 172.20.200.126 |      9 |           11 | status_rec_date | 12893390 |
| 818 | 172.16.166.2   |      9 |           11 | status_rec_date | 12893390 |
| 819 | 172.20.200.109 |     11 |           12 | status_rec_date | 12893390 |
| 582 | 10.200.0.172   |     25 |           25 | status_rec_date | 13312190 |
+-----+----------------+--------+--------------+-----------------+----------+
30 rows in set (0.01 sec)
`

**Comment by netniV** [comment] 2019-03-01 15:43
SQL is sorting that as a string.  Not a number.

**Comment by interduo** [comment] 2019-03-01 16:00
So the type of 'instate' is mistaken?

**Comment by netniV** [comment] 2019-03-01 20:12
I don't know why, by yes.

**Comment by netniV** [comment] 2019-03-04 11:56
Try this new one:

```sql
SELECT 
   host.id,host.hostname, graphs, data_sources, 
   IF(availability_method = 0, 
      'availability',
      IF(status_event_count > 0 AND status IN (1, 2), 
         'status_event_count',
         IF(UNIX_TIMESTAMP(status_rec_date) < 943916400 AND status IN (0, 3), 
            'total_polls',
            IF(UNIX_TIMESTAMP(status_rec_date) > 943916400, 
               'status_rec_date',
               IF(snmp_sysUptimeInstance>0 AND snmp_version > 0,
                  'sysUptimeInstance', 
                  'current_time'
               )
            )
         )
      )
   ) AS method,
   CAST(
      IF(availability_method = 0, 
         '0',
         IF(status_event_count > 0 AND status IN (1, 2), 
            status_event_count*(SELECT IFNULL(value,'300') FROM settings where name = 'poller_interval'),
            IF(UNIX_TIMESTAMP(status_rec_date) < 943916400 AND status IN (0, 3), 
               total_polls*(SELECT IFNULL(value,'300') FROM settings where name = 'poller_interval'),
               IF(UNIX_TIMESTAMP(status_rec_date) > 943916400, 
                  UNIX_TIMESTAMP() - UNIX_TIMESTAMP(status_rec_date),
                  IF(snmp_sysUptimeInstance>0 AND snmp_version > 0,
                     snmp_sysUptimeInstance/100, 
                     UNIX_TIMESTAMP()
                  )
               )
            )
         )
      ) AS unsigned
   ) AS instate
FROM host LEFT JOIN (
   SELECT host_id, COUNT(*) AS graphs 
   FROM graph_local 
   GROUP BY host_id
) AS gl 
ON host.id=gl.host_id 
LEFT JOIN (
   SELECT host_id, COUNT(*) AS data_sources 
   FROM data_local 
   GROUP BY host_id
) AS dl 
ON host.id=dl.host_id 
WHERE deleted = '' 
GROUP BY host.id 
ORDER BY `instate` ASC 
LIMIT 0,30;
```

This should work for you as it changes my data from

```
+-----+--------+--------------+-----------------+----------+
| id  | graphs | data_sources | method          | instate  |
+-----+--------+--------------+-----------------+----------+
|  69 |     23 |           22 | status_rec_date | 10539395 |
|  71 |      9 |            8 | status_rec_date | 10556915 |
| 137 |   NULL |         NULL | status_rec_date | 10801835 |
|  73 |     10 |            9 | status_rec_date | 10801835 |
|  89 |      3 |            3 | status_rec_date | 12098975 |
| 104 |      3 |            3 | status_rec_date | 12110255 |
| 100 |      3 |            3 | status_rec_date | 12110615 |
| 127 |      2 |            2 | status_rec_date | 12569795 |
|  79 |     10 |            9 | status_rec_date | 1272875  |
|  70 |     10 |            9 | status_rec_date | 13123355 |
| 115 |      2 |            2 | status_rec_date | 13176875 |
| 117 |      2 |            2 | status_rec_date | 13176875 |
|  75 |      9 |            8 | status_rec_date | 14300675 |
|  31 |      7 |            7 | status_rec_date | 1469735  |
|  44 |     27 |           26 | status_rec_date | 1573835  |
|  90 |      1 |            1 | status_rec_date | 1595435  |
|  39 |      9 |            8 | status_rec_date | 16577375 |
|  83 |      3 |            3 | status_rec_date | 1679135  |
| 116 |      2 |            2 | status_rec_date | 1679735  |
|  82 |      1 |            1 | status_rec_date | 1679735  |
|  80 |      5 |            5 | status_rec_date | 16889675 |
| 133 |      5 |            5 | status_rec_date | 16889675 |
| 132 |     11 |           10 | status_rec_date | 16889675 |
|  78 |      9 |            8 | status_rec_date | 16889675 |
|  98 |      3 |            3 | status_rec_date | 16889675 |
| 131 |     11 |           10 | status_rec_date | 16889675 |
| 109 |      3 |            3 | status_rec_date | 16889675 |
| 111 |      3 |            3 | status_rec_date | 16889915 |
|  42 |     12 |           12 | status_rec_date | 16889915 |
| 135 |      7 |           10 | status_rec_date | 16889975 |
+-----+--------+--------------+-----------------+----------+
```
to
```
+-----+--------+--------------+--------------------+---------+
| id  | graphs | data_sources | method             | instate |
+-----+--------+--------------+--------------------+---------+
|  60 |     10 |            9 | status_rec_date    |  249037 |
|  51 |     10 |           10 | status_rec_date    |  249097 |
| 142 |     12 |           12 | status_rec_date    |  297457 |
| 152 |     13 |           13 | status_rec_date    |  297457 |
| 145 |     23 |           23 | status_rec_date    |  297457 |
| 150 |     13 |           13 | status_rec_date    |  297457 |
| 143 |     17 |           17 | status_rec_date    |  297457 |
| 148 |     12 |           12 | status_rec_date    |  297457 |
| 141 |     14 |           13 | status_rec_date    |  297457 |
| 146 |     13 |           13 | status_rec_date    |  297457 |
| 151 |     14 |           14 | status_rec_date    |  297457 |
| 144 |     13 |           13 | status_rec_date    |  297457 |
| 149 |     12 |           12 | status_rec_date    |  297457 |
| 126 |      2 |            2 | status_rec_date    |  297517 |
| 108 |      1 |            1 | status_rec_date    |  297517 |
| 118 |      2 |            2 | status_rec_date    |  297517 |
| 124 |      2 |            2 | status_rec_date    |  297517 |
| 114 |      2 |            2 | status_rec_date    |  297517 |
| 139 |     10 |           10 | status_rec_date    |  298897 |
| 140 |   NULL |         NULL | status_rec_date    |  298957 |
| 103 |      1 |            1 | status_rec_date    |  299017 |
| 112 |      1 |            1 | status_rec_date    |  463357 |
| 147 |   NULL |         NULL | total_polls        |  604800 |
|  74 |     10 |            9 | status_rec_date    |  896017 |
|  87 |      3 |            3 | status_event_count |  935820 |
|  79 |     10 |            9 | status_rec_date    | 1272817 |
|  31 |      7 |            7 | status_rec_date    | 1469677 |
|  44 |     27 |           26 | status_rec_date    | 1573777 |
|  90 |      1 |            1 | status_rec_date    | 1595377 |
|  83 |      3 |            3 | status_rec_date    | 1679077 |
+-----+--------+--------------+--------------------+---------+
```

**Comment by interduo** [comment] 2019-03-04 12:00
Now query result is sorted correctly by instate in expected way.

**Comment by netniV** [comment] 2019-03-04 12:03
I have now committed this to the latest development code.

**Comment by interduo** [comment] 2019-03-04 16:17
Why did You not close this issue?

**Comment by netniV** [comment] 2019-03-04 19:49
We must have posted around the same time so I missed yours.  You can actually close your own issues if you believe them to be resolved 👍

**Closed** 2019-03-05 07:57 UTC
Labels: bug, resolved
