### ISSUE TITLE
polled data flushed to poller_output_boost table but but boost fails to update respective rrd

### ISSUE THREAD

**Issue by gj00354347** [Cacti/cacti#4320] opened 2021-06-24 09:10 UTC
# Describe the bug

Hi Developers ,

In our cacti , we observed gaps for a few devices . Initially we though it might be the device is overloaded and its not able to respond for a few polls and that results in gap in the graphs.

so to dig deeper , we enabled the device debug so that whenever we have gap in the graph  we can cross check like whether the data has been fetched or not by poller .

to our surprise there was not a single poll where we did not find the output for those traffic interfaces but the gaps were there . so we shifted our investigation to boost and we were capturing the contents of poller_output_boost table and we compared the data like whether the data in poll cycle is flushed to poller_output_boost or not and we observed yes it was being written to poller_output_boost but from there when boost used to run it failed to transfer the data to rrd of those graphs or data sources.

Cacti version - 1.2.17
spine 1.2.17
OS Red Hat Enterprise Linux Server release 7.8 (Maipo)
MySQL version mysql  Ver 15.1 Distrib 5.5.65-MariaDB
total number of devices - 3945
total number of graphs - 4,75,835 

## To Reproduce

**To reproduce the error cannot  , say what exactly to do .

-

**Comment by gj00354347** [comment] 2021-06-24 09:29
logs and snap

**Comment by gj00354347** [comment] 2021-06-24 09:33
[poller_output_boost data not flushed to rrd.docx](https://github.com/Cacti/cacti/files/6708064/poller_output_boost.data.not.flushed.to.rrd.docx)

**Comment by TheWitness** [comment] 2021-06-25 18:47
This could be a permission problem, but I'm about to log a separate ticket for another issue.  Ensure that you are on RRDtool 1.5+, preferably 1.7.2 as it's more tolerant of duplicate inserts.  You also need to change the setting under Console > Settings > General.

**Comment by TheWitness** [comment] 2021-06-25 18:53
Here is the ticket where you can find the fix.  https://github.com/Cacti/cacti/issues/4321  Update the RRDtool, change the setting and let us know if the issue is resolved.

**Comment by gj00354347** [comment] 2021-08-25 03:58
Hi Team , 

we are having instability in our prod cacti so that’s why we are shying away from new change . Once it is stable we will update rrdtool and update you.

Best Regards,
Gopal

**Comment by TheWitness** [comment] 2021-10-02 15:08
Going to close this for now.  If the issue continues, after the 1.2.19 release is installed, feel free to open a new bug.

**Comment by TheWitness** [comment] 2021-10-02 15:08
There have been multiple changes in both the cmd.php and spine pollers in 1.2.19 that address some "performance" problems with more recent versions of MariaDB.

**Closed by TheWitness** 2021-10-02 15:08 UTC
Labels: bug, duplicate
