### ISSUE TITLE
SQL broken if Get Script Data (index) fail and PHPSVR ERROR

### ISSUE THREAD

**Issue by rcalpha** [Cacti/cacti#1572] opened 2018-04-26 12:52 UTC
In the CLI if an script called from "Get Script Data (index)" data query fail It breaks the SQL query and generate PHPSVR ERROR afterwards

I think that the solution is to mysqlescape the SQL sentences if there is an error

I'm using Version 1.1.37

==============================================================
SPINE: Poller[Main Poller] ERROR: SQL Failed! Error:'1064', Message:'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*ip*' '17' '1:161:500:1:10:*snmp_community*::::::' 'num_indexes''' at line 1', SQL Fragment:'UPDATE poller_reindex SET assert_value='Warning: include(*/../include/global.php): failed to open stream: No such file or directory in */scripts/*php_script* on line 10' WHERE host_id='17' AND data_query_id='12' AND arg1='/*/scripts/php.sh /*/scripts/*php_script* '*ip*' '17' '1:161:500:1:10:*snmp_comunity*::::::' 'num_indexes'''

**Comment by cigamit** [comment] 2018-04-28 07:14
This is more of a configuration issue in Cacti and a very odd bug in spine.  If after you fix your configuration issue, you want this SQL error fixed in spine, please open a bug in the spine repo.

Again, this is a configuration issue and not a bug in Cacti.  I would suggest that you $url_path is not set correctly in config.php

**Closed by cigamit** 2018-04-28 07:14 UTC

**Comment by netniV** [comment] 2018-04-28 07:27
I agree that I think this a configuration issue.

Whilst at first thought, it might seem easy to detect PHP styled errors, the script may be using other languages / shells / i18n-based error text, so it would make it tricky to catch all variations automatically.

If anything, the script should be correctly handling these errors itself which is why anything using Cacti's global routines have error handlers in place to catch any warnings/errors and place them into the cacti log.
