### ISSUE TITLE
Poller and different polling time for hosts

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#233] opened 2017-01-24 12:40 UTC
So I have 10-20 graphs that should be reasonably updated every 15seconds.

I think that there should be other poller running every 15 seconds.
I don't want to torture my server to do this for every (8k) graphs.

 Is it possible to do that and how?

**Comment by cigamit** [comment] 2017-01-24 23:18
Please conduct research into data collection profiles.  There you can define differing data collection for various data source types.  From there, you can have some data being collected every 15 seconds, and other data being collected every hour.  However, you 'poller interval' would be required to be 15 seconds, and after making that change, you would need to rebuild you poller cache under the Utilities menu pick.  Since you are looking for help, I would encourage you to do such things on the forums.  Additionally, since this is not a bug, I will close this issue.

**Closed by cigamit** 2017-01-24 23:18 UTC
