### ISSUE TITLE
The aggregated graph cannot add 95th Percentile

### ISSUE THREAD

**Issue by babyfenei** [Cacti/cacti#900] opened 2017-08-10 15:38 UTC
I don't know the current version of 1.1.16 fo 'Create Aggregate Graph'and'Create Aggregate from Template' is how to define,
Now  I need to create graphics when polymerization can display 95th Percentile, but when I choose 'Create Aggregate from Template' to use  template, cacti cannot use the 95th Percentile,when I choose Create Aggregate Graph' I thought will add graphics as polymerization method and 0.8.8f version. But when I choose this option, cacti is used to create the template graphics. Also polymerization is unable to add 95th and Percentile graphics mode.
I don't know if the current version in addition when polymerization graphics use other ways to aggregate graphics add 95th Percentile

**Comment by cigamit** [comment] 2017-08-10 23:17
Duplicate of https://github.com/Cacti/cacti/issues/793 and one other existing enhancement request.  This functionality was removed from Aggregate prior to merge into the core Cacti tool.  We will add it back.

**Closed by cigamit** 2017-08-10 23:17 UTC
